Enabled to choose tiered or flat price on Admin side.
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #1004
Opened 2023-01-13 08:48 UTC by DeepikaDK001

2023-01-13 11:32 UTC, imranbashir01 submitted a review, later dismissed

2023-01-13 16:28 UTC, bjss-colin commented
The backlinks, for the Add Flat and Tiered list price page, will also need to be updated as they currently return the user to the Index page rather than the List Price Type page.

2023-01-17 17:28 UTC, imranbashir01 approved these changes

2023-01-17 17:49 UTC, bjss-colin approved these changes

2023-01-18 13:40 UTC, bjss-colin requested changes
Not yet to be merged

2023-01-19 09:36 UTC, closed without merging

2023-01-19 09:37 UTC, bjss-colin commented
Closed as these should target a `feature` branch rather than `develop`