Amend service recipients
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #1023
Opened 2023-01-25 12:30 UTC by magnusjohn-bjss

2023-01-31 14:54 UTC, imranbashir01 approved these changes

2023-02-01 09:54 UTC, bjss-colin requested changes

2023-02-01 09:54 UTC, bjss-colin commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Areas/Ordering/SolutionSelection/AdditionalServices/SelectAdditionalServiceRecipients.cs
> +            GetOrderItem().OrderItemRecipients.Count.Should().Be(0);
`Count.Should().Be(0)` -> `.Count.Should().BeEmpty();`

2023-02-01 09:54 UTC, bjss-colin commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Areas/Ordering/SolutionSelection/AdditionalServices/ConfirmAdditionalServiceRecipientsAmendment.cs
> +            GetService().OrderItemRecipients.Count.Should().Be(0);
`Count.Should().Be(0)` -> `Count.Should().BeEmpty()`

2023-02-01 09:54 UTC, bjss-colin commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Areas/Ordering/SolutionSelection/AdditionalServices/ConfirmAdditionalServiceRecipients.cs
> +            GetService().OrderItemRecipients.Count.Should().Be(0);
`Count.Should().Be(0)` -> `Count.Should().BeEmpty()`

2023-02-01 09:54 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Orders/Controllers/SolutionSelection/AdditionalServicesController.cs
> +        private static List<CatalogueItemId> GetCurrentServiceIds(CallOffId callOffId, OrderWrapper wrapper)
For the sake of Codecov, it's worth adding some tests for this. Seems like only 216-222 are being tested indirectly via the calling member.

2023-02-01 10:01 UTC, magnusjohn-bjss commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Orders/Controllers/SolutionSelection/AdditionalServicesController.cs
> +        private static List<CatalogueItemId> GetCurrentServiceIds(CallOffId callOffId, OrderWrapper wrapper)
Given this is gonna need refactoring and these tests are a massive pain to setup, any chance we can look the other way on this one and go for 100% test coverage on the refactored code? we'll need to refactor before the amend stuff goes live as there's an additional "copy service recipients" screen coming in, this controller code is waaaaaay too complex and brittle now to extend as-is

2023-02-01 10:12 UTC, bjss-colin approved these changes

2023-02-01 10:13 UTC, merged