Feature/us 21754 finance admin rpt additional fields
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #1036
Opened 2023-02-09 11:37 UTC by DeepikaDK001

2023-02-09 12:03 UTC, bjss-colin requested changes

2023-02-09 12:03 UTC, ghost commented on src/NHSD.GPIT.BuyingCatalogue.Services/Csv/CsvService.cs
> +                    PricingType = oir.OrderItem.OrderItemPrice.CataloguePriceType.ToString() == "Flat" ? " " : oir.OrderItem.OrderItemPrice.CataloguePriceType + " " + oir.OrderItem.OrderItemPrice.Cat
No need to use `ToString` on the `CataloguePriceType` comparison. It's an enum and, as such, you can directly compare against the enum values.

2023-02-09 12:03 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.Services/Csv/CsvService.cs
> +            result.Append(" [");
Unnecessary space at the start of the string

2023-02-09 12:03 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.Services/Csv/CsvService.cs
> +            for (int i = 0; i < orderItemPriceTiers.Count; i++)
This could be converted to a LINQ statement by using `.Select` and subsequently using `string.Join` with `;` as the delimiter.

2023-02-09 12:03 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.Services/Csv/CsvService.cs
> +                result.Append("[" + item.LowerRange + ":" + item.Price + "]");
String interpolation is generally preferred over concatenation as it's more readable

2023-02-09 12:03 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.Services/Csv/CsvService.cs
> +            result.Append("] ");
Unnecessary space at the end of the string

2023-02-09 12:03 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.Services/Csv/CsvService.cs
> +                    PricingType = oir.OrderItem.OrderItemPrice.CataloguePriceType.ToString() == "Flat" ? " " : oir.OrderItem.OrderItemPrice.CataloguePriceType + " " + oir.OrderItem.OrderItemPrice.Cat
Favor string interpolation over concatenation.

2023-02-09 13:29 UTC, bjss-colin requested changes

2023-02-09 13:29 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.Services/Csv/CsvService.cs
> +            return $" [{string.Join("; ", orderItemPriceTiers.Select(item => $"[{item.LowerRange}:{item.Price}]"))}]";
Still some unnecessary spaces in this string that violates the agreed format of the CSV. 

It is very important to follow the exact spec as this could cause Odoo to throw an error when consuming this data.

2023-02-09 16:16 UTC, imranbashir01 approved these changes

2023-02-09 16:30 UTC, imranbashir01 requested changes
need more clarification around the price type

2023-02-09 17:13 UTC, bjss-colin requested changes

2023-02-09 17:13 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.Services/Csv/CsvService.cs
> +                    PricingType = oir.OrderItem.OrderItemPrice.CataloguePriceType == CataloguePriceType.Flat || (oir.OrderItem.OrderItemPrice.CataloguePriceType == CataloguePriceType.Tiered && oir.Or
Both conditions could be shortened to `oir.OrderItem.OrderItemPrice.CataloguePriceType == CataloguePriceType.Tiered && oir.OrderItem.OrderItemPrice.CataloguePriceCalculationType == CataloguePriceCalculationType.Cumulative` and the true/false statements could be switched around.

2023-02-10 08:08 UTC, imranbashir01 approved these changes

2023-02-13 09:30 UTC, bjss-colin approved these changes

2023-02-13 09:32 UTC, merged