Feature/21552 order email template
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #1040
Opened 2023-02-10 16:20 UTC by dssherlock

2023-02-13 19:25 UTC, bjss-colin requested changes

2023-02-13 19:25 UTC, ghost commented on tests/NHSD.GPIT.BuyingCatalogue.Services.UnitTests/Orders/OrderServiceTests.cs
> +        public static async Task CompleteOrder_RequestIsValid_SendsEmails(
This is quite a large test. Is it worth breaking down to several smaller tests that check the individual blocks of functionality? That way it'll be easier to refactor the method, as that too is doing too much, in the future.

2023-02-14 10:52 UTC, dssherlock commented on tests/NHSD.GPIT.BuyingCatalogue.Services.UnitTests/Orders/OrderServiceTests.cs
> +        public static async Task CompleteOrder_RequestIsValid_SendsEmails(
Yep thats fine-this was just a case of trying to up code coverage as fast as possible! ;)

2023-02-14 15:56 UTC, imranbashir01 approved these changes, later dismissed

2023-02-14 16:49 UTC, magnusjohn-bjss approved these changes

2023-02-14 17:15 UTC, bjss-colin approved these changes

2023-02-15 10:04 UTC, imranbashir01 approved these changes

2023-02-15 13:41 UTC, merged