Changes on the Screen to display prices should Exclude VAT
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #1049
Opened 2023-02-20 16:00 UTC by DeepikaDK001

2023-02-21 09:48 UTC, bjss-colin requested changes

2023-02-21 09:48 UTC, bjss-colin commented on tests/NHSD.GPIT.BuyingCatalogue.WebApp.UnitTests/Models/PriceCalculationDetailsModelTests.cs
> +            if (priceType == CataloguePriceType.Tiered && calculationType != CataloguePriceCalculationType.SingleFixed)
Let's split this out to two tests

2023-02-21 09:48 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Views/OrderSummary/Index.cshtml
> +                            <pdf-summary-list-row label-text="Total monthly cost">
Indentation to be removed

2023-02-21 09:48 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Views/OrderSummary/Index.cshtml
> +                            <pdf-summary-list-row label-text="Total annual cost">
Indentation to be removed

2023-02-21 09:48 UTC, bjss-colin commented on tests/NHSD.GPIT.BuyingCatalogue.WebApp.UnitTests/Models/PriceCalculationDetailsModelTests.cs
> +            var expectedHeading = $"The total price for this Catalogue Solution will be calculated as a {priceType.ToString().ToLowerInvariant()}";
Separate tests

2023-02-21 09:48 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Orders/Views/FundingSource/FundingSources.cshtml
> +                    <nhs-table-cell><b>Total</b></nhs-table-cell>
Indentation and formatting

2023-02-21 09:48 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Orders/Views/FundingSource/FundingSources.cshtml
> +            <p><b>All prices exclude VAT.</b></p>
Indentation and formatting

2023-02-21 09:48 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Orders/Views/FundingSource/FundingSources.cshtml
> +            <p><b>All prices exclude VAT.</b></p>
Indentation and formatting

2023-02-22 14:11 UTC, imranbashir01 approved these changes

2023-02-22 14:30 UTC, bjss-colin approved these changes

2023-02-22 14:34 UTC, merged