Feature/21852 trud data
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #1061
Opened 2023-03-07 11:26 UTC by dssherlock

2023-03-08 13:22 UTC, bjss-colin requested changes

2023-03-08 13:22 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/ServiceCollectionExtensions.cs
> -            if (odsSettings.UseTrud)
Add an `[ExcludeFromCodeCoverage]` to this entire class (`ServiceCollectionExtensions`).

2023-03-08 14:48 UTC, imranbashir01 approved these changes, later dismissed

2023-03-09 11:21 UTC, bjss-colin submitted a review, later dismissed

2023-03-09 11:26 UTC, imranbashir01 approved these changes, later dismissed

2023-03-10 09:18 UTC, imranbashir01 approved these changes

2023-03-16 14:35 UTC, bjss-colin commented
Going to close this for now as we've identified some new requirements

2023-03-16 14:35 UTC, closed without merging