Add GP Practices to the buying catalogue
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #1083
Opened 2023-04-06 16:50 UTC by dssherlock

This draft PR is just for reference and compares against the ICB branch to avoid hundreds of additional changes. Once ICB has been merged into dev I will create a new PR.

2023-04-14 13:28 UTC, bjss-colin requested changes

2023-04-14 13:28 UTC, bjss-colin commented on tests/NHSD.GPIT.BuyingCatalogue.Services.UnitTests/Organisations/TrudOdsServiceTests.cs
> +        var service = new TrudOdsService(settings, context, orgService, logger);
Rather than instantiating this type manually, you should create a customization for `OdsSettings` that registers an instance of `OdsSettings` with the custom roles in the `IFixture`. See the existing `AutoFixtureCustomizations` folder in **NHSD.GPIT.BuyingCatalogue.UnitTests.Framework**. New customizations subsequently need to be registered in `FixtureFactory.Customizations`.

2023-04-14 13:28 UTC, bjss-colin commented on tests/NHSD.GPIT.BuyingCatalogue.Services.UnitTests/Organisations/TrudOdsServiceTests.cs
> +        var service = new TrudOdsService(settings, context, orgService, logger);
Same as above

2023-04-24 10:33 UTC, samdasari9 approved these changes

2023-04-26 08:57 UTC, bjss-colin approved these changes

2023-04-26 09:30 UTC, merged