Feature/21941 gp local funding
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #1084
Opened 2023-04-12 09:08 UTC by dssherlock

Again this PR is just for review purposes only as it is blocked by ICB work.

2023-04-13 15:36 UTC, bjss-colin requested changes

2023-04-13 15:36 UTC, ghost commented on src/NHSD.GPIT.BuyingCatalogue.Services/Orders/OrderItemService.cs
> +            else if (item.Order.SelectedFramework.LocalFundingOnly || item.Order.OrderingParty.OrganisationType == OrganisationType.GP)
This logic is duplicated in quite a lot of places. Let's split this out to a method on the order object instead. See `IsPerServiceRecipient` on `OrderItemPrice` for an example of a similar setup

2023-04-14 07:12 UTC, dssherlock commented on src/NHSD.GPIT.BuyingCatalogue.Services/Orders/OrderItemService.cs
> +            else if (item.Order.SelectedFramework.LocalFundingOnly || item.Order.OrderingParty.OrganisationType == OrganisationType.GP)
Yep i agree-wanted to get it in and working but yes needs refactoring.

2023-04-20 16:25 UTC, bjss-colin approved these changes

2023-04-20 16:26 UTC, merged