1b. - Filtering adding in the framework
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #1095
Opened 2023-04-24 07:32 UTC by DeepikaDK001

2023-04-26 14:13 UTC, dssherlock requested changes

2023-04-26 14:13 UTC, dssherlock commented on src/NHSD.GPIT.BuyingCatalogue.Services/Framework/FrameworkService.cs
Is it sufficient to know that the framework has solutions or do we need to know if those solutions are published? This is more an analysis question!

2023-04-26 14:13 UTC, dssherlock commented on src/NHSD.GPIT.BuyingCatalogue.Services/Solutions/SolutionsFilterService.cs
I am a bit sad this comment is going!

2023-04-26 14:13 UTC, dssherlock commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Controllers/SolutionsController.cs
> +            var frameworks = await frameworkService.GetFrameworksWithActiveSolutions();
IncludeAdditionalfiltersModel -> IncludeAdditionalFiltersModel

2023-04-26 14:13 UTC, dssherlock commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Models/Filters/IncludeAdditionalfiltersModel.cs
> +    [ExcludeFromCodeCoverage]
Could this not be AdditionalFiltersModel rather than IncludeAdditionalFiltersModel? To me this sounds like a bool rather than a class

2023-04-26 14:13 UTC, dssherlock commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Models/Filters/IncludeAdditionalfiltersModel.cs
> +
Probably ought to have a unit test to check frameworks assigned correctly (remove ExcludeFromCodeCoverage)

2023-04-26 14:13 UTC, dssherlock commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Models/SolutionsModel.cs
Can this be renamed something more generic related to what its actually checking i.e. HasCapabilities, so that it can be used in SearchCriteriaApplied as well.

2023-04-26 14:13 UTC, dssherlock commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/Shared/IncludeAdditionalfilters.cshtml
> +@using NHSD.GPIT.BuyingCatalogue.WebApp.Areas.Solutions.Controllers
Check the camel casing (IncludeAdditional**f**ilters) on the filename

2023-04-26 14:13 UTC, dssherlock commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/Shared/IncludeAdditionalfilters.cshtml
> +
What is supposed to happen in the scenario that only 1 framework is returned?

2023-04-26 14:23 UTC, dssherlock requested changes

2023-04-26 14:23 UTC, dssherlock commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Areas/PublicBrowse/Solution/CatalogueSolutions.cs
Maybe add a few new integration tests for the new filter layout/functionality

2023-04-26 15:31 UTC, DeepikaDK001 commented on src/NHSD.GPIT.BuyingCatalogue.Services/Framework/FrameworkService.cs
This should include published solution. Changes will be added to this PR. Thank you for pointing it out :)

2023-04-27 09:24 UTC, DeepikaDK001 commented on src/NHSD.GPIT.BuyingCatalogue.Services/Solutions/SolutionsFilterService.cs
I have added that back

2023-04-27 09:24 UTC, DeepikaDK001 commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Models/Filters/IncludeAdditionalfiltersModel.cs
> +
I have added the test coverage..

2023-04-27 09:26 UTC, DeepikaDK001 commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/Shared/IncludeAdditionalfilters.cshtml
> +
If there is only one framework available then the framework filtering card will not be there (as there is nothing available to filter too)

2023-04-27 09:59 UTC, bjss-colin requested changes

2023-04-27 09:59 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.Services/Framework/FrameworkService.cs
> +        public Task<List<EntityFramework.Catalogue.Models.Framework>> GetFrameworksWithActiveAndPublishedSolutions() => dbContext.Frameworks
This will generate one query and a subquery, but can be reduced to a single query. Rather than accessing `dbContext.Frameworks` directory, have a think about approaching this from a different angle by accessing `dbContext.FrameworkSolutions`.

`FrameworkSolutions` is a many to many relationship table that contains the IDs of all frameworks and solutions. The entities also contain the navigation properties which mean it can be done with no explicit `Include` or `Join` statements.

2023-04-27 15:22 UTC, bjss-colin requested changes

2023-04-27 15:22 UTC, ghost commented on src/NHSD.GPIT.BuyingCatalogue.Services/Framework/FrameworkService.cs
> +            return dbContext.Frameworks
This is still going directly to the Frameworks table which is going to use multiple queries. As previously mentioned, use `dbContext.FrameworkSolutions` directly. It already has everything that you need and doing so would drastically simplify the query that's being generated here.

2023-05-02 10:12 UTC, samdasari9 approved these changes, later dismissed

2023-05-03 09:35 UTC, bjss-colin requested changes, later dismissed

2023-05-03 09:35 UTC, ghost commented on src/NHSD.GPIT.BuyingCatalogue.ServiceContracts/Models/FilterModels/FrameworkFilterInfo.cs
> +        public string Name { get; init; }
`Name` isn't used anywhere so it can be removed.

2023-05-03 09:35 UTC, bjss-colin commented on tests/NHSD.GPIT.BuyingCatalogue.Services.UnitTests/Frameworks/FrameworkServiceTests.cs
> +            var expectedFrameworks = await dbContext.FrameworkSolutions
`expectedFramework` should be known at this point because of the bootstrapping that takes place on lines 55-57. Rather than using this query the test assertion should be more concrete. In other words, Create a new list of `FrameworkFilterInfo` that contains the expected values. If the solution contains any unexpected frameworks then these should be cleared down prior to bootstrapping on line 55.

2023-05-03 09:35 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.Services/Framework/FrameworkService.cs
> +                    fs => fs.Solution.CatalogueItem.CatalogueItemType == CatalogueItemType.Solution
Comparing against the `CatalogueItemType` is unnecessary here. The code is navigating from a Solution (`fs.Solution.`), therefore `CatalogueItemType == CatalogueItemType.Solution` will always be true.

2023-05-03 09:35 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.Services/Framework/FrameworkService.cs
> +        public async Task<List<FrameworkFilterInfo>> GetFrameworksByCatalogueItems(IList<CatalogueItem> catalogueItems)
Try this instead

```csharp
public async Task<List<FrameworkFilterInfo>>
    GetFrameworksByCatalogueItems(IList<CatalogueItemId> catalogueItems) => await dbContext.FrameworkSolutions.AsNoTracking()
        .Where(
            x => x.Solution.CatalogueItem.PublishedStatus == PublicationStatus.Published)
        .GroupBy(x => new { x.FrameworkId, x.Framework.ShortName })
        .Select(
            x => new FrameworkFilterInfo
            {
                Id = x.Key.FrameworkId,
                ShortName = x.Key.ShortName,
                CountOfActiveSolutions = x.Count(y => catalogueItems.Contains(y.SolutionId)),
            })
        .ToListAsync();
```

2023-05-03 14:30 UTC, bjss-colin commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Areas/PublicBrowse/Solution/CatalogueSolutions.cs
Marking this as unresolved as some Integration tests still need to be added to assert that the UI elements appear.

2023-05-04 10:58 UTC, bjss-colin commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Areas/PublicBrowse/Solution/CatalogueSolutions.cs
Closing this again. Integration tests can't actually be written since this page uses a stored proc.

2023-05-04 12:37 UTC, samdasari9 approved these changes

2023-05-04 13:29 UTC, dssherlock commented on src/NHSD.GPIT.BuyingCatalogue.Services/Solutions/SolutionsFilterService.cs
Misleading function name-actually returning filtered _or_ non-filtered query plus count

2023-05-04 13:31 UTC, dssherlock commented on src/NHSD.GPIT.BuyingCatalogue.Services/Framework/FrameworkService.cs
> -        public async Task<EntityFramework.Catalogue.Models.Framework> GetFramework(string frameworkId) =>
Maybe misleading function name? Not actually returning frameworks based on the catalogue items. Just getting a count based on them. Not sure how to make it less misleading though!

2023-05-04 13:39 UTC, dssherlock approved these changes

2023-05-04 13:46 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.Services/Solutions/SolutionsFilterService.cs
As mentioned on Slack - we'll leave it as is for now and pick this up in the future. The whole approach to filtering is over-engineered really due to the stored procedure. In the future it will be good to get rid of the stored proc and do it all in code, making it extensible at the same time so that we can apply different levels of filtering without re-running the query each time.

2023-05-04 13:48 UTC, merged