Additional filters by Client application type
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #1108
Opened 2023-05-09 15:18 UTC by DeepikaDK001

2023-05-09 16:13 UTC, bjss-colin requested changes

2023-05-09 16:13 UTC, ghost commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Models/Filters/AdditionalFiltersModel.cs
> +            .Cast<ClientApplicationType>()
Very nice - I like the usage of `.Cast<ClientApplicationType>` here.

2023-05-09 16:13 UTC, ghost commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/Shared/_AdditionalFilters.cshtml
> +            @foreach (var value in Model.ClientApplicaitontypeOptions)
Use a `for` loop rather than a `foreach` loop.

2023-05-09 16:13 UTC, ghost commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/Shared/_AdditionalFilters.cshtml
> +        var clientAppTypeIndex = 0;
This can be removed by using a `for` loop below.

2023-05-09 16:13 UTC, ghost commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/Shared/_AdditionalFilters.cshtml
> +                <nhs-table-row-container>
Checkbox components should live inside an `nhs-fieldset-form-label` and not a table. Have a peek at some other in-code examples of `nhs-fieldset-form-label` and `nhs-checkbox-container`

2023-05-09 16:13 UTC, ghost commented on src/NHSD.GPIT.BuyingCatalogue.Services/Solutions/SolutionsFilterService.cs
> +using Microsoft.IdentityModel.Tokens;
This namespace import shouldn't be needed since it doesn't look like any code uses it.

2023-05-09 16:13 UTC, ghost commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Models/Filters/AdditionalFiltersModel.cs
> +        public List<SelectOption<int>> ClientApplicaitontypeOptions { get; set; }
Spelling mistake and casing -

`ClientApplicationTypeOptions`

2023-05-09 16:13 UTC, ghost commented on tests/NHSD.GPIT.BuyingCatalogue.WebApp.UnitTests/Areas/Solutions/Models/Filters/AdditionalFilterModelTests.cs
> +                if (clientApplicationTypeSelected != null && clientApplicationTypeSelected.Contains(item.Value.ToString()))
Remember that tests should be written in an assertive fashion. It's not immediately clear whether this test will pass with all `Selected` values being true or false. Or whether the test will fail because one `Selected` value isn't as expected.

Typically if a test contains an `if` statement then it indicates that the test should be split up into two separate tests as there are different edge cases being tested.

Be sure to identify the edge cases of the system under test, in this case `AdditionalFiltersModel`, and write one test per edge case. While also ensuring that the tests follow the [Arrange, Act, Assert pattern](https://freecontent.manning.com/making-better-unit-tests-part-1-the-aaa-pattern/)

2023-05-09 16:13 UTC, ghost commented on src/NHSD.GPIT.BuyingCatalogue.Services/Solutions/SolutionsFilterService.cs
> +                string[] clientApplicationtypes = clientApplicationTypeSelected.Split(',');
Let's refactor this to clean up a bit. Lines 67-88 can be split out to an appropriately named method.

2023-05-09 16:13 UTC, ghost commented on src/NHSD.GPIT.BuyingCatalogue.Services/Solutions/SolutionsFilterService.cs
> +                string[] clientApplicationtypes = clientApplicationTypeSelected.Split(',');
The Client Application Types can be parsed as enums at this point. Add some LINQ statements after the `.Split(','`) call in order to convert these from string to enum.

2023-05-09 16:13 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.Framework/Models/SelectOption.cs
> +            else
`else` is redundant here since the `if` returns from the method.

2023-05-09 16:13 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.Services/Solutions/SolutionsFilterService.cs
> +                        int presentCount = 0;
The current `presentCount` logic means this behaves as an _**OR**_. As in, it searches for Client App Type A _OR_ B rather than A _AND_ B.

I appreciate it's not easy because the Client Application Type schema is, well, terrible.

In order to do this as an _AND_ then lines 73-82 can be replaced with a LINQ `.Where` statement on the `clientApplicationTypes` array from line #67.

The `.Where` should use `HasClientApplicationType`. You can then use `.Count` on this result. If the `.Count` is less than the number of elements in `clientApplicationTypes` then that means the solution does not reference all selected Client Application Types and the `query.Where` statement should be updated accordingly to exclude the row ID

2023-05-10 07:17 UTC, dssherlock commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Controllers/SolutionsController.cs
> +
Could this be moved into the AdditionalFiltersModel as a Get property?

2023-05-10 08:42 UTC, bjss-colin requested changes

2023-05-10 08:42 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.Services/Solutions/SolutionsFilterService.cs
> +            string[] clientApplicationTypes = clientApplicationTypeSelected?.Split(',');
These can be combined since `clientApplicationTypes` is only used in one place. Let's chain the `.Select` to the end, but also let's add a `.Where` that uses `Enum.IsDefined` in order to only parse valid entries, since the user could manipulate the URL manually.

2023-05-10 08:42 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.Services/Solutions/SolutionsFilterService.cs
> +            if (query != null)
Let's move this if condition to the top of the method to reduce the level of nesting in the code. If the query is null then the rest of the method shouldn't execute.

2023-05-10 08:42 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.Services/Solutions/SolutionsFilterService.cs
> +                    if (!string.IsNullOrEmpty(row.Solution.ClientApplication))
Similarly here, in order to reduce nesting if the `ClientApplication` is null/empty then update the query and `continue`.

2023-05-10 09:59 UTC, bjss-colin requested changes

2023-05-10 09:59 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Models/Filters/AdditionalFiltersModel.cs
> +            })
This list needs to be ordered alphabetically

2023-05-10 10:22 UTC, dssherlock commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Controllers/SolutionsController.cs
> +            string selectedFrameworkId,
I wonder if this parameter should be selectedClientApplicationTypeIds (to match the capability and epic naming) if it is doing a similar thing (linking several together in a string)

2023-05-10 11:40 UTC, dssherlock commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Models/Filters/AdditionalFiltersModel.cs
> +            {
Should this use the FilterConstants.Delimiter as per the Epic and Capability IDs?

2023-05-10 12:02 UTC, DeepikaDK001 commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Models/Filters/AdditionalFiltersModel.cs
> +            {
yes that makes sense ..

2023-05-10 13:09 UTC, bjss-colin requested changes

2023-05-10 13:09 UTC, ghost commented on src/NHSD.GPIT.BuyingCatalogue.Services/Solutions/SolutionsFilterService.cs
> +                    continue;
Shouldn't this also also exclude this record because it doesn't have a ClientApplication?

2023-05-10 13:09 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.ServiceContracts/Solutions/ISolutionsFilterService.cs
> +       IQueryable<CatalogueItem> GetClientApplicationTypeFilterQuery(IQueryable<CatalogueItem> query, string selectedClientApplicationTypeIds);
This doesn't need to be part of the interface because it isn't actually used anywhere other than in the `SolutionsFilterService`

2023-05-10 13:30 UTC, DeepikaDK001 commented on src/NHSD.GPIT.BuyingCatalogue.Services/Solutions/SolutionsFilterService.cs
> +                    continue;
Sorry mistakenly removed it..

2023-05-11 08:24 UTC, bjss-colin requested changes

2023-05-11 08:24 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.Services/Solutions/SolutionsFilterService.cs
> +            var clientApplicationTypeEnums = selectedClientApplicationTypeIds?.Split(FilterConstants.Delimiter).Select(t => (ClientApplicationType)Enum.Parse(typeof(ClientApplicationType), t));
Don't forget about the suggested `.Where` statement, after the `.Split`, which uses `Enum.IsDefined` in order to only parse valid results.

At the moment a user can manipulate the URL and type any values in which would cause this code to throw an exception. Try it out locally by changing the values in the URL.

2023-05-11 08:24 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Models/Filters/AdditionalFiltersModel.cs
> +            ClientApplicationTypeOptions = Enum.GetValues(typeof(ClientApplicationType))
Since this code is now greatly reduced, this can be moved to the constructor and the method can be deleted

2023-05-11 10:35 UTC, imranbashir01 approved these changes

2023-05-11 10:45 UTC, bjss-colin approved these changes

2023-05-11 10:46 UTC, merged