Feature/21767 save filter query
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #1110
Opened 2023-05-11 09:50 UTC by dssherlock

2023-05-12 09:54 UTC, DeepikaDK001 commented on src/NHSD.GPIT.BuyingCatalogue.EntityFramework/Catalogue/Models/ClientApplicationType.cs
>      }
For the both enums - ClientApplicationType and HostingType, we can parse the Integer values with the Enum.TryParse() method irrespective of those integer values are defined in the Enum or not

2023-05-12 10:18 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.EntityFramework/Catalogue/Models/ClientApplicationType.cs
>      }
Exactly that. We can't change the value of the enums because it'll affect the interpretation of data. The values behind an Enum default at 0, so BrowserBased is 0 while MobileTablet is 1. After this change it's possible that the application will treat all `MobileTablet` applications as `BrowserBased`, and `Desktop` will be treated as `MobileTablet`.

Same applies to `HostingType` too.

2023-05-12 11:55 UTC, imranbashir01 submitted a review, later dismissed

2023-05-15 09:13 UTC, bjss-colin requested changes

2023-05-15 09:13 UTC, ghost commented on database/NHSD.GPITBuyingCatalogue.Database/NHSD.GPITBuyingCatalogue.Database.sqlproj
>    <Import Condition="'$(SQLDBExtensionsRefPath)' != ''" Project="$(SQLDBExtensionsRefPath)\Microsoft.Data.Tools.Schema.SqlTasks.targets" />
Let's add some Post-Deployment scripts to populate the database with test data too

2023-05-15 09:13 UTC, ghost commented on src/NHSD.GPIT.BuyingCatalogue.EntityFramework/Filtering/Configuration/FilterEntityTypeConfiguration.cs
> +                .HasMaxLength(10);
This should be 36, based on the recent changes for Framework Management Admin pages.

2023-05-15 09:13 UTC, ghost commented on src/NHSD.GPIT.BuyingCatalogue.EntityFramework/Filtering/Models/Filter.cs
> +    public partial class Filter : IAudited
`IAudited` could be preserved on `FIlter` in order to know who created it, but it's not necessary on `FilterCapability`, `FilterEpic`, `FilterHostingType`, `FilterClientApplicationType` since these can't change once a fitler is created.

2023-05-15 09:13 UTC, ghost commented on src/NHSD.GPIT.BuyingCatalogue.Services/ServiceHelpers/SolutionsFilterHelper.cs
> +                .Where(x => Enum.TryParse(typeof(ClientApplicationType), x, out var catValue) && Enum.IsDefined(typeof(ClientApplicationType), catValue))
`TryParse` and `Enum.IsDefined` yield the same result. `IsDefined` would be better IMO since there are less allocations taking place.

2023-05-15 09:13 UTC, ghost commented on src/NHSD.GPIT.BuyingCatalogue.Services/ServiceHelpers/SolutionsFilterHelper.cs
> +                .Where(x => Enum.TryParse(typeof(HostingType), x, out var hostingValue) && Enum.IsDefined(typeof(HostingType), hostingValue))
Same as above

2023-05-15 09:13 UTC, ghost commented on src/NHSD.GPIT.BuyingCatalogue.ServiceContracts/Solutions/IManageFiltersService.cs
> +        Task AddFilterCapabilities(int filterId, List<int> capabilityIds);
The `Add` methods, except `AddFilter`, don't need to be exposed via an interface since they're only used in the `ManageFiltersService` class. As far as I know, filters can't be edited once they've been saved.

2023-05-15 09:13 UTC, ghost commented on src/NHSD.GPIT.BuyingCatalogue.Services/Solutions/ManageFiltersService.cs
> +        public async Task AddFilterCapabilities(int filterId, List<int> capabilityIds)
`Add` methods, except `AddFilter`, can be marked as private here - see comment on the interface type. Alternatively mark as `internal` if they're unit tested.

2023-05-15 09:13 UTC, ghost commented on database/NHSD.GPITBuyingCatalogue.Database/Filtering/Tables/FilterHostingTypes .sql
> +﻿CREATE TABLE filtering.FilterHostingTypes
There's a space in this filename between `FilterHostingTypes` and `.sql`

2023-05-15 11:52 UTC, imranbashir01 approved these changes, later dismissed

2023-05-16 08:24 UTC, bjss-colin commented
Note that I did hput some comments regarding temporal tables, which you may see in your emails. I've since deleted these as we can actually use the Temporal functionality of the Filters as part of Gen 2.

In other words, let's stick with the usage of Temporal tables.

2023-05-17 08:32 UTC, dssherlock commented on src/NHSD.GPIT.BuyingCatalogue.Services/Solutions/ManageFiltersService.cs
> +        public async Task AddFilterCapabilities(int filterId, List<int> capabilityIds)
They originally were all private. But then i tried to be clever and make them public for the manage filters ticket!

2023-05-17 08:34 UTC, dssherlock commented on src/NHSD.GPIT.BuyingCatalogue.ServiceContracts/Solutions/IManageFiltersService.cs
> +        Task AddFilterCapabilities(int filterId, List<int> capabilityIds);
See above! Easy to swap back

2023-05-17 08:50 UTC, dssherlock commented on src/NHSD.GPIT.BuyingCatalogue.Services/ServiceHelpers/SolutionsFilterHelper.cs
> +                .Where(x => Enum.TryParse(typeof(ClientApplicationType), x, out var catValue) && Enum.IsDefined(typeof(ClientApplicationType), catValue))
TryParse returns success (and a value) for values that haven't actually been defined. E.g. if gave the function the string 1.6 it would return 2 values rather than filtering out the 6 which isnt actually defined as anything.

2023-05-17 08:50 UTC, dssherlock commented on src/NHSD.GPIT.BuyingCatalogue.Services/ServiceHelpers/SolutionsFilterHelper.cs
> +                .Where(x => Enum.TryParse(typeof(HostingType), x, out var hostingValue) && Enum.IsDefined(typeof(HostingType), hostingValue))
Same as above!

2023-05-17 09:13 UTC, bjss-colin requested changes

2023-05-17 09:13 UTC, ghost commented on src/NHSD.GPIT.BuyingCatalogue.EntityFramework/Filtering/Configuration/FilterCapabilityEntityTypeConfiguration.cs
> +            builder.ToTable("FilterCapabilities", Schemas.Filtering);
Since these have support for Temporal tables, all `ToTable` calls will need a third parameter of `b => b.IsTemporal()`. There are some examples of this available in other Configuration classes.

2023-05-17 09:13 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.Services/Solutions/ManageFiltersService.cs
> +        public async Task AddFilterCapabilities(int filterId, List<int> capabilityIds)
I may be out of the loop in terms of requirements, but what will the Manage Filters ticket be doing? Capabilities, Epics and Additional Filters can't be changed by the user once their filter is created, so the writing is a one time operation that takes place via  `AddFilter`.

All of the methods can still exist, they just don't need to be public unless the requirements on adding/editing filters has changed.

2023-05-17 09:13 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.Services/ServiceHelpers/SolutionsFilterHelper.cs
> +                .Where(x => Enum.TryParse(typeof(ClientApplicationType), x, out var catValue) && Enum.IsDefined(typeof(ClientApplicationType), catValue))
`IsDefined` does have an overload which accepts an object rather than the specific `Enum` type. Hence, parsing isn't required in order to call `IsDefined`. In this case parsing occurs twice, once in `.Where` and again in `.Select`

2023-05-17 09:24 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.Services/ServiceHelpers/SolutionsFilterHelper.cs
> +                .Where(x => Enum.TryParse(typeof(ClientApplicationType), x, out var catValue) && Enum.IsDefined(typeof(ClientApplicationType), catValue))
`IsDefined` does have an overload which accepts an object rather than the specific `Enum` type. Hence, parsing isn't required in order to call `IsDefined`. In this case parsing occurs twice, once in `.Where` and again in `.Select`

2023-05-17 09:24 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.Services/Solutions/ManageFiltersService.cs
> +        public async Task AddFilterCapabilities(int filterId, List<int> capabilityIds)
I may be out of the loop in terms of requirements, but what will the Manage Filters ticket be doing? Capabilities, Epics and Additional Filters can't be changed by the user once their filter is created, so the writing is a one time operation that takes place via AddFilter.

All of the methods can still exist, they just don't need to be public unless the requirements on adding/editing filters has changed.

2023-05-17 09:39 UTC, dssherlock commented on src/NHSD.GPIT.BuyingCatalogue.EntityFramework/Filtering/Configuration/FilterCapabilityEntityTypeConfiguration.cs
> +            builder.ToTable("FilterCapabilities", Schemas.Filtering);
There only seem to be 2 uses of this? The Suppliers table and the AspNetUsers table?

2023-05-17 09:39 UTC, dssherlock commented on src/NHSD.GPIT.BuyingCatalogue.EntityFramework/Filtering/Configuration/FilterCapabilityEntityTypeConfiguration.cs
> +            builder.ToTable("FilterCapabilities", Schemas.Filtering);
Why are these special?!

2023-05-17 09:45 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.EntityFramework/Filtering/Configuration/FilterCapabilityEntityTypeConfiguration.cs
> +            builder.ToTable("FilterCapabilities", Schemas.Filtering);
`IEntityTypeConfiguration<T>` is applied during model building in EF Core and tells EF Core how the model is made up.

More importantly, if we use a code-first approach, as we do in the Integration tests (`EnsureCreated`), and EF Core isn't aware of temporal tables then any Temporal queries will fail.

2023-05-17 10:16 UTC, dssherlock commented on src/NHSD.GPIT.BuyingCatalogue.Services/ServiceHelpers/SolutionsFilterHelper.cs
> +                .Where(x => Enum.TryParse(typeof(ClientApplicationType), x, out var catValue) && Enum.IsDefined(typeof(ClientApplicationType), catValue))
But you would still need to do an int.parse? Enum.IsDefined(typeof(ClientApplicationType), "1") returns false because u are passing it "1" not 1. It would work if you passed it the string name.

2023-05-17 10:32 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.Services/ServiceHelpers/SolutionsFilterHelper.cs
> +                .Where(x => Enum.TryParse(typeof(ClientApplicationType), x, out var catValue) && Enum.IsDefined(typeof(ClientApplicationType), catValue))
Good point actually. Just tested this locally too. In that case it looks like the code in `SolutionsFilterService` is somehow behaving correctly despite not parsing first. We can revisit that one separately.

2023-05-18 08:19 UTC, bjss-colin approved these changes

2023-05-18 09:17 UTC, samdasari9 approved these changes

2023-05-18 09:20 UTC, merged