Feature/21806 manage filters summary
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #1125
Opened 2023-05-18 15:00 UTC by dssherlock

2023-05-18 15:33 UTC, bjss-colin requested changes
Just a few minor points

2023-05-18 15:33 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Controllers/ManageFiltersController.cs
> +                BackLinkText = "Go back",
`Go back` is the default value so no assignment to `BackLinkText` is needed her

2023-05-18 15:33 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Controllers/ManageFiltersController.cs
>              var existingFilters = await manageFiltersService.GetFilters(organisationId);
`GetFilters` returns _everything_ that lives under a filter. We've previously had issues with performance when doing this, particularly when it's a dashboard

It's worth adding a new method to the `FilterService` that returns just the filter with no navigational properties because all you're really after here is the Name, Description and Last Updated date.

As a separate point, it's worth adding `AsSplitQuery` to the implementation of `GetFilters` in order to prevent a [cartesian explosion](https://www.thinktecture.com/en/entity-framework-core/cartesian-explosion-problem-in-3-1/).

2023-05-18 15:33 UTC, ghost commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/ManageFilters/Index.cshtml
> +            <p>@Model.Filters.Count() saved search @filters.</p>
Since `Filters` is a `List<T>`, you can use `Count` here rather than LINQ's `Count()`

2023-05-19 07:00 UTC, dssherlock commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Controllers/ManageFiltersController.cs
>              var existingFilters = await manageFiltersService.GetFilters(organisationId);
Thinking about it, do we really need to add another method (i.e GetFiltersThin)? I think we can just replace GetFilters altogether as we only need all the details for a specific Filter on the Details page?

2023-05-19 11:07 UTC, imranbashir01 approved these changes, later dismissed

2023-05-19 13:11 UTC, imranbashir01 approved these changes

2023-05-19 13:14 UTC, bjss-colin approved these changes

2023-05-19 13:17 UTC, merged