Filtering - Add Detailed view of a saved filter
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #1133
Opened 2023-05-23 10:25 UTC by martinkimmings

2023-05-23 10:56 UTC, bjss-colin requested changes

2023-05-23 10:56 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/ManageFilters/DeleteFilter.cshtml
> +﻿@using NHSD.GPIT.BuyingCatalogue.UI.Components.TagHelpers
Let's remove this page for now as the story is currently being worked on

2023-05-23 10:56 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Controllers/ManageFiltersController.cs
> +        public IActionResult DeleteFilter(int filterId)
Let's remove this one for now also, same reason as below.

2023-05-23 10:56 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.Services/Solutions/ManageFiltersService.cs
> +            return dbContext.Filters.Where(o => o.Id == filterId)
There's a risk of this resulting in a cartesian explosion - can be resolved by adding `AsSplitQuery()`.

Additionally, the `Where` can be dropped and the query can be added to the `FirstOrDefaultAsync`. Also worth adding `AsNoTracking`

2023-05-23 10:56 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Models/ManageFilters/FilterDetailsModel.cs
> +        public Dictionary<string, IOrderedEnumerable<Epic>> GroupedCapabilities { get; init; }
`IOrderedEnumerable` is being enumerated multiple times in the View. `ToList` on the query, line 29, should fix this.

2023-05-23 10:56 UTC, bjss-colin commented on tests/NHSD.GPIT.BuyingCatalogue.Services.UnitTests/Solutions/ManageFiltersServiceTests.cs
> +            await context.SaveChangesAsync();
Do we need to clear the `ChangeTracker` here to ensure it's not returning a cached copy?

2023-05-24 09:01 UTC, bjss-colin approved these changes

2023-05-24 12:14 UTC, imranbashir01 approved these changes

2023-05-24 12:17 UTC, merged