Filtering - Delete Saved Filter
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #1136
Opened 2023-05-25 09:54 UTC by DeepikaDK001

2023-05-25 10:38 UTC, bjss-colin requested changes

2023-05-25 10:38 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/ManageFilters/DeleteFilter.cshtml
> +            @Html.HiddenFor(model => model.FilterId)
Have a look at other examples in the app on how to add hidden inputs.

2023-05-25 10:38 UTC, bjss-colin commented on tests/NHSD.GPIT.BuyingCatalogue.Services.UnitTests/Solutions/ManageFiltersServiceTests.cs
> +            await dbContext.SaveChangesAsync();
Call `dbContext.ChangeTracker.Clear()` after `dbContext.SaveChangesAsync()` in order to ensure that EF Core isn't caching the `Filter`

2023-05-25 10:38 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/ManageFilters/DeleteFilter.cshtml
> +
Lots of whitespace throughout this page can be removed. Be sure to run Visual Studio's code formatter to ensur elements are indented correctly.

2023-05-25 10:38 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.Services/Solutions/ManageFiltersService.cs
> +        public async Task SoftDeleteFilter(int filterId)
This can be named as `DeleteFilter`. The fact that it's a soft delete is just an implementation detail.

2023-05-25 10:38 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Controllers/ManageFiltersController.cs
> +            var filter = await manageFiltersService.GetFilter(filterId);
In this and the POST method there's the risk that a user can enumerate the Filter IDs, belonging to other organisations, and delete them. Both methods need to validate that the filter belongs to the users organisation.

2023-05-25 10:38 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Controllers/ManageFiltersController.cs
> +            var model = new FilterDetailsModel()
Let's create a new model rather than repurposing this one.

2023-05-25 10:38 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/ManageFilters/DeleteFilter.cshtml
> +            <a href="@Url.Action("Index", "ManageFilters")">Cancel</a>
See other examples for how we use `Url.Action` as this doesn't follow the convention

2023-05-31 12:25 UTC, bjss-colin commented
Closing this one for now as there are quite a few merge conflicts to handle

2023-06-01 13:41 UTC, bjss-colin requested changes

2023-06-01 13:41 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.ServiceContracts/Solutions/IManageFiltersService.cs
> -        Task<FilterDetailsModel> GetFilterDetails(int organisationId, int filterId);
This method is required

2023-06-02 08:57 UTC, bjss-colin requested changes
Mostly looking good - just some minor points

2023-06-02 08:57 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Controllers/ManageFiltersController.cs
> +        public async Task<IActionResult> DeleteFilterConfirmed(int filterId)
This could be renamed to `DeleteFilter`, but the parameters would need to be updated to pass the `DeleteFilterModel` parameter.

Take a peek at some other Delete forms that we've implemented to see what I mean.

2023-06-02 08:57 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/ManageFilters/DeleteFilter.cshtml
> +        <form method="post" asp-action="DeleteFilterConfirmed" asp-controller="ManageFilters">
`asp-action` and `asp-controller` can be removed with the above changes suggested in the controller

2023-06-02 08:57 UTC, bjss-colin commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Utils/SeedData/FiltersSeedData.cs
> +using NHSD.GPIT.BuyingCatalogue.ServiceContracts.Identity;
Looks like this import may not be used since there are no other changes in this file

2023-06-02 08:57 UTC, bjss-colin commented on tests/NHSD.GPIT.BuyingCatalogue.Services.UnitTests/Solutions/ManageFiltersServiceTests.cs
> +            Organisation organisation,
I'm curious about these changes - are organisations required for all of these tests?

2023-06-02 08:57 UTC, bjss-colin commented on tests/NHSD.GPIT.BuyingCatalogue.WebApp.UnitTests/Areas/Solutions/Models/Filters/DeleteFilterModelTests.cs
> +        public static void Constructor_InitializesProperties(string filterName, int filterId)
The constructor isn't actually being used here to assign the properties. Lines 16-19 demonstrate the Object Initializer syntax.

See the following link for a ocmparison between an object initializer and a constructor that assigns properties https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/object-and-collection-initializers#object-initializers

Since you're using the object initializer here the values are always going to be assigned - as such there's nothing to test.

**Add** a _**new**_ constructor to `DeleteFilterModel` that accepts the Filter ID and Name, then assigning these to the properties. Leave the parameterless constructor as it currently is, in `DeleteFilterModel`, since this will be required by ASP.NET Core's model binders when submitting forms.

2023-06-02 08:57 UTC, bjss-colin commented on tests/NHSD.GPIT.BuyingCatalogue.WebApp.UnitTests/Areas/Solutions/Controllers/ManageFiltersControllerTests.cs
> +            var viewResult = Assert.IsType<ViewResult>(result);
This combines usage of FluentAssertions and `Assert`. See the preceding tests for an example on how to validate a type of result, such as `ViewResult`

2023-06-02 08:57 UTC, bjss-colin commented on tests/NHSD.GPIT.BuyingCatalogue.Services.UnitTests/Solutions/ManageFiltersServiceTests.cs
> +            context.ChangeTracker.Clear();
`ChangeTracker.Clear` should be called after the `SaveChangesAsync` on line 630.

2023-06-02 08:57 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Controllers/ManageFiltersController.cs
> +                BackLink = Url.Action(nameof(FilterDetails), typeof(ManageFiltersController).ControllerName(), new { filterId }),
`typeof(ManageFiltersController)` can be removed here since `FilterDetails` already lives in the same controller as `DeleteFilter`. Specifying the controller is only required if you're generating a link from a View, or the link is going across to another controller.

2023-06-02 09:12 UTC, imranbashir01 approved these changes

2023-06-02 09:18 UTC, DeepikaDK001 commented on tests/NHSD.GPIT.BuyingCatalogue.Services.UnitTests/Solutions/ManageFiltersServiceTests.cs
> +            context.ChangeTracker.Clear();
My understanding is, **ChangeTracker.Clear** used to clear method is used to clear the change made to the entities like addition, modification and deletion. I called it in the last to keep track of the changes made to the entity that is delete. if I bring before that, the test fails.

2023-06-02 09:22 UTC, DeepikaDK001 commented on tests/NHSD.GPIT.BuyingCatalogue.Services.UnitTests/Solutions/ManageFiltersServiceTests.cs
> +            Organisation organisation,
when I run the tests all the existing tests that changes were made are failing that they were not adding Filters in the statement - context.Filters.Add(filter); and throws the error - value cannot be null. without adding Organisations - context.Organisations.Add(organisation); . Still I'm not able to figure that out.

2023-06-02 09:22 UTC, bjss-colin commented on tests/NHSD.GPIT.BuyingCatalogue.Services.UnitTests/Solutions/ManageFiltersServiceTests.cs
> +            context.ChangeTracker.Clear();
Calling it last is somewhat redundant since the test has already finished running. The context is no longer being used and so there's no reason to refresh the cache.

It must be called after the `SaveChangesAsync` to clear the cache so that `ManageFiltersService` is going to the In-memory database and not the cache.

If the test is faling, with `ChangeTracker.Clear` moved further up, then it will be due to a valid issue that would need to be addressed.

2023-06-02 09:26 UTC, bjss-colin commented on tests/NHSD.GPIT.BuyingCatalogue.Services.UnitTests/Solutions/ManageFiltersServiceTests.cs
> +            Organisation organisation,
Not a problem - I'll mark this as resolved as it sounds like a test data issue that you've resolved

2023-06-02 12:13 UTC, bjss-colin commented on tests/NHSD.GPIT.BuyingCatalogue.WebApp.UnitTests/Areas/Solutions/Models/Filters/DeleteFilterModelTests.cs
> +        public static void Constructor_InitializesProperties(string filterName, int filterId)
This test still needs to be updated because it's still using the object initializer syntax

2023-06-02 12:19 UTC, bjss-colin requested changes

2023-06-02 12:19 UTC, bjss-colin commented on tests/NHSD.GPIT.BuyingCatalogue.WebApp.UnitTests/Areas/Solutions/Controllers/ManageFiltersControllerTests.cs
> +            var result = await controller.DeleteFilter(deleteFilterModel);
Since `DeleteFilterModel` is now being passed as a parameter don't forget that `deleteFilterModel.FilterId` needs to be assigned a value since `manageFiltersService` is being configured to return `FilterDetailsModel` when called with `filterId`, but is returning a `filterDetailsModel` which _also_ contains an `Id` property. There are essentially 3 different filter IDs being used in this test so it's not actually validating that the `ManageFilterService.DeleteFilter` method is being called.

Best option would be to remove `filterId` from Line 410, assign `filterDetailsModel.Id` to `deleteFilterModel.Id` and also update the service stubbing on Line 424 to reference `filterDetailsModel.Id` rather than `filterId`. Also add a `Verify` to confirm that `ManageFilterService.DeleteFilter` is being called at least one.

2023-06-02 12:19 UTC, ghost commented on tests/NHSD.GPIT.BuyingCatalogue.Services.UnitTests/Solutions/ManageFiltersServiceTests.cs
> +        {
Don't forget to add `filter.IsDeleted = false;` here to ensure it isn't created/seeded in a deleted state.

2023-06-02 12:46 UTC, DeepikaDK001 commented on tests/NHSD.GPIT.BuyingCatalogue.WebApp.UnitTests/Areas/Solutions/Models/Filters/DeleteFilterModelTests.cs
> +        public static void Constructor_InitializesProperties(string filterName, int filterId)
sorry forgot to update this one. now it is added.

2023-06-02 13:51 UTC, bjss-colin approved these changes

2023-06-02 13:54 UTC, imranbashir01 approved these changes

2023-06-02 13:55 UTC, merged