Display the legal supplier name in the contract, pdf and csv
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #1147
Opened 2023-06-06 13:14 UTC by DeepikaDK001

2023-06-06 15:38 UTC, bjss-colin requested changes

2023-06-06 15:38 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.Services/Csv/CsvService.cs
> +            return (output?.Id ?? 0, string.Equals(output.Name, output.LegalName, StringComparison.OrdinalIgnoreCase) ? output.Name : output.LegalName ?? string.Empty);
`?? string.Empty` is only being applied to the legal name. An exception will also be thrown if `output` is null since the null-conditional operator has been removed (see the differences between the previous and current files).

Maybe consider assigning `output.Name` and `output.LegalName` to two separate variables, ensuring to use the original format of the null conditional and null coalescing operators in both variables. Then use the ternary to check for equality picking the variable based on the outcome.

2023-06-07 14:14 UTC, samdasari9 approved these changes

2023-06-07 14:14 UTC, samdasari9 approved these changes

2023-06-07 14:17 UTC, bjss-colin approved these changes

2023-06-07 14:17 UTC, merged