Feature/21527 1a add bespoke milestones
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #1153
Opened 2023-06-14 08:59 UTC by dssherlock

2023-06-14 10:23 UTC, bjss-colin requested changes

2023-06-14 10:23 UTC, ghost commented on database/NHSD.GPITBuyingCatalogue.Database/NHSD.GPITBuyingCatalogue.Database.sqlproj
> +    <Build Include="Cache\SessionData.sql" />
Although it's a PITA since this happens automatically, let's revert this to the left hand glob convention for now.

The SQL Project is using a new SDK by Microsoft to bridge the gap between SQL Projects and .NET/.NET Core. They'll eventually release an update for SSDT to support this better too.

2023-06-14 10:23 UTC, ghost commented on database/NHSD.GPITBuyingCatalogue.Database/Ordering/Tables/Contracts.sql
> +) WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = ordering.Contracts_History));
We shouldn't need temporal functionality on this since it's just a link table that joins the order and contractual information together.

2023-06-14 10:23 UTC, ghost commented on src/NHSD.GPIT.BuyingCatalogue.EntityFramework/Ordering/Configuration/ContractEntityTypeConfiguration.cs
> +                .WithMany()
This should be a one to one since there's no central place for implementation plans to be managed/shared across orders and I don't believe we allow users to preselect previous implementation plans. A user will add an implementation plan to an order that will be tied to that specific order. One order has one contract that has one implementation plan.

2023-06-14 10:23 UTC, ghost commented on database/NHSD.GPITBuyingCatalogue.Database/Ordering/Tables/Contracts.sql
> +    LastUpdatedBy int NULL,
Auditing (`LastUpdatedBy`) probably not needed her also for the same reason as below.

2023-06-14 10:23 UTC, ghost commented on src/NHSD.GPIT.BuyingCatalogue.Services/Contracts/ImplementationPlanService.cs
> +        public async Task<int> AddBespokeMilestone(int contractId, string name, string paymentTrigger)
Nothing currently stops users from manipulating the URL to enumerate contracts. Consider adding an order ID too.

2023-06-14 10:23 UTC, ghost commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Orders/Models/Orders/SummaryModel.cs
> +            DefaultPlan = defaultPlan ?? throw new ArgumentNullException(nameof(defaultPlan));
This shouldn't ever be null since there should always be a default implementation plan. Although if it is null then we should handle it gracefully as exceptions are expensive to throw.

2023-06-14 10:23 UTC, ghost commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Orders/Views/Shared/MilestoneTable.cshtml
> +    var milestones = Model?.Milestones ?? new List<ImplementationPlanMilestone>();
This can be done in the model

2023-06-14 10:23 UTC, ghost commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Orders/Models/Shared/MilestoneTableModel.cs
> +        public ICollection<ImplementationPlanMilestone> Milestones { get; set; }
This can be `IEnumerable<ImplementationPlanMilestones>` and then `Enumerable.Empty<ImplementationPlanMilestones>()` could be used rather than `new List<T>()` since the former won't allocate new memory on each instance

2023-06-14 10:23 UTC, bjss-colin commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Areas/Ordering/Contracts/ImplementationPlans/ImplementationPlan.cs
> +                context.ContractFlags.Remove(contract);
Since integration tests share state in the same `Collection`, does the removal of ContractFlags cause any other tests to fail when run locally?

2023-06-14 10:23 UTC, bjss-colin commented on tests/NHSD.GPIT.BuyingCatalogue.Services.UnitTests/Contracts/ImplementationPlanServiceTests.cs
> +        public static async Task AddBespokeMilestone_NullImplementationPlan_IpAndMilestoneCreated(
Let's use something like `PlanAndMilestoneCreated` rather than `Ip` since it has many meanings in computing

2023-06-14 10:23 UTC, bjss-colin commented on tests/NHSD.GPIT.BuyingCatalogue.Services.UnitTests/Contracts/ImplementationPlanServiceTests.cs
> +            await context.SaveChangesAsync();
In order to ensure Entity Framework hasn't cached anything, call `context.ChangeTracker.Clear()` after `SaveChanges`/`SaveChangesAsync` when seeding test data

2023-06-14 13:36 UTC, dssherlock commented on tests/NHSD.GPIT.BuyingCatalogue.Services.UnitTests/Contracts/ImplementationPlanServiceTests.cs
> +            await context.SaveChangesAsync();
Just at the end of the test?

2023-06-14 13:55 UTC, bjss-colin commented on tests/NHSD.GPIT.BuyingCatalogue.Services.UnitTests/Contracts/ImplementationPlanServiceTests.cs
> +            await context.SaveChangesAsync();
Immediately after `SaveChanges`/`SaveChangesAsync` when seeding test data

2023-06-14 15:49 UTC, dssherlock commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Areas/Ordering/Contracts/ImplementationPlans/ImplementationPlan.cs
> +                context.ContractFlags.Remove(contract);
All tests currently failing :(
Looking into it

2023-06-15 08:47 UTC, bjss-colin commented on tests/NHSD.GPIT.BuyingCatalogue.Services.UnitTests/Contracts/ImplementationPlanServiceTests.cs
> +            await context.SaveChangesAsync();
This one isn't quite there yet. `context.ChangeTracker.Clear` needs to go _immediately after_ `SaveChanges`/`SaveChangesAsync` when seeding the test data. So in this file there needs to be calls to `context.ChangeTracker.Clear()` on lines 138, 177, and in `ContractsServiceTests` on lines 40, 74 and 112, 

Doing this ensures the service _isn't_ using EF Core's cache and is going to to the "database". We've discovered several tests in the past that haven't behaved as expected due to this, with @martinkimmings finding some more recently relating to the JSON columns PR.

2023-06-15 09:34 UTC, dssherlock commented on tests/NHSD.GPIT.BuyingCatalogue.Services.UnitTests/Contracts/ImplementationPlanServiceTests.cs
> +            await context.SaveChangesAsync();
Ah i see-ok that makes more sense. Ok I'll update that

2023-06-15 09:54 UTC, imranbashir01 approved these changes

2023-06-15 11:02 UTC, bjss-colin approved these changes

2023-06-15 11:15 UTC, merged