Marketing : menu item 2 Features
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #1173
Opened 2023-07-05 14:19 UTC by DeepikaDK001

2023-07-05 14:55 UTC, bjss-colin requested changes

2023-07-05 14:55 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.UI.Components/Views/Shared/TagHelpers/Card/CardTagHelper.cs
> +        private TagBuilder BuildContent(TagHelperContent childContent)
Pass `TagHelperOutput` here rather than `TagHelperContent`.

2023-07-05 14:55 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.UI.Components/Views/Shared/TagHelpers/Card/CardTagHelper.cs
> +            if (string.IsNullOrWhiteSpace(Text))
This condition is redundant if `TagHelperOutput` is passed as the check only needs to be performed in one place that is the `BuildCardText` method

2023-07-05 14:55 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.UI.Components/Views/Shared/TagHelpers/Card/CardTagHelper.cs
> +                cardText.InnerHtml.Append(Text);
Return early, after this line, to reduce nesting in the rest of the method.

2023-07-05 14:55 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.UI.Components/Views/Shared/TagHelpers/Card/CardTagHelper.cs
> +        private TagBuilder BuildCardText(TagHelperContent childContent)
Pass `TagHelperOutput` here rather than `TagHelperContent` and apply the conditional check only in this method

2023-07-05 14:55 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/Solutions/Features.cshtml
> +                            <ul>
Indentation is a bit off. Let's run this file through Visual Studio's formatter

2023-07-05 14:55 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/Solutions/Description.cshtml
> +            <nhs-card style="white-space: pre-line" title="Full description">
Since the card supports embedded HTML now, this style can be removed and can instead be applied in a `<p></p>` tag that wraps the Description.

2023-07-05 16:23 UTC, imranbashir01 approved these changes

2023-07-06 11:30 UTC, bjss-colin approved these changes

2023-07-06 11:50 UTC, imranbashir01 approved these changes

2023-07-06 11:52 UTC, merged