Gen2 import and CompliancyLevelId schema change
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #1174
Opened 2023-07-06 16:34 UTC by martinkimmings

This PR adds navigations to the new `CapabiltyEpics` join entity type from `Capability` and `Epic` in addition to the existing skip navigations for the many to many relationship between `Capability` and `Epic`

> [In a sense, this mapping provides the best of both worlds between a simple many-to-many mapping, and a mapping that more explicitly matches the database schema.](https://learn.microsoft.com/en-us/ef/core/modeling/relationships/many-to-many#many-to-many-with-navigations-to-join-entity)

We need this additional control over the join entity so that we can set and query `CompliancyLevel`

> [It is also common to create navigations to the join entity in addition to the "skip navigations" used for the many-to-many relationship. These additional navigations allow the join entity to be easily referenced from code, thereby facilitating reading and/or changing the payload data](https://learn.microsoft.com/en-us/ef/core/modeling/relationships/many-to-many#many-to-many-and-join-table-with-payload)

`CompliancyLevelId` moved to `CompatabilityEpics`

![image](https://github.com/nhs-digital-gp-it-futures/GPITBuyingCatalogue/assets/63051516/b9b4fdf5-be1f-4177-9249-b9a4c29b6eb7)

2023-07-11 12:32 UTC, bjss-colin requested changes
Two minor points

2023-07-11 12:32 UTC, bjss-colin commented on database/NHSD.GPITBuyingCatalogue.Database/Catalogue/Tables/CapabilityEpics.sql
> +    CompliancyLevelId int NULL,
Let's add an idempotent Post-Deployment script to handle the data migration for migrating all existing epics to this new CompliancyLevel format. The post deployment script should only run once based on whether there are any rows with this column being empty.

2023-07-11 12:32 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.EntityFramework/Catalogue/Models/Capability.Custom.cs
> +    public sealed partial class Capability
I've personally never been a fan of this `.Custom.cs` convention that has been used in this codebase, since it doesn't yiled much of a benefit, and have been removing any I come across. These methods could live in the `Capability` class directly.

2023-07-11 14:02 UTC, martinkimmings commented on database/NHSD.GPITBuyingCatalogue.Database/Catalogue/Tables/CapabilityEpics.sql
> +    CompliancyLevelId int NULL,
I've added `database/NHSD.GPITBuyingCatalogue.Database/PostDeployment/MigrateEpicCompliancyLevel.sql`

2023-07-12 08:20 UTC, bjss-colin requested changes
One more point, otherwise everything else looks good.

2023-07-12 08:20 UTC, ghost commented on database/NHSD.GPITBuyingCatalogue.Database/PostDeployment/MigrateEpicCompliancyLevel.sql
> +	    ON e.CapabilityId = ce.CapabilityId AND e.id = ce.EpicId
Just the Epic ID should be fine for now. The problem is that the CapabilityId column on the Epics table hasn't been in use since the 2nd or 3rd last release. There may be null values in the production database for this.

Since Epics are still a one to one, wrapped as a one to many, I don't think using just the Epic Id will cause any problems.

2023-07-13 08:55 UTC, bjss-colin approved these changes

2023-07-13 09:24 UTC, imranbashir01 approved these changes

2023-07-13 11:16 UTC, merged