Feature/2a associated service bespoke milestones
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #1175
Opened 2023-07-07 11:16 UTC by dssherlock

2023-07-11 13:11 UTC, bjss-colin requested changes

2023-07-11 13:11 UTC, ghost commented on database/NHSD.GPITBuyingCatalogue.Database/Ordering/Tables/ContractBilling.sql
> +﻿CREATE TABLE ordering.ContractBilling
This is a link table so I'm not sure if we need temporal functionality. What would be the use case?

2023-07-11 13:11 UTC, ghost commented on database/NHSD.GPITBuyingCatalogue.Database/Ordering/Tables/ContractBillingItems.sql
> +﻿CREATE TABLE ordering.ContractBillingItems
Also worth considering whether this needs temporalness. We should always evaluate the use case on a table by table basis when adding new ones.

2023-07-11 13:11 UTC, ghost commented on src/NHSD.GPIT.BuyingCatalogue.Services/Contracts/ContractBillingService.cs
> +                .Include(x => x.Order)
These includes are only required in `AddBespokeContractBillingItem`, whereas `ContractBillingController` also calls this method and discards the Order, OrderItems, CatalogueItem and ContractBilling.

Let's use a separate query in `AddBespokeContractBillingItem` and make use of the `??=` operator to conditionally assign a new instance of `ContractBilling` if it is indeed null.

2023-07-11 13:11 UTC, ghost commented on src/NHSD.GPIT.BuyingCatalogue.Services/Contracts/ContractBillingService.cs
> +                .FirstOrDefaultAsync(o => o.Id == contractId && o.OrderId == orderId) ?? throw new ArgumentException("Invalid contract", nameof(contractId));
Is there a scneario where this Contract could ever be null if the user is this far? Let's remove this exception and handle accordingly.

2023-07-11 13:11 UTC, ghost commented on src/NHSD.GPIT.BuyingCatalogue.Services/Contracts/ContractBillingService.cs
> +            var associatedService = contract.Order.GetAssociatedService(catalogueItemId) ?? throw new ArgumentException("Invalid associated service", nameof(catalogueItemId));
Same as above regarding the exception

2023-07-11 13:11 UTC, ghost commented on src/NHSD.GPIT.BuyingCatalogue.Services/Contracts/ContractBillingService.cs
> +                .FirstOrDefaultAsync(x => x.Id == orderId) ?? throw new ArgumentException("Invalid order", nameof(orderId));
Same as above regarding exception

2023-07-11 13:11 UTC, ghost commented on src/NHSD.GPIT.BuyingCatalogue.Services/Contracts/ContractBillingService.cs
> +            var associatedService = order.GetAssociatedService(catalogueItemId) ?? throw new ArgumentException("Invalid associated service", nameof(catalogueItemId));
Same as above regarding exception

2023-07-11 13:11 UTC, ghost commented on src/NHSD.GPIT.BuyingCatalogue.Services/Contracts/ContractBillingService.cs
> +            var associatedService = order.GetAssociatedService(catalogueItemId) ?? throw new ArgumentException("Invalid associated service", nameof(catalogueItemId));
You could go directly to the dbContext.OrderItems table to retrieve the associated service by Order and Item ID, since we already have this information at hand via the method parameters

2023-07-11 13:11 UTC, ghost commented on src/NHSD.GPIT.BuyingCatalogue.Services/Contracts/ContractBillingService.cs
> +            if (items.Any())
Let's invert this if statement to reduce nesting

2023-07-11 13:11 UTC, ghost commented on src/NHSD.GPIT.BuyingCatalogue.Services/Contracts/ContractBillingService.cs
> +            var contract = await AddContractBilling(orderId, contractId);
Is it possible that the `ContractBilling` object won't exist at this time? The Controller flow looks like it will exist.

2023-07-11 13:11 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.Services/Contracts/ContractsService.cs
> +            var output = await AddContract(contract, orderId);
I understand the intent behind this, but it's a bit confusing to see calls to `AddContract` in the `GetContract` method. since Get methods should usually be idempotent whereas this will have side-effects. This should return null if there's no contract, or a valid contract if there is one.

2023-07-11 13:11 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.Services/Contracts/ContractsService.cs
> +            var output = await AddContract(contract, orderId);
Same as above

2023-07-11 13:11 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.Services/Contracts/ContractsService.cs
> +            var output = await AddContract(contract, orderId);
Same as above

2023-07-11 13:11 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.Services/Contracts/ImplementationPlanService.cs
> +                .FirstOrDefaultAsync(o => o.Id == contractId && o.OrderId == orderId) ?? throw new ArgumentException("Invalid contract", nameof(contractId));
No need for an exception here if the contract isn't null, or can't be null at this point.

2023-07-11 13:11 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Orders/Views/ContractBilling/DeleteContractBillingItem.cshtml
> +                <input type="hidden" asp-for="CallOffId" />
We'll need to add the backlink as a hidden input also also

2023-07-11 13:11 UTC, bjss-colin commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/NHSD.GPIT.BuyingCatalogue.IntegrationTests.csproj
> +  <ItemGroup>
Can be removed

2023-07-12 08:55 UTC, dssherlock commented on database/NHSD.GPITBuyingCatalogue.Database/Ordering/Tables/ContractBilling.sql
> +﻿CREATE TABLE ordering.ContractBilling
The existence of a ContractBilling on the contract indicates that the Default milestones have been accepted. Felt this was worth keeping track of.

2023-07-12 09:22 UTC, dssherlock commented on database/NHSD.GPITBuyingCatalogue.Database/Ordering/Tables/ContractBillingItems.sql
> +﻿CREATE TABLE ordering.ContractBillingItems
Yep similar to above. The existing table ImplementationPlanMilestones has the temporal tables associated. This is an equivalent table so felt if it was deemed necessary for the one then it will be for this one

2023-07-12 10:03 UTC, bjss-colin commented on database/NHSD.GPITBuyingCatalogue.Database/Ordering/Tables/ContractBilling.sql
> +﻿CREATE TABLE ordering.ContractBilling
> As you say the default at present is to add them so followed the convention

Not sure if this was something agreed/decided by the previous team, I can't recall any conversations around temporal support other than it being a thing. The default _should_ be to evaluate on a case by case basis to determine whether an entity could benefit from temporal functionality, since temporal restricts some actions and introduces further complexities with data migration. Particularly with link tables, I can't imagine many scenarios where we'd take advantage of this in terms of auditing or presentation.

2023-07-12 11:44 UTC, dssherlock commented on src/NHSD.GPIT.BuyingCatalogue.Services/Contracts/ContractsService.cs
> +            var output = await AddContract(contract, orderId);
So make the AddContract public and call directly from the controller after each Get call? Feels a bit repetitive

2023-07-13 09:18 UTC, bjss-colin approved these changes

2023-07-13 09:33 UTC, samdasari9 approved these changes

2023-07-13 09:34 UTC, merged