Marketing : menu item 3 List Price and menu item 4 Capabilities.
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #1177
Opened 2023-07-10 13:37 UTC by DeepikaDK001

…pics

2023-07-10 15:01 UTC, bjss-colin requested changes

2023-07-10 15:01 UTC, ghost commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/Solutions/ListPrice.cshtml
> +    const string ContextualContent = "This is how much this Catalogue Solution costs:";
I don't think this particularly needs to be a variable since it's only used in one place.

2023-07-10 15:01 UTC, ghost commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/Solutions/Capabilities.cshtml
> +<nhs-summary-list>
HTML indentation is off. Please ensure all pages are being run through Visual Studio's code formatter, or formatted manually.

2023-07-10 15:01 UTC, ghost commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Views/CatalogueSolutions/ManageCatalogueSolution.cshtml
> +                    <nhs-table-cell>Capabilities and epics</nhs-table-cell>
Epics needs to be uppercased here

2023-07-10 15:30 UTC, bjss-colin requested changes

2023-07-10 15:30 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/Solutions/Capabilities.cshtml
> +<nhs-summary-list>
Thinking about it, this whole summary list could be a partial. The content seems to be the same across every marketing page.

2023-07-11 08:55 UTC, bjss-colin requested changes

2023-07-11 08:55 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/Solutions/_SolutionSummary.cshtml
> +﻿@using NHSD.GPIT.BuyingCatalogue.EntityFramework.Catalogue.Models;
This partial needs to be told which mode it should use. `SolutionDisplayBaseModel` is a good candidate here.

2023-07-11 08:55 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Models/ListPriceModel.cs
> +        public string SupplierName { get; }
With the inclusion of a partial, these new properties can be moved to the `SolutionDisplayBaseModel` on this class and the previous classes

2023-07-11 10:10 UTC, samdasari9 approved these changes

2023-07-11 12:34 UTC, bjss-colin approved these changes

2023-07-11 12:50 UTC, samdasari9 approved these changes

2023-07-11 12:51 UTC, merged