Feature/21870 2b requirements
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #1186
Opened 2023-07-20 10:05 UTC by dssherlock

2023-07-21 10:16 UTC, samdasari9 approved these changes

2023-07-26 09:06 UTC, bjss-colin requested changes
Just a few minor suggestions

2023-07-26 09:06 UTC, ghost commented on database/NHSD.GPITBuyingCatalogue.Database/Ordering/Tables/ImplementationPlanMilestones.sql
> +    ImplementationPlanId int NULL DEFAULT NULL,
`DEFAULT NULL` can be removed here since `NULL` is already the default for nullable columns

2023-07-26 09:06 UTC, ghost commented on database/NHSD.GPITBuyingCatalogue.Database/Ordering/Tables/ImplementationPlans.sql
> +    ContractId int NULL DEFAULT NULL,
`DEFAULT NULL` can be removed here - same reason as above

2023-07-26 09:06 UTC, ghost commented on src/NHSD.GPIT.BuyingCatalogue.Services/Contracts/ContractsService.cs
> +                .AsNoTracking()
Let's apply an `AsSplitQuery` to this query since it's joining on quite a few tables

2023-07-26 09:06 UTC, ghost commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Orders/Views/Requirement/RequirementDetails.cshtml
> +                <input type="hidden" asp-for="CallOffId"/>
Here's where things get a bit confusing - `CallOffId` and `InternalOrgId` don't actually need to be specified as hidden inputs here.

They already form part of the URL so ASP.NET Core's Model Binders will map the properties on the model based on the values from the URL, when the form is being submitted.

2023-07-26 09:06 UTC, ghost commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Orders/Views/Requirement/DeleteRequirement.cshtml
> +                <input type="hidden" asp-for="CallOffId" />
Same as below regarding `CallOffId` and `InternalOrgId`

2023-07-26 09:06 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Orders/Controllers/Contracts/RequirementController.cs
> +                    typeof(RequirementController).ControllerName(),
Optional - you could remove the `typeof(RequirementController)` here. Typically, when you're redirecting to an action in the same controller you don't need to explicitly specify the controller type. That's only necessary when you're jumping from one controller to another

2023-07-26 10:39 UTC, dssherlock commented on database/NHSD.GPITBuyingCatalogue.Database/Ordering/Tables/ImplementationPlanMilestones.sql
> +    ImplementationPlanId int NULL DEFAULT NULL,
For some reason-I havent quite got to the bottom of it yet-but if i remove this then the cascade delete seems to stop working.

2023-07-26 11:12 UTC, bjss-colin approved these changes

2023-07-26 11:13 UTC, merged