Reg amend step1 - Description
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #1191
Opened 2023-07-26 12:32 UTC by samdasari9

2023-07-26 13:36 UTC, bjss-colin requested changes

2023-07-26 13:36 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.UI.Components.WebApp/wwwroot/govuk-frontend/assets/js/govuk-frontend.min.js
> -!function(t,e){"object"==typeof exports&&"undefined"!=typeof module?e(exports):"function"==typeof define&&define.amd?define("GOVUKFrontend",["exports"],e):e(t.GOVUKFrontend={})}(this,(function(t){"us
This one shouldn't be deleted.

2023-07-27 12:49 UTC, imranbashir01 approved these changes

2023-07-27 12:55 UTC, bjss-colin approved these changes

2023-07-27 13:01 UTC, merged