Feature/22199 update admin page for gen 2 mapping
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #1193
Opened 2023-07-26 15:15 UTC by Patrick-M-BJSS

2023-07-28 10:52 UTC, bjss-colin requested changes

2023-07-28 10:52 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Views/Shared/SelectCapabilities.cshtml
> +﻿@using NHSD.GPIT.BuyingCatalogue.WebApp.Controllers
We could instead re-use the FilterCapabilities.cshtml file here as having two pages means we'd have to maintain both when there are any changes to the design

2023-07-28 10:52 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Models/Shared/SelectCapabilitiesModel.cs
> +﻿using System.Collections.Generic;
`FilterCapabilitiesModel` could also be used in place of this as it's essentially the same

2023-07-31 15:40 UTC, imranbashir01 approved these changes

2023-08-04 09:22 UTC, bjss-colin requested changes
Some minor changes and a few merge/rebase conflicts still appearing

2023-08-04 09:22 UTC, bjss-colin commented on tests/NHSD.GPIT.BuyingCatalogue.Services.UnitTests/Competitions/CompetitionsServiceTests.cs
> +    public static async Task SetCompetitionCriteria(
Looks like a merge or rebase issue as it's unrelated to this feature

2023-08-04 09:22 UTC, bjss-colin commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Areas/Admin/SupplierDefinedEpics/AddEpicCapabilities.cs
> +/*using NHSD.GPIT.BuyingCatalogue.Framework.Extensions;
This entire class is commented out. Should we remove or refactor this?

2023-08-04 09:22 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/SupplierDefinedEpics/EditSupplierDefinedEpicModel.cs
> +            CapabilityList = epic.Capabilities.First().Name;
`string.Join` will be beneficial here as it can trim down by 4-5 lines of code.

2023-08-04 09:22 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Views/SupplierDefinedEpics/EditSupplierDefinedEpicDetails.cshtml
> +            <input type="hidden" asp-for="RelatedItems" />
`RelatedItems` is a List of complex objects so using a hidden input here won't quite work. The data will need to be re-populated in the POST action on the controller when the model is in an errored state.

2023-08-04 09:22 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Controllers/SupplierDefinedEpicsController.cs
> +                var newModel = new FilterCapabilitiesModel(capabilities, false, selectedIds)
Rather than creating a new model, we should return the existing one from the parameters.

2023-08-04 09:22 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Controllers/SupplierDefinedEpicsController.cs
> +                var newModel = new FilterCapabilitiesModel(capabilities, false, null)
Same as below. We should return the same model via the parameters rather than instantiating a new one.

2023-08-04 09:22 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.UI.Components/Views/Shared/TagHelpers/Card/CardTagHelper.cs
>  ﻿using System.Text.Encodings.Web;
Potentially a rebase/merge conflict as this change has already been applied in `develop`.

2023-08-04 09:22 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.Services/Capabilities/SupplierDefinedEpicsService.cs
> +        private async Task<List<Capability>> GetCapabilities(AddEditSupplierDefinedEpic epicModel)
This method could be removed and shortened, further up in `EditSupplierDefinedEpic`, to something like `dbContext.Capabilities.Where(x => epicModel.CapabilityIds.Contains(x.Id)).ToListAsync();`

2023-08-08 13:24 UTC, Patrick-M-BJSS commented on tests/NHSD.GPIT.BuyingCatalogue.Services.UnitTests/Competitions/CompetitionsServiceTests.cs
> +    public static async Task SetCompetitionCriteria(
Code coverage fails without this test due to appearing as an indirect change

2023-08-08 14:16 UTC, bjss-colin approved these changes

2023-08-08 14:25 UTC, merged