Feature/bespoke milestone data migration
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #1194
Opened 2023-07-27 10:59 UTC by dssherlock

2023-08-04 09:26 UTC, bjss-colin requested changes

2023-08-04 09:26 UTC, bjss-colin commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Utils/Extensions/BuyingCatalogueDbContextExtensions.cs
> +        public static Contract GetContract(this BuyingCatalogueDbContext context, int orderId)
Let's make this asynchronous by using `FirstOrDefaultAsync` on the context. It might also be worth making this an extension method for `DbSet<Contract>` since then you can use `await context.Contracts.GetContract()` which just makes it a bit more isolated to the contracts tables.

2023-08-09 07:35 UTC, dssherlock commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Utils/Extensions/BuyingCatalogueDbContextExtensions.cs
> +        public static Contract GetContract(this BuyingCatalogueDbContext context, int orderId)
Yep can do-it was just a direct copy of the existing GetContractFlags method above that is not really required anymore (or has limited usage) as I've removed code references to the flags. I didnt spend any time on it as I didnt think we were really supporting integration tests anymore.

2023-08-09 15:10 UTC, dssherlock commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Utils/Extensions/BuyingCatalogueDbContextExtensions.cs
> +        public static Contract GetContract(this BuyingCatalogueDbContext context, int orderId)
Would u do the context.SaveChanges() after each call then?

2023-08-09 15:21 UTC, imranbashir01 approved these changes

2023-08-09 16:02 UTC, bjss-colin approved these changes

2023-08-09 16:03 UTC, merged