Gen2
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #1198
Opened 2023-08-01 13:04 UTC by martinkimmings

2023-08-10 11:04 UTC, imranbashir01 submitted a review, later dismissed

2023-08-10 11:31 UTC, bjss-colin requested changes
Minor point regarding the Capability Categories

2023-08-10 11:31 UTC, bjss-colin commented on database/NHSD.GPITBuyingCatalogue.Database/PostDeployment/InsertCapabilityCategories.sql
>  (10, 'Reporting and data analytics', 'Find solutions that allow local data analysis across all aspects of a GP practice.'),
We should remove the descriptions from these categories since we can't support them going forward into Gen 2. 

This script may also be better suited as Test Data, since the function app should now import the categories as well. In this case,

2023-08-10 11:31 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.Services/Solutions/SolutionsFilterService.cs
> -            using var cmd = dbContext.Database.GetDbConnection().CreateCommand();
No change required here - but I'm glad to see this god-awful stored procedure is finally gone.

2023-08-11 10:01 UTC, martinkimmings commented on database/NHSD.GPITBuyingCatalogue.Database/PostDeployment/InsertCapabilityCategories.sql
>  (10, 'Reporting and data analytics', 'Find solutions that allow local data analysis across all aspects of a GP practice.'),
It is now a test data script and I've removed the descriptions.

2023-08-11 14:24 UTC, bjss-colin submitted a review, later dismissed

2023-08-11 14:24 UTC, bjss-colin commented
Great work to both you @martinkimmings and @Patrick-M-BJSS on this milestone

2023-08-11 15:36 UTC, bjss-colin approved these changes

2023-08-11 15:37 UTC, merged