Add supplier details view
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #120
Opened 2021-06-17 10:32 UTC by NickNewlands

Task: AB#15270
Story: AB#14662

2021-06-17 13:28 UTC, kiran-mastek requested changes

2021-06-17 13:28 UTC, kiran-mastek commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/MappingProfiles/SolutionDetailsProfile.cs
> +                        x => "SolutionsLastReviewedDate"))
The following should cater for `Supplier` being null

2021-06-17 13:28 UTC, kiran-mastek commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Models/SolutionSupplierDetailsModel.cs
> +
Instead of using domain model, please create a new model for display with only the relevant properties (`FullName`, `Email` and `PhoneNumber`) and add a mapping from `SupplierContact` to the new model.
AutoMapper will look it up and fill `Contacts` property with the current code.
This should be done to avoid logic and changes in one layer from affecting other layers.

2021-06-18 08:27 UTC, NickNewlands commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/MappingProfiles/SolutionDetailsProfile.cs
> +                        x => "SolutionsLastReviewedDate"))
Done.

2021-06-18 08:28 UTC, NickNewlands commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Models/SolutionSupplierDetailsModel.cs
> +
I think I have done this correctly now, see SupplierContactViewModel.cs.

2021-06-18 11:34 UTC, kiran-mastek requested changes

2021-06-18 11:34 UTC, kiran-mastek commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/MappingProfiles/SolutionDetailsProfile.cs
> +            CreateMap<SupplierContact, SupplierContactViewModel>()
String interpolation would be concise & easier to read:
`opt.MapFrom(src => $"{src.FirstName} {src.LastName}")`

2021-06-18 11:34 UTC, kiran-mastek commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/MappingProfiles/SolutionDetailsProfile.cs
> +                .ForMember(dest => dest.SolutionName, opt => opt.MapFrom(src => src.Name))
AutoMapper won't be able to map from null if `Supplier` is null, suggest change it to empty list:
`.ForMember(dest => dest.Contacts, opt => opt.MapFrom(src => src.Supplier == null ? new List<SupplierContact>() : src.Supplier.SupplierContacts))`

2021-06-19 04:56 UTC, kiran-mastek approved these changes

2021-06-19 04:58 UTC, merged