Summary page
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #1217
Opened 2023-08-25 11:21 UTC by dssherlock

2023-08-30 09:23 UTC, bjss-colin requested changes

2023-08-30 09:23 UTC, ghost commented on src/NHSD.GPIT.BuyingCatalogue.Services/Pdf/CachedOrderPdfService.cs
> +        var blobDocument = order.OrderStatus == OrderStatus.Completed ? $"{order.CallOffId.ToString()}.pdf" : $"{order.CallOffId.ToString()}-terminated.pdf";
Might be worth adding a switch statement here as the assumption here is that an order is terminated if it's not completed, which isn't always the case since admins can download PDFs of a deleted order from the admin side.

2023-08-30 14:57 UTC, dssherlock commented on src/NHSD.GPIT.BuyingCatalogue.Services/Pdf/CachedOrderPdfService.cs
> +        var blobDocument = order.OrderStatus == OrderStatus.Completed ? $"{order.CallOffId.ToString()}.pdf" : $"{order.CallOffId.ToString()}-terminated.pdf";
But if the order has been deleted surely it wont reach this point in code as it would have returned the CreateOrderSummaryPdf?

2023-08-30 15:05 UTC, dssherlock commented on src/NHSD.GPIT.BuyingCatalogue.Services/Pdf/CachedOrderPdfService.cs
> +        var blobDocument = order.OrderStatus == OrderStatus.Completed ? $"{order.CallOffId.ToString()}.pdf" : $"{order.CallOffId.ToString()}-terminated.pdf";
I could swap it round so that the check for Terminated is first?

2023-08-30 15:16 UTC, samdasari9 approved these changes

2023-08-31 08:17 UTC, bjss-colin approved these changes

2023-08-31 09:54 UTC, merged