Feature/tiered pricing toggle
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #1219
Opened 2023-08-30 14:25 UTC by Patrick-M-BJSS

2023-09-04 15:42 UTC, imranbashir01 submitted a review, later dismissed

2023-09-06 08:43 UTC, bjss-colin requested changes
Looks like a submodule has been added in a previous commit. There may be a `GPITBuyingCatalogue` folder at the root project directory that should be removed

2023-09-06 08:49 UTC, bjss-colin requested changes

2023-09-06 08:49 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Controllers/SolutionsController.cs
> +            var additionalService = await solutionsService.GetSolutionWithCataloguePrice(serviceId);
For the additional and associated services it might be better to use the `IListPriceService` rather than `ISolutionService`. All Solutions are Catalogue Items but not all Catalogue Items are Solutions.

Unit tests will need updating also to ensure the `IListPriceService` is being mocked.

2023-09-06 08:49 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Controllers/SolutionsController.cs
> +            var associatedService = await solutionsService.GetSolutionWithCataloguePrice(serviceId);
Same as below

2023-09-08 15:11 UTC, bjss-colin approved these changes

2023-09-08 15:17 UTC, merged