Feature/Terminate Contract
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #1224
Opened 2023-09-01 15:37 UTC by dssherlock

2023-09-04 14:16 UTC, samdasari9 submitted a review, later dismissed

2023-09-06 08:56 UTC, bjss-colin requested changes

2023-09-06 08:56 UTC, bjss-colin commented on database/NHSD.GPITBuyingCatalogue.Database/Ordering/Tables/OrderTermination.sql
> +    CONSTRAINT FK_OrderTermination_Order FOREIGN KEY (OrderId) REFERENCES ordering.Orders(Id),
`ON DELETE CASCADE` might be useful here as I'm imagining a scenario similar to the recent contract deletion bug for an amended order. The buyer wouldn't be able to delete the amendment but an admin may be able to via the admin > Manage Orders section.

2023-09-06 08:56 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.Services/Csv/CsvService.cs
> +                    items.AddRange(await CreateFullOrderCsv(id));
Rather than looping, `CreateFullOrderCsv` could instead accept `params int[] orderIds` and do a `.Contains` check on the `OrderItemRecipents` so it does a bulk query.

2023-09-07 10:31 UTC, bjss-colin approved these changes

2023-09-07 10:32 UTC, merged