Service recipient improvements
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #1227
Opened 2023-09-05 16:45 UTC by martinkimmings

2023-09-13 12:22 UTC, samdasari9 approved these changes, later dismissed

2023-09-19 10:28 UTC, bjss-colin requested changes
Two minor points and two backwards compatibility points relating to the database

2023-09-19 10:28 UTC, bjss-colin commented on database/NHSD.GPITBuyingCatalogue.Database/Ordering/Tables/ServiceRecipients.sql
> -﻿CREATE TABLE ordering.ServiceRecipients
Let's leave this in place for now as it'll cause a DROP statement which will in turn prevent this from being backwards compatible

2023-09-19 10:28 UTC, bjss-colin commented on database/NHSD.GPITBuyingCatalogue.Database/Ordering/TemporalTables/ServiceRecipients_History.sql
> -﻿CREATE TABLE ordering.ServiceRecipients_History
Same as above

2023-09-19 10:28 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.Services/Orders/SupplierService.cs
> +        public async Task<Supplier> GetSupplierByDate(int id, DateTime dateTime)
It looks like this could be removed since we now have `SupplierTemporalService`

2023-09-19 10:28 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.UI.Components/Views/Shared/Components/NhsSecondaryButton/NhsSecondaryButtonViewComponent.cs
> +        public async Task<IViewComponentResult> InvokeAsync(string text, string url, ButtonType type, bool disabled = false)
Disabled logic could be removed since we're no longer using this

2023-09-19 14:03 UTC, bjss-colin approved these changes, later dismissed

2023-09-20 08:35 UTC, imranbashir01 approved these changes

2023-09-20 13:39 UTC, bjss-colin approved these changes

2023-09-20 13:45 UTC, merged