Consolidate the non practice based information sent to finance
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #1235
Opened 2023-09-21 11:59 UTC by DeepikaDK001

2023-09-22 08:51 UTC, bjss-colin requested changes

2023-09-22 08:51 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.Services/Csv/CsvService.cs
> +                        ServiceRecipientId = oir.OrderItem.OrderItemPrice.CataloguePriceQuantityCalculationType != CataloguePriceQuantityCalculationType.PerServiceRecipient && (oir.OrderItem.OrderIte
`IPrice`, of which `OrderItemPrice` implements, has an `IsPerServiceRecipient` method that contains similar logic as the condition block in this ternary. You'd have to cast `oir.OrderItem.OrderItemPrice` to `IPrice` but it should help reduce code by re-using existing business logic

2023-09-22 08:55 UTC, martinkimmings reviewed
I think it is worth adding some unit tests for the consolidation changes to show/test how multiple recipients sometimes result in a single row.

`CsvService` was recently changed to extract the dependency on temporal table data to `ISupplierTemporalService` which means testing this should be possible now.

2023-09-22 09:35 UTC, imranbashir01 approved these changes, later dismissed

2023-09-22 11:31 UTC, bjss-colin requested changes

2023-09-22 11:31 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.Services/Csv/CsvService.cs
> +                        ServiceRecipientId = (oir.OrderItem.OrderItemPrice as IPrice).IsPerServiceRecipient() == false && (oir.OrderItem.OrderItemPrice.ProvisioningType == ProvisioningType.Declarativ
How about `!(oir.OrderItem.OrderItemPrice as IPrice).IsPerServiceRecipient()`?

2023-09-25 12:45 UTC, imranbashir01 approved these changes, later dismissed

2023-09-26 13:47 UTC, martinkimmings approved these changes

2023-09-26 13:49 UTC, imranbashir01 approved these changes

2023-09-26 14:20 UTC, bjss-colin approved these changes

2023-09-26 14:21 UTC, merged