Feature/22844 edit frameworks
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #1244
Opened 2023-09-29 15:19 UTC by Patrick-M-BJSS

2023-10-04 16:15 UTC, bjss-colin requested changes

2023-10-04 16:15 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Controllers/FrameworksController.cs
> +        var view = View("Add", model);
`View` can be returned directly

2023-10-04 16:15 UTC, bjss-colin commented on tests/NHSD.GPIT.BuyingCatalogue.Services.UnitTests/Frameworks/FrameworkServiceTests.cs
> +        dbContext.ChangeTracker.Clear();
`dbContext.ChangeTracker.Clear()` needs to be added to any tests that update the `dbContext` via `SaveChangesAsync`. There are just a few more in this change that'll need it.

This prevents the `dbContext` from returning a cached result when later retrieving the updated entity as part of the test.

2023-10-04 16:15 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.Services/Framework/FrameworkService.cs
> +            if (string.IsNullOrWhiteSpace(name))
`ArgumentNullException.ThrowIfNullOrEmpty` should work here with `name`

2023-10-04 16:15 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Controllers/FrameworksController.cs
> +        AddFrameworkModel model = new AddFrameworkModel
Create a new constructor on `AddFrameworkModel` to accept the `Framework` as a parameter. That way the `FrameworkId`, `Name` and `FundingTypes.Selected` logic can be done via the constructor.

It'll also be worth renaming `AddFrameworkModel` to `AddEditFrameworkModel` since it now serves two purposes

2023-10-05 08:58 UTC, imranbashir01 approved these changes, later dismissed

2023-10-06 14:02 UTC, bjss-colin approved these changes

2023-10-06 15:11 UTC, imranbashir01 approved these changes

2023-10-06 15:11 UTC, merged