Regression tests
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #1245
Opened 2023-10-02 11:48 UTC by imranbashir01

2023-10-04 16:16 UTC, bjss-colin requested changes

2023-10-04 16:16 UTC, bjss-colin commented on database/NHSD.GPITBuyingCatalogue.Database/PostDeployment/InsertFrameworks.sql
> +       ('TIF001', 'Tech Innovation Framework', 'Tech Innovation', 'NHS Digital', '1,2', 0),
Let's have a catch up on this just so I can understand whether this is test data or intentional

Unfortunately we won't be able to do this if it's test data as it'll impact live directly when we do a release

2023-10-10 11:13 UTC, imranbashir01 commented on database/NHSD.GPITBuyingCatalogue.Database/PostDeployment/InsertFrameworks.sql
> +       ('TIF001', 'Tech Innovation Framework', 'Tech Innovation', 'NHS Digital', '1,2', 0),
I have reverted the commit and will look to handle the change differently

2023-10-11 11:18 UTC, bjss-colin approved these changes

2023-10-11 11:35 UTC, merged