Adjust logic for order summary CSV buttons
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #1248
Opened 2023-10-04 12:44 UTC by Patrick-M-BJSS

2023-10-04 15:52 UTC, bjss-colin requested changes

2023-10-04 15:52 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Views/ManageOrders/ViewOrder.cshtml
> +                @if (Model.OrderStatus != OrderStatus.InProgress)
Being more specific will be better here because changing it to a `not InProgress` will allow the CSV to be downloaded in every state that isn't `Completed` or `Terminated`, like `Deleted`, whereas this story only wants to allow downloads for those two states (`Completed` and `Terminated`).

2023-10-05 09:35 UTC, imranbashir01 approved these changes, later dismissed

2023-10-06 13:10 UTC, bjss-colin approved these changes

2023-10-06 13:55 UTC, merged