Feature/22742 home page
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #1250
Opened 2023-10-06 10:38 UTC by dssherlock

2023-10-10 11:18 UTC, imranbashir01 approved these changes, later dismissed

2023-10-11 14:26 UTC, bjss-colin requested changes
Looks good overall, really good to see the design improvements to the home page.

Just some minor comments around the components and some consistency with links

2023-10-11 14:26 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.UI.Components/Views/Shared/Components/NhsLoginIcon/NhsLoginIconViewComponent.cs
> +        public async Task<IViewComponentResult> InvokeAsync()
A synchronous `Invoke` method could be defined instead of `InvokeAsync`. See the docs here for an example https://learn.microsoft.com/en-us/aspnet/core/mvc/views/view-components?view=aspnetcore-7.0#view-components-1

2023-10-11 14:26 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.UI.Components/Views/Shared/Components/NhsLoginLink/NhsLoginLinkViewComponent.cs
> +            return await Task.FromResult(View("LoginLink", model));
A synchronous `Invoke` method could be used in place of `InvokeAsync`

2023-10-11 14:26 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.UI.Components/Views/Shared/Components/NhsNavigationPanel/NhsNavigationPanelViewComponent.cs
> +        public async Task<IViewComponentResult> InvokeAsync(string title, List<KeyValuePair<string, string>> items)
Same as previous component comments

2023-10-11 14:26 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Views/Shared/Navigation/_AdminNavigation.cshtml
> +        navigationItems.Add(new("Log out", Url.Action(nameof(AccountController.Logout), typeof(AccountController).ControllerName(), new { area = typeof(AccountController).AreaName() })));
`typeof(AccountController).AreaName()` could also be used on line 8 of this file for consistency

2023-10-11 15:33 UTC, bjss-colin approved these changes

2023-10-11 16:23 UTC, merged