NHS App Integration - Admin &  Marketing pages
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #1254
Opened 2023-10-11 19:47 UTC by DeepikaDK001

2023-10-13 13:01 UTC, imranbashir01 submitted a review, later dismissed

2023-10-16 08:49 UTC, bjss-colin requested changes

2023-10-16 08:49 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.EntityFramework/Catalogue/Models/Integration.cs
> +        public HashSet<string> NHSAppIntegrationTypes { get; set; }
There are currently are no database changes included in this PR so these values won't actually be getting stored anywhere.

This could either be stored as a comma separated list in the database, to a single column, or would require a new table and a class to map to that table.

Also, rather than using `HashSet<T>`, see the other entity types that use `ICollection<T>` and assign `HashSet` as a default empty collection.

2023-10-16 08:49 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/InteroperabilityModels/AddEditNhsAppIntegrationModel.cs
> +            if (nhsAppIntegrationTypes != null)
Invert the `if` statement and return early to prevent code nesting

2023-10-16 08:49 UTC, bjss-colin commented on tests/NHSD.GPIT.BuyingCatalogue.WebApp.UnitTests/Areas/Admin/Models/InteroperabilityModels/AddEditNhsAppIntegrationModelTests.cs
> +            await context.SaveChangesAsync();
Don't forget to add `context.ChangeTracker.Clear()` after every instance of `SaveChangesAsync`

2023-10-16 09:37 UTC, DeepikaDK001 commented on src/NHSD.GPIT.BuyingCatalogue.EntityFramework/Catalogue/Models/Integration.cs
> +        public HashSet<string> NHSAppIntegrationTypes { get; set; }
As discussed I changed NHSAppIntegrationTypes  from HashSet<string> to ICollection<string> and assigned to default value => new HashSet<string>().

2023-10-16 10:06 UTC, imranbashir01 approved these changes

2023-10-16 10:06 UTC, bjss-colin approved these changes

2023-10-16 10:08 UTC, merged