On-catalogue competition improvements - Download PDFs
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #1273
Opened 2023-11-01 20:52 UTC by DeepikaDK001

2023-11-02 15:07 UTC, bjss-colin requested changes

2023-11-02 15:07 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Competitions/Controllers/CompetitionScoringController.cs
> +    public async Task<IActionResult> FeaturePdf(
Since all of the following PDF methods are implemented identically, you could instead use a single method and parameterize, in some way, the correct file that needs to be downloaded.

2023-11-06 09:30 UTC, bjss-colin requested changes

2023-11-06 09:30 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Competitions/Controllers/CompetitionScoringController.cs
> +        switch (pdfType)
Introducing methods per each non-price element PDF will allow for this switch statement to be removed.

What I meant in my original comment by reusing code is that a single method, that is not `[HttpGet]` decorated, could be used for handling the PDF logic, while other `[HttpGet]` decorated methods pass in the InternalOrgId, CompetitionId, Url and FileName suffix (e.g: features, implementation, interoperability, sla) as parameters.

2023-11-06 14:27 UTC, imranbashir01 submitted a review, later dismissed

2023-11-06 14:49 UTC, bjss-colin submitted a review, later dismissed

2023-11-06 16:18 UTC, bjss-colin approved these changes

2023-11-06 16:24 UTC, imranbashir01 approved these changes

2023-11-06 16:25 UTC, merged