Add check epics view
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #128
Opened 2021-06-17 15:20 UTC by NickNewlands

AB#14655
AB#15169

2021-06-18 05:59 UTC, kiran-mastek requested changes
Please add some more test data (one/more Capability with some/no NHS/Supplier defined Epics to show case the look in various situations - with both, one set of capabilities. 
This should mean updating `InsertCapabilities.sql` &/or related files in the `Database` project.

2021-06-18 05:59 UTC, kiran-mastek commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/MappingProfiles/SolutionDetailsProfile.cs
> +
The following method can be made more effective and simpler as follows by passing in the `Capability` as its prudent to check the properties for validity.
```
private static List<string> GetEpics(Capability capability, bool supplierDefined) =>
    capability?.Epics == null
        ? new List<string>()
        : capability.Epics
            .Where(e => e.Active && e.SupplierDefined == supplierDefined)
            .Select(epic => epic.Name)
            .ToList();
```

2021-06-18 05:59 UTC, kiran-mastek commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Controllers/SolutionDetailsController.cs
> +        [Route("solutions/futures/{id}/capability/{capabilityId:guid}")]
With the `{capabilityId:guid}` restriction the `capabilityId` parameter can be of type `Guid` instead of string - we can check it for not being empty to validate.

2021-06-18 05:59 UTC, kiran-mastek commented on src/NHSD.GPIT.BuyingCatalogue.Services/Solutions/SolutionsService.cs
>          }
The following can be changed as shown so a separate call for `CatalogueItem` is not required just for its name:
```
public async Task<CatalogueItem> GetSolutionCapability(string catalogueItemId, Guid capabilityId)
{
    catalogueItemId.ValidateNotNull(nameof(catalogueItemId));
    if (capabilityId == Guid.Empty)
        throw new ArgumentException(nameof(capabilityId));

    return await dbContext.CatalogueItems
        .Include(c => c.Solution)
        .ThenInclude(s => s.SolutionCapabilities)
        .ThenInclude(sc => sc.Capability)
        .Where(
            c => c.CatalogueItemId == catalogueItemId
                && c.Solution.SolutionCapabilities.Any(sc => sc.CapabilityId == capabilityId))
        .FirstOrDefaultAsync();
}
```

2021-06-18 05:59 UTC, kiran-mastek commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Controllers/SolutionDetailsController.cs
> +
The `GetSolutionCapability` method can be updated as covered in the service to make one call so the following code can be updated to:
```
var solution = await solutionsService.GetSolutionCapability(id, capabilityId);
if (solution == null)
    return BadRequest($"No Catalogue Item found for Id: {id} with Capability Id: {capabilityId}");

var solutionCapability =
    solution.Solution.SolutionCapabilities.FirstOrDefault(sc => sc.Capability.Id == capabilityId)
    ?? new SolutionCapability();

var model = mapper.Map<SolutionCapability, SolutionCheckEpicsModel>(solutionCapability);
model.SolutionName = solution.Name;
```

2021-06-18 05:59 UTC, kiran-mastek commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Models/SectionModel.cs
> +
The `Hidden` property is not being used and redundant with a `Show` property so should be removed.

2021-06-18 05:59 UTC, kiran-mastek commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/SolutionDetails/CheckEpics.cshtml
> +
It is best to have a method like `HasNhsDefined()` to call, which can be unit tested and be extended without having to add more code in `cshtml` file.
Also this code will fail if `NhsDefined` is `null` - that should be checked and unit tested in the method.

2021-06-18 05:59 UTC, kiran-mastek commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/SolutionDetails/CheckEpics.cshtml
> +
Same as previous comment.

2021-06-18 08:40 UTC, NickNewlands commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Controllers/SolutionDetailsController.cs
> +        [Route("solutions/futures/{id}/capability/{capabilityId:guid}")]
I did have it implemented like that but it seems like although it is obviously validated as a Guid to hit the route, it still gets passed as a string to the function, I will change it back and see if you prefer it.

2021-06-21 07:20 UTC, kiran-mastek commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Controllers/SolutionDetailsController.cs
> +        [Route("solutions/futures/{id}/capability/{capabilityId:guid}")]
Not sure how that happens, if I define it as `Guid` in the action it gets passed as `Guid`, let's have a call if the issue persists for you. The following works for me:
```
[Route("solutions/futures/{id}/capability/{capabilityId:guid}")]
public async Task<IActionResult> CheckEpics(string id, Guid capabilityId)
{
    if (string.IsNullOrWhiteSpace(id))
        throw new ArgumentException($"{nameof(CheckEpics)}-{nameof(id)}");

    if (capabilityId == Guid.Empty)
        throw new ArgumentException($"{nameof(CheckEpics)}-{nameof(capabilityId)}");
    ...
    ...
```

2021-06-23 09:41 UTC, kiran-mastek submitted a review, later dismissed

2021-06-23 11:48 UTC, leerogers-bjss requested changes

2021-06-23 11:48 UTC, leerogers-bjss commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Controllers/SolutionDetailsController.cs
> +            if (capabilityId == Guid.Empty)
the parameter null checks can be removed due to the new ArgumentNullActionFilter doing the checks automatically

2021-06-23 11:48 UTC, leerogers-bjss commented on tests/NHSD.GPIT.BuyingCatalogue.WebApp.UnitTests/Areas/Solutions/Controllers/SolutionDetailsControllerTests.cs
> +            var controller = new SolutionDetailsController(Mock.Of<IMapper>(),
these null check tests can be removed due to the ArgumentNullActionFilter doing the checks for you

2021-06-29 09:18 UTC, leerogers-bjss approved these changes

2021-06-29 09:19 UTC, merged