Feature/22470 pdd apply to all
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #1283
Opened 2023-11-10 13:52 UTC by dssherlock

2023-11-15 15:56 UTC, bjss-colin requested changes
General point: the pull request title just needs to be updated to something more descriptive around the change itself so it's clear what the change is in relation to when creating release notes

2023-11-15 15:56 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Orders/Views/DeliveryDates/SelectDate.cshtml
> +        <nhs-validation-summary RadioId="ApplyToAll" />
`nameof` could be used here to add compile-time safety

2023-11-15 15:56 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Orders/Models/Contracts/DeliveryDates/SelectDateModel.cs
> +        public string ApplyToAll { get; set; }
Might be worth seeing if `SelectOption<bool>` could be used with standard radio buttons since then the model can accept `bool?`

2023-11-15 16:31 UTC, dssherlock commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Orders/Models/Contracts/DeliveryDates/SelectDateModel.cs
> +        public string ApplyToAll { get; set; }
Do u mean updating the Yes No Component? This could be quite a big change as its used in quite a few places

2023-11-15 16:34 UTC, ghost commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Orders/Models/Contracts/DeliveryDates/SelectDateModel.cs
> +        public string ApplyToAll { get; set; }
Not updating the Yes No component, but using `SelectOption<bool>` with `<nhs-radio-buttons />` similar to how it's done here 

https://github.com/nhs-digital-gp-it-futures/GPITBuyingCatalogue/blob/55b32829416bb35b850d67212c8cbe695e64a2bf/src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Orders/Models/CommencementDate/ConfirmChangesModel.cs#L26

2023-11-15 16:42 UTC, dssherlock commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Orders/Models/Contracts/DeliveryDates/SelectDateModel.cs
> +        public string ApplyToAll { get; set; }
Do u mean not bother with the "nhs-yesno-radio-buttons" then? Just create my own using SelectOption?

2023-11-15 16:45 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Orders/Models/Contracts/DeliveryDates/SelectDateModel.cs
> +        public string ApplyToAll { get; set; }
More or less. Here's a better example since it only uses "Yes" and "No"

https://github.com/nhs-digital-gp-it-futures/GPITBuyingCatalogue/blob/55b32829416bb35b850d67212c8cbe695e64a2bf/src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Orders/Models/Contracts/DeliveryDates/MatchDatesModel.cs#L35

2023-11-15 17:27 UTC, bjss-colin requested changes
One more minor change on the model validator following the type change

2023-11-15 17:27 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Orders/Validators/Contracts/DeliveryDates/SelectDateModelValidator.cs
> +                .NotEmpty()
Since `ApplyToAll` is now a `bool?`, this will need changing from `NotEmpty` to `NotNull`

2023-11-16 09:20 UTC, dssherlock commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Orders/Validators/Contracts/DeliveryDates/SelectDateModelValidator.cs
> +                .NotEmpty()
Ah yes good spot!

2023-11-17 09:55 UTC, imranbashir01 approved these changes

2023-11-17 11:29 UTC, bjss-colin approved these changes

2023-11-17 11:29 UTC, merged