Add link to marketing pages on Additional and Associated Services
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #1298
Opened 2023-12-01 11:56 UTC by DeepikaDK001

2023-12-04 09:36 UTC, bjss-colin requested changes

2023-12-04 09:36 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Orders/Views/Shared/SelectSolution.cshtml
> +                                      new { solutionId = selectListItem.Value, area = "Solutions" })" target="_blank">
Let's use the `AreaName()` method rather than specifying the area manually.

2023-12-04 09:36 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Views/Shared/Services/SelectAssociatedServices.cshtml
> +                                      new { solutionId = @Model.SolutionId, area = "Solutions" })" target="_blank">
Let's use the `AreaName()` method rather than specifying the area manually.

2023-12-04 09:36 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Orders/Views/Shared/SelectSolution.cshtml
> +                                                   value="" />
This `value` attribute doesn't look like it's required

2023-12-04 13:06 UTC, bjss-colin requested changes
One more minor suggestion

2023-12-04 13:06 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Orders/Controllers/SolutionSelection/AssociatedServicesController.cs
> +                SolutionId = order.AssociatedServicesOnly
There's already a similar method on the `Order` object that retrieves the solution ID

2023-12-05 11:58 UTC, imranbashir01 approved these changes

2023-12-05 13:14 UTC, bjss-colin approved these changes

2023-12-05 13:25 UTC, merged