Display Count of Service Recipients in PDF
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #1316
Opened 2024-01-02 16:18 UTC by DeepikaDK001

2024-01-02 16:58 UTC, bjss-colin requested changes

2024-01-02 16:58 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Views/OrderSummary/Index.cshtml
> +                    <nhs-summary-list>
This is a PDF, so the PDF classes should be used

2024-01-02 16:58 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Views/OrderSummary/Index.cshtml
> +                    <nhs-summary-list>
Same as above. There are PDF tags available which should be used

2024-01-03 10:41 UTC, bjss-colin requested changes

2024-01-03 10:41 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Views/OrderSummary/OrderItem.cshtml
> +    <table catches-errors="false">
`catches-errors` is not a valid attribute on a standard HTML `table` element.

2024-01-03 11:23 UTC, martinkimmings commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Views/OrderSummary/OrderItem.cshtml
>      var tiers = Model.OrderItemPrice?.OrderItemPriceTiers?.OrderBy(x => x.LowerRange).ToList() ?? new List<OrderItemPriceTier>();
Looks like some of these aren't used anymore. Worth checking and removing unused code.

2024-01-03 11:51 UTC, imranbashir01 approved these changes

2024-01-03 12:04 UTC, bjss-colin approved these changes

2024-01-03 12:08 UTC, merged