Upload or manually select Service Recipients - code change
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #1321
Opened 2024-01-08 17:59 UTC by DeepikaDK001

2024-01-09 09:52 UTC, bjss-colin requested changes

2024-01-09 09:52 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Competitions/Controllers/CompetitionRecipientsController.cs
> +            return await Index(internalOrgId, competitionId);
There are two different coding styles in play here.

Line 70 is correct in that it redirects to the Index for uploading recipients. Why doesn't line 77 also redirect?

2024-01-09 09:52 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Orders/Controllers/SolutionSelection/ServiceRecipientsController.cs
> +                return await SelectServiceRecipients(internalOrgId, callOffId);
There are two different coding styles in play here.

Line 70 is correct in that it redirects to the Index for uploading recipients. Why doesn't line 77 also redirect?

2024-01-09 09:52 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Orders/Controllers/SolutionSelection/ServiceRecipientsController.cs
> +            else
This else statement is redundant. The first `if` scenario returns directly from the true condition, so this else and parenthesis could be removed to reduce code nesting.

2024-01-09 09:52 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Competitions/Controllers/CompetitionRecipientsController.cs
> +        else
This else statement is redundant. The first `if` scenario returns directly from the true condition, so this else and parenthesis could be removed to reduce code nesting.

2024-01-09 09:52 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Competitions/Controllers/CompetitionRecipientsController.cs
> +            Title = "Service Recipients",
Title looks to be the same across the order and competition journeys. Could this maybe be set in the model directly as an override on `Title`?

2024-01-09 09:52 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Orders/Controllers/SolutionSelection/ServiceRecipientsController.cs
> +                Title = "Service Recipients",
Title looks to be the same across the order and competition journeys. Could this maybe be set in the model directly as an override on `Title`?

2024-01-09 09:52 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Models/Shared/ServiceRecipientModels/UploadOrSelectServiceRecipientModel.cs
> +            new("Upload Service Recipients using a CSV file", "Upload"),
This could use a boolean rather than strings as there are only two values. `SelectedServiceRecipientOptions` could become `bool? ShouldUploadRecipients`

2024-01-09 10:29 UTC, DeepikaDK001 commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Competitions/Controllers/CompetitionRecipientsController.cs
> +            return await Index(internalOrgId, competitionId);
The line 70 redirects to the upload recipients and the line 77 redirects to the manual selection page.

2024-01-09 10:30 UTC, DeepikaDK001 commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Orders/Controllers/SolutionSelection/ServiceRecipientsController.cs
> +                return await SelectServiceRecipients(internalOrgId, callOffId);
The first one inside if, redirects to the upload recipients and the second one redirects to the manual selection page.

2024-01-09 11:33 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Orders/Controllers/SolutionSelection/ServiceRecipientsController.cs
> +                return await SelectServiceRecipients(internalOrgId, callOffId);
The second one isn't redirecting, it's invoking the action directly and returning the result of that action

2024-01-09 11:33 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Competitions/Controllers/CompetitionRecipientsController.cs
> +            return await Index(internalOrgId, competitionId);
Same as below

2024-01-09 11:42 UTC, DeepikaDK001 commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Orders/Controllers/SolutionSelection/ServiceRecipientsController.cs
> +                return await SelectServiceRecipients(internalOrgId, callOffId);
sorry got that now

2024-01-09 14:52 UTC, bjss-colin requested changes

2024-01-09 14:52 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Models/Shared/ServiceRecipientModels/UploadOrSelectServiceRecipientModel.cs
> +    public string SelectedServiceRecipient { get; set; }
Is this still required?

2024-01-09 14:52 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Models/Shared/ServiceRecipientModels/UploadOrSelectServiceRecipientModel.cs
> +    public string ImportRecipientsLink { get; set; }
Where is this used?

2024-01-09 14:52 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Models/Shared/ServiceRecipientModels/UploadOrSelectServiceRecipientModel.cs
> +    public override string Title
There are other examples available, throughout the WebApp project, on how to override `Title` and `Advice`

2024-01-09 14:52 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Orders/Controllers/SolutionSelection/ServiceRecipientsController.cs
> +                nameof(Index),
Indentation and formatting of lines 83-85

2024-01-09 14:52 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Competitions/Controllers/CompetitionRecipientsController.cs
> +            nameof(CompetitionImportServiceRecipientsController.Index),
Indentation and formatting of lines 70-72

2024-01-09 14:52 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Views/Shared/ServiceRecipients/UploadOrSelectServiceRecipient.cshtml
> +                    @for (int i = 0; i < Model.ServiceRecipientOptions.Count();i++)
`nhs-radio-buttons` should be fine to use here. See other examples in the WebApp project for the typical approach to implementing `nhs-radio-buttons` with `IEnumerable<SelectOption<T>>`

2024-01-09 15:16 UTC, DeepikaDK001 commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Models/Shared/ServiceRecipientModels/UploadOrSelectServiceRecipientModel.cs
> +    public string ImportRecipientsLink { get; set; }
removed it.

2024-01-09 15:16 UTC, DeepikaDK001 commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Models/Shared/ServiceRecipientModels/UploadOrSelectServiceRecipientModel.cs
> +    public string SelectedServiceRecipient { get; set; }
removed it.

2024-01-09 16:08 UTC, bjss-colin requested changes

2024-01-09 16:08 UTC, bjss-colin commented on tests/NHSD.GPIT.BuyingCatalogue.WebApp.UnitTests/Validation/UploadOrSelectServiceRecipientModelValidatorTests.cs
> +    public static class UploadOrSelectServiceRecipientModelValidatorTests
The test names are incorrect. Looks like an issue that was carried over from copying the `OrderItemTypeModelValidatorTests` class

2024-01-09 16:08 UTC, ghost commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Competitions/Controllers/CompetitionRecipientsController.cs
> +        var competition = await competitionsService.GetCompetitionWithRecipients(internalOrgId, competitionId);
Not sure we need to call `GetCompetitionWithRecipients` here since the recipients aren't being used for anything in this action. Competition Name is the only required item which comes from the `Competition` entity. Try `GetCompetition` instead.

Tests will also need to be updated as they're currently stubbing `GetCompetitionWithRecipients`

2024-01-09 16:08 UTC, ghost commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Views/Shared/ServiceRecipients/UploadOrSelectServiceRecipient.cshtml
> +        <nhs-page-title model="@Model" />
One scenario worth testing is to cause a form validation error and see if the Caption and Title are still present after the page is returned with a validation error

2024-01-09 16:19 UTC, DeepikaDK001 commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Views/Shared/ServiceRecipients/UploadOrSelectServiceRecipient.cshtml
> +        <nhs-page-title model="@Model" />
checked it and its working fine.

2024-01-09 16:27 UTC, imranbashir01 approved these changes, later dismissed

2024-01-09 16:50 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Views/Shared/ServiceRecipients/UploadOrSelectServiceRecipient.cshtml
> +        <nhs-page-title model="@Model" />
Reopened. This doesn't look fine to me 😅 

Order journey before validation error
![image](https://github.com/nhs-digital-gp-it-futures/GPITBuyingCatalogue/assets/90630744/9f90c584-68fb-496b-83eb-7bdb097ab648)

Order journey after validation error
![image](https://github.com/nhs-digital-gp-it-futures/GPITBuyingCatalogue/assets/90630744/7d92f2fb-0758-435a-845f-166edb21be31)

Competition journey before validation error
![image](https://github.com/nhs-digital-gp-it-futures/GPITBuyingCatalogue/assets/90630744/1b984e75-d37e-454a-ac2b-31f2e6364195)

Competition journey after validation error
![image](https://github.com/nhs-digital-gp-it-futures/GPITBuyingCatalogue/assets/90630744/efc1c2f6-13cb-48c8-bb31-47deea9b1f50)

2024-01-09 17:07 UTC, DeepikaDK001 commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Views/Shared/ServiceRecipients/UploadOrSelectServiceRecipient.cshtml
> +        <nhs-page-title model="@Model" />
sorry i missed to Validate the caption. Now it is sorted.

2024-01-09 17:10 UTC, imranbashir01 approved these changes

2024-01-10 09:57 UTC, bjss-colin approved these changes

2024-01-10 09:59 UTC, merged