Feature/22765 Service Recipients-search modal
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #1327
Opened 2024-01-19 16:45 UTC by dssherlock

2024-01-26 13:03 UTC, bjss-colin requested changes
Let's exclude ModalSearch.js, ModalSearch.js.map and ModalSearch.min.js as these are artifacts that should be produced at build time when ModalSearch.ts is transpiled into JavaScript

2024-01-26 13:03 UTC, ghost commented on src/NHSD.GPIT.BuyingCatalogue.UI.Components/Views/Shared/Components/NhsModalSearch/NhsModalSearch.cshtml
> +                    <h2 class="nhsuk-heading-m nhsuk-u-margin-bottom-0 nhsuk-u-margin-top-0" id="@(Model.Id + "-title")">
How about string interpolation like `@($"{Model.Id}-title")`

As some of these are reused in multiple places, like the `-title` attribute, it might be worth assigning these to a set of variables at the top of the file and then reusing

2024-01-26 13:03 UTC, ghost commented on src/NHSD.GPIT.BuyingCatalogue.UI.Components/Views/Shared/Components/NhsModalSearch/NhsModalSearchViewComponent.cs
> +                Id = id,
As `Id` is used for HTML attributes, this will need to be sanitized. I can't remember which files in particular do this but there are some examples in this UI Components library for sanitizing IDs.

2024-01-26 13:03 UTC, ghost commented on src/NHSD.GPIT.BuyingCatalogue.UI.Components/Views/Shared/Components/NhsSearchIcon/NhsSearchIcon.cs
> +        public async Task<IViewComponentResult> InvokeAsync()
There's a non async version of Invoke available that would allow for the direct return of `View("NhsSearchIcon")`

2024-01-26 13:03 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Views/Shared/ServiceRecipients/SelectRecipients.cshtml
> +        <form method="post" id = "sr-form">
HTML formatting is a bit funky on the ID attribute

2024-01-29 20:36 UTC, dssherlock commented on src/NHSD.GPIT.BuyingCatalogue.UI.Components/Views/Shared/Components/NhsModalSearch/NhsModalSearchViewComponent.cs
> +                Id = id,
I'm not absolutely sure what you mean by this. Do u mean use a different term e.g. 'Title' like they do in a few of the components? The only other example i can find using 'Id' is the NhsSuggestionSearch and that doesn't appear to do anything special with it.

2024-01-30 09:37 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.UI.Components/Views/Shared/Components/NhsModalSearch/NhsModalSearchViewComponent.cs
> +                Id = id,
So in the `NhsModalSearch` file the `Id` property is used as the `id` of the parent element. In your example below you assign it an ID of `search-recipients-modal`.

Now what happens if I assign it an ID of the literal `Search Recipients Modal`? That's not a valid value for an id attribute in HTML since it has whitespace between each word, as such it'll need to be sanitized so that `Search Recipients Model` needs to be turned into `search-recipients-model`

Sounds like `NhsSuggestionSearch` would need to be revisited as well but we can pick this up separately.

2024-01-30 11:10 UTC, imranbashir01 approved these changes, later dismissed

2024-02-01 09:56 UTC, dssherlock commented on src/NHSD.GPIT.BuyingCatalogue.UI.Components/Views/Shared/Components/NhsModalSearch/NhsModalSearchViewComponent.cs
> +                Id = id,
Ah i see yep I'll fix that now

2024-02-02 14:53 UTC, imranbashir01 approved these changes

2024-02-02 15:23 UTC, bjss-colin approved these changes

2024-02-02 16:25 UTC, merged