Merger and split journey should handle when we have no suppliers.
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #1328
Opened 2024-01-23 15:11 UTC by martinkimmings

Draft - waiting for content to be finalised.

2024-01-24 14:37 UTC, bjss-colin requested changes

2024-01-24 14:37 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.Services/Orders/SupplierService.cs
> +                query = query.Where(ci => ci.SupplierServiceAssociations.Any());
`else` block can be removed if the `.Any` clause is added to the main `Where` clause on line 126. The result should be the same

2024-01-24 14:37 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.Services/Orders/SupplierService.cs
> +        private IQueryable<Supplier> GetAllSuppliersFromBuyingCatalogue()
Based on the implementation, maybe something like `GetAllActiveSuppliers`

2024-01-24 14:37 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.Services/Orders/SupplierService.cs
> +        public Task<List<Supplier>> GetAllSuppliersByOrderType(OrderType orderType)
What about `GetAllSuppliersSupportingOrderType`, though it's a bit wordy

2024-01-24 15:35 UTC, martinkimmings commented on src/NHSD.GPIT.BuyingCatalogue.Services/Orders/SupplierService.cs
> +                query = query.Where(ci => ci.SupplierServiceAssociations.Any());
Unless I'm misunderstanding, doesn't this mean we'd be doing this for mergers and splits.

```
.Where(
  ci =>
  ci.CatalogueItemType == CatalogueItemType.Solution
  && ci.PublishedStatus == PublicationStatus.Published
  && ci.Solution.FrameworkSolutions.Select(f => f.Framework).Distinct().Any(f => !f.IsExpired)
  && ci.SupplierServiceAssociations.Any()
  && ci.SupplierServiceAssociations.Any(ssa => (ssa.AssociatedService.PracticeReorganisationType & practiceReorganisationType) == practiceReorganisationType));
```

Not suggesting it affects the results but it felt unnecessary to do both. Might even result in more complicated sql.

2024-01-24 15:45 UTC, martinkimmings commented on src/NHSD.GPIT.BuyingCatalogue.Services/Orders/SupplierService.cs
> +        public Task<List<Supplier>> GetAllSuppliersByOrderType(OrderType orderType)
Maybe `ByOrderType` is superfluous as it's implied by the parameter. How about `GetActiveSuppliers` and `HasActiveSuppliers`. This is inline with renaming the private methods to `GetActiveSuppliers...`

2024-01-24 15:46 UTC, martinkimmings commented on src/NHSD.GPIT.BuyingCatalogue.Services/Orders/SupplierService.cs
> +        private IQueryable<Supplier> GetAllSuppliersFromBuyingCatalogue()
I've gone with `GetActiveSuppliersForSolutions` and `GetActiveSuppliersForSolutionsWithAssociatedServices`

2024-01-24 16:29 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.Services/Orders/SupplierService.cs
> +                query = query.Where(ci => ci.SupplierServiceAssociations.Any());
I was thinking more along the lines of this for the base query

```csharp
.Where(
  ci =>
  ci.CatalogueItemType == CatalogueItemType.Solution
  && ci.PublishedStatus == PublicationStatus.Published
  && ci.Solution.FrameworkSolutions.Select(f => f.Framework).Distinct().Any(f => !f.IsExpired)
  && ci.SupplierServiceAssociations.Any())
```

2024-01-24 16:33 UTC, martinkimmings commented on src/NHSD.GPIT.BuyingCatalogue.Services/Orders/SupplierService.cs
> +                query = query.Where(ci => ci.SupplierServiceAssociations.Any());
Yeah sorry I've not explained myself well.  I meant the base query you suggest with the additional where clause of merger and split condition would result in this - that's my understanding.

```
.Where(
  ci =>
  ci.CatalogueItemType == CatalogueItemType.Solution
  && ci.PublishedStatus == PublicationStatus.Published
  && ci.Solution.FrameworkSolutions.Select(f => f.Framework).Distinct().Any(f => !f.IsExpired)
  && ci.SupplierServiceAssociations.Any()
  && ci.SupplierServiceAssociations.Any(ssa => (ssa.AssociatedService.PracticeReorganisationType & practiceReorganisationType) == practiceReorganisationType))
```

2024-01-24 16:57 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.Services/Orders/SupplierService.cs
> +                query = query.Where(ci => ci.SupplierServiceAssociations.Any());
Fair point, that is true

2024-01-25 09:31 UTC, bjss-colin approved these changes

2024-01-25 09:57 UTC, imranbashir01 approved these changes

2024-01-25 10:34 UTC, merged