Feature/23206 changes to solutions and services
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #1331
Opened 2024-01-29 09:58 UTC by Patrick-M-BJSS

2024-02-15 13:43 UTC, bjss-colin requested changes

2024-02-15 13:43 UTC, ghost commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Views/Shared/Services/SelectAssociatedServices.cshtml
> +    Model.Services.RemoveAll(x => x.IsSelected);
Let's do this in the model instead as views should really only contain presentation logic while this is business logic.

The first constructor could be updated to exclude `currentServices` from `allServices`, thus rendering the `IsSelected` logic redundant on line number 26 of the model class.

2024-02-15 13:43 UTC, ghost commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Orders/Views/TaskList/TaskListOrderItem.cshtml
> +    if (!(Model.PriceStatus == TaskProgress.NotStarted | Model.PriceStatus == TaskProgress.CannotStart))
Pattern matching could be used here, example:

```csharp
if (Model.PriceStatus is not (TaskProgress.NotStarted or TaskProgress.CannotStart))
```

Same with `QuantityStatus`

2024-02-15 13:43 UTC, ghost commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Orders/Views/AdditionalServices/SelectAdditionalServices.cshtml
> +    Model.Services.RemoveAll(x => x.IsSelected);
Same as earlier comment. This could be done in the model directly

2024-02-15 13:43 UTC, ghost commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Orders/Controllers/SolutionSelection/CatalogueSolutionsController.cs
> +            if (model.ConfirmChanges.GetValueOrDefault(false))
`false` won't be required here in `GetValueOrDefault` since [the default value of a boolean is false](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/default-values)

2024-02-16 16:52 UTC, imranbashir01 approved these changes

2024-02-19 11:24 UTC, bjss-colin approved these changes

2024-02-19 11:41 UTC, merged