Advanced filtering changes - not including modals.
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #1335
Opened 2024-02-09 20:47 UTC by martinkimmings

2024-02-12 14:47 UTC, imranbashir01 approved these changes, later dismissed

2024-02-13 11:03 UTC, bjss-colin requested changes
Two minor changes

2024-02-13 11:03 UTC, ghost commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/Shared/_SolutionSearchDisplay.cshtml
> +            foreach (var fs in Model.CatalogueItem.Solution.FrameworkSolutions) //.Select(fs => $"{fs.Framework.ShortName}{(fs.Framework.IsExpired ? " (expired)" : string.Empty)}")))</p>
Commented out code here could be removed

2024-02-13 11:03 UTC, ghost commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/Shared/_AdditionalFilters.cshtml
> +               asp-route-selected="5|11|12|13|14|15">
Magic numbers. Might be worth creating a consts class, just to give the IDs some meaning in terms of which capabilities they refer to, appending to an array and then doing a `string.Join`

2024-02-13 11:24 UTC, martinkimmings commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/Shared/_SolutionSearchDisplay.cshtml
> +            foreach (var fs in Model.CatalogueItem.Solution.FrameworkSolutions) //.Select(fs => $"{fs.Framework.ShortName}{(fs.Framework.IsExpired ? " (expired)" : string.Empty)}")))</p>
Good spot.

2024-02-13 14:04 UTC, bjss-colin approved these changes

2024-02-13 14:16 UTC, imranbashir01 approved these changes

2024-02-13 14:17 UTC, merged