Feature/22914 view your account
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #1342
Opened 2024-02-16 17:18 UTC by dssherlock

2024-02-19 09:35 UTC, bjss-colin requested changes

2024-02-19 09:35 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.UI.Components/Views/Shared/Components/NhsLoginLink/LoginLink.cshtml
>  ﻿@model NHSD.GPIT.BuyingCatalogue.UI.Components.Views.Shared.Components.NhsLoginLink.LoginLinkModel
This View Component could be removed and all HTML shifted to the view directly since there's less going on in here now and I can't imagine a scenario where we'd re-use this anywhere other than the page header

2024-02-19 09:35 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.UI.Components/Views/Shared/Components/NhsSideNavigationPanel/NhsSideNavigationPanel.cshtml
> +﻿@model NHSD.GPIT.BuyingCatalogue.UI.Components.Views.Shared.Components.NhsSideNavigationPanel.NhsSideNavigationPanelModel
These type of components would typically be better as Tag Helpers as they're generally more flexible by allowing the consumer to construct a dynamic list of tags based on their use case.

However, I don't think we need View Components or Tag Helpers here since these are now only used in a single place in the `_SideNavigationLayout`. Let's remove the View Components for now until a need to reuse arises in the future

2024-02-19 09:35 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.UI.Components/Views/Shared/Components/NhsSideNavigationSection/NhsSideNavigationSection.cshtml
> +﻿@model NHSD.GPIT.BuyingCatalogue.UI.Components.Views.Shared.Components.NhsSideNavigationSection.NhsSideNavigationSectionModel
Same as above

2024-02-19 09:35 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/NHSD.GPIT.BuyingCatalogue.WebApp.csproj
> +    <Folder Include="Areas\Identity\Views\YourAccount\" />
Can be removed

2024-02-19 10:11 UTC, dssherlock commented on src/NHSD.GPIT.BuyingCatalogue.UI.Components/Views/Shared/Components/NhsSideNavigationPanel/NhsSideNavigationPanel.cshtml
> +﻿@model NHSD.GPIT.BuyingCatalogue.UI.Components.Views.Shared.Components.NhsSideNavigationPanel.NhsSideNavigationPanelModel
I was absolutely thinking the same thing! I've been round in circles with this a few times! I was very unhappy with how i left it on Friday and its been bugging me the whole weekend! After all the faffing they ended up becoming a bit irrelevant!

2024-02-19 10:11 UTC, dssherlock commented on src/NHSD.GPIT.BuyingCatalogue.UI.Components/Views/Shared/Components/NhsSideNavigationPanel/NhsSideNavigationPanel.cshtml
> +﻿@model NHSD.GPIT.BuyingCatalogue.UI.Components.Views.Shared.Components.NhsSideNavigationPanel.NhsSideNavigationPanelModel
I'm really glad u said that-it confirmed my gut!

2024-02-19 11:07 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.UI.Components/Views/Shared/Components/NhsSideNavigationPanel/NhsSideNavigationPanel.cshtml
> +﻿@model NHSD.GPIT.BuyingCatalogue.UI.Components.Views.Shared.Components.NhsSideNavigationPanel.NhsSideNavigationPanelModel
Enjoying your day off? 🤣

2024-02-19 12:45 UTC, dssherlock commented on src/NHSD.GPIT.BuyingCatalogue.UI.Components/Views/Shared/Components/NhsSideNavigationPanel/NhsSideNavigationPanel.cshtml
> +﻿@model NHSD.GPIT.BuyingCatalogue.UI.Components.Views.Shared.Components.NhsSideNavigationPanel.NhsSideNavigationPanelModel
I know! I can't settle when im unhappy with something tho!

2024-02-21 17:16 UTC, bjss-colin requested changes

2024-02-21 17:16 UTC, bjss-colin commented on tests/NHSD.GPIT.BuyingCatalogue.WebApp.UnitTests/Models/SideNavigationBaseModelTests.cs
> +        public static void ChildClasses_InheritFrom_SideNavigationBaseModel(Type childType)
This test will never fail because the project will fail to compile if `SolutionDisplayBaseModel` doesn't inherit from `SideNavigationBaseModel`

2024-02-21 17:16 UTC, bjss-colin commented on tests/NHSD.GPIT.BuyingCatalogue.WebApp.UnitTests/Areas/Identity/Models/YourAccountModelTests.cs
> +        public static void Constructor_Requires_Organisation()
There's another way of testing constructors that's commonly used in the test projects, that's actually used in `YourAccountControllerTests`.

One of the caveats with manually instantiating a constructor is that any changes to the number of parameters means you'll potentially have to update every constructor validation test that manually instantiates the constructor.

2024-02-21 17:16 UTC, bjss-colin commented on tests/NHSD.GPIT.BuyingCatalogue.WebApp.UnitTests/Areas/Identity/Models/YourAccountBaseModelTests.cs
> +        [InlineData(typeof(YourAccountModel))]
This test will never fail because the project will fail to compile if `YourAccountModel` doesn't inherit from `YourAccountBaseModel`. In this case I think compiler errors give better assurance.

2024-02-21 17:57 UTC, dssherlock commented on tests/NHSD.GPIT.BuyingCatalogue.WebApp.UnitTests/Areas/Identity/Models/YourAccountModelTests.cs
> +        public static void Constructor_Requires_Organisation()
This fails the Verify Guard clause due to the circular recursive behaviour. I think it doesnt like that Organisation has a LastUpdatedByUser, which has a PrimaryOrganisation.

2024-02-21 18:01 UTC, dssherlock commented on tests/NHSD.GPIT.BuyingCatalogue.WebApp.UnitTests/Areas/Identity/Models/YourAccountModelTests.cs
> +        public static void Constructor_Requires_Organisation()
It is possible to omit the recursive behaviour failure but still failing further down when trying to auto-create the organisation.

2024-02-22 09:23 UTC, imranbashir01 approved these changes

2024-02-22 09:28 UTC, bjss-colin approved these changes

2024-02-22 09:51 UTC, merged