23418/bugfix status for additional service
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #1353
Opened 2024-03-06 16:39 UTC by Patrick-M-BJSS

2024-03-07 14:50 UTC, bjss-colin requested changes

2024-03-07 14:50 UTC, ghost commented on tests/NHSD.GPIT.BuyingCatalogue.WebApp.UnitTests/Areas/Order/Models/SolutionSelection/TaskList/TaskListModelTests.cs
> +        [CommonAutoData(MockingFramework.NSubstitute)]
Let's update all tests in this class to use NSubstitute

2024-03-07 14:50 UTC, ghost commented on tests/NHSD.GPIT.BuyingCatalogue.WebApp.UnitTests/Areas/Order/Models/SolutionSelection/TaskList/TaskListOrderItemModelTests.cs
> +        [CommonAutoData(MockingFramework.NSubstitute)]
Same as above - let's update all tests in this class to use NSubstitute

2024-03-07 14:50 UTC, ghost commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Orders/Views/AdditionalServices/SelectAdditionalServices.cshtml
> +        <form method="post" autocomplete="off">
I'm somewhat curious about this one - what does `autocomplete` do here?

2024-03-07 16:27 UTC, Patrick-M-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Orders/Views/AdditionalServices/SelectAdditionalServices.cshtml
> +        <form method="post" autocomplete="off">
This was a minor issue I found while working on it. If you pressed the browser's back button to return to the page, it would remember that the first option (or whichever one you chose) was selected so would automatically select the first etc. one even though none of them should be selected and the options in the list have changed.

2024-03-07 16:41 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Orders/Views/AdditionalServices/SelectAdditionalServices.cshtml
> +        <form method="post" autocomplete="off">
That behaviour should be okay as the user is returning to a page from an existing journey. One thing we'd have to test with this approach is how form validation errors are presented and whether items would be prepopulated in that scenario. It could potentially introduce more edge cases

2024-03-07 17:02 UTC, Patrick-M-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Orders/Views/AdditionalServices/SelectAdditionalServices.cshtml
> +        <form method="post" autocomplete="off">
So if you selected the 3rd element in the list and hit submit, then pressed the back button it would preselect the 3rd element in the list which is now the element that was below the 3rd element because the other one was removed. It's just preselecting random elements which is different behaviour from if you hit the back link.

2024-03-07 17:07 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Orders/Views/AdditionalServices/SelectAdditionalServices.cshtml
> +        <form method="post" autocomplete="off">
Ah, understood. The key bit there is that the previously selected service won't be in the list anymore and that a random service would instead be picked.

In that case I'll mark this comment as resolved.

2024-03-08 09:23 UTC, imranbashir01 approved these changes

2024-03-08 09:31 UTC, bjss-colin approved these changes

2024-03-08 10:57 UTC, merged