Feature/23386 solutions and services improvements
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #1357
Opened 2024-03-13 11:14 UTC by Patrick-M-BJSS

2024-03-13 16:10 UTC, imranbashir01 approved these changes, later dismissed

2024-03-13 16:23 UTC, bjss-colin requested changes

2024-03-13 16:23 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Orders/Views/TaskList/TaskList.cshtml
> +                    <img src="~/images/circle-info-solid.svg" style="vertical-align:middle; display:inline-block; margin-right:8px" aria-hidden="true" width="20px" /><span style="display:inline-block
Let's create style classes for both the `img` style and `span` style as they seem to be used regularly

2024-03-14 17:32 UTC, bjss-colin approved these changes

2024-03-15 09:10 UTC, imranbashir01 approved these changes

2024-03-15 09:43 UTC, merged