Implementation details e2e tests added
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #137
Opened 2021-06-21 14:56 UTC by EnitanOO

AB#15157
AB#15367

2021-06-21 15:01 UTC, PhysicsJon requested changes

2021-06-21 15:01 UTC, PhysicsJon commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Areas/PublicBrowse/Solution/ImplementationDetails.cs
> +        [InlineData("implementation")]
This can be reduced to a `[Fact]` rather than a `[Theory]` as it's a single data set

2021-06-21 15:40 UTC, EnitanOO commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Actions/PublicBrowse/SolutionAction.cs
> +
done

2021-06-21 15:40 UTC, EnitanOO commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Areas/PublicBrowse/Solution/ImplementationDetails.cs
> +   public class ImplementationDetails : TestBase, IClassFixture<LocalWebApplicationFactory>
removed

2021-06-21 15:41 UTC, EnitanOO commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Areas/PublicBrowse/Solution/ImplementationDetails.cs
> +        [InlineData("implementation")]
changed to [Fact]

2021-06-22 07:02 UTC, PhysicsJon requested changes

2021-06-22 07:02 UTC, PhysicsJon commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Areas/PublicBrowse/Solution/ImplementationDetails.cs
> +            PublicBrowsePages.SolutionAction.ImplementationNameDisplayed().Should().NotBeNullOrEmpty();
I think this should be done by checking that the returned string enumerable contains implementation rather than not null as this could create false positives

2021-06-22 09:37 UTC, PhysicsJon submitted a review, later dismissed
just need to resolve each conversation

2021-06-22 10:30 UTC, PhysicsJon approved these changes

2021-06-22 10:32 UTC, merged