Notifications and preference management for contract expiry.
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #1371
Opened 2024-04-03 12:51 UTC by martinkimmings

2024-04-04 13:50 UTC, bjss-colin requested changes
Some minor points and a few sanity-checks (mostly for myself)

2024-04-04 13:50 UTC, ghost commented on database/NHSD.GPITBuyingCatalogue.Database/Notifications/Tables/EmialNotifications.sql
> +CREATE TABLE notifications.EmailNotifications
Typo in filename
`EmialNotifications` -> `EmailNotifications`

2024-04-04 13:50 UTC, ghost commented on src/BuyingCatalogueFunction/Notifications/ContractExpiryFunction.cs
> +            logger.LogInformation($"Contract Expiry: Executed at { utcNow }");
Rather than string interpolation, let's use this approach https://learn.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-8.0#create-logs

This will create a category in the logging platform that'll allow us to filter on specifically. 

Same applies to all log events

2024-04-04 13:50 UTC, ghost commented on src/BuyingCatalogueFunction/local.settings.json
> +    // TODO: NOTIFY_API_KEY and these need adding to function app settings/terraform
Let's pick this up as part of this PR. There should be some variable substitution files in the terraform functionapp project which'll make this a breeze.

Happy to go through it to sanity check

2024-04-04 13:50 UTC, ghost commented on src/BuyingCatalogueFunction/Notifications/SendEmailNotificationFunction.cs
> +                // TODO: NotificationClient.PrepareUpload can throw ArgumentException("File is larger than 2MB"). Consider catching and throwing NoneTransientException to suppress retries.
Remaining TODO - we shouldn't be emailing PDFs anymore so this may not be an issue now

2024-04-04 13:50 UTC, bjss-colin commented on tests/BuyingCatalogueFunctionTests/Notifications/Services/ContractExpiryServiceTests.cs
> +            var options = fixture.Freeze<IOptions<QueueOptions>>();
Thinking out loud - is this approach because there's a race-condition in that `IOptions<T>.Value` is called in the constructor of `ContractExpiryService`?

2024-04-04 13:50 UTC, bjss-colin commented on tests/NHSD.GPIT.BuyingCatalogue.Services.UnitTests/Orders/OrderServiceTests.cs
>          [InMemoryDbAutoData]
Looks like there's a Moq using at the top of this file. Let's convert any Moq based tests over to NSubstitute while we're making changes

2024-04-04 13:50 UTC, bjss-colin commented on tests/NHSD.GPIT.BuyingCatalogue.UnitTest.Framework/AutoFixtureCustomisations/MoqRelaySpecimenBuilder.cs
> +            : base(new MockRelay(new ExactTypeSpecification(typeof(T))))
Is this for backwards compatibility with existing tests or is it possibly redundant now?

2024-04-04 14:03 UTC, martinkimmings commented on tests/NHSD.GPIT.BuyingCatalogue.Services.UnitTests/Orders/OrderServiceTests.cs
>          [InMemoryDbAutoData]
I saw these changes as a light touch to fix the existing tests. I did initially consider moving them over to NSubstitute but the size of the file put me off. I'll take another look

2024-04-04 14:07 UTC, bjss-colin commented on tests/NHSD.GPIT.BuyingCatalogue.Services.UnitTests/Orders/OrderServiceTests.cs
>          [InMemoryDbAutoData]
There are some regex patterns that I shared in Teams which will simplify most of the migration. There are patterns for changing the parameters from `Mock<T>` to `T` and another pattern that switches the `Setup` over to the NSubstitute way

2024-04-04 14:40 UTC, martinkimmings commented on tests/BuyingCatalogueFunctionTests/Notifications/Services/ContractExpiryServiceTests.cs
> +            var options = fixture.Freeze<IOptions<QueueOptions>>();
I've moved more of the test code to use [Frozen] parameters however I think I ended up doing this because I was having problems with the `IOptions<T>`.  `Value` was always null when the `ContractExpiryService` service was created unless I explicitly created it after the `IOptions<T>` was fully mocked.

2024-04-04 14:42 UTC, bjss-colin commented on tests/BuyingCatalogueFunctionTests/Notifications/Services/ContractExpiryServiceTests.cs
> +            var options = fixture.Freeze<IOptions<QueueOptions>>();
This makes sense. I'd imagined it was a race condition of sorts. It's easier to do this too rather than creating many different customizations or some overly-smart way of getting/setting.

2024-04-05 14:13 UTC, imranbashir01 approved these changes

2024-04-08 09:54 UTC, martinkimmings commented on database/NHSD.GPITBuyingCatalogue.Database/Notifications/Tables/EmialNotifications.sql
> +CREATE TABLE notifications.EmailNotifications
Good spot. I've renamed the file.

2024-04-08 09:56 UTC, martinkimmings commented on src/BuyingCatalogueFunction/Notifications/ContractExpiryFunction.cs
> +            logger.LogInformation($"Contract Expiry: Executed at { utcNow }");
Yes that's good to know. I should have spotted this as I was inconsistent the existing code anyway. I've made those changes.

2024-04-08 09:58 UTC, martinkimmings commented on src/BuyingCatalogueFunction/Notifications/SendEmailNotificationFunction.cs
> +                // TODO: NotificationClient.PrepareUpload can throw ArgumentException("File is larger than 2MB"). Consider catching and throwing NoneTransientException to suppress retries.
I've removed the `TODO` and the `PrepareUpload` call because it's currently unused for the emails that this PR adds.

2024-04-08 10:06 UTC, martinkimmings commented on tests/NHSD.GPIT.BuyingCatalogue.UnitTest.Framework/AutoFixtureCustomisations/MoqRelaySpecimenBuilder.cs
> +            : base(new MockRelay(new ExactTypeSpecification(typeof(T))))
I added this as part of replacing `BlobServiceClientCustomization.cs` which returned a real `BlobServiceClient` rather than a mocked version and I took the same approach with the NSubstitute queue based tests.

This moq version will be redundant when the last moq test that uses `BlobServiceClient` is swapped over to NSubstitute.

2024-04-08 10:10 UTC, martinkimmings commented on tests/NHSD.GPIT.BuyingCatalogue.Services.UnitTests/Orders/OrderServiceTests.cs
>          [InMemoryDbAutoData]
All the tests in this file use NSubstitute now :

2024-04-08 13:48 UTC, martinkimmings commented on src/BuyingCatalogueFunction/local.settings.json
> +    // TODO: NOTIFY_API_KEY and these need adding to function app settings/terraform
I've made the terraform changes

2024-04-09 08:24 UTC, bjss-colin approved these changes

2024-04-09 08:43 UTC, merged