Bug/233585 Bug fix for Planned Delivery Date matching page.
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #1375
Opened 2024-04-04 10:41 UTC by dssherlock

Matching does not occur when OrderItemRecipients have not already been created for Service.

2024-04-04 12:07 UTC, imranbashir01 submitted a review, later dismissed

2024-04-04 12:34 UTC, bjss-colin requested changes

2024-04-04 12:34 UTC, bjss-colin commented on tests/NHSD.GPIT.BuyingCatalogue.WebApp.UnitTests/Areas/Order/Controllers/Contracts/DeliveryDatesControllerTests.cs
> +            [Frozen] Mock<IOrderService> orderService,
Tests should be using the new NSubstitute approach. While we're making changes in this class, let's update all tests in this class to use NSubstitute. 

https://github.com/nhs-digital-gp-it-futures/GPITBuyingCatalogue/pull/1360

2024-04-04 12:34 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Orders/Controllers/Contracts/DeliveryDatesController.cs
> +            if (model.MatchDates == true && solutionId != null)
This can be shortened to a ternary where the value is assigned to `dates` directly.

```csharp
var dates = (model.MatchDate.GetValueOrDefault() && solutionId is not null)
    ? ...
    : ...;
```

2024-04-05 14:54 UTC, bjss-colin approved these changes

2024-04-05 15:17 UTC, merged