Prevent user saving a shortlist with zero results
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #1383
Opened 2024-04-11 09:01 UTC by dssherlock

2024-04-11 09:25 UTC, bjss-colin requested changes

2024-04-11 09:25 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/wwwroot/ts/Filters.ts
> +        return sortOptions ? sortOptions.value : null;
As `getSortBy` is used to set query string key-value pairs in the URL, this will result in a `sortBy=null` in the URL. Let's update the code above to prevent that when `getSortBy` returns null

2024-04-11 10:41 UTC, dssherlock commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/wwwroot/ts/Filters.ts
> +        return sortOptions ? sortOptions.value : null;
ah yes good spot

2024-04-11 14:45 UTC, bjss-colin commented
CodeCov is having a moment again - identifying a change in test coverage where there are existing tests that validate the behaviour.

I'll force-merge this once it's gone through testing.

2024-04-12 09:35 UTC, imranbashir01 approved these changes

2024-04-12 09:48 UTC, bjss-colin approved these changes

2024-04-12 09:48 UTC, merged