Nav bar and Logo updates-Buyer
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #1388
Opened 2024-04-17 15:06 UTC by dssherlock

2024-04-17 15:15 UTC, bjss-colin commented
Don't forget to update unit tests prior to raising PRs as per the recent ways of working changes 😉 

Happy to leave this active for now as there aren't many unit tests required for the Nav Menu Model

2024-04-18 09:21 UTC, imranbashir01 approved these changes

2024-04-18 09:41 UTC, bjss-colin requested changes

2024-04-18 09:41 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Models/Shared/NavigationMenuModel.cs
> +                                nameof(DashboardController.Index),
As `DashboardController.Index` is essentially a redirect, this will set up a redirect chain that'll prevent the users' browser back button from taking them back to the previous page, unless they click the back button fast enough. Let's update this instead to point at the `Organisation` method which requires the `internalOrgId`

2024-04-18 13:52 UTC, bjss-colin approved these changes

2024-04-18 13:54 UTC, merged