Feature/23520 Pagination Component
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #1397
Opened 2024-05-01 15:44 UTC by dssherlock

Add the govuk-frontend pagination component in the following places:

- Catalogue Solutions
- View Orders
- View Competitions

2024-05-01 16:23 UTC, bjss-colin requested changes
Some minor points and one point related to the recent pentest

2024-05-01 16:23 UTC, ghost commented on src/NHSD.GPIT.BuyingCatalogue.Services/Competitions/CompetitionsService.cs
> +        var query = await GetCompetitions(internalOrgId);
This will be a list rather than a query at this point, since `GetCompetitions` uses `ToListAsync`. Since this is dynamically sized, it might be better to craft a query here so that the pagination will take effect at a database level.

2024-05-01 16:23 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/Solutions/SearchResults.cshtml
> +        base-url="@(Url.Action(
Thinking about the recent pentest and the issue where embedded URLs were called out as a risk for cross-site-scripting, I'm wondering if it's possible to achieve this without specifying a full URL.

2024-05-01 16:23 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.UI.Components/Views/Shared/TagHelpers/GDSPagination/GDSPaginationTagHelper.cs
> +                ? ViewContext.HttpContext.Request.GetEncodedUrl()
Further to my comment on the view about XSS, `GetEncodedUrl` seems to work sufficiently here when I've tested this locally. Each time the JavaScript variant of filtering is used, `GetEncodedUrl` returns the correct URL.

The issue with `BaseUrl` in this case is that we're using `AppendHtml` to embed that in the body. This completes the attack vector since the user browser will treat malicious HTML, injected via the query string, as valid HTML.

One thing I have spotted is that `GetEncodedUrl` maybe returns a bit _too_ much info when using the JavaScript based filtering process. The TypeScript may need to be revisited so that it's only setting query string params when the value is not null.

2024-05-01 16:23 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/Solutions/SearchResults.cshtml
> +    <govuk-pagination
It's entirely possible that I'm being dense, but having done an `npx gulp min` and a rebuild, I'm not seeing any styling on the pagination component

![image](https://github.com/nhs-digital-gp-it-futures/GPITBuyingCatalogue/assets/90630744/dfb5cb0e-8026-44f0-95da-37648d0d43f6)

2024-05-01 17:25 UTC, dssherlock commented on src/NHSD.GPIT.BuyingCatalogue.UI.Components/Views/Shared/TagHelpers/GDSPagination/GDSPaginationTagHelper.cs
> +                ? ViewContext.HttpContext.Request.GetEncodedUrl()
No ive definitely had issues when it just uses GetEncodedUrl as it returns the searchResult ajax callback url instead.

2024-05-02 08:10 UTC, dssherlock commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/Solutions/SearchResults.cshtml
> +        base-url="@(Url.Action(
So i think the reason this was used in the original pagination component in the first place is because when you are on the Solutions page, the urls are initially all set correctly, however as soon as you start filtering, it does an ajax callback to update the search results. If you don't use that base url and just use the Request Url, then the new page urls will use the ajax callback instead and when the user clicks on it, they just see a partial view rendered on the page.

2024-05-02 08:12 UTC, dssherlock commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/Solutions/SearchResults.cshtml
> +        base-url="@(Url.Action(
I did half consider in this case trying to use the Request.RefererUrl instead as this could possibly work, but decided to go with the existing logic as it reduced the testing required.

2024-05-02 08:20 UTC, dssherlock commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/Solutions/SearchResults.cshtml
> +        base-url="@(Url.Action(
Another issue i found with this is that the HttpUtility library does not seem to work well with relative urls. So any of the standard ways of updating a parameter using ParseQueryString become a bit unwieldy unless u use the Url.ActionContext.HttpContext.Request.Scheme. I guess always possible to just use a regex to update the page parameter but its not encouraged.

2024-05-02 08:24 UTC, dssherlock commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/Solutions/SearchResults.cshtml
> +    <govuk-pagination
Tbh i messed around with my local environment so many times swapping between current, version 4.2 and the latest version im not 100% sure how i ended up with it working!
![image](https://github.com/nhs-digital-gp-it-futures/GPITBuyingCatalogue/assets/113588987/2b8a317b-60ba-4a93-a26f-85b6f13cab0d)
I think this is what got it working in the end.

2024-05-02 08:46 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/Solutions/SearchResults.cshtml
> +        base-url="@(Url.Action(
Fair point - I'd tested based on some of the quick filters available which happened to match the edge cases where `GetEncodedUrl` works. It works all of the time when not using JavaScript since the app uses GET and POST.

2024-05-02 08:46 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.UI.Components/Views/Shared/TagHelpers/GDSPagination/GDSPaginationTagHelper.cs
> +                ? ViewContext.HttpContext.Request.GetEncodedUrl()
Conversation resolved based on previous point

2024-05-02 09:07 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/Solutions/SearchResults.cshtml
> +    <govuk-pagination
That's done the trick locally. This change will need persisting in the PR so the build agent can pick up the relevant versions and artifacts

2024-05-02 09:12 UTC, dssherlock commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/package-lock.json
> +      "dev": true,
I'm not sure these should be included tho? They were added when did the install

2024-05-02 09:15 UTC, dssherlock commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/Solutions/SearchResults.cshtml
> +    <govuk-pagination
I'm not sure how this will work as part of the build and release process tho. I assumed updating the version in package.json and package-lock would be sufficient. There are some other changes that appeared in the package-lock.json file that I'm not convinced should be there though-the additional "dev" property, along with a few bits that have been removed. This happened as part of the npm install process. Thoughts?

2024-05-02 09:35 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/Solutions/SearchResults.cshtml
> +    <govuk-pagination
> I'm not sure how this will work as part of the build and release process th

It's a standard package restore process much like NuGet is. Packages will be restored at build time based on the packages and versions listed in package.json. package-lock.json just freezes the dependencies so that others are able to install the same dependencies in the same manner.

> There are some other changes that appeared in the package-lock.json file that I'm not convinced should be there though-the additional "dev" property

The `dev` property isn't referring to any of the dependencies required to run this in a release mode. They're packages required specifically for development processes, such as the gulp build process. This can/should be tested locally by using the `--production` switch with `npm install`.

In this case, the govuk-frontend package version needs to be updated to `4.6.0` otherwise the build agent won't restore the correct version and subsequently the styles won't work on any environment.

2024-05-02 10:06 UTC, dssherlock commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/Solutions/SearchResults.cshtml
> +    <govuk-pagination
Ok yep thats what i thought. So i will just leave the legitimate version update changes in the package-lock.json file and revert the other ones (in red)
![image](https://github.com/nhs-digital-gp-it-futures/GPITBuyingCatalogue/assets/113588987/b553059e-3912-4597-a938-c2fcbd9203d4)

2024-05-02 10:08 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/Solutions/SearchResults.cshtml
> +    <govuk-pagination
I'd leave the package-lock.json as it currently is since this file is generated automatically. Manual changes will be overriden. We literally just need to update the package version of govuk-frontend to 4.6.0 and that'll resolve this one

2024-05-02 10:16 UTC, dssherlock commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/Solutions/SearchResults.cshtml
> +    <govuk-pagination
Ok why 4.6 though? I thought that was a typo!!

2024-05-02 14:35 UTC, imranbashir01 approved these changes

2024-05-02 15:06 UTC, bjss-colin approved these changes

2024-05-02 15:09 UTC, merged