Order triage and form framework changes
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #1399
Opened 2024-05-07 08:24 UTC by martinkimmings

2024-05-07 16:18 UTC, imranbashir01 submitted a review, later dismissed

2024-05-08 09:20 UTC, bjss-colin requested changes
One minor change. 

On a side note, it's good to finally see the Triage Value query parameter being removed

2024-05-08 09:20 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.Services/Orders/OrderService.cs
> +            var framework = dbContext.Frameworks.Where(f => f.Id == selectedFrameworkId).FirstOrDefault();
Prefer `FirstOrDefaultAsync` to prevent any thread blocking

2024-05-08 11:54 UTC, bjss-colin approved these changes

2024-05-08 12:16 UTC, merged