Feature/23410 viewing specific shortlist
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #1401
Opened 2024-05-08 09:19 UTC by Patrick-M-BJSS

2024-05-08 10:11 UTC, bjss-colin requested changes
Rough first review pass: spotted an issue with filtering logic and a few minor code cleanup points

2024-05-08 10:11 UTC, ghost commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Views/Shared/Shortlists/_ResultsForFramework.cshtml
> +    <h3></h3>
Empty H3

2024-05-08 10:11 UTC, ghost commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Competitions/Views/CompetitionSelectSolutions/_MultiSolutionSelection.cshtml
> +            <nhs-card-v2 class="nhsuk-card__inverted" style="margin-bottom:20px">
I imagine we'll want to use the inverted cards elsewhere.

This could be a property on the tag helpper, such as `IsInverted` (HTML attribute name `inverted`), that conditionally adds the `nhsuk-card__inverted` class when set to true via html attributes. There are some examples in this PR where the inverted card is used in multiple places, that could be swapped out with an attribute.

Example:

```html
<nhs-card-v2 inverted="true"></nhs-card-v2>
```

2024-05-08 10:11 UTC, ghost commented on src/NHSD.GPIT.BuyingCatalogue.Services/Solutions/SolutionsFilterService.cs
> +            Task<(IList<CatalogueItem> CatalogueItems, PageOptions Options, List<CapabilitiesAndCountModel>
Doesn't look like elements 2 & 3 in this tuple are used anywhere. This method return could be simplified

2024-05-08 10:11 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Competitions/Controllers/CompetitionsDashboardController.cs
> +        frameworkId = (await filterService.GetFilterIds(organisation.Id, filterId))?.FrameworkId ?? frameworkId;
Logic seems to be the wrong way around here since the value in `frameworkId` should take precendence.

This whole check could be removed since the `frameworkId` is passed in via the shortlist results page. Rather than defaulting, if the value is manipulated in the URL then we should return.

The two things to validate
1. `frameworkId` is not null or empty (prefer `string.IsNullOrWhitespace` rather than `framework.IsNullOrEmpty`)
2. Is it a valid framework that exists in the database. Query the `IFrameworkService.GetFramework` and check for null

2024-05-08 10:11 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Controllers/ManageFiltersController.cs
> +                FilterResults = (List<EntityFramework.Catalogue.Models.CatalogueItem>)solutions,
`.ToList()` should work here rather than casting, since casts could fail

2024-05-08 10:11 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Controllers/ManageFiltersController.cs
> +            var frameworks = await frameworkService.GetFrameworksWithPublishedCatalogueItems();
Worth sanity checking this logic with `frameworks` to think about this approach. If I save a shortlist that includes TIF as a framework, I wouldn't necessarily expect to see DFOCVC in the shortlist results page :wink:

![image](https://github.com/nhs-digital-gp-it-futures/GPITBuyingCatalogue/assets/90630744/c03a4e9b-3b87-4d1f-8bcf-0474651b9e0c)

![image](https://github.com/nhs-digital-gp-it-futures/GPITBuyingCatalogue/assets/90630744/13bc7a36-3bab-4f2c-b479-030d06794c0b)


The frameworks should be driven from the solutions returned from the shortlist. The model should manipulate that solutions list (hint: `GroupBy`) to group the solutions by framework. Bear in mind that models are great places for massaging data into the required format, rather than doing too much in the Controller or Service layers.

2024-05-08 10:11 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Views/Shared/Shortlists/FilterDetails.cshtml
> +                                  text="Delete filter" />
Should this read `Delete shortlist` instead?

2024-05-08 13:30 UTC, bjss-colin requested changes
As Martin's PR has been merged (see #1399), let's also update `CompetitionOrderService.CreateOrder` to pass in the Framework from the Competition, and `CompetitionSelectSolutionsController.HandleDirectAward` to we're passing the framework in via `selectedFrameworkId`

2024-05-09 08:51 UTC, bjss-colin requested changes
Some additional code cleanup suggestions

2024-05-09 08:51 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Models/Shared/ReviewFilterModel.cs
> +    public ReviewFilterModel(FilterDetailsModel filterDetails, string internalOrgId, List<FrameworkFilterInfo> frameworks, List<CatalogueItem> filterResults, bool inCompetition, FilterIdsModel filter
How about this?

Note that `frameworks` isn't actually needed. As mentioned above, that data is already discoverable via `CatalogueItem.Solution.FrameworkSolutions`. `CatalogueItem` is the type held within the `filterResults` collection.

Also worth noting that `ResultsForFrameworkModel` has been updated since that only needs access to the Framework Id and Framework Name.

It'll be good to sanity check the data returned in various filters such as framework only, capabilities and epics etc.

```csharp
public ReviewFilterModel(FilterDetailsModel filterDetails, string internalOrgId, List<CatalogueItem> filterResults, bool inCompetition, FilterIdsModel filterIds = null)
    : this(filterDetails, filterIds)
{
    ArgumentNullException.ThrowIfNull(filterIds);

    ResultsCount = filterResults.Count;
    InCompetition = inCompetition;

    var selectedFrameworks = filterResults
        .SelectMany(x => x.Solution.FrameworkSolutions)
        .GroupBy(x => (x.Framework.ShortName, x.Framework.Id));

    if (!string.IsNullOrWhiteSpace(filterIds.FrameworkId))
        selectedFrameworks = selectedFrameworks.Where(x => string.Equals(x.Key.Id, filterIds.FrameworkId));

    ResultsForFrameworks = selectedFrameworks.Select(
            x => new ResultsForFrameworkModel(
                internalOrgId,
                filterDetails.Id,
                x.Key.Id,
                x.Key.ShortName,
                x.Select(y => y.Solution.CatalogueItem).ToList(),
                !inCompetition))
        .ToList();
}
```

2024-05-09 08:51 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Controllers/ManageFiltersController.cs
> +            var frameworks = await frameworkService.GetFrameworksWithPublishedCatalogueItems();
Reiterating that `frameworks` isn't actually required here. See comment below on the model for more

2024-05-09 08:51 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Views/Shared/Shortlists/FilterDetails.cshtml
> +                            <partial name="_ResultsForFramework.cshtml" model="resultsForFrameworkModel"/>
.cshtml not required here

2024-05-09 08:51 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Competitions/Controllers/CompetitionsDashboardController.cs
> +        return View("Views/Shared/Shortlists/FilterDetails.cshtml", model);
`View` takes a view name rather than a file path. `.cshtml` not required here and `Views/Shared` can be removed 😃 

Worth doing a Find All to find similar instances (should be 2 in this PR)

2024-05-09 08:51 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Views/Shared/Shortlists/FilterDetails.cshtml
> +    var hasResults = @Model.ResultsCount > 0;
`@` not required here since this is already within the context of a code block

2024-05-09 08:51 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Views/Shared/Shortlists/FilterDetails.cshtml
> +                            <a href="@Url.Action(nameof(ManageFiltersController.DeleteFilter),
There is an existing component for delete links - `vc:nhs-delete-button`

That could be wrapped in a `<span></span>` which then applies the additional styles :wink:

2024-05-09 16:01 UTC, Patrick-M-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Views/Shared/Shortlists/FilterDetails.cshtml
> +                            <partial name="_ResultsForFramework.cshtml" model="resultsForFrameworkModel"/>
It only seems to work when there is a .cshtml

2024-05-10 07:38 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Views/Shared/Shortlists/FilterDetails.cshtml
> +                            <partial name="_ResultsForFramework.cshtml" model="resultsForFrameworkModel"/>
What happens in that scenario? What error occurs and what paths does the error contain? 

Hint: neither `Views` nor `Shared` are required in the name, but the name of a certain subdirectory is required.

2024-05-13 12:19 UTC, bjss-colin requested changes
1 minor point and 2 around the link issue we saw during the demo on Friday

2024-05-13 12:19 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Controllers/ManageFiltersController.cs
> +            return View("Views/Shared/Shortlists/FilterDetails.cshtml", model);
Looks like this was missed during the recent rebase.

View path can be changed to `Shortlists/FilterDetails` without the cshtml and without the `Views/Shared` path-part. ASP.NET Core already knows to look in `Views/Shared` for shared views.

2024-05-13 12:19 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Views/Shared/Shortlists/FilterDetails.cshtml
> +                                    <vc:nhs-delete-button url="@Url.Action(nameof(ManageFiltersController.DeleteFilter),
This link looks like it'll break on the Competition journey as we saw during the demo. Let's fix this.

When building links in ASP.NET core, the Action, Controller and Area are all mandatory if the user is being redirected to a different controller and area.

2024-05-13 12:19 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Views/Shared/Shortlists/FilterDetails.cshtml
> +            <vc:nhs-delete-button url="@Url.Action(nameof(ManageFiltersController.DeleteFilter),
Same as above, this link isn't specific enough that would allow ASP.NET Core to choose the correct link, since it isn't being told which Controller and Area the `DeleteFilter` action lives on.

2024-05-14 09:39 UTC, bjss-colin requested changes
Minor points from latest commit

2024-05-14 09:39 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Competitions/Views/CompetitionSelectSolutions/_MultiSolutionSelection.cshtml
> +        @Html.HiddenFor(m => m.ReviewFilter.FilterDetails.ApplicationTypes[i])
Inconsistent approaches: let's use the `<input type="hidden" asp-for="..." />` approach as above

2024-05-14 09:39 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Competitions/Views/CompetitionSelectSolutions/_SingleSolutionSelection.cshtml
> +        @Html.HiddenFor(m => m.ReviewFilter.FilterDetails.ApplicationTypes[i])
Inconsistent approaches: let's use the `<input type="hidden" asp-for="..." />` approach as above

2024-05-14 10:13 UTC, imranbashir01 requested changes
links on the Results for the shortlist page are broken, I get an incorrect URL page when I click on the link. Also a full stop missing from "All links open in a new tab"

2024-05-14 15:42 UTC, imranbashir01 approved these changes

2024-05-15 08:34 UTC, bjss-colin approved these changes

2024-05-15 08:44 UTC, merged