Add additional services page
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #142
Opened 2021-06-22 12:47 UTC by RahulJha-mastek

Story AB#14877
Task AB#15320
Task AB#15410

2021-06-22 15:19 UTC, leerogers-bjss submitted a review, later dismissed

2021-06-22 15:19 UTC, leerogers-bjss commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Controllers/SolutionDetailsController.cs
> +            if (string.IsNullOrWhiteSpace(id))
this is no longer needed because of the new ArgumentNullActionFilter doing Generic Controller Parameters null checks

2021-06-22 15:19 UTC, leerogers-bjss commented on tests/NHSD.GPIT.BuyingCatalogue.WebApp.UnitTests/Areas/Solutions/Controllers/SolutionDetailsControllerTests.cs
> +            var controller = new SolutionDetailsController(Mock.Of<IMapper>(),
this test can be removed due to the new ArgumentNullActionFilter handling all the null checks

2021-06-23 07:57 UTC, RahulJha-mastek commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Controllers/SolutionDetailsController.cs
> +            if (string.IsNullOrWhiteSpace(id))
Removed null check

2021-06-23 07:57 UTC, RahulJha-mastek commented on tests/NHSD.GPIT.BuyingCatalogue.WebApp.UnitTests/Areas/Solutions/Controllers/SolutionDetailsControllerTests.cs
> +            var controller = new SolutionDetailsController(Mock.Of<IMapper>(),
Removed null check test case

2021-06-23 08:30 UTC, kiran-mastek commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/SolutionDetails/AdditionalServices.cshtml
> +                    <dd class="nhsuk-summary-list__value">
Please use the taghelper with controller, action and route Id parameter for both the links below so the URL won't need hardcoding and change later if routing changes. 

There should be examples of similar usage in the project.

2021-06-23 12:43 UTC, RahulJha-mastek commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/SolutionDetails/AdditionalServices.cshtml
> +                    <dd class="nhsuk-summary-list__value">
Used Tag helper for page links

2021-07-01 10:16 UTC, bjss-chris requested changes

2021-07-01 10:16 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/MappingProfiles/SolutionDetailsProfile.cs
> +
Ideally we shouldn't be adding more mappings. However, we can leave this as is for now as you originally did this last week.

2021-07-01 10:16 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Models/AdditionalServiceModel.cs
> +    public class AdditionalServiceModel
`sealed`

2021-07-01 10:16 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Models/AdditionalServiceModel.cs
> +        public string SolutionId { get; set; }
Should be of type `CatalogueItemId`.

2021-07-01 10:16 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Models/AdditionalServicesModel.cs
> +using NHSD.GPIT.BuyingCatalogue.ServiceContracts.Solutions;
Is this required?

2021-07-01 10:16 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Models/AdditionalServicesModel.cs
> +    public class AdditionalServicesModel : SolutionDisplayBaseModel
`sealed`

2021-07-05 10:19 UTC, RahulJha-mastek commented on src/NHSD.GPIT.BuyingCatalogue.Services/Csv/CsvService.cs
> +                        CommencementDate = order.CommencementDate.Value,
Reverted changes.

2021-07-05 10:19 UTC, RahulJha-mastek commented on src/NHSD.GPIT.BuyingCatalogue.Services/Csv/CsvService.cs
> +                        M1Planned = recipient.DeliveryDate.Value,
Reverted changes.

2021-07-05 10:19 UTC, RahulJha-mastek commented on src/NHSD.GPIT.BuyingCatalogue.Services/Solutions/SolutionsService.cs
> +                .Include(i => i.Supplier).ThenInclude(s => s.CatalogueItems).ThenInclude(c => c.AdditionalService)
Updated Code in new `GetSolutionOverview()` method.

2021-07-05 10:19 UTC, RahulJha-mastek commented on src/NHSD.GPIT.BuyingCatalogue.Services/Solutions/SolutionsService.cs
> +                .Include(i => i.Supplier).ThenInclude(s => s.CatalogueItems).ThenInclude(c => c.AdditionalService)
Updated `GetSolutionWithAllAdditionalServices()` method with new approach.

2021-07-05 10:19 UTC, RahulJha-mastek commented on src/NHSD.GPIT.BuyingCatalogue.Services/Solutions/SolutionsService.cs
> +                .Include(i => i.Supplier).ThenInclude(s => s.CatalogueItems).ThenInclude(c => c.AssociatedService)
For Associated/ Additional service page, we are calling only their specific methods `GetSolutionWithAllAssociatedServices()`/`GetSolutionWithAllAdditionalServices()`, and not GetSolutionOverview().
That is why Associated Services is included with `.Take(1)`, which will pull only one associated service data.

2021-07-05 10:19 UTC, RahulJha-mastek commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/MappingProfiles/SolutionDetailsProfile.cs
> +
Leaving mapper for now.

2021-07-05 10:20 UTC, RahulJha-mastek commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Models/AdditionalServiceModel.cs
> +    public class AdditionalServiceModel
Updated `AdditionalServiceModel `as sealed

2021-07-05 10:20 UTC, RahulJha-mastek commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Models/AdditionalServiceModel.cs
> +        public string SolutionId { get; set; }
Updated type to `CatalogueItemId`

2021-07-05 10:21 UTC, RahulJha-mastek commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Models/AdditionalServicesModel.cs
> +using NHSD.GPIT.BuyingCatalogue.ServiceContracts.Solutions;
Removed namespace `using NHSD.GPIT.BuyingCatalogue.ServiceContracts.Solutions;`

2021-07-05 10:21 UTC, RahulJha-mastek commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Models/AdditionalServicesModel.cs
> +    public class AdditionalServicesModel : SolutionDisplayBaseModel
Updated `AdditionalServicesModel` as `sealed`

2021-07-05 10:50 UTC, bjss-chris approved these changes

2021-07-05 10:55 UTC, merged