Feature/23321 nhs app filters
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #1435
Opened 2024-06-19 11:37 UTC by dssherlock

2024-06-20 14:51 UTC, imranbashir01 approved these changes, later dismissed

2024-06-21 10:25 UTC, bjss-colin requested changes
One minor point

2024-06-21 10:25 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.EntityFramework/Catalogue/Configuration/InteropNhsAppIntegrationType.cs
> +    Online_Consultations,
Let's add explicit integers here. Enums apply ints based on the order so if, for example, `Online_Consultations` is moved to the end of this enum then the implicit int will change from 0 to 3 and all other enum values will decrement by -1.

2024-06-21 12:02 UTC, bjss-colin approved these changes

2024-06-21 12:03 UTC, merged