23637 admin manage orders
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #1438
Opened 2024-06-27 10:16 UTC by dssherlock

2024-06-27 10:57 UTC, bjss-colin requested changes
Some minor model binding observations and potentially unused properties

2024-06-27 10:57 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.Services/Orders/OrderAdminService.cs
> +                if (Enum.TryParse(status, true, out OrderStatus orderStatus)
ASP.NET Core will handle this out of the box for us. Pass `OrderStatus?` to the controller query string parameters and leave model binding handle it.

We did similar with the older `OrderTriageValue` enum that was passed around in the order journey, though that's now removed.

2024-06-27 10:57 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.Services/Orders/OrderAdminService.cs
> +using System.Runtime.CompilerServices;
I don't think these 3 using statements are required

2024-06-27 10:57 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/ManageOrders/ManageOrdersDashboardModel.cs
> +            Enum.GetValues(typeof(OrderStatus))
Could use `Enum.GetValues<OrderStatus>()` here which would remove the need for `Cast<OrderStatus>()`

2024-06-27 10:57 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Controllers/ManageOrdersController.cs
> +            return RedirectToAction(
What happens if the form is submitted with no selection?

2024-06-27 10:57 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/ManageOrders/ManageOrdersDashboardModel.cs
> +        public List<FrameworkFilterInfo> Frameworks { get; set; }
Doesn't look like this is used anywhere

2024-06-27 10:57 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.Services/Orders/OrderAdminService.cs
> +            var orderList = await baseQuery.ToListAsync();
This will pull in all orders, from the database, not matching the order status and apply filtering in-memory

2024-06-27 10:57 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Controllers/ManageOrdersController.cs
> +            [FromQuery] string status = "")
This can be `OrderStatus?` with a default of `null`

2024-06-27 11:14 UTC, dssherlock commented on src/NHSD.GPIT.BuyingCatalogue.Services/Orders/OrderAdminService.cs
> +            var orderList = await baseQuery.ToListAsync();
Yes i didn't believe we could filter on order status as this isn't an actual value in the DB-it is a property that is calculated in-memory.

2024-06-27 11:18 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.Services/Orders/OrderAdminService.cs
> +            var orderList = await baseQuery.ToListAsync();
I'll add a cleanup activity to remove the `OrderStatusId` column, and other unused columns, in the database

2024-06-27 11:21 UTC, dssherlock commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Controllers/ManageOrdersController.cs
> +            return RedirectToAction(
Technically nothing-it will just redirect to the index with the filters set to nothing-so it will basically act like the clear all filters link. But it could leave the url looking a bit odd i guess (status=&framework=.

2024-06-27 11:24 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Controllers/ManageOrdersController.cs
> +            return RedirectToAction(
I don't think we need to add validation or anything but it might not be a bad idea to set the values only if they're populated

2024-06-27 12:54 UTC, dssherlock commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Controllers/ManageOrdersController.cs
> +            return RedirectToAction(
Actually having debugged it, it appears to be clever enough to only add the route values if they are not null. So it is all fine.

2024-06-27 14:52 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Controllers/ManageOrdersController.cs
> +            return RedirectToAction(
Ah, even better. That's perfect

2024-06-28 12:23 UTC, bjss-colin requested changes

2024-06-28 12:23 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.Services/Framework/FrameworkService.cs
> +        public async Task<List<FrameworkFilterInfo>> GetAllFrameworks() =>
This does the same thing as `GetFrameworks` in this class, but with a different model. Let's update the code to use the existing `GetFrameworks`

2024-06-28 13:14 UTC, imranbashir01 submitted a review, later dismissed

2024-06-28 13:59 UTC, imranbashir01 approved these changes

2024-06-28 14:09 UTC, bjss-colin approved these changes

2024-06-28 14:36 UTC, merged