Feature: Add and edit Integration types
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #1446
Opened 2024-07-10 13:48 UTC by bjss-colin

2024-07-10 15:18 UTC, dssherlock commented on src/NHSD.GPIT.BuyingCatalogue.Services/Integrations/IntegrationsService.cs
> +
No null check-does this integration exist?

2024-07-10 15:27 UTC, dssherlock commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Controllers/ManageIntegrationsController.cs
> +
Check valid integration id

2024-07-10 15:49 UTC, dssherlock commented on tests/NHSD.GPIT.BuyingCatalogue.WebApp.UnitTests/Areas/Admin/Controllers/ManageIntegrationsControllerTests.cs
> +
Maybe a check here that the id is actually a valid Enum value.

2024-07-10 15:50 UTC, dssherlock commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/IntegrationsModels/AddEditIntegrationTypeModel.cs
> +
Maybe make these const that can be referenced in the tests. Easier to keep track of if we change the value

2024-07-10 15:52 UTC, dssherlock requested changes
Mainly just around the Enum bug fix

2024-07-11 08:15 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.Services/Integrations/IntegrationsService.cs
> +
Added in a null check. Replicating the behaviour of the Edit method below, the check will return early.

2024-07-11 08:16 UTC, bjss-colin commented on tests/NHSD.GPIT.BuyingCatalogue.WebApp.UnitTests/Areas/Admin/Controllers/ManageIntegrationsControllerTests.cs
> +
Switched to an int. Added an extension method to convert int to the SupportedIntegrations enum type.

This enum will be removed once the Admin > Solutions > Interop section is reworked so that it's more dynamic.

2024-07-11 08:49 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/IntegrationsModels/AddEditIntegrationTypeModel.cs
> +
Done

2024-07-11 08:50 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Controllers/ManageIntegrationsController.cs
> +
Changed to use `int` in the controllers, that is converted to `SupportedIntegrations` with an error raised if the ID is changed in the URL.

2024-07-11 10:27 UTC, dssherlock approved these changes

2024-07-11 10:40 UTC, merged