POC
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #1470
Opened 2024-08-28 07:09 UTC by dssherlock

2024-08-29 14:21 UTC, bjss-colin reviewed
Haven't yet finished reviewing as I'm working on finishing my DPI changes also. Took a quick sneak peek

2024-08-29 14:21 UTC, ghost commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Views/Shared/QuantitySelection/SelectServiceRecipientQuantity.cshtml
> +                            var index = Array.FindIndex(Model.SubLocations[i].ServiceRecipients, x => x.OdsCode.Contains(recipient.OdsCode));
Let's use a nested for loop instead of `FindIndex`

2024-08-29 14:21 UTC, ghost commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/wwwroot/scss/_custom.scss
> +.nhsuk-details.nhsuk-expander.nhsuk-expander-index.nhsuk-error-summary {
I think the approach we talked about earlier was to create a new class that applies the red border. Let's do that instead if we can as it allows us to reuse that style elsewhere. This approach will require a new class for each component that we wish to add this style to.

I'm not too familiar with `unset` but, at face value, this potentially has an unexpected side effect of undoing all padding where some may be expected or wanted.

2024-08-29 14:21 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Validation/Quantity/ServiceRecipientQuantityModelValidator.cs
> +        public const string ValueNotEnteredErrorMessage = "Enter a practice list size< for {0}>";
Validation can be tricky with our current implementation and we're definitely overdue a rework to make that system more modular. With that said, I'm wondering if using an attribute on the text input component might be an easier approach vs delimiting the error messages. Then it's only the text input tag builder that needs updated to append hidden text if it has been specified, and this error can become `Enter a practice list size`.

Part of the challenge with delimiting is that it can easily break if another developer were to inadvertently remove this as it's not immediately clear what it is/is doing.

2024-08-30 14:36 UTC, dssherlock commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/wwwroot/scss/_custom.scss
> +.nhsuk-details.nhsuk-expander.nhsuk-expander-index.nhsuk-error-summary {
It allows the css to use the inherited value (i.e. which is how the expander works) rather than the padding being explicitly set by the error class. But if we create a new error class for the border then we wont have that issue anyway.

2024-09-04 07:36 UTC, bjss-colin requested changes

2024-09-04 07:36 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.UI.Components/Views/Shared/TagHelpers/Helpers/TagHelperBuilders.cs
> +using System.Text.RegularExpressions;
Namespace is no longer in use following the refactoring

2024-09-04 07:36 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Validation/Quantity/SubLocationModelValidator.cs
> +            RuleFor(x => x)
I think the validator is still giving up halfway through as there are too many errors with all of the individual recipients being tracked.

Neither of the 2 collapsed sublocations have quantities defined
![image](https://github.com/user-attachments/assets/05f7d095-9620-4165-8142-f3408f535866)

![image](https://github.com/user-attachments/assets/4fb513a6-8e42-47b8-a913-830239c4a266)

The last errored sublocation has a point at which errors stop appearing against empty quantities
![image](https://github.com/user-attachments/assets/75ec9861-177e-4c35-898e-3620f1bc5f55)

2024-09-04 07:47 UTC, dssherlock commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Validation/Quantity/SubLocationModelValidator.cs
> +            RuleFor(x => x)
Have you tried this in Dev? Is this something new or did it do this before?

2024-09-04 07:53 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Validation/Quantity/SubLocationModelValidator.cs
> +            RuleFor(x => x)
Tested locally just now.

It does give up part-way through in live, so it's an existing behaviour, but I'm wondering if there's something to be done that would at least highlight all sublocations that are missing quantities

2024-09-04 09:34 UTC, bjss-colin approved these changes

2024-09-04 10:40 UTC, merged