Feature/23690 review order
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #1481
Opened 2024-09-27 13:54 UTC by dssherlock

2024-09-27 15:25 UTC, bjss-colin requested changes

2024-09-27 15:25 UTC, ghost commented on src/NHSD.GPIT.BuyingCatalogue.UI.Components/Views/Shared/TagHelpers/DetailsAndExpander/ExpanderSummaryContentTagHelper.cs
> +        public const string JsOnlyName = "js-only";
It doesn't yet look like `JsOnly` is in use, as it's only used once we could potentially add the class directly in that view file. I wouldn't be too influenced by the current expander implementation as creating this new expander component should enable us to strip out lots of the bespoke logic that we had to add to the original Expander component due to how limiting it was.

With this new version, it should be dynamic to a degree that allows us to adapt and extend any individual page to meet the needs of that particular view, where the tag helper simply bootstraps the layout to a specification (the NHS Frontend). That way it prevents the need for a V3 in the future if it becomes too restrictive.

`Url` and `UrlTitle` may also be suitable candidates for handling in the view directly since that currently only happens on one page under Review - Planned Delivery Dates.

There should be short-hand attributes for setting the title in the 90% of scenarios where the title is straight forward. In the other 10% of scenarios we should be able to define HTML directly in the view to hand-craft that specific title, but if there comes a point where that style is used in more than one place then we can bake that into the tag builders in some way to streamline the process.

2024-09-27 15:44 UTC, dssherlock commented on src/NHSD.GPIT.BuyingCatalogue.UI.Components/Views/Shared/TagHelpers/DetailsAndExpander/ExpanderSummaryContentTagHelper.cs
> +        public const string JsOnlyName = "js-only";
Yep i agree  completely

2024-10-02 15:26 UTC, dssherlock commented on src/NHSD.GPIT.BuyingCatalogue.UI.Components/Views/Shared/TagHelpers/DetailsAndExpander/ExpanderSummaryContentTagHelper.cs
> +        public const string JsOnlyName = "js-only";
So this latest change works...but thinking probably worth removing the ExpanderSummaryContentTagHelper completely and just putting the SecondaryText and SecondaryTitle properties back into the ExpanderSummaryTagHelper. If they want to use the default secondary content, then provide the secondary text and title, otherwise provide the html directly in the view. Thoughts?

2024-10-02 17:29 UTC, dssherlock commented on src/NHSD.GPIT.BuyingCatalogue.UI.Components/Views/Shared/TagHelpers/DetailsAndExpander/ExpanderSummaryContentTagHelper.cs
> +        public const string JsOnlyName = "js-only";
Updated to remove ExpanderSummaryContentTagHelper as suggested. Added secondary content properties to ExpanderSummaryTagHelper. Can be rolled back if you think its better to include explicitly.

2024-10-09 08:14 UTC, bjss-colin requested changes

2024-10-09 08:14 UTC, ghost commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Orders/Views/Order/Summary.cshtml
> +                            <div class="nhsuk-u-margin-bottom-9">
Margin bottom results in excess whitespace. Let's remove this, from here and on line 202, to be consistent with other expanders on the page.

![image](https://github.com/user-attachments/assets/58afe5ca-31a9-4d7f-89b1-ebd00ff5cf80)

2024-10-09 08:14 UTC, ghost commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Orders/Views/Order/Summary.cshtml
> +                            itemModel.OrderTotals = orderTotals;
Let's remove the card as it does look a bit funky. The prices could be displayed directly in the expander

2024-10-09 08:14 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Orders/Views/Order/Summary.cshtml
> +                    <h2 id="costs-title">Cost of order</h2>
Should this be present for all types of orders? At the moment it's only visible for an original order

2024-10-09 08:14 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Orders/Views/Order/Summary.cshtml
> +            @switch (Model.Order.OrderStatus)
As this page is becoming quite large with lots of different conditions, this could potentially be moved to the model which would allow for it to be unit tested

2024-10-09 08:14 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Orders/Views/Order/_OrderTotal.cshtml
> +<nhs-card-v2 inverted="@Model.Inverted">
Let's handle the card in the parent page as this partial should be agnostic of the implementation details. Adding a card here means every consumer of this partial is constrained to this specific design.

Handling this in the parent design also removes the need for an inverted card since that one scenario can display this data directly in the expander.

2024-10-09 15:26 UTC, bjss-colin approved these changes

2024-10-09 15:35 UTC, merged