Add "Expired" OrderStatus
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #1491
Opened 2024-11-11 12:54 UTC by ashleywntrbjss

This PR:

- Adds a new Expired status to the order status enum

- Uses the existing Order.ContractExpired property to return the Expired value for Order.OrderStatus

- Status tag
    - adds a new 'orange' expired status and,
    - simplifies the duplicated logic for evaluating the tag colour / title

- Indirectly disables the terminate contract button for an expired order by no longer using the Complete status which the terminate button was tied to.

To be thorough, I also evaluated all references to OrderStatus to check for other logic that relied on this value, as a new status represents quite a substantial change.
Changes unrelated to the feature request but required due to refactor are as follows:

- Uses InProgress status for CanComplete, rather than !Complete status, as expired, terminated or deleted orders should also not be completed
    - Removes checks for InProgress status when used in conjunction with CanComplete 

- The linq queries for orders (GetOrders and GetOrdersBySearchTerm) now consider the expired status in the Take Until query as there shouldn't be any revisions after an expiration, as the CanBeAmended check already explicitly checks for expiration 

- Updates all instances of PDF naming logic to use a formatted version of the enum label directly. Three existing implementations did it each slightly differently.

- Updates PDF cache lookup to skip the cache for in progress orders, but check it for all others - simplifies existing logic and factors in new expired status.

2024-11-20 10:14 UTC, dssherlock commented on src/NHSD.GPIT.BuyingCatalogue.Framework/NHSD.GPIT.BuyingCatalogue.Framework.csproj
>      <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" Version="8.0.1" />
Keep this change in its own feature branch

2024-11-20 10:14 UTC, dssherlock commented on src/NHSD.GPIT.BuyingCatalogue.ServiceContracts/NHSD.GPIT.BuyingCatalogue.ServiceContracts.csproj
>      <PackageReference Include="Azure.Storage.Queues" Version="12.12.0" />
And this one!

2024-11-20 10:15 UTC, dssherlock commented on src/NHSD.GPIT.BuyingCatalogue.Services/NHSD.GPIT.BuyingCatalogue.Services.csproj
>      <PackageReference Include="LinqKit.Microsoft.EntityFrameworkCore" Version="8.1.5" />
And this!

2024-11-20 10:18 UTC, dssherlock commented on src/NHSD.GPIT.BuyingCatalogue.EntityFramework/NHSD.GPIT.BuyingCatalogue.EntityFramework.csproj
>      <PackageReference Include="Newtonsoft.Json" Version="13.0.2" />
I think this should actually only be needed in the Regression test project. It shouldn't need adding to others

2024-11-20 10:32 UTC, dssherlock commented on database/NHSD.GPITBuyingCatalogue.Database/PostDeployment/OrderSeedData/InsertTestOrderSeedData.sql
>      INSERT INTO ordering.Orders
I'm not sure why we need to add the OrderTypeId on here for this change?

2024-11-20 10:36 UTC, ashleywntrbjss commented on src/NHSD.GPIT.BuyingCatalogue.EntityFramework/NHSD.GPIT.BuyingCatalogue.EntityFramework.csproj
>      <PackageReference Include="Newtonsoft.Json" Version="13.0.2" />
Ah nuget said it was in every project.. I'll be more discerning next time! Have removed all of the webdriver updates

2024-11-20 10:39 UTC, ashleywntrbjss commented on database/NHSD.GPITBuyingCatalogue.Database/PostDeployment/OrderSeedData/InsertTestOrderSeedData.sql
>      INSERT INTO ordering.Orders
I updated this to address an exception that happens because this ID isn't included in the test data currently. As I was working in this area the frequent crashes were a bit of a chore. Could probably move it to the regression test branch or can raise a bug for it

2024-11-20 10:58 UTC, dssherlock commented on src/NHSD.GPIT.BuyingCatalogue.Services/Orders/OrderService.cs
>                  .GroupBy(x => x.OrderNumber)
I've talked this through with Seana and I think this is correct. An order can have multiple amendments (revisions). However these will all have the same Commencement date. As a result, orders with a particular OrderNumber will all Expire at the same time. The logic below ensures only the most recent amendment of an Expired order will be displayed on the dashboard.

2024-11-20 11:45 UTC, dssherlock commented on src/NHSD.GPIT.BuyingCatalogue.Services/Pdf/CachedOrderPdfService.cs
> +
Changing the filename will have implications for all existing orders. Caching the pdf improves efficiency, but it was also introduced to maintain data integrity at the point the order was made i.e they user should always see the PDF as it appeared at the time of order. This is important as it outlines the contract. By changing the filename, existing orders will not be found in the blob storage and so a new one will be created. This would include any changes that have been made to the PDF format in the interim.

2024-11-20 11:47 UTC, dssherlock commented on src/NHSD.GPIT.BuyingCatalogue.Services/Pdf/CachedOrderPdfService.cs
> +
Changing the filename will have implications for all existing orders. Caching the pdf improves efficiency, but it was also introduced to maintain data integrity at the point the order was made i.e they user should always see the PDF as it appeared at the time of order. This is important as it outlines the contract. By changing the filename, existing orders will not be found in the blob storage and so a new one will be created. This would include any changes that have been made to the PDF format in the interim.

2024-11-20 11:51 UTC, dssherlock commented on src/NHSD.GPIT.BuyingCatalogue.Services/Pdf/CachedOrderPdfService.cs
This condition is to allow "throw-away" versions of the PDF to be opened from within the order journey. These aren't cached. I think it is fine for it only to be allowed for InProgress orders. However, it will have a knock-on effect of allowing Deleted orders and Expired orders to be cached. Not sure if this is correct. Worth checking.

2024-11-20 11:54 UTC, dssherlock commented on src/NHSD.GPIT.BuyingCatalogue.UI.Components/Views/Shared/TagHelpers/Tags/NhsTagsTagHelper.cs
>              {
Not sure who decides colours! Possibly worth checking the design guide.

2024-11-20 12:10 UTC, dssherlock commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Orders/Controllers/OrderController.cs
Wider discussion wrt allowing the download of other Status'

2024-11-20 12:18 UTC, dssherlock requested changes, later dismissed
Looks good! A couple of questions wrt wider functionality and how the site should behave in some edge case scenarios-e.g. if an order is Deleted. May be worth talking through with Colin when he is back. But looks good.

2024-11-20 12:20 UTC, dssherlock commented on database/NHSD.GPITBuyingCatalogue.Database/PostDeployment/OrderSeedData/InsertTestOrderSeedData.sql
>      INSERT INTO ordering.Orders
Nope that's fine-I just couldn't work out how it related to the changes!

2024-11-20 12:25 UTC, ashleywntrbjss commented on src/NHSD.GPIT.BuyingCatalogue.UI.Components/Views/Shared/TagHelpers/Tags/NhsTagsTagHelper.cs
>              {
Thanks, do you know where I can find it?

2024-11-21 10:33 UTC, ashleywntrbjss commented on src/NHSD.GPIT.BuyingCatalogue.UI.Components/Views/Shared/TagHelpers/Tags/NhsTagsTagHelper.cs
>              {
Using red for expired as discussed

2024-11-21 10:35 UTC, ashleywntrbjss commented on src/NHSD.GPIT.BuyingCatalogue.Services/Pdf/CachedOrderPdfService.cs
> +
Reinstated previous file naming scheme to preserve cache

2024-11-26 13:33 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.Services/Pdf/CachedOrderPdfService.cs
I think this is fine. Deleted orders aren't visible to the buyers and we don't expose PDF downloading capabilities to  admins for a deleted order.

In terms of an expired order, since the order will have been completed previously then there should be a pre-existing PDF in the cache from when it was originally completed. This logic means that an expired order will download the original order PDF which is fine since that's the buyers audit trail.

2024-11-26 13:35 UTC, ghost commented on src/NHSD.GPIT.BuyingCatalogue.Services/Orders/OrderService.cs
>                  .GroupBy(x => x.OrderNumber)
Another point on this. The reason the logic is this way is because an order is comprised of order revisions. Each amendment doesn't create a new order, instead they create revisions on an existing order.

This logic ensures that a user only sees the most recent completed, expired or terminated order revision - whether it be an original order revision or an amendment.

2024-11-26 13:40 UTC, bjss-colin approved these changes
Happy with this approach - nicely done

2024-11-26 14:03 UTC, bjss-colin approved these changes

2024-11-27 11:31 UTC, merged