Add breadcrumb to admin manage solution
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #152
Opened 2021-06-24 09:04 UTC by NickNewlands

Task: AB#15453
Story: AB#14712

2021-06-24 11:34 UTC, NickNewlands commented
I need to change this to use the admin layout, just realised that it exists.

2021-06-24 14:49 UTC, leerogers-bjss requested changes
you've got a failing unit test, fix this and the other minor style stuff and i'll approve it :)

```  Failed Get_CapabilitiesSelector_ReturnsDefaultView [62 ms]
  Error Message:
     Expected string length 24 but was 7. Strings differ at index 7.
  Expected: "Go back to previous page"
  But was:  "Go back"
  ------------------^

  Stack Trace:
     at NHSD.GPIT.BuyingCatalogue.WebApp.UnitTests.Areas.Solutions.Controllers.FuturesControllerTests.Get_CapabilitiesSelector_ReturnsDefaultView() in /home/vsts/work/1/s/tests/NHSD.GPIT.BuyingCatalogue.WebApp.UnitTests/Areas/Solutions/Controllers/FuturesControllerTests.cs:line 94
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.GetResult()
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.<>c__DisplayClass4_0.<PerformWork>b__0()
   at NUnit.Framework.Internal.ContextUtils.<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)```

2021-06-24 14:49 UTC, leerogers-bjss commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/DetailsModel.cs
> +            return new Dictionary<string, string> {
the ending brace needs to be on a new line

2021-06-24 14:49 UTC, leerogers-bjss commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Views/Organisations/Details.cshtml
> +@section Breadcrumbs {
brace needs to be on a new line

2021-06-30 16:23 UTC, NickNewlands reviewed
I pulled my other PR into this as I needed something from it (feature/14685-admin-manage-organisations).

2021-06-30 16:23 UTC, NickNewlands commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/DetailsModel.cs
> +                },
This sucks and needs improving, I could not see any amazing way to faithfully extract the 'route' from the controller, perhaps we need to setup a base class which marries up and can easily provides it? Something Like that. @leerogers-bjss

2021-07-08 15:52 UTC, closed without merging