Feature/14692 create add solution page
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #154
Opened 2021-06-24 16:45 UTC by nehajain008

Story AB#14692
Task AB#15463
Task AB#15464

2021-06-28 18:10 UTC, leerogers-bjss requested changes

2021-06-28 18:10 UTC, leerogers-bjss commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Views/Home/AddSolution.cshtml
> +<div class="nhsuk-width-container ">
This whole page needs the UI Components being applier to it.

I can go through with you tomorrow on how to apply them :)

2021-06-30 15:35 UTC, nehajain008 commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Views/Home/AddSolution.cshtml
> +<div class="nhsuk-width-container ">
Updated page with UI components, except nested checkbox as it's component is not present yet.

2021-07-01 08:09 UTC, kiran-mastek approved these changes

2021-07-01 08:38 UTC, leerogers-bjss requested changes

2021-07-01 08:38 UTC, leerogers-bjss commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Views/Home/AddSolution.cshtml
> +                <h1>Add a solution</h1>
this needs to be an nhs page title
`<nhs-page-title title="Add a solution" advice="Provide the following information about your Catalogue Solution."/>`

2021-07-01 08:38 UTC, leerogers-bjss commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Views/Home/ManageCatalogueSolutions.cshtml
> +                <h1>Manage Catalogue Solutions</h1>
this needs to be an nhs-page-title
<nhs-page-title title="Manage Catalogue Solutions" advice="Add a new solution or edit one that's already been published"/>

2021-07-01 09:07 UTC, nehajain008 commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Views/Home/AddSolution.cshtml
> +                <h1>Add a solution</h1>
done

2021-07-01 09:07 UTC, nehajain008 commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Views/Home/ManageCatalogueSolutions.cshtml
> +                <h1>Manage Catalogue Solutions</h1>
done

2021-07-01 10:32 UTC, bjss-chris requested changes

2021-07-01 10:32 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.Services/Solutions/SolutionsService.cs
> +        }
Can't we just do this here?

```c#
public async Task<IList<Supplier>> GetAllSuppliers()
{
    return await dbContext.Suppliers.OrderBy(s => s.Name).ToListAsync();
}
```

2021-07-01 10:32 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Controllers/HomeController.cs
> +                Suppliers = suppliers?.ToDictionary(x => x.Id, x => x.Name),
Please use a more appropriate lambda parameter name than `x`. (`s` would be fine here.)

2021-07-01 10:32 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/AddSolutionModel.cs
> +    public class AddSolutionModel : NavBaseModel
`sealed`

2021-07-01 10:32 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/AddSolutionModel.cs
> +        public bool GPITFuturesFramework { get; set; }
Should be `GpitFuturesFramework` to match standard .NET naming conventions.

2021-07-01 10:32 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/AddSolutionModel.cs
> +        public bool DFOCVCFramework { get; set; }
Should be `DfocvcFramework` to match standard .NET naming conventions.

2021-07-01 10:32 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Views/Home/AddSolution.cshtml
> +                                </h1>
Is this valid HTML – having an `h1` nested inside a `legend`?

2021-07-01 10:32 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Views/Home/AddSolution.cshtml
> +@using NHSD.GPIT.BuyingCatalogue.Framework.Extensions;
Are these `using` statements needed?

2021-07-01 10:32 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.WebApp.UnitTests/Areas/Admin/Controllers/HomeControllerTests.cs
> +            var mockAddSolutionModel = new Mock<AddSolutionModel>().Object;
It looks like this mock isn't used.

2021-07-01 10:32 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.WebApp.UnitTests/Areas/Admin/Controllers/HomeControllerTests.cs
> +            var mockOrganisationModels = new Mock<IList<OrganisationModel>>().Object;
As above, it looks like this mock isn't used.

2021-07-01 13:30 UTC, leerogers-bjss commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Views/Home/AddSolution.cshtml
> +                                </h1>
hey chris, this is how the NHS want it built, with H1 inside a ledgend (i know)
leave as is for now since i'm still building out the ability for conditional nesting in checkboxes, so i'll update this once i've got that working

2021-07-01 14:18 UTC, nehajain008 commented on src/NHSD.GPIT.BuyingCatalogue.Services/Solutions/SolutionsService.cs
> +        }
Done.

2021-07-01 14:18 UTC, nehajain008 commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Controllers/HomeController.cs
> +                Suppliers = suppliers?.ToDictionary(x => x.Id, x => x.Name),
Done.

2021-07-01 14:19 UTC, nehajain008 commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/AddSolutionModel.cs
> +    public class AddSolutionModel : NavBaseModel
Done.

2021-07-01 14:19 UTC, nehajain008 commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/AddSolutionModel.cs
> +        public bool GPITFuturesFramework { get; set; }
Done.

2021-07-01 14:20 UTC, nehajain008 commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/AddSolutionModel.cs
> +        public bool DFOCVCFramework { get; set; }
Done.

2021-07-01 14:20 UTC, nehajain008 commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Views/Home/AddSolution.cshtml
> +@using NHSD.GPIT.BuyingCatalogue.Framework.Extensions;
Done.

2021-07-01 14:20 UTC, nehajain008 commented on tests/NHSD.GPIT.BuyingCatalogue.WebApp.UnitTests/Areas/Admin/Controllers/HomeControllerTests.cs
> +            var mockAddSolutionModel = new Mock<AddSolutionModel>().Object;
Done.

2021-07-01 14:21 UTC, nehajain008 commented on tests/NHSD.GPIT.BuyingCatalogue.WebApp.UnitTests/Areas/Admin/Controllers/HomeControllerTests.cs
> +            var mockOrganisationModels = new Mock<IList<OrganisationModel>>().Object;
Removed.

2021-07-01 14:53 UTC, bjss-chris approved these changes

2021-07-01 14:54 UTC, bjss-chris commented
@leerogers-bjss – just needs your approval.

@nehajain008 – can you resolve the conversations?

2021-07-01 14:58 UTC, leerogers-bjss approved these changes

2021-07-01 15:14 UTC, merged