Bug fix: Associated services call causing delays
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #163
Opened 2021-06-28 07:19 UTC by kiran-mastek

Separate full associated services query from general query for all sections

2021-06-28 08:04 UTC, bjss-chris requested changes

2021-06-28 08:04 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.Services/Solutions/SolutionsService.cs
> +                .FirstOrDefaultAsync();
Please use a more appropriate lambda parameter name than `x`.

2021-06-28 08:04 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Controllers/SolutionDetailsController.cs
> +        public async Task<IActionResult> AssociatedServices(CatalogueItemId id)
I missed the tag helper in my earlier PR but the route parameter name shouldn't have to be `id` to work with the anchor tag helper. However, we can merge this as is for now and investigate the tag helper and route parameter issue separately.

2021-06-28 10:58 UTC, kiran-mastek commented on src/NHSD.GPIT.BuyingCatalogue.Services/Solutions/SolutionsService.cs
> +                .FirstOrDefaultAsync();
done

2021-06-28 11:26 UTC, bjss-chris submitted a review, later dismissed
Sorry, missed a couple of things last time.

2021-06-28 11:26 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.Services/Solutions/SolutionsService.cs
> +                .Include(i => i.Supplier).ThenInclude(s => s.CatalogueItems).ThenInclude(c => c.CataloguePrices).ThenInclude(cp => cp.PricingUnit)
Can we filter the catalogue items to `CatalogueItemType.AssociatedService`? Otherwise we're going to be retrieving all catalogue items for a particular supplier and not just their associated services.

2021-06-28 11:26 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.Services/Solutions/SolutionsService.cs
>                  .FirstOrDefaultAsync();
SingleOrDefaultAsync() would be more appropriate here as there should only ever be one catalogue item that matches a particular ID.

2021-06-28 12:43 UTC, kiran-mastek commented on src/NHSD.GPIT.BuyingCatalogue.Services/Solutions/SolutionsService.cs
>                  .FirstOrDefaultAsync();
done

2021-06-28 13:38 UTC, kiran-mastek commented on src/NHSD.GPIT.BuyingCatalogue.Services/Solutions/SolutionsService.cs
> +                .Include(i => i.Supplier).ThenInclude(s => s.CatalogueItems).ThenInclude(c => c.CataloguePrices).ThenInclude(cp => cp.PricingUnit)
Good catch, done, thank you.

2021-06-29 08:33 UTC, MichaelRobinson-BJSS submitted a review, later dismissed

2021-06-29 11:20 UTC, MichaelRobinson-BJSS submitted a review, later dismissed

2021-06-29 13:33 UTC, MichaelRobinson-BJSS submitted a review, later dismissed

2021-06-29 13:42 UTC, bjss-chris requested changes

2021-06-29 13:42 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.EntityFramework/Models/GPITBuyingCatalogue/CatalogueItem.partial.cs
> +            || (Supplier?.CatalogueItems?.Any(c => c.AssociatedService is not null) == true);
Brackets added are redundant.

2021-06-29 13:42 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.Services/Solutions/SolutionsService.cs
> +                .Include(i => i.Supplier).ThenInclude(s => s.CatalogueItems).ThenInclude(c => c.CataloguePrices).ThenInclude(cp => cp.PricingUnit)
I believe this line will still cause all catalogue items for the relevant supplier to be loaded – can we add a filter that restricts it to associated services or `solutionId`?

2021-06-30 07:21 UTC, kiran-mastek commented on src/NHSD.GPIT.BuyingCatalogue.EntityFramework/Models/GPITBuyingCatalogue/CatalogueItem.partial.cs
> +            || (Supplier?.CatalogueItems?.Any(c => c.AssociatedService is not null) == true);
removed

2021-06-30 07:27 UTC, kiran-mastek commented on src/NHSD.GPIT.BuyingCatalogue.Services/Solutions/SolutionsService.cs
> +                .Include(i => i.Supplier).ThenInclude(s => s.CatalogueItems).ThenInclude(c => c.CataloguePrices).ThenInclude(cp => cp.PricingUnit)
done

2021-06-30 08:19 UTC, bjss-chris approved these changes

2021-06-30 08:22 UTC, merged