Add Manage Suppliers page
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #166
Opened 2021-06-28 14:12 UTC by RahulJha-mastek

Story AB#15247
Task AB#15460

2021-06-28 18:09 UTC, leerogers-bjss requested changes

2021-06-28 18:09 UTC, leerogers-bjss commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Views/Home/ManageSuppliers.cshtml
> +﻿@model IList<NHSD.GPIT.BuyingCatalogue.EntityFramework.Models.GPITBuyingCatalogue.Supplier>;
This whole page needs the UI Components applying.
I can go through with you tomorrow if you want on how to apply these :)

2021-06-29 12:06 UTC, RahulJha-mastek commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Views/Home/ManageSuppliers.cshtml
> +﻿@model IList<NHSD.GPIT.BuyingCatalogue.EntityFramework.Models.GPITBuyingCatalogue.Supplier>;
Replaced HTML with UI components

2021-06-30 11:38 UTC, leerogers-bjss submitted a review, later dismissed
hey rahul, as i mentioned on slack

all the <vc:nhs-action-link> url's need to be updated to use the @URL.Action() function for URL generation :)

2021-06-30 14:32 UTC, RahulJha-mastek commented
> hey rahul, as i mentioned on slack
> 
> all the vc:nhs-action-link url's need to be updated to use the @URL.Action() function for URL generation :)


Updated vc:nhs-action-link url's with @URL.Action() in `Index.cshtml`. And in `ManageSuppliers.cshtml`, URL can be triggered with string format route URL.

2021-07-05 11:16 UTC, bjss-chris requested changes

2021-07-05 11:16 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.WebApp.UnitTests/Areas/Admin/Controllers/HomeControllerTests.cs
> +            var mockSolutionService = new Mock<ISolutionsService>();
It looks like this variable isn't used.

2021-07-05 11:16 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.WebApp.UnitTests/Areas/Admin/Controllers/HomeControllerTests.cs
> +            var mockSolutionService = new Mock<ISolutionsService>();
As above, it looks like this variable isn't used.

2021-07-05 11:16 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.WebApp.UnitTests/Areas/Admin/Controllers/HomeControllerTests.cs
> +        }
I don't think this test adds any value (it's not testing behaviour).

2021-07-05 12:26 UTC, RahulJha-mastek commented on tests/NHSD.GPIT.BuyingCatalogue.WebApp.UnitTests/Areas/Admin/Controllers/HomeControllerTests.cs
> +            var mockSolutionService = new Mock<ISolutionsService>();
Removed unused variable.

2021-07-05 12:26 UTC, RahulJha-mastek commented on tests/NHSD.GPIT.BuyingCatalogue.WebApp.UnitTests/Areas/Admin/Controllers/HomeControllerTests.cs
> +            var mockSolutionService = new Mock<ISolutionsService>();
Removed unused variable.

2021-07-05 12:26 UTC, RahulJha-mastek commented on tests/NHSD.GPIT.BuyingCatalogue.WebApp.UnitTests/Areas/Admin/Controllers/HomeControllerTests.cs
> +        }
Removed test case.

2021-07-05 13:02 UTC, bjss-chris approved these changes

2021-07-05 14:17 UTC, merged