Manage Catalogue Solutions dashboard
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #167
Opened 2021-06-29 06:08 UTC by kiran-mastek

Display all Catalogue Solutions ordered by date created and then by name
UI for filter functionality
Update admin home link for Catalogue Solutions
Correct condition for Additional Services in Catalogue Item

2021-06-30 11:32 UTC, bjss-chris requested changes

2021-06-30 11:32 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.Framework/Extensions/EnumExtensions.cs
> +        }
This isn't needed – we can add the `Enums.NET` package to the project and use `.AsString(EnumFormat.DisplayName)`.

2021-06-30 11:32 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Controllers/CatalogueSolutionsController.cs
> +using System.Linq;
Are these `using` statements needed?

2021-06-30 11:32 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Controllers/CatalogueSolutionsController.cs
> +    public class CatalogueSolutionsController : Controller
`sealed`.

2021-06-30 11:32 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/CatalogueSolutionsModel.cs
> +            .Select(p => new PublicationStatusModel { Id = (int)p, Display = p.GetDisplayName(), })
Trailing comma not needed here.

2021-06-30 11:32 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/CatalogueSolutionsModel.cs
> +        public CatalogueSolutionsModel(IList<CatalogueItem> solutions)
Parameter can be of type `IEnumerable<CatalogueItem>`?

2021-06-30 11:32 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/PublicationStatusModel.cs
> +    public class PublicationStatusModel
`sealed`

2021-06-30 11:32 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/PublicationStatusModel.cs
> +        public int Id { get; set; }
Can this be of type `PublicationStatus`?

2021-06-30 11:32 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Views/CatalogueSolutions/Index.cshtml
> +﻿@using NHSD.GPIT.BuyingCatalogue.WebApp.Areas.Admin.Models
Is this `using` needed?

2021-06-30 11:32 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Views/CatalogueSolutions/Index.cshtml
> +            <tr role="row">
Can we not use the table component here?

2021-06-30 11:32 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Views/Shared/_AdminHeader.cshtml
> +    <div class="nhsuk-width-container">
Can we not use the breadcrumb component here?

2021-06-30 11:32 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.WebApp.UnitTests/Areas/Admin/Controllers/CatalogueSolutionsControllerTests.cs
> +                    {
I can't see any `await` statements in the test method (only the lambda). Using `async` with `.ForEach` also looks a bit iffy to me.

It feels like this should be a data driven test with each enum value passed in via a parameter.

2021-06-30 11:49 UTC, kiran-mastek commented on src/NHSD.GPIT.BuyingCatalogue.Framework/Extensions/EnumExtensions.cs
> +        }
replaced

2021-06-30 11:50 UTC, kiran-mastek commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Controllers/CatalogueSolutionsController.cs
> +    public class CatalogueSolutionsController : Controller
done

2021-06-30 11:51 UTC, kiran-mastek commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/CatalogueSolutionsModel.cs
> +        public CatalogueSolutionsModel(IList<CatalogueItem> solutions)
changed

2021-06-30 11:52 UTC, kiran-mastek commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/CatalogueSolutionsModel.cs
> +            .Select(p => new PublicationStatusModel { Id = (int)p, Display = p.GetDisplayName(), })
removed

2021-06-30 11:52 UTC, kiran-mastek commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/PublicationStatusModel.cs
> +    public class PublicationStatusModel
changed

2021-06-30 11:53 UTC, kiran-mastek commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/PublicationStatusModel.cs
> +        public int Id { get; set; }
renamed

2021-06-30 11:53 UTC, kiran-mastek commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Views/CatalogueSolutions/Index.cshtml
> +﻿@using NHSD.GPIT.BuyingCatalogue.WebApp.Areas.Admin.Models
removed

2021-06-30 12:04 UTC, kiran-mastek commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Views/Shared/_AdminHeader.cshtml
> +    <div class="nhsuk-width-container">
Not a good idea as it doesn't use anchor taghelper which allows using `Controller` and `Action` so the URL does not need to be changed if routing changes.

2021-06-30 12:12 UTC, kiran-mastek commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Controllers/CatalogueSolutionsController.cs
> +using System.Linq;
removed

2021-06-30 13:47 UTC, kiran-mastek commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Views/CatalogueSolutions/Index.cshtml
> +            <tr role="row">
no table component, used the tag helper

2021-06-30 13:57 UTC, kiran-mastek commented on tests/NHSD.GPIT.BuyingCatalogue.WebApp.UnitTests/Areas/Admin/Controllers/CatalogueSolutionsControllerTests.cs
> +                    {
Removed async on the test.
To my knowledge `CommonAutoData` cannot be used along with defined values for the `PublicationStatus` enum in `InlineData`, hence the `.ForEach`.

2021-06-30 16:55 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.WebApp.UnitTests/Areas/Admin/Controllers/CatalogueSolutionsControllerTests.cs
> +                    {
You're correct, you won't be able to use `CommonAutoData`. However, you could use `CommonInlineAutoData` or the `MemberAutoData` attributes, with the latter being the better option in this case I think.

2021-07-01 08:00 UTC, kiran-mastek commented on tests/NHSD.GPIT.BuyingCatalogue.WebApp.UnitTests/Areas/Admin/Controllers/CatalogueSolutionsControllerTests.cs
> +                    {
Spent nearly an hour trying to use attributes suggested to inject `PublicationStatus` and list of `CatalogueItem` but not successful. Issues with unit testing indicate issues with code - in this case coupling requiring injecting domain models into a unit test for controller action. 
Removed the 'iffy' bit with random selection of enum as it doesn't impact the method under test.

2021-07-01 15:31 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.EntityFramework/Models/GPITBuyingCatalogue/PublicationStatus.cs
>          Withdrawn = 4,
I think Seana should have an update on the statuses today so we hopefully get this merged tomorrow.

2021-07-02 08:14 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.EntityFramework/Models/GPITBuyingCatalogue/PublicationStatus.cs
>          Withdrawn = 4,
Based on the updated requirements, `Draft`, `Unpublished` and `Published` can remain the same. We can rename `Withdrawn` to `Suspended` and add a new status `InRemediation`.

2021-07-02 10:26 UTC, bjss-chris submitted a review, later dismissed

2021-07-02 10:46 UTC, kiran-mastek commented on src/NHSD.GPIT.BuyingCatalogue.EntityFramework/Models/GPITBuyingCatalogue/PublicationStatus.cs
>          Withdrawn = 4,
done

2021-07-02 11:26 UTC, bjss-chris approved these changes

2021-07-02 12:43 UTC, merged