Bug fix: Associated services call causing delays
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #174
Opened 2021-06-30 11:30 UTC by kiran-mastek

Filter retrieved Associated Services to one for links display

2021-07-01 15:35 UTC, bjss-chris requested changes

2021-07-01 15:35 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.Services/Solutions/SolutionsService.cs
> +            return await dbContext.CatalogueItems
The `async` and `await` are redundant here.

2021-07-02 08:38 UTC, kiran-mastek commented on src/NHSD.GPIT.BuyingCatalogue.Services/Solutions/SolutionsService.cs
> +            return await dbContext.CatalogueItems
removed

2021-07-02 09:23 UTC, bjss-chris approved these changes

2021-07-02 11:02 UTC, merged