Feature/15504 ordering general review
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #177
Opened 2021-06-30 13:48 UTC by MichaelRobinson-BJSS

2021-06-30 16:35 UTC, bjss-chris requested changes

2021-06-30 16:35 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Order/Controllers/CatalogueSolutionsController.cs
> +        public async Task<IActionResult> DeleteSolution(string odsCode, CallOffId callOffId, CatalogueItemId catalogueItemId, string catalogueItemName)
Long line.

2021-06-30 16:35 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Order/Controllers/CatalogueSolutionsController.cs
> +        public async Task<IActionResult> DeleteSolution(string odsCode, CallOffId callOffId, CatalogueItemId catalogueItemId, string catalogueItemName, DeleteSolutionModel model)
Long line.

2021-06-30 16:35 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Order/Models/AdditionalServices/EditAdditionalServiceModel.cs
> +using NHSD.GPIT.BuyingCatalogue.Framework.Constants;
Needed?

2021-06-30 16:35 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Order/Models/AdditionalServices/EditAdditionalServiceModel.cs
> +                    return "Quantity " + OrderItem.TimeUnit?.Description();
This `get` can be converted to a switch expression:

```c#
return OrderItem.ProvisioningType switch
    {
        ProvisioningType.Declarative => "Quantity",
        ProvisioningType.OnDemand => "Quantity " + OrderItem.TimeUnit?.Description(),
        _ => "Practice list size",
    };
```

2021-06-30 16:35 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Order/Models/AdditionalServices/SelectAdditionalServiceRecipientsModel.cs
>                  BackLink = $"/order/organisation/{odsCode}/order/{callOffId}/additional-services/{additionalServiceId}";
There a couple of alternative options here using the ternary operator:

```c#
BackLink = isNewOrder
    ? $"/order/organisation/{odsCode}/order/{callOffId}/additional-services/select/additional-service"
    : $"/order/organisation/{odsCode}/order/{callOffId}/additional-services/{additionalServiceId}";
```

Or a single expression:

```c#
BackLink = $"/order/organisation/{odsCode}/order/{callOffId}/additional-services/{(isNewOrder ? "select/additional-service" : additionalServiceId)}";
```

2021-06-30 16:35 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Order/Models/AssociatedServices/EditAssociatedServiceModel.cs
> +                    BackLink = $"/order/organisation/{odsCode}/order/{state.CallOffId}/associated-services/select/associated-service/price";
As per previous comment – there a couple of alternative options here using the ternary operator:

```c#
BackLink = state.SkipPriceSelection
    ? $"/order/organisation/{odsCode}/order/{state.CallOffId}/associated-services/select/associated-service"
    : $"/order/organisation/{odsCode}/order/{state.CallOffId}/associated-services/select/associated-service/price";
```

Or a single expression:

```c#
BackLink = $"/order/organisation/{odsCode}/order/{state.CallOffId}/associated-services/select/{(state.SkipPriceSelection ? "associated-service" : "associated-service/price")}";
```

2021-06-30 16:35 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Order/Models/CatalogueSolutions/EditSolutionModel.cs
> +                    return "Quantity " + OrderItem.TimeUnit?.Description();
As per earlier comment, the body of this `get` can be converted to a `switch` expression:

```c#
return OrderItem.ProvisioningType switch
{
    ProvisioningType.Declarative => "Quantity",
    ProvisioningType.OnDemand => "Quantity " + OrderItem.TimeUnit?.Description(),
    _ => "Practice list size",
};
```

2021-06-30 16:35 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Order/Models/CatalogueSolutions/SelectSolutionServiceRecipientsDateModel.cs
> +                BackLink = $"/order/organisation/{odsCode}/order/{state.CallOffId}/catalogue-solutions/select/solution/price";
As per previous comment – there a couple of alternative options here using the ternary operator:

```c#
BackLink = state.SkipPriceSelection
    ? $"/order/organisation/{odsCode}/order/{state.CallOffId}/catalogue-solutions/select/solution/price/recipients"
    : $"/order/organisation/{odsCode}/order/{state.CallOffId}/catalogue-solutions/select/solution/price";
```

Or a single expression:

```c#
BackLink = $"/order/organisation/{odsCode}/order/{state.CallOffId}/catalogue-solutions/select/solution/price{(state.SkipPriceSelection ? "/recipients" : string.Empty)}";
```

2021-06-30 16:35 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Order/Models/AdditionalServices/SelectAdditionalServiceRecipientsDateModel.cs
> +                BackLink = $"/order/organisation/{odsCode}/order/{state.CallOffId}/additional-services/select/additional-service/price";
As per previous comment – there a couple of alternative options here using the ternary operator:

```c#
BackLink = state.SkipPriceSelection
    ? $"/order/organisation/{odsCode}/order/{state.CallOffId}/additional-services/select/additional-service/price/recipients"
    : $"/order/organisation/{odsCode}/order/{state.CallOffId}/additional-services/select/additional-service/price";
```

Or a single expression:

```c#
BackLink = $"/order/organisation/{odsCode}/order/{state.CallOffId}/additional-services/select/additional-service/price{(state.SkipPriceSelection ? "/recipients" : string.Empty)}";
```

2021-06-30 16:35 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Order/Views/AssociatedServices/DeleteAssociatedService.cshtml
> +                                                Model.CatalogueItemId
Should have a trailing comma: `Model.CatalogueItemId,`

2021-06-30 16:35 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Order/Views/CatalogueSolutions/EditSolution.cshtml
> +                                                new { Model.OdsCode, Model.OrderItem.CallOffId, @Model.OrderItem.CatalogueItemId, @Model.OrderItem.CatalogueItemName})"
`@` sign is redundant in object initializer.

2021-06-30 19:41 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Order/Views/CatalogueSolutions/EditSolution.cshtml
> +                                                new { Model.OdsCode, Model.OrderItem.CallOffId, @Model.OrderItem.CatalogueItemId, @Model.OrderItem.CatalogueItemName})"
Done

2021-06-30 19:49 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.Services/Session/SessionService.cs
>  ﻿using System.Text;
No, but for some reason VS didn't highlight it

2021-06-30 19:51 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Order/Controllers/AssociatedServicesController.cs
> +            orderSessionService.ClearSession(callOffId);
Done

2021-06-30 19:53 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Order/Controllers/AssociatedServicesController.cs
>                  || model.OrderItem.ServiceRecipients[0].Quantity.Value == 0)
Done

2021-06-30 19:54 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Order/Controllers/AssociatedServicesController.cs
>                  ModelState.AddModelError($"OrderItem.ServiceRecipients[0].Quantity", "Quantity is Required");
Done

2021-06-30 19:56 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Order/Controllers/AssociatedServicesController.cs
> +        public async Task<IActionResult> DeleteAssociatedService(string odsCode, CallOffId callOffId, CatalogueItemId catalogueItemId, string catalogueItemName, DeleteAssociatedServiceModel model)
Done

2021-06-30 19:56 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Order/Controllers/CatalogueSolutionsController.cs
> +        public async Task<IActionResult> DeleteSolution(string odsCode, CallOffId callOffId, CatalogueItemId catalogueItemId, string catalogueItemName)
Done

2021-06-30 19:57 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Order/Controllers/CatalogueSolutionsController.cs
> +        public async Task<IActionResult> DeleteSolution(string odsCode, CallOffId callOffId, CatalogueItemId catalogueItemId, string catalogueItemName, DeleteSolutionModel model)
Done

2021-06-30 19:57 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Order/Models/AdditionalServices/EditAdditionalServiceModel.cs
> +using NHSD.GPIT.BuyingCatalogue.Framework.Constants;
Done

2021-06-30 19:58 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Order/Models/AdditionalServices/EditAdditionalServiceModel.cs
> +                    return "Quantity " + OrderItem.TimeUnit?.Description();
Done

2021-06-30 19:59 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Order/Models/CatalogueSolutions/EditSolutionModel.cs
> +                    return "Quantity " + OrderItem.TimeUnit?.Description();
Done

2021-06-30 20:00 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Order/Views/AssociatedServices/DeleteAssociatedService.cshtml
> +                                                Model.CatalogueItemId
Done

2021-06-30 20:02 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.ServiceContracts/Session/IOrderSessionService.cs
> +        public CreateOrderItemModel InitialiseStateForCreate(CallOffId callOffId, DateTime? commencementDate, string supplierId, CatalogueItemType catalogueItemType, IEnumerable<CatalogueItemId> solu
Done

2021-06-30 20:02 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.Services/Session/OrderSessionService.cs
> +        public CreateOrderItemModel InitialiseStateForCreate(CallOffId callOffId, DateTime? commencementDate, string supplierId, CatalogueItemType catalogueItemType, IEnumerable<CatalogueItemId> solu
Done

2021-06-30 20:02 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.Services/Session/OrderSessionService.cs
> +            if (model is null)
Done

2021-06-30 20:04 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.Services/Session/OrderSessionService.cs
> +                    serviceRecipient.DeliveryDate = orderItem.DefaultDeliveryDate;
Not sure that is more readable, but done

2021-06-30 20:04 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Order/Controllers/AdditionalServicesController.cs
> +            var state = orderSessionService.InitialiseStateForCreate(callOffId, order.CommencementDate, order.SupplierId, CatalogueItemType.AdditionalService, solutionIds, null);
Done

2021-06-30 20:04 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Order/Controllers/AdditionalServicesController.cs
> +        public async Task<IActionResult> DeleteAdditionalService(string odsCode, CallOffId callOffId, CatalogueItemId catalogueItemId, string catalogueItemName)
Done

2021-06-30 20:04 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Order/Controllers/AdditionalServicesController.cs
> +        public async Task<IActionResult> DeleteAdditionalService(string odsCode, CallOffId callOffId, CatalogueItemId catalogueItemId, string catalogueItemName, DeleteAdditionalServiceModel model)
Done

2021-06-30 20:04 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Order/Controllers/AssociatedServicesController.cs
> +            var state = orderSessionService.InitialiseStateForCreate(callOffId, order.CommencementDate, order.SupplierId, CatalogueItemType.AssociatedService, null, new OrderItemRecipientModel { OdsC
Done

2021-06-30 20:05 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Order/Controllers/AssociatedServicesController.cs
>                  ModelState.AddModelError($"OrderItem.ServiceRecipients[0].Quantity", "Quantity is Required");
Done

2021-06-30 20:05 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Order/Controllers/AssociatedServicesController.cs
> +        public async Task<IActionResult> DeleteAssociatedService(string odsCode, CallOffId callOffId, CatalogueItemId catalogueItemId, string catalogueItemName)
Done

2021-06-30 20:12 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.EntityFramework/Ordering/Models/Order.Custom.cs
>                  || o.CatalogueItem.Solution?.Id == catalogueItemId);
Done. The previous code didn't delete the additional service, the code in OAPI is different and I was a bit confused. My change worked, so does yours so I have changed to what you suggest.

2021-07-01 08:01 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.Services/Orders/OrderItemService.cs
> +            var estimationPeriod = catalogueItem.CatalogueItemType.InferEstimationPeriod(model.ProvisioningType, model.TimeUnit);
It was actually being passed the selected estimation period, I was just using the same model field, i.e. defaulted to CataloguePrice TimeUnit and replaced with the EstimationPeriod if set by user. I've split it out into two fields and renamed them to try and avoid confusion.

2021-07-01 08:02 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.ServiceContracts/Models/CreateOrderItemModel.cs
> +        public int? PriceId { get; set; }
I was using a single TimeUnit field defaulted to the CataloguePrice TimeUnit and updated to the users selected EstimationPeriod. I've split it into two fields again to avoid confusion.

2021-07-01 09:04 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Order/Models/CatalogueSolutions/SelectSolutionServiceRecipientsDateModel.cs
> +                BackLink = $"/order/organisation/{odsCode}/order/{state.CallOffId}/catalogue-solutions/select/solution/price";
I don't like the back links and would like to revisit. The skip price thing is also awful, but can't think of an alternative at the moment.

Done

2021-07-01 09:04 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Order/Models/AdditionalServices/SelectAdditionalServiceRecipientsDateModel.cs
> +                BackLink = $"/order/organisation/{odsCode}/order/{state.CallOffId}/additional-services/select/additional-service/price";
Done

2021-07-01 11:44 UTC, bjss-chris requested changes

2021-07-01 11:44 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.ServiceContracts/Models/CreateOrderItemModel.cs
> +        public TimeUnit? CataloguePriceTimeUnit { get; set; }
Can we incorporate `CataloguePrice` into the model? That would give us `PriceId`, `CataloguePrice`, `CurrencyCode`, `ProvisioningType`, `CataloguePriceTimeUnit` and `PricingUnit`.

2021-07-01 11:44 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.ServiceContracts/Models/CreateOrderItemModel.cs
> +        }
I'm guessing the intention of this property is for display purposes in views? If so, I think we could probably give it a better name.

Also, this will currently cause a stack overflow exception as it's recursive.

2021-07-01 11:44 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Order/Controllers/AdditionalServicesController.cs
> +                ModelState.AddModelError(nameof(model.EstimationPeriod), "Time Unit is Required");
Estimation period is required?

2021-07-01 11:52 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.EntityFramework/Ordering/Models/Order.Custom.cs
>              var order = orderItems.Single(o => o.CatalogueItemId == catalogueItemId);
Done

2021-07-01 11:53 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Order/Controllers/AdditionalServicesController.cs
> +                ModelState.AddModelError(nameof(model.EstimationPeriod), "Time Unit is Required");
Done

2021-07-01 11:58 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.ServiceContracts/Models/CreateOrderItemModel.cs
> +        }
Done

2021-07-01 12:49 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.ServiceContracts/Models/CreateOrderItemModel.cs
> +        public TimeUnit? CataloguePriceTimeUnit { get; set; }
Done. I think I did that originally and it barfed when being saved to session cos of the cyclic issue

2021-07-01 14:31 UTC, bjss-chris approved these changes

2021-07-01 14:58 UTC, merged