Update summary views to use components
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #181
Opened 2021-07-01 12:09 UTC by leerogers-bjss

update order form process to new process
fix order address to model

2021-07-01 16:13 UTC, bjss-chris requested changes

2021-07-01 16:13 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Order/Views/Order/PrintSummary.cshtml
> +                                            && si.CatalogueItemId == orderItem.CatalogueItemId).FirstOrDefault()?.ServiceInstanceId)
LINQ expression can be simplified to `Model.Order.ServiceInstanceItems.FirstOrDefault(si => si.OdsCode == recipient.Recipient.OdsCode && si.CatalogueItemId == orderItem.CatalogueItemId)?.ServiceInstanceId`.

2021-07-01 16:13 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Order/Views/Order/PrintSummary.cshtml
> +                                    <nhs-table-cell>@($"{recipient.Quantity} {@orderItem.EstimationPeriod?.Description()}")</nhs-table-cell>
`@` before `orderItem` is redundant.

2021-07-01 16:13 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Order/Views/Order/PrintSummary.cshtml
> +                            @(((Model.Order.OrderItems.Where(oi => oi.CostType == CostType.Recurring).Sum(oi => oi.OrderItemRecipients.Sum(r => r.Quantity * oi.Price)).Value)/ 12).ToString("N"))
Redundant brackets around LINQ expression (closing bracket after `.Value`).

2021-07-01 16:13 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Order/Views/Order/PrintSummary.cshtml
> +                            @(((Model.Order.OrderItems.Where(oi => oi.CostType == CostType.OneOff).Sum(oi => oi.OrderItemRecipients.Sum(r => r.Quantity * oi.Price)).Value)
Redundant brackets around LINQ expression (closing bracket after `.Value`).

2021-07-01 16:13 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Order/Views/Order/PrintSummary.cshtml
> +                        + ((Model.Order.OrderItems.Where(oi => oi.CostType == CostType.Recurring).Sum(oi => oi.OrderItemRecipients.Sum(r => r.Quantity * oi.Price)) * 3).Value))
Redundant brackets around LINQ expression (closing bracket after `.Value`).

2021-07-01 16:13 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Order/Views/Order/Summary.cshtml
> +    int itemId = 0;
We can use `var` here.

2021-07-01 16:13 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Order/Views/Order/Summary.cshtml
> +                                            && si.CatalogueItemId == orderItem.CatalogueItemId).FirstOrDefault()?.ServiceInstanceId)
We can simplify the LINQ expression to `Model.Order.ServiceInstanceItems.FirstOrDefault(si => si.OdsCode == recipient.Recipient.OdsCode && si.CatalogueItemId == orderItem.CatalogueItemId)?.ServiceInstanceId`.

2021-07-01 16:13 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Order/Views/Order/Summary.cshtml
> +                                <nhs-table-cell>@($"{recipient.Quantity} {@orderItem.EstimationPeriod?.Description()}")</nhs-table-cell>
`@` before `orderItem` is redundant.

2021-07-01 16:13 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Order/Views/Order/Summary.cshtml
> +                        @(((Model.Order.OrderItems.Where(oi => oi.CostType == CostType.Recurring).Sum(oi => oi.OrderItemRecipients.Sum(r => r.Quantity * oi.Price)).Value)/ 12).ToString("N"))
Redundant brackets around LINQ expression (closing bracket after `.Value`).

2021-07-01 16:13 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Order/Views/Order/Summary.cshtml
> +                        @(((Model.Order.OrderItems.Where(oi => oi.CostType == CostType.OneOff).Sum(oi => oi.OrderItemRecipients.Sum(r => r.Quantity * oi.Price)).Value)
Redundant brackets around LINQ expression (closing bracket after `.Value`).

2021-07-01 16:13 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Order/Views/Order/Summary.cshtml
> +                        + ((Model.Order.OrderItems.Where(oi => oi.CostType == CostType.Recurring).Sum(oi => oi.OrderItemRecipients.Sum(r => r.Quantity * oi.Price)) * 3).Value))
Redundant brackets around LINQ expression (closing bracket after `.Value`).

2021-07-01 16:13 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Utils/UserSeedData.cs
> +                new Organisation { OrganisationId = new Guid("3b2e4572-f9ac-4931-9536-b276a6bdf92a"), Name = "North Midlands Commissioning Hub", Address = JsonSerializer.Deserialize<Address>(@"{""lin
Instead of deserializing strings, these should create a new `Address` object, e.g.

```c#
Address = new Address { Line1 = "C/O NHS England" } // Line2 = "Foo", Line3 = "Bar" etc.
```

My reg-ex can be used for that.

Unless @PhysicsJon prefers your approach, @PhysicsJon?

2021-07-02 08:22 UTC, leerogers-bjss commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Order/Views/Order/Summary.cshtml
> +                                <nhs-table-cell>@($"{recipient.Quantity} {@orderItem.EstimationPeriod?.Description()}")</nhs-table-cell>
the @ isn't redundant, because we need to add a space inbetween the price and unit price description. because of this we require double @ because it becomes a seperate query as such

2021-07-02 08:24 UTC, leerogers-bjss commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Order/Views/Order/Summary.cshtml
> +                        @(((Model.Order.OrderItems.Where(oi => oi.CostType == CostType.Recurring).Sum(oi => oi.OrderItemRecipients.Sum(r => r.Quantity * oi.Price)).Value)/ 12).ToString("N"))
the bracket is required, because of the bracket structure for the calculation, if we don't have a bracket to contain it, it won't recognise the ToString("N") at the end as part of the query

2021-07-02 08:25 UTC, leerogers-bjss commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Order/Views/Order/Summary.cshtml
> +                        @(((Model.Order.OrderItems.Where(oi => oi.CostType == CostType.OneOff).Sum(oi => oi.OrderItemRecipients.Sum(r => r.Quantity * oi.Price)).Value)
the bracket is required, because of the bracket structure for the calculation, if we don't have a bracket to contain it, it won't recognise the ToString("N") at the end as part of the query

2021-07-02 08:25 UTC, leerogers-bjss commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Order/Views/Order/Summary.cshtml
> +                        + ((Model.Order.OrderItems.Where(oi => oi.CostType == CostType.Recurring).Sum(oi => oi.OrderItemRecipients.Sum(r => r.Quantity * oi.Price)) * 3).Value))
the bracket is required, because of the bracket structure for the calculation, if we don't have a bracket to contain it, it won't recognise the ToString("N") at the end as part of the query

2021-07-02 08:27 UTC, leerogers-bjss commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Order/Controllers/OrderController.cs
> +            return View(model);
that check was already existing, but i'll update it

2021-07-02 08:29 UTC, leerogers-bjss commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Order/Views/Order/PrintSummary.cshtml
> +                    <div style='page-break-after:always'></div>
i copied it from the original printsummary html, but i'll update it

2021-07-02 08:30 UTC, leerogers-bjss commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Order/Views/Order/PrintSummary.cshtml
> +        <main class="nhsuk-main-wrapper nhsuk-bc-print" id="maincontent">
yeah, carlos is currently creating the CSS to fix the printing page, and this is the target he's going to use, so needs to be kept in.

2021-07-02 08:49 UTC, PhysicsJon commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Utils/UserSeedData.cs
> +                new Organisation { OrganisationId = new Guid("3b2e4572-f9ac-4931-9536-b276a6bdf92a"), Name = "North Midlands Commissioning Hub", Address = JsonSerializer.Deserialize<Address>(@"{""lin
I kinda prefer the object approach, but it's close

2021-07-02 10:30 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Order/Views/Order/Summary.cshtml
> +                        @(((Model.Order.OrderItems.Where(oi => oi.CostType == CostType.Recurring).Sum(oi => oi.OrderItemRecipients.Sum(r => r.Quantity * oi.Price)).Value)/ 12).ToString("N"))
Suspect you've removed the wrong brackets, should look like this once the redundant ones are removed:

```c#
@((Model.Order.OrderItems.Where(oi => oi.CostType == CostType.Recurring).Sum(oi => oi.OrderItemRecipients.Sum(r => r.Quantity * oi.Price)).Value / 12).ToString("N"))
```

2021-07-02 10:31 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Order/Views/Order/Summary.cshtml
> +                        + ((Model.Order.OrderItems.Where(oi => oi.CostType == CostType.Recurring).Sum(oi => oi.OrderItemRecipients.Sum(r => r.Quantity * oi.Price)) * 3).Value))
As above,

```c#
@((Model.Order.OrderItems.Where(oi => oi.CostType == CostType.OneOff).Sum(oi => oi.OrderItemRecipients.Sum(r => r.Quantity * oi.Price)).Value
```

2021-07-02 13:25 UTC, bjss-chris submitted a review, later dismissed

2021-07-02 13:26 UTC, bjss-chris approved these changes

2021-07-02 13:56 UTC, bjss-chris approved these changes

2021-07-02 13:57 UTC, merged