Set correct order for Catalogue Solution filters
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #185
Opened 2021-07-02 13:36 UTC by kiran-mastek

2021-07-02 14:26 UTC, bjss-chris requested changes

2021-07-02 14:26 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/CatalogueSolutionsModel.cs
> +                .ToList();
Can we use the `Order` property of the `Display` attribute on the `PublicationStatus` and Enums.NET to make the code slightly clearer here? Perhaps something like below?

```c#
public enum PublicationStatus
    {
        [Display(Name = nameof(Draft), Order = 1)]
        Draft = 1,

        [Display(Name = nameof(Unpublished), Order = 3)]
        Unpublished = 2,

        [Display(Name = nameof(Published), Order = 2)]
        Published = 3,

        [Display(Name = nameof(Suspended), Order = 5)]
        Suspended = 4,

        [Display(Name = "In Remediation", Order = 4)]
        InRemediation = 5,
    }
```

```c#
private readonly IReadOnlyList<PublicationStatus> models =
    Enums.GetValues<EntityFramework.Models.GPITBuyingCatalogue.PublicationStatus>(EnumMemberSelection.DisplayOrder)
        .Select(s => new PublicationStatus { Id = (int)s, Display = s.AsString(EnumFormat.DisplayName) })
        .ToList();
```

2021-07-02 14:26 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.WebApp.UnitTests/Areas/Admin/Models/CatalogueSolutionsModelTests.cs
> +                    new List<NHSD.GPIT.BuyingCatalogue.WebApp.Areas.Admin.Models.PublicationStatus>
I think the type name can be simplified to `WebApp.Areas.Admin.Models.PublicationStatus` here.

2021-07-02 15:33 UTC, kiran-mastek commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/CatalogueSolutionsModel.cs
> +                .ToList();
Good idea, done.

2021-07-02 15:34 UTC, kiran-mastek commented on tests/NHSD.GPIT.BuyingCatalogue.WebApp.UnitTests/Areas/Admin/Models/CatalogueSolutionsModelTests.cs
> +                    new List<NHSD.GPIT.BuyingCatalogue.WebApp.Areas.Admin.Models.PublicationStatus>
done

2021-07-02 16:39 UTC, bjss-chris requested changes

2021-07-03 15:46 UTC, kiran-mastek commented on src/NHSD.GPIT.BuyingCatalogue.EntityFramework/Models/GPITBuyingCatalogue/PublicationStatus.cs
> +    }}
done

2021-07-04 15:58 UTC, bjss-chris approved these changes

2021-07-05 09:31 UTC, merged