Manage Catalogue Solutions e2e tests added
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #193
Opened 2021-07-06 12:57 UTC by EnitanOO

AB#14687
AB#15449

2021-07-07 08:08 UTC, bjss-chris requested changes

2021-07-07 08:08 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Actions/Admin/AddSolution.cs
> +        public void ManageCatalougeSolution()
Typo in catalogue.

2021-07-07 08:08 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Actions/Admin/AddSolution.cs
> +            Wait.Until(d => NumberOfFilterRadioButtonsDisplayed() > 0);
Parameter `d` isn't used so we can use a discard.

2021-07-07 08:08 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Actions/Admin/AddSolution.cs
> +                Wait.Until(s => ElementDisplayed(Objects.Admin.AddSolutionObjects.AddSolutionLink));
Similar to above, parameter `s` isn't used so we can use a discard.

2021-07-07 08:08 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Actions/Admin/AddSolution.cs
> +            int numberOfItems = -1;
Initial value is never used so can be removed.

2021-07-07 08:08 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Actions/Admin/AddSolution.cs
> +                   .FindElements(By.CssSelector("tbody tr")).Count();
We can use the `Count` property here.

2021-07-07 08:08 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Actions/Admin/AddSolution.cs
> +        }
Unnecessary white space added after brace.

2021-07-07 08:08 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Views/Home/Index.cshtml
>          <br><br>
The formatting looks like it's gone slightly skew-whiff here. If you have CodeMaid installed recommend running a clean-up.

2021-07-07 08:08 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Areas/Admin/ManageCatalogueSolutions.cs
> +using NHSD.GPIT.BuyingCatalogue.EntityFramework.Ordering.Models;
Is this needed?

2021-07-07 08:08 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Areas/Admin/ManageCatalogueSolutions.cs
> +    public class ManageCatalogueSolutions : TestBase, IClassFixture<LocalWebApplicationFactory>
`sealed`

2021-07-07 08:08 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Objects/Admin/AddSolutionObjects.cs
> +        internal static By CatalogueSolutionRowHead => By.ClassName("nhsuk-table__head");
Expecting this to be used in the near future? (It looks like it isn't currently used.)

2021-07-07 08:08 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Objects/Admin/AddSolutionObjects.cs
> +        internal static By FilterRadioButtonLabel => By.CssSelector("div.nhsuk-radios__item label.nhsuk-radios__label");
Expecting this to be used in the near future? (It looks like it isn't currently used.)

2021-07-07 11:48 UTC, EnitanOO commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Actions/Admin/AddSolution.cs
> +        public void ManageCatalougeSolution()
corrected

2021-07-07 11:48 UTC, EnitanOO commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Actions/Admin/AddSolution.cs
> +            Wait.Until(d => NumberOfFilterRadioButtonsDisplayed() > 0);
done

2021-07-07 11:49 UTC, EnitanOO commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Actions/Admin/AddSolution.cs
> +                Wait.Until(s => ElementDisplayed(Objects.Admin.AddSolutionObjects.AddSolutionLink));
Done

2021-07-07 11:49 UTC, EnitanOO commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Actions/Admin/AddSolution.cs
> +            int numberOfItems = -1;
removed

2021-07-07 11:49 UTC, EnitanOO commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Actions/Admin/AddSolution.cs
> +                   .FindElements(By.CssSelector("tbody tr")).Count();
done

2021-07-07 11:50 UTC, EnitanOO commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Views/Home/Index.cshtml
>          <br><br>
CodeMaid installed and used

2021-07-07 11:50 UTC, EnitanOO commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Areas/Admin/ManageCatalogueSolutions.cs
> +using NHSD.GPIT.BuyingCatalogue.EntityFramework.Ordering.Models;
removed

2021-07-07 11:50 UTC, EnitanOO commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Areas/Admin/ManageCatalogueSolutions.cs
> +    public class ManageCatalogueSolutions : TestBase, IClassFixture<LocalWebApplicationFactory>
done

2021-07-07 11:50 UTC, EnitanOO commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Objects/Admin/AddSolutionObjects.cs
> +        internal static By CatalogueSolutionRowHead => By.ClassName("nhsuk-table__head");
removed

2021-07-07 11:50 UTC, EnitanOO commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Objects/Admin/AddSolutionObjects.cs
> +        internal static By FilterRadioButtonLabel => By.CssSelector("div.nhsuk-radios__item label.nhsuk-radios__label");
removed

2021-07-07 15:35 UTC, EnitanOO commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Actions/Admin/AddSolution.cs
> +        }
sorted

2021-07-07 16:51 UTC, bjss-chris reviewed
Looks fine. Just needs bringing up-to-date with the latest main.

2021-07-07 17:08 UTC, bjss-chris approved these changes
Squash and merge please and can you rewrite your commit message in the imperative?

E.g. 'Add manage catalogue solutions E2E tests'.

I'll expand on some of this stuff when I run the git session.

2021-07-07 17:27 UTC, EnitanOO commented
Ok Chris. Thanks!

But I think there has been another change now and not able to do a merge...


From: bjss-chris ***@***.***>
Sent: 07 July 2021 18:09
To: nhs-digital-gp-it-futures/GPITBuyingCatalogue ***@***.***>
Cc: Enitan Onabamiro ***@***.***>; Author ***@***.***>
Subject: Re: [nhs-digital-gp-it-futures/GPITBuyingCatalogue] Manage Catalogue Solutions e2e tests added (#193)

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


@bjss-chris approved this pull request.

Squash and merge please and can you rewrite your commit message in the imperative?

E.g. 'Add manage catalogue solutions E2E tests'.

I'll expand on some of this stuff when I run the git session.

-
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnhs-digital-gp-it-futures%2FGPITBuyingCatalogue%2Fpull%2F193%23pullrequestreview-701254035&data=04%7C01%7Cenitan.onabamiro%40mastek.com%7C773d6c3a63734927ed7c08d94169e59d%7Cadd1c500a6d74dbdb8907f8cb6f7d861%7C0%7C0%7C637612745356510592%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=9MxN0lJV%2FonQWthvrGtPSPTXYYZDTGH8JjDUFSyeZm4%3D&reserved=0>, or unsubscribe<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FATCN4YBIISE2HTTYIGN72ZTTWSC2FANCNFSM474QXWLA&data=04%7C01%7Cenitan.onabamiro%40mastek.com%7C773d6c3a63734927ed7c08d94169e59d%7Cadd1c500a6d74dbdb8907f8cb6f7d861%7C0%7C0%7C637612745356510592%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=xDLqr4Z6HZ57yoTH59Ip4HIsGujiZWwgOdjbzbRgFy0%3D&reserved=0>.

2021-07-07 18:18 UTC, merged

2021-07-07 18:18 UTC, bjss-chris commented
> Ok Chris. Thanks! But I think there has been another change now and not able to do a merge...

It was fine, no issues. I've just merged it.

2021-07-08 07:25 UTC, EnitanOO commented
Thank you Chris