Manage Suppliers e2e tests added
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #198
Opened 2021-07-07 08:20 UTC by EnitanOO

AB#15247
AB#15458

2021-07-07 11:14 UTC, PhysicsJon requested changes

2021-07-07 11:14 UTC, PhysicsJon commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Actions/Admin/AddSolution.cs
> +                Wait.Until(s => ElementDisplayed(Objects.Admin.AddSolutionObjects.AddSuppliersOrgLink));
Should use a discard here rather than `s`

2021-07-07 11:14 UTC, PhysicsJon commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Actions/Admin/AddSolution.cs
> +                throw new WebDriverException();
this will trigger if there are no rows in the table, which will potentially fail the test even if it is a valid number of rows

2021-07-07 11:14 UTC, PhysicsJon commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Areas/PublicBrowse/Solution/AdditionalServicesDetails.cs
> +}
Does this class need to be in this pr?

2021-07-07 11:14 UTC, PhysicsJon commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Objects/Admin/AddSolutionObjects.cs
> +        internal static By SupplierEditLink => By.LinkText("Edit");
are there any better locators than LinkText? currently these are very fragile if the content changes

2021-07-07 16:13 UTC, EnitanOO commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Actions/Admin/AddSolution.cs
> +                Wait.Until(s => ElementDisplayed(Objects.Admin.AddSolutionObjects.AddSuppliersOrgLink));
Refactored

2021-07-07 16:14 UTC, EnitanOO commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Actions/Admin/AddSolution.cs
> +                throw new WebDriverException();
refactored

2021-07-07 16:14 UTC, EnitanOO commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Areas/PublicBrowse/Solution/AdditionalServicesDetails.cs
> +}
removed

2021-07-07 16:15 UTC, EnitanOO commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Objects/Admin/AddSolutionObjects.cs
> +        internal static By SupplierEditLink => By.LinkText("Edit");
customised

2021-07-07 16:25 UTC, PhysicsJon submitted a review, later dismissed

2021-07-07 16:25 UTC, PhysicsJon commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Actions/Admin/AddSolution.cs
>          }
This will fail if there aren't any rows in the table.

2021-07-07 16:25 UTC, PhysicsJon commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Actions/Admin/AddSolution.cs
>          }
Also should remove the parentheses from `.Count`

2021-07-07 16:42 UTC, EnitanOO commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Actions/Admin/AddSolution.cs
>          }
parentheses from count removed. 

review re catch had being sorted with an earlier push?

2021-07-08 14:36 UTC, bjss-chris approved these changes

2021-07-08 14:44 UTC, bjss-chris approved these changes

2021-07-08 15:07 UTC, merged