Admin manage organisations page
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #205
Opened 2021-07-07 15:47 UTC by RahulJha-mastek

Story AB#14685
Task: AB#15456

2021-07-08 08:51 UTC, bjss-chris requested changes

2021-07-08 08:51 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Controllers/HomeController.cs
> +            logger.LogInformation($"Taking user to Admin {nameof(HomeController)}.{nameof(Index)}");
I don't think we need this log message so I'd recommend removing it and the logger dependency.

2021-07-08 08:51 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/ListOrganisationsModel.cs
>      public class ListOrganisationsModel : NavBaseModel
`sealed`

I think `using NHSD.GPIT.BuyingCatalogue.EntityFramework.Models.GPITBuyingCatalogue;` can also be removed.

2021-07-08 08:51 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/ListOrganisationsModel.cs
> +        public IList<OrganisationModel> Organisations { get; private set; }
It looks like we should be able to remove the `private set;`

2021-07-08 08:51 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/ListOrganisationsModel.cs
> +            return new Dictionary<string, string>
The type name can be omitted using the `new()` expression, e.g. `return new()`...

2021-07-08 08:51 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/OrganisationModel.cs
> +using System.Collections.Generic;
We don't need this using.

2021-07-08 08:51 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Views/Home/BuyerOrganisations.cshtml
> +                    <a data-test-id="org-link" data-org-id="@organisationModel.Id" href="/admin/organisations/@organisationModel.Id">Manage</a>
We should use the anchor tag helper here, e.g.:

```razor
<a data-test-id="org-link" data-org-id="@organisationModel.Id" asp-area="Admin" asp-controller="Organisations" asp-action="Details" asp-route-id="@organisationModel.Id">Manage</a>
```

Please double check the values are correct in my example.

2021-07-08 08:51 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Views/Home/Index.cshtml
> +                            <a class="nhsuk-card__link" href="~/admin/buyer-organisations">Manage organisations and users</a>
As above, we should be using the anchor tag helper here, e.g.

```razor
<a class="nhsuk-card__link" asp-area="Admin" asp-controller="Home" asp-action="BuyerOrganisations">Manage organisations and users</a>
```

Please double-check the values in the example.

2021-07-08 08:51 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Areas/Admin/AdminDashboard.cs
> +﻿using System;
Do we need this?

2021-07-08 08:57 UTC, PhysicsJon requested changes

2021-07-08 08:57 UTC, PhysicsJon commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Areas/Admin/AdminDashboard.cs
> +            var otherProgramList = organisationIds.Select(x => x.ToString()).ToList();
Can the variable name be a little more clear as to what it is?

2021-07-08 08:57 UTC, PhysicsJon commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Areas/Admin/AdminDashboard.cs
> +            var otherProgramList = organisationIds.Select(x => x.ToString()).ToList();
The lambda variable should be changed to something a little more in line with what it's selecting

2021-07-08 08:58 UTC, PhysicsJon commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Areas/Admin/AdminDashboard.cs
> +            var otherProgramList = organisationIds.Select(x => x.ToString()).ToList();
In addition, can all these be grabbed using a single query that returns an organisation model rather than multiple queries that return parts of the organisation?

2021-07-08 09:55 UTC, RahulJha-mastek commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Controllers/HomeController.cs
> +            logger.LogInformation($"Taking user to Admin {nameof(HomeController)}.{nameof(Index)}");
Removed logger from controller and its test cases.

2021-07-08 09:56 UTC, RahulJha-mastek commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/ListOrganisationsModel.cs
>      public class ListOrganisationsModel : NavBaseModel
Made class as `sealed` and removed unused namespace

2021-07-08 09:56 UTC, RahulJha-mastek commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/ListOrganisationsModel.cs
> +        public IList<OrganisationModel> Organisations { get; private set; }
removed `private set`

2021-07-08 09:56 UTC, RahulJha-mastek commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/ListOrganisationsModel.cs
> +            return new Dictionary<string, string>
replaced code with `new()`

2021-07-08 09:56 UTC, RahulJha-mastek commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/OrganisationModel.cs
> +using System.Collections.Generic;
removed namespace

2021-07-08 09:57 UTC, RahulJha-mastek commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Views/Home/Index.cshtml
> +                            <a class="nhsuk-card__link" href="~/admin/buyer-organisations">Manage organisations and users</a>
Updated anchor tag with tag helper

2021-07-08 09:57 UTC, RahulJha-mastek commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Areas/Admin/AdminDashboard.cs
> +﻿using System;
Removed namespace

2021-07-08 09:58 UTC, RahulJha-mastek commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Areas/Admin/AdminDashboard.cs
> +            var otherProgramList = organisationIds.Select(x => x.ToString()).ToList();
Renamed Variables and method.
and 
Used one database call for all values

2021-07-08 17:22 UTC, bjss-chris requested changes
Just a couple of small things.

2021-07-08 17:22 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Areas/Admin/AdminDashboard.cs
> +                    OdsCode = o.OdsCode,
Can be simplified to:

```c#
o.Name,
o.OrganisationId,
o.OdsCode,
```

2021-07-08 17:22 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Areas/Admin/AdminDashboard.cs
> +            actualOrganisationNames.Should().HaveCount(expectedOrganisationNames.Count());
We can use the `Count` property here.

2021-07-08 18:29 UTC, RahulJha-mastek commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Areas/Admin/AdminDashboard.cs
> +                    OdsCode = o.OdsCode,
Updated code.

2021-07-08 18:29 UTC, RahulJha-mastek commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Areas/Admin/AdminDashboard.cs
> +            actualOrganisationNames.Should().HaveCount(expectedOrganisationNames.Count());
Used `Count` property

2021-07-08 20:23 UTC, bjss-chris approved these changes

2021-07-09 07:42 UTC, PhysicsJon requested changes

2021-07-09 07:42 UTC, PhysicsJon commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Areas/Admin/AdminDashboard.cs
> -            : base(factory, "admin/organisations")
Please revert this change, the tests in this area are to be rewritten for the new area

2021-07-09 09:11 UTC, RahulJha-mastek commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Areas/Admin/AdminDashboard.cs
> -            : base(factory, "admin/organisations")
Reverted to `: base(factory, "admin/organisations")` and skipped 2 test cases
`AdminDashboard_AddOrgButtonDisplayed()` and `AdminDashboard_AllOrgsDisplayed()`

2021-07-09 09:12 UTC, PhysicsJon approved these changes

2021-07-09 09:14 UTC, merged