Breadcrumbs for Marketing Pages e2e tests added
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #233
Opened 2021-07-09 11:33 UTC by EnitanOO

AB#15190
AB#15652

2021-07-09 13:20 UTC, PhysicsJon requested changes

2021-07-09 13:20 UTC, PhysicsJon commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Objects/PublicBrowse/SolutionObjects.cs
> +        internal static By HomePage => By.Id("maincontent");
HomePage check should use objects from another area. Tis is not in the right place and will only confuse matters further

2021-07-09 13:20 UTC, PhysicsJon commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Actions/PublicBrowse/SolutionAction.cs
> +        public bool HomePageDisplayed()
2 major issues in this to me. Firstly this method is doing 2 actions (Clicking the breadcrumb and checking that the homepage is displayed), secondly the check that the homepage is displayed should not be in SolutionActions, it should be in the HomepageActions class

2021-07-09 13:20 UTC, PhysicsJon commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Actions/PublicBrowse/SolutionAction.cs
> +            ClickCatalogueSolutionBreadcrumb();
This should be removed from this method and added to the test instead

2021-07-09 13:20 UTC, PhysicsJon commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Actions/PublicBrowse/SolutionAction.cs
> +            Driver.FindElement(Objects.PublicBrowse.SolutionObjects.CatalogueSolutionCrumb).Click();
The wrong object is being used here

2021-07-09 13:20 UTC, PhysicsJon commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Actions/PublicBrowse/SolutionAction.cs
> +            var row = rows.Single(s => s.FindElement(By.TagName("a")).Text.Contains(breadcrumbItem, System.StringComparison.OrdinalIgnoreCase));
Why have you used a lambda parameter of `s` here? would `r` not be better?

2021-07-09 14:10 UTC, EnitanOO commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Actions/PublicBrowse/SolutionAction.cs
> +            var row = rows.Single(s => s.FindElement(By.TagName("a")).Text.Contains(breadcrumbItem, System.StringComparison.OrdinalIgnoreCase));
done

2021-07-09 14:11 UTC, EnitanOO commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Actions/PublicBrowse/SolutionAction.cs
> +            Driver.FindElement(Objects.PublicBrowse.SolutionObjects.CatalogueSolutionCrumb).Click();
corrected

2021-07-09 15:03 UTC, EnitanOO commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Actions/PublicBrowse/SolutionAction.cs
> +        public bool HomePageDisplayed()
Hopefully redone right

2021-07-09 15:04 UTC, EnitanOO commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Actions/PublicBrowse/SolutionAction.cs
> +            ClickCatalogueSolutionBreadcrumb();
done

2021-07-09 15:04 UTC, EnitanOO commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Actions/PublicBrowse/SolutionAction.cs
> +            var row = rows.Single(s => s.FindElement(By.TagName("a")).Text.Contains(breadcrumbItem, System.StringComparison.OrdinalIgnoreCase));
corrected

2021-07-14 08:22 UTC, PhysicsJon approved these changes

2021-07-14 08:35 UTC, merged