Feature/15109 additional capabibilities
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #245
Opened 2021-07-13 14:32 UTC by RahulJha-mastek

Story AB#15109
Task AB#15748
Task AB#15745

2021-07-13 14:52 UTC, PhysicsJon requested changes

2021-07-13 14:52 UTC, PhysicsJon commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/SolutionDetails/CapabilitiesAdditionalServices.cshtml
> +                        Supports the administration, scheduling, resourcing and reporting of appointments.
Is hardcoding this correct?

2021-07-13 16:17 UTC, RahulJha-mastek commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/SolutionDetails/CapabilitiesAdditionalServices.cshtml
> +                        Supports the administration, scheduling, resourcing and reporting of appointments.
Verified and updated content to Additional Service Description.

2021-07-14 11:58 UTC, PhysicsJon approved these changes

2021-07-14 12:21 UTC, merged