Fix Layout and Add a Solution Issues
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #249
Opened 2021-07-14 16:04 UTC by leerogers-bjss

Move all Layout files to a central location and combine them into understandable layouts and partials.
Update all layout files to use the same, new footer
update all layout files to use new menu look, with the separation being either admin or non-admin menu.
Remove duplicate HTML into different partials which are then called by the layout pages
update all _ViewStart files to reference these layout files
update pages to call the correct layout files.

Fix add a solution to attach the error correctly to the list of checkboxes by fixing the fluid validation property attachment

update add a solution to return the catalogueItemId so that we can then redirect to the manage solutions page after creating a new solution

2021-07-14 16:47 UTC, PhysicsJon requested changes
one small change

2021-07-14 16:47 UTC, PhysicsJon commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Views/AddCatalogueSolution/Index.cshtml
> +                    @for (var i = 0; i < Model.Frameworks.Count; i++)
could this be done as a foreach?

2021-07-14 17:03 UTC, leerogers-bjss commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Views/AddCatalogueSolution/Index.cshtml
> +                    @for (var i = 0; i < Model.Frameworks.Count; i++)
nope, needs the correct list reference or it won't attach correct on the post

2021-07-15 06:51 UTC, PhysicsJon approved these changes

2021-07-15 08:12 UTC, merged