Update implementation of app gateway
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #257
Opened 2021-07-16 10:32 UTC by steves-bjss

Update terraform to add App Gateway

2021-07-16 10:39 UTC, MichaelRobinson-BJSS submitted a review, later dismissed

2021-07-16 10:42 UTC, PhysicsJon requested changes
Looks sensible enough, just got a few missing EoF newlines

2021-07-16 10:42 UTC, PhysicsJon commented on terraform/app_gateway_ingress.tf
> +}
EoF newline missing

2021-07-16 10:42 UTC, PhysicsJon commented on terraform/modules/bc_app_gateway_ingress/variables.tf
> +}
EoF newline missing

2021-07-16 10:42 UTC, PhysicsJon commented on terraform/modules/bc_webapp_pri/output.tf
> +}
EoF newline missing

2021-07-16 10:42 UTC, PhysicsJon commented on terraform/modules/bc_webapp_pri/variables.tf
>  }
EoF newline missing

2021-07-16 10:42 UTC, PhysicsJon commented on terraform/network_security_group_association.tf
> +
EoF newline missing

2021-07-16 10:42 UTC, PhysicsJon commented on terraform/virtual_network_subnet.tf
>  }
EoF newline missing

2021-07-16 10:42 UTC, PhysicsJon commented on terraform/webapp_virtual_network.tf
> +}
EoF newline missing

2021-07-20 10:58 UTC, steves-bjss commented on terraform/webapp_virtual_network.tf
> +}
Updated

2021-07-20 10:58 UTC, steves-bjss commented on terraform/network_security_group_association.tf
> +
Updated

2021-07-20 10:58 UTC, steves-bjss commented on terraform/virtual_network_subnet.tf
>  }
Updated

2021-07-20 10:58 UTC, steves-bjss commented on terraform/modules/bc_webapp_pri/variables.tf
>  }
Updated

2021-07-20 10:58 UTC, steves-bjss commented on terraform/modules/bc_webapp_pri/output.tf
> +}
Updated

2021-07-20 10:58 UTC, steves-bjss commented on terraform/modules/bc_app_gateway_ingress/variables.tf
> +}
Updated

2021-07-20 10:58 UTC, steves-bjss commented on terraform/app_gateway_ingress.tf
> +}
Updated

2021-07-20 11:07 UTC, PhysicsJon approved these changes

2021-07-20 11:46 UTC, merged