Feature/15766 order journey e2e
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #269
Opened 2021-07-20 14:11 UTC by leerogers-bjss

Add Order E2E Tests
Add new TestBases for Different Login Types
Update Order Object CallOffId to be Generated in code and ignored in EF
Have E2E Tests load CSS and JS for correct functionality tests
General Cleanups and Relocation of TestBases and Custom Actions

2021-07-20 14:26 UTC, PhysicsJon requested changes
A few small changes, but everything looks good so far

2021-07-20 14:26 UTC, PhysicsJon commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Actions/Common/CommonActions.cs
> +        }
Change this to call the ElementIsDisplayed method

2021-07-20 14:26 UTC, PhysicsJon commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Actions/Ordering/CallOffPartyInformation.cs
> +        }
All of these methods can call the ElementIsDisplayed method from CommonActions

2021-07-20 14:26 UTC, PhysicsJon commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Actions/Ordering/OrderDashboard.cs
> +        }
This can use ElementIsDisplayed as well

2021-07-20 14:26 UTC, PhysicsJon commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Actions/Ordering/OrderDescription.cs
> +        }
This can use ElementIsDisplayed as well

2021-07-20 14:26 UTC, PhysicsJon commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Actions/Ordering/OrganisationDashboard.cs
> +        }
The 3 actions here could all use the ElementIsDisplayed method too

2021-07-20 14:26 UTC, PhysicsJon commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Actions/PublicBrowse/SolutionAction.cs
> +            return  Driver.FindElement(Objects.PublicBrowse.SolutionObjects.ImplementationName).Text;
Extra whitespace?

2021-07-20 14:47 UTC, bjss-chris requested changes
I've left a few comments but not really focused on the main E2E test functionality. I'll have a quick scan through that now but probably best for @PhysicsJon to look through as well as the E2E tests main man. 😃

2021-07-20 14:47 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.EntityFramework/Ordering/Models/CallOffId.cs
> +                throw new ArgumentOutOfRangeException(nameof(id), $"id must be between 0 and {MaxId}: Current Value - {id}");
I'm not convinced the message here really adds much value. However, I think this would be better:

```c#
throw new ArgumentOutOfRangeException(nameof(id), id, $"Value must be between 0 and {MaxId}.");
```

2021-07-20 14:47 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.EntityFramework/Ordering/Models/CallOffId.cs
> +                throw new ArgumentOutOfRangeException(nameof(revision), $"revision must be less than {MaxRevision}: Current Value - {revision}");
As above, I'm not convinced the message here really adds much value. However, I think this would be better:

```c#
throw new ArgumentOutOfRangeException(nameof(revision), revision, $"Value must be less than {MaxRevision}.");
```

2021-07-20 14:47 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.Test.Framework/AutoFixtureCustomisations/FixtureFactory.cs
> +            new OrderEntityCustomization(),
I don't think `CallOffIdCustomization` should be removed – please see my next comment.

2021-07-20 14:47 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.Test.Framework/AutoFixtureCustomisations/OrderEntityCustomization.cs
> +    public sealed class OrderEntityCustomization : ICustomization
Name should be `OrderCustomization` to be consistent with other customizations.

2021-07-20 14:47 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.Test.Framework/AutoFixtureCustomisations/OrderEntityCustomization.cs
> +                .With(o => o.Revision, (fixture.Create<byte>() % CallOffId.MaxRevision) + 1));
Suggest this instead (with `CallOffIdCustomization` included as per previous comment):

```c#
public void Customize(IFixture fixture)
{
    var callOffId = fixture.Create<CallOffId>();

    fixture.Customize<Order>(order => order
        .With(o => o.Id, callOffId.Id)
        .With(o => o.Revision, callOffId.Revision));
}
```

2021-07-20 16:28 UTC, leerogers-bjss commented on src/NHSD.GPIT.BuyingCatalogue.EntityFramework/Ordering/Models/CallOffId.cs
> +                throw new ArgumentOutOfRangeException(nameof(id), $"id must be between 0 and {MaxId}: Current Value - {id}");
i added it because autofixture was failing and just saying "id".
displaying the id actually helped me solve the issue, so would push back on this one 😬

2021-07-20 16:29 UTC, leerogers-bjss commented on src/NHSD.GPIT.BuyingCatalogue.EntityFramework/Ordering/Models/CallOffId.cs
> +                throw new ArgumentOutOfRangeException(nameof(revision), $"revision must be less than {MaxRevision}: Current Value - {revision}");
same argument as above

2021-07-20 16:34 UTC, leerogers-bjss commented on src/NHSD.GPIT.BuyingCatalogue.EntityFramework/Ordering/Models/CallOffId.cs
> +                throw new ArgumentOutOfRangeException(nameof(id), $"id must be between 0 and {MaxId}: Current Value - {id}");
actually, your format is correct :)

2021-07-21 11:06 UTC, PhysicsJon approved these changes

2021-07-21 11:21 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.EntityFramework/Ordering/Models/CallOffId.cs
> +                throw new ArgumentOutOfRangeException(nameof(revision), revision, $"revision must be less than {MaxRevision}");
I think just a generic "Value must be..." would have been fine here as the name of the property will be added to the exception message anyway. However, while it's unlikely that the name of either parameter will change we could use `nameof` here.

2021-07-21 11:23 UTC, leerogers-bjss commented on src/NHSD.GPIT.BuyingCatalogue.EntityFramework/Ordering/Models/CallOffId.cs
> +                throw new ArgumentOutOfRangeException(nameof(revision), revision, $"revision must be less than {MaxRevision}");
i'll just change it to Value

2021-07-21 11:36 UTC, PhysicsJon submitted a review, later dismissed

2021-07-21 14:47 UTC, PhysicsJon approved these changes

2021-07-21 17:23 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Actions/Common/CommonActions.cs
> +                            .FirstOrDefault() as HttpGetAttribute)?.Template;
Can this be simplified to this?

```c#
var controllerRoute = controller.GetCustomAttribute<RouteAttribute>(false)?.Template;
var methodRoute = controller.GetMethod(methodName)?.GetCustomAttribute<HttpGetAttribute>(false)?.Template;
```

2021-07-21 17:23 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Actions/Common/CommonActions.cs
> +            return true;
What do you think of the LINQ option?

```c#
return !actionUrl.Segments.Where((t, i) => !t.StartsWith("%7B") && driverUrl.Segments[i] != t).Any();
```

2021-07-21 17:23 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Actions/Common/CommonActions.cs
> +        /// Formats a string by removing all newline and whitespace so that we get more consistant comparisons.
Typo in consistent.

2021-07-21 17:23 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Actions/Common/CommonActions.cs
> +        internal string FormatStringForComparison(string formatString) =>
Can be `static`.

2021-07-21 17:23 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Actions/Common/CommonActions.cs
> +            .Trim();
A possible alternative:

```c#
new(formatString.Where(c => !char.IsWhiteSpace(c)).ToArray());
```

Do we definitely need the `Trim()`? Won't removing all the white space have already had the same effect?

I'm not sure which implementation I prefer. My alternative is more concise and I suspect it will be more efficient but I'm not particularly concerned about efficiency here (assuming my alternative above is correct).

What do you think?

2021-07-21 17:24 UTC, leerogers-bjss commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Actions/Common/CommonActions.cs
> +                            .FirstOrDefault() as HttpGetAttribute)?.Template;
controller one yes

method one is required sue to GetMethod throwing ambiguious references error.

2021-07-21 17:27 UTC, leerogers-bjss commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Actions/Common/CommonActions.cs
>              Driver.FindElement(CommonSelectors.GoBackLink).Click();
ahh, these were moved over base CommonActions, but i forgot to delete them :D

2021-07-21 17:30 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Actions/Common/CommonActions.cs
> +            Type controller,
I almost forgot, I wonder if `controllerType` might be a slightly better name as we're not actually taking in the controller but its type. Any thoughts?

2021-07-21 17:39 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Actions/Common/CommonActions.cs
> +                            .FirstOrDefault() as HttpGetAttribute)?.Template;
What about this one? Assuming it's correct 😃, I think it's slightly more readable.

```c#
var methodRoute = controller.GetMethods()
    .FirstOrDefault(m => m.Name == methodName && m.GetCustomAttribute<HttpGetAttribute>(false) is not null)
    ?.GetCustomAttribute<HttpGetAttribute>(false)?.Template;
```

I can never decide how I prefer the `?.`! Alternative format:

```c#
var methodRoute = controller.GetMethods()
    .FirstOrDefault(m => m.Name == methodName && m.GetCustomAttribute<HttpGetAttribute>(false) is not null)?
    .GetCustomAttribute<HttpGetAttribute>(false)?.Template;
```

2021-07-21 17:41 UTC, leerogers-bjss commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Actions/Common/CommonActions.cs
> +            return true;
i like it.
gona add a comment on it just to make sure people know whats its doing, since it has the whole "magic variable" issue "%7B". but yeah, noice 👯

2021-07-21 17:50 UTC, leerogers-bjss commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Actions/Common/CommonActions.cs
> +        /// Formats a string by removing all newline and whitespace so that we get more consistant comparisons.
at least i consistantly can't spell consistant :D

2021-07-21 17:56 UTC, leerogers-bjss commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Actions/Common/CommonActions.cs
> +        internal string FormatStringForComparison(string formatString) =>
yeah it can be, but i left it not static because of it will messy references inside tests.

as an example, we currently call the FormatStringForComparison like this

```c#
CommonActions.PageTitle().Should().BeEquivalentTo(CommonActions.FormatStringForComparison("No supplier found"));
```

but because CommonActions is qualified capitalised, if we made this function static, we would have to reference it like this:

```c#
CommonActions.PageTitle().Should().BeEquivalentTo(Actions.Common.CommonActions.FormatStringForComparison("No supplier found"));
```  

which frankly, looks messy, especially since we get the reference for free.

Honestly its your call :) don't mind either.

2021-07-21 18:02 UTC, leerogers-bjss commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Actions/Common/CommonActions.cs
> +            .Trim();
look nice. stealing

2021-07-21 20:51 UTC, leerogers-bjss commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Actions/Common/CommonActions.cs
> +                            .FirstOrDefault() as HttpGetAttribute)?.Template;
Sadly, Method info doesn't contain a
```c#
.GetCustomAttribute<HttpGetAttribute>(false);
```
only
```c#
.GetCustomAttributes(typeof(HttpGetAttribute, false));
```
so the best i could do would be something like this
```c#
var methodRoute = (controllerType.GetMethods()
    .FirstOrDefault(m => 
        m.Name == methodName 
        && m.GetCustomAttributes(typeof(HttpGetAttribute), false) is not null)?
    .GetCustomAttributes(typeof(HttpGetAttribute), false).FirstOrDefault() as HttpGetAttribute)?.Template;
 ```

2021-07-22 07:34 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Actions/Common/CommonActions.cs
> +                            .FirstOrDefault() as HttpGetAttribute)?.Template;
`GetCustomAttribute<HttpGetAttribute>(false);` is a `MemberInfo` extension method. `MethodInfo` derives from `MethodBase` which in turn derives from `MemberInfo`. I've just tried it in VS and it compiles and tests pass.

2021-07-22 07:48 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Actions/Common/CommonActions.cs
> +        internal string FormatStringForComparison(string formatString) =>
Yeah, it's not as neat as without the qualifiers but I probably wouldn't call it messy. My preference would be for the static, but why not go the extension route? Perhaps something like this?

```c#
internal static class StringExtensions
{
    internal static string FormatForComparison(this string value) => new(value.Where(c => !char.IsWhiteSpace(c)).ToArray());

    internal static bool EqualsIgnoreWhiteSpace(this string a, string b) => a.FormatForComparison().Equals(b.FormatForComparison(), StringComparison.Ordinal);
}
```

2021-07-22 08:27 UTC, leerogers-bjss commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Actions/Common/CommonActions.cs
> +                            .FirstOrDefault() as HttpGetAttribute)?.Template;
wtf, it didn't work yesterday, now it does. v0v. updated it :D

2021-07-22 08:44 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Actions/Common/CommonActions.cs
> +                    ?.FirstOrDefault() as RouteAttribute)?.Template;
You going to update this one as well now that you've got `GetCustomAttribute<T>` working?

```c#
var controllerRoute = controllerType.GetCustomAttribute<RouteAttribute>(false)?.Template;
```

2021-07-22 08:44 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Actions/Common/CommonActions.cs
>              Driver.FindElements(By.CssSelector("input[type=checkbox]")).First().Click();
What's happening with this and `ClickFirstCheckbox`, `ClickCheckbox`, `ClickSection`, `SelectDropdownItem`?

Did you forget to delete them again?

2021-07-22 08:59 UTC, leerogers-bjss commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Actions/Common/CommonActions.cs
>              Driver.FindElements(By.CssSelector("input[type=checkbox]")).First().Click();
ClickCheckbox is used
ClickSection isn't used r/n but will need to be used with stuff like summary lists
SelectDropdownItem is also used

2021-07-22 09:00 UTC, leerogers-bjss commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Actions/Common/CommonActions.cs
> +                    ?.FirstOrDefault() as RouteAttribute)?.Template;
yeah, will do

2021-07-22 09:36 UTC, bjss-chris reviewed
Just a few more small-ish suggestions/questions.

2021-07-22 09:36 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Areas/Ordering/OrganisationDashboard.cs
> +            using var context = GetEndToEndDbContext();
We can use `await using` here.

2021-07-22 09:36 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Areas/Ordering/SupplierInformation.cs
> +            using var context = GetEndToEndDbContext();
We can use `await using` here.

2021-07-22 09:36 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Areas/Ordering/SupplierInformation.cs
> +            using var context = GetEndToEndDbContext();
We can use `await using` here.

2021-07-22 09:36 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Areas/PublicBrowse/Solutions/CapabilitySelector.cs
> +            using var context = GetEndToEndDbContext();
We can use `await using` here.

2021-07-22 09:36 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Utils/SeedData/OrderSeedData.cs
> +            var orderId = 90000;
`const`

(Same in the other methods.)

2021-07-22 09:36 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Utils/SeedData/OrderSeedData.cs
> +            var timenow = DateTime.UtcNow;
`timeNow`

(Same in the other methods.)

2021-07-22 09:36 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Utils/TestBases/TestBase.cs
> +        public TestBase(LocalWebApplicationFactory factory, string urlArea = "")
`protected`?

2021-07-22 09:36 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Utils/TestBases/TestBase.cs
> +        internal WebDriverWait Wait { get; private set; }
`private set` redundant? Can be `get` only?

2021-07-22 09:36 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Utils/TestBases/TestBase.cs
> +            }
I'd invert this.

2021-07-22 09:36 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Utils/TestBases/TestBase.cs
> +            }
As above, I'd invert this.

2021-07-22 09:36 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Utils/TestBases/TestBase.cs
> +                            .FirstOrDefault() as HttpGetAttribute)?.Template;
Can we apply the same changes here that we applied to `CommonActions`, including name of `controller`?

I've not double-checked but it looks almost exactly the same as the earlier version of the code in `CommonActions`. Would be preferable to avoid duplicating – is this one of the things you were thinking about refactoring later?

2021-07-22 09:36 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.Test.Framework/AutoFixtureCustomisations/OrderCustomization.cs
> +using AutoFixture.Kernel;
Needed?

2021-07-22 09:36 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.Test.Framework/AutoFixtureCustomisations/OrderCustomization.cs
> +            .Without(o => o.OrderStatus));
Missing an indent?

2021-07-22 09:45 UTC, leerogers-bjss commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Utils/TestBases/TestBase.cs
> +                            .FirstOrDefault() as HttpGetAttribute)?.Template;
yeah, the top half of this and PageLoadedCorrectly are the same, may need to find a new home for it. but for now i'll just update it

2021-07-22 09:47 UTC, leerogers-bjss commented on tests/NHSD.GPIT.BuyingCatalogue.Test.Framework/AutoFixtureCustomisations/OrderCustomization.cs
> +using AutoFixture.Kernel;
i've slapped it off the face of the earth.

2021-07-22 09:47 UTC, leerogers-bjss commented on tests/NHSD.GPIT.BuyingCatalogue.Test.Framework/AutoFixtureCustomisations/OrderCustomization.cs
> +            .Without(o => o.OrderStatus));
dont seem to be?

2021-07-22 09:48 UTC, leerogers-bjss commented on tests/NHSD.GPIT.BuyingCatalogue.Test.Framework/AutoFixtureCustomisations/OrderCustomization.cs
> +            .Without(o => o.OrderStatus));
wait, yeah, sorry. thick moment for a second there. done

2021-07-22 10:04 UTC, bjss-chris approved these changes

2021-07-22 10:16 UTC, merged