Add hosting type data
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #278
Opened 2021-07-22 16:12 UTC by RahulJha-mastek

Story AB#15484
Task AB#15966

2021-07-27 12:31 UTC, bjss-chris requested changes
There are a number of issues here.

I will push a commit with some suggested changes for you to have a look at. You'll need to check and update the tests as the only changes I made were to make sure that the solution will build.

Let me know if you have any questions.

2021-07-27 12:31 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Controllers/CatalogueSolutionsController.cs
>              }
There are few issues here.

There are two places here where the model data received is ignored.

```c#
model = new HostingTypeSectionModel(solution);
```

We're also doing model validation that can/should be done in a model validator.

2021-07-27 12:31 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Controllers/CatalogueSolutionsController.cs
> +                    return RedirectToAction(nameof(AddHostingType), new { solutionId });
Seems more complicated than it needs to be.

2021-07-27 12:31 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Controllers/CatalogueSolutionsController.cs
> +                return BadRequest($"No Hosting found for Solution Id: {solutionId}");
Due to the implementation of `GetHosting`, `hosting` will never be `null`.

2021-07-27 12:31 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Controllers/CatalogueSolutionsController.cs
> +            return RedirectToAction(nameof(HostingType), new { solutionId, model });
We should only be supplying route values here. `model` isn't a route value so shouldn't be supplied. However, because it is supplied the correct values won't be passed back during a subsequent POST following one of these redirects.

The same issues mentioned here and in the comments above occur in other action methods in this controller too.

2021-07-27 12:31 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/HostingTypeSectionModel.cs
> +        public OnPremiseModel OnPremise { get; set; }
I think these aren't necessary.

2021-07-27 12:31 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Program.cs
> +                    webBuilder.UseIIS();
This shouldn't be necessary as we can just run the app using Kestrel, although we probably ought to remove the IIS option from `launchSettings` – we can do that as a separate tech debt task though.

2021-07-27 12:43 UTC, bjss-chris commented
Apologies, I missed a validator so I've just pushed another commit.

2021-07-27 14:53 UTC, RahulJha-mastek commented
> Apologies, I missed a validator so I've just pushed another commit.

Updated test cases based on new changes.

2021-07-27 15:42 UTC, RahulJha-mastek commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Program.cs
> +                    webBuilder.UseIIS();
Removed `webBuilder.UseIIS();`

2021-07-28 08:04 UTC, bjss-chris requested changes
A couple of minor suggestions/questions.

Also, did you look at review/fixing `HostingTypeSectionModelTests`?

2021-07-28 08:04 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.WebApp.UnitTests/Areas/Admin/Models/HostingTypeSectionModelTests.cs
>          }
Did you have a look at this one?

2021-07-28 09:39 UTC, RahulJha-mastek commented on tests/NHSD.GPIT.BuyingCatalogue.WebApp.UnitTests/Areas/Admin/Models/HostingTypeSectionModelTests.cs
>          }
Updated Test case.

2021-07-28 09:39 UTC, RahulJha-mastek commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Validators/HostingTypeSelectionModelValidator.cs
> +                .Unless(m => !m.HostingTypesAvailableForSelection);
Updated to `.When(m => m.HostingTypesAvailableForSelection)`

2021-07-28 09:39 UTC, RahulJha-mastek commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/HostingTypeModels/BaseCloudModel.cs
> +        public virtual bool? IsValid() =>
Updated properties as `Non-Nullable`

2021-07-28 09:39 UTC, RahulJha-mastek commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/HostingTypeModels/BaseCloudModel.cs
> +        public string SolutionId { get; set; }
Removed `SolutionId` property, as it was not set anywhere and only referenced in `View` page

2021-07-28 10:23 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.WebApp.UnitTests/Areas/Admin/Models/HostingTypeSectionModelTests.cs
> +            HostingTypeSectionModel model = new HostingTypeSectionModel(catalogueItem);
Can we use AutoFixture to generate `model` by marking `catalogueItem` as `[Frozen]`?

2021-07-28 11:42 UTC, RahulJha-mastek commented on tests/NHSD.GPIT.BuyingCatalogue.WebApp.UnitTests/Areas/Admin/Models/HostingTypeSectionModelTests.cs
> +            HostingTypeSectionModel model = new HostingTypeSectionModel(catalogueItem);
Added new `HostingTypeSectionModelCustomization` for model creation.

2021-07-28 14:28 UTC, bjss-chris requested changes

2021-07-28 14:28 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.Test.Framework/AutoFixtureCustomisations/HostingTypeSectionModelCustomization.cs
> +        }
I think this can be simplified to this:

```c#
public void Customize(IFixture fixture)
{
    fixture.Customize<HostingTypeSectionModel>(c => c.FromFactory(new MethodInvoker(new GreedyConstructorQuery()))
        .Without(m => m.SolutionId)
        .Without(m => m.SolutionName));
}
```

2021-07-28 14:28 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.WebApp.UnitTests/Areas/Admin/Models/HostingTypeSectionModelTests.cs
> +        public static void StatusHostingType_AvailableHosting_ReturnsCompleted(
If we make the change suggested to the customization above, we should be able to simplify `FromCatalogueItem_ValidCatalogueItem_PropertiesSetAsExpected` to:

```c#
[Theory]
[CommonAutoData]
public static void FromCatalogueItem_ValidCatalogueItem_PropertiesSetAsExpected(
    [Frozen] CatalogueItem catalogueItem,
    HostingTypeSectionModel expected)
{
    var actual = new HostingTypeSectionModel(catalogueItem);

    actual.SolutionId.Should().BeEquivalentTo(expected.SolutionId);
    actual.SolutionName.Should().BeEquivalentTo(expected.SolutionName);
}
```

This test is fine (only commented here due to GitHub limitations).

2021-07-28 14:42 UTC, RahulJha-mastek commented on tests/NHSD.GPIT.BuyingCatalogue.WebApp.UnitTests/Areas/Admin/Models/HostingTypeSectionModelTests.cs
> +        public static void StatusHostingType_AvailableHosting_ReturnsCompleted(
Updated `FromCatalogueItem_ValidCatalogueItem_PropertiesSetAsExpected` test case.

2021-07-28 14:54 UTC, bjss-chris requested changes

2021-07-28 15:02 UTC, RahulJha-mastek commented on tests/NHSD.GPIT.BuyingCatalogue.Test.Framework/AutoFixtureCustomisations/HostingTypeSectionModelCustomization.cs
> +                .Without(m => m.SolutionName));
Sorry. Forgot to remove unused code.
Removed it now.

2021-07-28 15:05 UTC, bjss-chris approved these changes

2021-07-28 15:24 UTC, merged