Create view of edit client application type
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #285
Opened 2021-07-23 15:40 UTC by nehajain008

Story AB#15298
Task AB#15969

2021-07-27 13:48 UTC, bjss-chris requested changes
The follows a similar pattern to #278 in places and as a result, it has some of the same issues. I pushed a couple of commits with suggested changes to @RahulJha-mastek's branch on #278 so I'd recommend having a look at my suggested changes for #278 – you can probably apply similar fixes here.

Let me know if you have any questions.

2021-07-27 13:48 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Controllers/CatalogueSolutionsController.cs
> +            }
This action method has the same issues as those described in #278, such as:

-  the `model` that is received as a parameter is ignored
- the validation should probably be moved to a validator

2021-07-27 13:48 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/ClientApplicationTypeSectionModel.cs
> +    public class ClientApplicationTypeSectionModel : MarketingBaseModel
`sealed`

2021-07-27 13:48 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/ClientApplicationTypeSectionModel.cs
> +            IsNativeDesktop = Convert.ToBoolean(CatalogueItem.Solution?.GetClientApplication()?.ClientApplicationTypes.Any(x => x.EqualsIgnoreCase("native-desktop")));
Can we use something other than `x` for the lambda parameter?

There's no need to use `Convert.ToBoolean` here either, instead we could use `expression ?? false`.

2021-07-27 13:48 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/ClientApplicationTypeSectionModel.cs
> +        public virtual bool IsNativeDesktop { get; set; }
Don't need to be `virtual`.

2021-07-27 13:48 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/ClientApplicationTypeSectionModel.cs
> +        public override bool? IsComplete => Convert.ToBoolean(IsBrowserBased) || Convert.ToBoolean(IsNativeMobile) || Convert.ToBoolean(IsNativeDesktop);
No need for `Convert.ToBoolean`.

2021-07-27 13:48 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/ClientApplicationTypeSectionModel.cs
> +        public bool? AddedClientApplicationType => IsComplete == true ? true : null;
Why nullable? Can we not just return `false` is not complete? In which case, we can just do `IsComplete.GetValueOrDefault()`.

2021-07-27 13:48 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/ClientApplicationTypeSectionModel.cs
> +           Convert.ToBoolean(IsComplete)
IsComplete.GetValueOrDefault()

2021-07-30 11:14 UTC, nehajain008 commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Controllers/CatalogueSolutionsController.cs
> +            }
Changes done as described in #278

2021-07-30 11:15 UTC, nehajain008 commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/ClientApplicationTypeSectionModel.cs
> +    public class ClientApplicationTypeSectionModel : MarketingBaseModel
Done

2021-07-30 11:15 UTC, nehajain008 commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/ClientApplicationTypeSectionModel.cs
> +            IsNativeDesktop = Convert.ToBoolean(CatalogueItem.Solution?.GetClientApplication()?.ClientApplicationTypes.Any(x => x.EqualsIgnoreCase("native-desktop")));
Done.

2021-07-30 11:16 UTC, nehajain008 commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/ClientApplicationTypeSectionModel.cs
> +        public virtual bool IsNativeDesktop { get; set; }
Removed these properties.

2021-07-30 11:16 UTC, nehajain008 commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/ClientApplicationTypeSectionModel.cs
> +        public override bool? IsComplete => Convert.ToBoolean(IsBrowserBased) || Convert.ToBoolean(IsNativeMobile) || Convert.ToBoolean(IsNativeDesktop);
Done.

2021-07-30 11:16 UTC, nehajain008 commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/ClientApplicationTypeSectionModel.cs
> +        public bool? AddedClientApplicationType => IsComplete == true ? true : null;
Done.

2021-07-30 11:16 UTC, nehajain008 commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/ClientApplicationTypeSectionModel.cs
> +           Convert.ToBoolean(IsComplete)
Done.

2021-07-30 16:35 UTC, nehajain008 commented
> 
> 
> The follows a similar pattern to #278 in places and as a result, it has some of the same issues. I pushed a couple of commits with suggested changes to @RahulJha-mastek's branch on #278 so I'd recommend having a look at my suggested changes for #278 – you can probably apply similar fixes here.
> 
> Let me know if you have any questions.

Done.

2021-08-02 11:28 UTC, bjss-chris commented
Fixed up a couple of issues with the existing functionality and content.

There's some tech debt here – added some TODO comments to review in the near future.

2021-08-04 09:15 UTC, merged