Refactor views to use new components
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #287
Opened 2021-07-28 08:10 UTC by NickNewlands

Story: AB#14974
Ticket: AB#15437

2021-07-28 14:38 UTC, PhysicsJon commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Identity/Models/ForgotPasswordViewModel.cs
> +    public class ForgotPasswordViewModel
Why has `sealed` been removed?

2021-07-28 14:38 UTC, PhysicsJon commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Identity/Models/ResetPasswordViewModel.cs
> +        [Password]
What is the benefit of a Password attribute when the DataType attribute is set to Password?

2021-07-28 14:50 UTC, NickNewlands commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Identity/Models/ForgotPasswordViewModel.cs
> +    public class ForgotPasswordViewModel
That is a mistake, good catch.

2021-07-28 14:51 UTC, NickNewlands commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Identity/Models/ResetPasswordViewModel.cs
> +        [Password]
I believe this allows the input to be '******' instead of 'xyz123'.

2021-07-29 17:54 UTC, bjss-chris requested changes

2021-07-29 17:54 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Models/SolutionDetailModel.cs
> +                    Contacts.Add(new Address { Line1 = $"{contact.FirstName} {contact.LastName}", Line2 = contact.Department, Line3 = contact.PhoneNumber, Line4 = contact.Email });
The use of `Address` seems a bit odd here. If we don't have an appropriate type let's create a new one.

Also, any reason we can't use a `Select` statement here rather than the slightly odd `if` statements? (e.g. `Contacts = CatalogueItem.Solution.MarketingContacts.Select(c => new Thing(c)).ToList();`

2021-07-29 17:54 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/DFOCVC/Index.cshtml
>      ViewData["Title"] = "DFOCVC framework - results";
EN dash, '–'

2021-07-29 17:54 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/DFOCVC/Index.cshtml
>                              <a href="~/solutions/dfocvc/@solution.CatalogueItemId">
Tag helper: `<a asp-area="Solutions" asp-controller="SolutionDetails" asp-action="DVOCVCSolutionDetail" asp-route-id="@solution.CatalogueItemId">`

(At line 38 as well).

2021-07-29 17:54 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/Futures/CapabilitiesSelector.cshtml
>      ViewData["Title"] = "Catalogue Solutions on the GP IT Futures framework - Capability selector";
EN dash, '–'

2021-07-29 17:54 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/Futures/Foundation.cshtml
>      ViewData["Title"] = "Foundation Solution Sets on the GP IT Futures framework - results";
EN dash, '–'

2021-07-29 17:54 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/Futures/Foundation.cshtml
>                              <a href="~/solutions/futures/foundation/@solution.CatalogueItemId">
Tag helper, `<a asp-area="Solutions" asp-controller="SolutionDetails" asp-action="Description" asp-route-id="@solution.CatalogueItemId">`

(At line 41 as well).

2021-07-29 17:54 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/Futures/SearchResults.cshtml
>      ViewData["Title"] = "GP IT Futures framework - results";
EN dash, '–'

2021-07-29 17:54 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/Futures/SearchResults.cshtml
>                          <a href="~/solutions/futures/@solution.CatalogueItemId">
Tag helper, `<a asp-area="Solutions" asp-controller="SolutionDetails" asp-action="Description" asp-route-id="@solution.CatalogueItemId">` (same at line 49).

2021-07-29 17:54 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/SolutionDetails/HostingType.cshtml
> +    <p><strong>These are the ways this Catalogue Solution can be hosted:</strong></p>
Not yours, but 'centre' is misspelt in this view.

2021-07-29 17:54 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/SolutionDetails/SolutionDetail.cshtml
> +    @if (Model.CatalogueItem.Solution.FrameworkSolutions.Any(x => x.IsFoundation))
Can we use something other than `x` for the lambda parameter? (`fs` would be fine.)

2021-07-29 17:54 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/SolutionDetails/SolutionDetail.cshtml
> +@*Description DONE*@
What's this here for? 🤔

2021-07-29 17:54 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/SolutionDetails/SolutionDetail.cshtml
> +                                    <div data-test-id="view-question-data-link" class="bc-c-data-link ">
Is `bc-c-data-link` a valid CSS class?

2021-07-29 17:54 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/SolutionDetails/SolutionDetail.cshtml
> +@*Features DONE*@
What's this here for? 🤔

2021-07-29 17:54 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/SolutionDetails/SolutionDetail.cshtml
> +                <div data-test-id="view-features-guidance" class="bc-c-data-text bc-t-font-color--grey-1 nhsuk-u-margin-bottom-4 nhsuk-grid-column-two-thirds">This Catalogue Solution has the followin
Is `bc-c-data-text` a valid CSS class?

2021-07-29 17:54 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/SolutionDetails/SolutionDetail.cshtml
> +                <div data-test-id="view-question-data-bulletlist" class="bc-c-data-bulletlist ">
Is `bc-c-data-bulletlist` a valid CSS class?

2021-07-29 17:54 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/SolutionDetails/SolutionDetail.cshtml
> +@*Capabilities*@
Not sure this is adding much value.

2021-07-29 17:54 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/SolutionDetails/SolutionDetail.cshtml
> +@*Integrations DONE*@
Or this 😃

2021-07-29 17:54 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/SolutionDetails/SolutionDetail.cshtml
> +                                    <a href="document/integrations.pdf" target="_blank">
Tag helper, `<a asp-controller="Document" asp-action="GetDocument" asp-route-documentName="integrations.pdf" target="_blank">`

2021-07-29 17:54 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/SolutionDetails/SolutionDetail.cshtml
> +@*Implementation*@
I think all of these can go. I won't bother commenting on the rest in this view.

2021-07-29 17:54 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/SolutionDetails/SolutionDetail.cshtml
> +@*Roadmap DONE APART FROM LINK*@
A TODO comment might be better, if this still needs doing. Looking at the link (it looks dodgy to me), I suspect so.

2021-07-29 17:54 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/Vaccinations/Index.cshtml
>                          <a href="~/solutions/vaccinations/10064-004">
Tag helper, `<a asp-area="Solutions" asp-controller="SolutionDetails" asp-action="VaccinationsSolutionDetail" asp-route-id="10064-004">` 

(Same format for the others.)

2021-07-29 17:54 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Views/NominateOrganisation/Index.cshtml
> +        <vc:nhs-action-link url="mailto:buying.catalogue@nhs.net?subject=Nominate an organisation&body=To%20the%20Buying%20Catalogue%20team%2C%0A%0AI%20wish%20to%20nominate%20an%20organisation%20to%2
Should `&body` be `&amp;body`?

2021-07-29 17:54 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Views/Shared/Layouts/_AdminLayout.cshtml
>      @RenderSection("breadcrumbs", false)
Can be async, e.g. `@await RenderSectionAsync("breadcrumbs", false)`.

2021-07-30 10:29 UTC, NickNewlands commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Views/Organisations/AddUser.cshtml
> +            <p data-test-id="org-name" class="bc-c-data-text nhsuk-u-margin-bottom-9">
It is but it seems to be a very inconsistently used class, it makes the text look a bit robotic.

2021-08-01 15:23 UTC, NickNewlands commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/SolutionDetails/SolutionDetail.cshtml
> +                                    <a href="document/integrations.pdf" target="_blank">
This link looks right so I have used it but it does not work on local.

2021-08-01 15:24 UTC, NickNewlands commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/Futures/Foundation.cshtml
>                              <a href="~/solutions/futures/foundation/@solution.CatalogueItemId">
I think this link is correct and the old one wrong as this behaves similar to listing pages. Needs checking.
old link: https://localhost:5001/solutions/futures/foundation/100000-001
new link: https://localhost:5001/solutions/futures/100000-001

2021-08-01 15:26 UTC, NickNewlands commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Identity/Models/ResetPasswordViewModel.cs
> +        [Password]
I am not sure what you mean, should be done in another ticket I think,

2021-08-01 15:31 UTC, NickNewlands commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Models/SolutionDetailModel.cs
> +                    Contacts.Add(new Address { Line1 = $"{contact.FirstName} {contact.LastName}", Line2 = contact.Department, Line3 = contact.PhoneNumber, Line4 = contact.Email });
I think the use of address is fine. I have not altered the if statements.

2021-08-05 10:17 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Identity/Models/ResetPasswordViewModel.cs
> +        [Password]
Done

2021-08-05 10:19 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Views/CatalogueSolutions/HostingType.cshtml
> -<div class="nhsuk-width-container">
Done

2021-08-05 10:20 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Views/CatalogueSolutions/HostingTypeData.cshtml
Done

2021-08-05 10:21 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Views/CatalogueSolutions/Index.cshtml
> +                    <nhs-tag text="@item.PublishedStatus" colour="@GetTagColour(item)" />
Looks to have been done

2021-08-05 10:23 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Views/Shared/Layouts/_AdminLayout.cshtml
>      @RenderSection("breadcrumbs", false)
Appears to have been done

2021-08-05 10:25 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/SolutionDetails/SolutionDetail.cshtml
> +@*Roadmap DONE APART FROM LINK*@
Appears done. Shouldn't these pages be going anyway?

2021-08-05 10:25 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/SolutionDetails/SolutionDetail.cshtml
> +@*Implementation*@
Done

2021-08-05 10:30 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Views/Organisations/Create.cshtml
>                  <a data-test-id="change-org-link" href="/admin/organisations/find?ods=@Model.OdsOrganisation.OdsCode" class="nhsuk-grid-column-one-half nhsuk-u-font-size-19">Change organisation</a>
Appears to have been done. And I have tested it works

2021-08-05 10:35 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Views/Organisations/Details.cshtml
> +                <a data-test-id="edit-org-button" href="/admin/organisations/@Model.Organisation.OrganisationId/edit" class="bc-u-float-right nhsuk-u-margin-left-2">Change</a>
Appears done. I've tested it

2021-08-05 10:36 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Views/Organisations/Details.cshtml
> +        <vc:nhs-action-link url="/admin/organisations/@Model.Organisation.OrganisationId/adduser"  text="Add new user" />
Already done

2021-08-05 10:37 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Views/Organisations/Details.cshtml
> +                        <a data-test-id="user-name-@Model.Users[i].Id" href="/admin/organisations/@Model.Organisation.OrganisationId/@Model.Users[i].Id">Manage</a>
Already done. Tested it

2021-08-05 10:38 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Views/Organisations/Details.cshtml
> +            @for (int i = 0; i < Model.RelatedOrganisations.Count(); i++)
Already done

2021-08-05 10:38 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Views/Organisations/Details.cshtml
> +                        <a data-test-id="related-org-remove-@Model.RelatedOrganisations[i].OrganisationId" href="/admin/organisations/removeproxy/@Model.Organisation.OrganisationId/@Model.RelatedOrga
Already done

2021-08-05 10:39 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Views/Organisations/RemoveAnOrganisation.cshtml
>                  <a href="/admin/organisations/@Model.OrganisationId">Cancel</a>
Already done

2021-08-05 10:40 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Identity/Models/ResetPasswordViewModel.cs
>          [Compare("Password", ErrorMessage = ErrorMessages.PasswordMismatch)]
Done

2021-08-05 10:41 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Views/Organisations/AddAnOrganisation.cshtml
>      ViewData["Title"] = "Buying Catalogue - Admin";
Already done

2021-08-05 10:41 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Views/Organisations/Details.cshtml
>      ViewData["Title"] = "Buying Catalogue - Admin";
Already done

2021-08-05 10:41 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Views/Organisations/EditOrganisation.cshtml
>      ViewData["Title"] = "Buying Catalogue - Admin";
Already done

2021-08-05 10:41 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Views/Organisations/RemoveAnOrganisation.cshtml
>      ViewData["Title"] = "Buying Catalogue - Admin";
Already done

2021-08-05 10:42 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Marketing/Views/BrowserBased/AdditionalInformation.cshtml
>      ViewData["Title"] = "Browser-based application - additional information";
Already done

2021-08-05 10:42 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Marketing/Views/BrowserBased/ConnectivityAndResolution.cshtml
>      ViewData["Title"] = "Browser-based application - connectivity and resolution";
Already done

2021-08-05 10:42 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Marketing/Views/BrowserBased/HardwareRequirements.cshtml
>      ViewData["Title"] = "Browser-based application - hardware requirements";
Already done

2021-08-05 10:43 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Marketing/Views/BrowserBased/MobileFirstApproach.cshtml
>      ViewData["Title"] = "Browser based application - mobile first approach";
Done

2021-08-05 10:43 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Marketing/Views/BrowserBased/PlugInsOrExtensions.cshtml
>      ViewData["Title"] = "Browser-based application - plug-ins or extensions required";
Done

2021-08-05 10:44 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Marketing/Views/BrowserBased/SupportedBrowsers.cshtml
>      ViewData["Title"] = "Browser-based application - suppported browsers";
Done

2021-08-05 10:44 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Marketing/Views/ClientApplicationType/BrowserBased.cshtml
>      ViewData["Title"] = "Browser based application - all sections";
Done

2021-08-05 10:45 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Marketing/Views/ClientApplicationType/NativeDesktop.cshtml
>      ViewData["Title"] = "Native desktop application - all sections";
Already done

2021-08-05 10:45 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Marketing/Views/ClientApplicationType/NativeMobile.cshtml
>      ViewData["Title"] = "Native mobile or tablet application - all sections";
Already done

2021-08-05 10:46 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Marketing/Views/HostingType/Hybrid.cshtml
>      ViewData["Title"] = "Hosting type - hybrid";
Already done

2021-08-05 10:46 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Marketing/Views/HostingType/OnPremise.cshtml
>      ViewData["Title"] = "Hosting type - on premise";
Already done

2021-08-05 10:46 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Marketing/Views/HostingType/PublicCloud.cshtml
>      ViewData["Title"] = "Hosting type - public cloud";
Already done

2021-08-05 10:47 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Marketing/Views/NativeDesktop/AdditionalInformation.cshtml
>      ViewData["Title"] = "Native desktop application - additional information";
Already done

2021-08-05 10:47 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Marketing/Views/NativeDesktop/Connectivity.cshtml
>      ViewData["Title"] = "Native desktop application - connectivity";
Already done

2021-08-05 10:47 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Marketing/Views/NativeDesktop/HardwareRequirements.cshtml
>      ViewData["Title"] = "Native desktop application - hardware requirements";
Already done

2021-08-05 10:48 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Marketing/Views/NativeDesktop/MemoryAndStorage.cshtml
>      ViewData["Title"] = "Native desktop application - memory, storage, processing and resolution";
Already done

2021-08-05 10:48 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Marketing/Views/NativeDesktop/OperatingSystems.cshtml
>      ViewData["Title"] = "Native desktop application - supported operating systems";
Already done

2021-08-05 10:48 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Marketing/Views/NativeDesktop/ThirdParty.cshtml
>      ViewData["Title"] = "Native desktop application - third-party components and device capabilities";
Already done

2021-08-05 10:49 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Marketing/Views/NativeMobile/AdditionalInformation.cshtml
>      ViewData["Title"] = "Native mobile or tablet application - additional information";
Already done

2021-08-05 10:49 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Marketing/Views/NativeMobile/Connectivity.cshtml
>      ViewData["Title"] = "Native mobile or tablet application - connectivity";
Already done

2021-08-05 10:49 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Marketing/Views/NativeMobile/MemoryAndStorage.cshtml
>      ViewData["Title"] = "Native mobile or tablet application - memory and storage";
Already done

2021-08-05 10:49 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Marketing/Views/NativeMobile/MobileFirstApproach.cshtml
>      ViewData["Title"] = "Native mobile or tablet application - mobile first approach";
Already done

2021-08-05 10:49 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Marketing/Views/NativeMobile/OperatingSystems.cshtml
>      ViewData["Title"] = "Native mobile or tablet application - supported operating systems";
Already done

2021-08-05 10:49 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Marketing/Views/NativeMobile/ThirdParty.cshtml
>      ViewData["Title"] = "Native mobile or tablet application - third-party components and device capabilities";
Already done

2021-08-05 10:50 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Marketing/Views/Solution/Index.cshtml
> +    ViewData["Title"] = $"{Model.CatalogueItemName} listing page - all sections";
Already done

2021-08-05 10:50 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/DFOCVC/Index.cshtml
>      ViewData["Title"] = "DFOCVC framework - results";
Already done

2021-08-05 10:51 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/DFOCVC/Index.cshtml
>                              <a href="~/solutions/dfocvc/@solution.CatalogueItemId">
Already done

2021-08-05 10:51 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/Futures/Foundation.cshtml
>      ViewData["Title"] = "Foundation Solution Sets on the GP IT Futures framework - results";
Already done

2021-08-05 10:51 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/Futures/SearchResults.cshtml
>      ViewData["Title"] = "GP IT Futures framework - results";
Already done

2021-08-05 10:57 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/Futures/SearchResults.cshtml
>                          <a href="~/solutions/futures/@solution.CatalogueItemId">
Already done. Fixed a hard coded solution name though

2021-08-05 10:58 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/SolutionDetails/SolutionDetail.cshtml
> +    @if (Model.CatalogueItem.Solution.FrameworkSolutions.Any(x => x.IsFoundation))
Already done

2021-08-05 10:58 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Views/Vaccinations/Index.cshtml
>                          <a href="~/solutions/vaccinations/10064-004">
Already done

2021-08-05 10:59 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Views/Organisations/Details.cshtml
> +            @for (int i = 0; i < Model.Users.Count(); i++)
Already done

2021-08-05 11:48 UTC, bjss-chris requested changes
Just one additional request.

There's still some tech debt here but let's sort that separately. This PR is already too large as it is.

@MichaelRobinson-BJSS, guess you're looking into the pipeline failure?

2021-08-05 11:48 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.UI.Components/DataAttributes/PasswordAttribute.cs
> +    public class PasswordAttribute : DataTypeAttribute
`sealed`

2021-08-05 12:04 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.UI.Components/DataAttributes/PasswordAttribute.cs
> +    public class PasswordAttribute : DataTypeAttribute
Done. Looking into the pipeline failure. All the tests run locally

2021-08-05 12:10 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.UI.Components/DataAttributes/PasswordAttribute.cs
> +    public class PasswordAttribute : DataTypeAttribute
@PhysicsJon mentioned that the tests in the pipeline have started to fail intermittently – we need to look into the cause – but it could be that.

2021-08-05 13:16 UTC, bjss-chris approved these changes

2021-08-05 13:31 UTC, merged