Add E2E Test Session Handling
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #293
Opened 2021-07-30 14:07 UTC by leerogers-bjss

Add Session Handler Class to handle getting session key from session cookie and then initialise a DistributedSession.

Update LocalWebApplicationFactory to return the required services to handle session

Update Bases Classes to Handle Setting Session Values

update CatalogueSolutionSelectSolution Class to use Session Handler

2021-07-30 15:38 UTC, bjss-chris requested changes

2021-07-30 15:38 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Areas/Ordering/CatalogueSolutions/CatalogueSolutionSelectSolution.cs
> +﻿using System;
Needed?

2021-07-30 15:38 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Utils/Session/SessionHandler.cs
> +        }
Is this actually used?

2021-07-30 15:38 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Utils/Session/SessionHandler.cs
> +        }
`async/await` can be omitted here.

2021-07-30 15:38 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Utils/Session/SessionHandler.cs
> +            await Session.CommitAsync();
As above, `async/await` can be omitted here.

2021-07-30 15:38 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Utils/Session/SessionHandler.cs
> +        }
Is this used at the moment, or is the expectation that it will be required at some point?

2021-07-30 15:38 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Utils/TestBases/AuthorityTestBase.cs
> +                Task.Run(() => InitializeSessionAndSetValuesToSession()).Wait();
Can be simplified to `Task.Run(InitializeSessionAndSetValuesToSession).Wait();`.

2021-07-30 15:38 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Utils/TestBases/BuyerTestBase.cs
> +                Task.Run(() => InitializeSessionAndSetValuesToSession()).Wait();
As above, can be simplified to `Task.Run(InitializeSessionAndSetValuesToSession).Wait();`.

2021-07-30 15:38 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Utils/TestBases/TestBase.cs
> +                foreach (var entry in SessionValues)
We could use deconstruction here, e.g. `foreach (var (key, value) in SessionValues)`

2021-07-30 15:38 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Utils/TestBases/TestBase.cs
>          protected static string GenerateUrlFromMethod(
Looks like there's a few things that can be tidied up in this method but they aren't things you've changed so we can do that separately.

2021-07-30 15:51 UTC, leerogers-bjss commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Utils/Session/SessionHandler.cs
> +        }
not yet, will be used in later tests

2021-07-30 15:52 UTC, leerogers-bjss commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Utils/Session/SessionHandler.cs
> +        }
will be required in future tests for disposing

2021-07-31 12:25 UTC, bjss-chris requested changes

2021-07-31 12:25 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Utils/TestBases/AuthorityTestBase.cs
> +                InitializeSessionAndSetValuesToSession();
Thinking about this some more, this is a tad smelly.

We should avoid making calls to an `async` method in a constructor.

The best option would likely be an `async` factory method but that isn't going to work here due to the way inheritance is used.

While initialize methods can also be considered smelly, one option might be an `async InitializeSession` method that any tests that require session initialization have to call. (Feel free to suggest an alternative.)

A second constructor might be worth considering, rather than using optional parameters, perhaps something like this?

```c#
protected AuthorityTestBase(
    LocalWebApplicationFactory factory,
    string urlArea = "")
    : this(factory, urlArea, new Dictionary<string, object>())
{
}

protected AuthorityTestBase(
    LocalWebApplicationFactory factory,
    string urlArea,
    IDictionary<string, object> sessionValues)
    : base(factory, urlArea, sessionValues)
{
}
```

This would avoid the need to check whether `sessionValues` is `null`. (I've assumed session initialization is done outside the constructor in this suggestion.)

2021-07-31 12:25 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Utils/TestBases/BuyerTestBase.cs
> +                InitializeSessionAndSetValuesToSession();
As for `AuthorityTestBase`.

2021-08-02 11:55 UTC, bjss-chris requested changes

2021-08-02 11:55 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Areas/Ordering/CatalogueSolutions/CatalogueSolutionSelectSolution.cs
> +            var expectedCatalogueItemName = "E2E With Contact Multiple Prices";
`const`

2021-08-02 11:55 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Areas/Ordering/CatalogueSolutions/CatalogueSolutionSelectSolution.cs
> +            var expectedCatalogueItemName = "E2E With Contact With Single Price";
`const`

2021-08-02 11:55 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Utils/LocalWebApplicationFactory.cs
> +        }
Not essential but these could use expression body syntax:

```c#
internal IDistributedCache GetCache => host.Services.GetRequiredService<IDistributedCache>();

internal IDataProtectionProvider GetDataProtectionProvider => host.Services.GetRequiredService<IDataProtectionProvider>();

internal ILoggerFactory GetLoggerFactory => host.Services.GetRequiredService<ILoggerFactory>();
```

2021-08-02 11:55 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Utils/Session/SessionHandler.cs
> +        }
Should return `Task`.

2021-08-02 11:55 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Utils/Session/SessionHandler.cs
> +        }
Should return `Task`.

2021-08-02 11:59 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Utils/TestBases/TestBase.cs
> +                foreach (var (key, value) in sessionValues)
Will `sessionValues` every be `null`? If so, why we pass a null value?

2021-08-03 08:16 UTC, bjss-chris approved these changes

2021-08-03 08:17 UTC, merged