Edit/Save Hosting Type e2e tests implemented
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #294
Opened 2021-07-30 14:35 UTC by EnitanOO

AB#15299
AB#15961

E2E test for Go Back without saving Hosting Type is not implemented yet

2021-07-30 14:46 UTC, PhysicsJon reviewed
It looks OK to me, can you merge latest of main and make sure everything is happy then I'll approve it

2021-07-30 15:12 UTC, leerogers-bjss requested changes
found a few small issues with where things are living :)

2021-07-30 15:12 UTC, leerogers-bjss commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Actions/Marketing/HostingTypeActions.cs
> +        internal void ClickRadioButton()
as far as i can tell, this isn't being used?

2021-07-30 15:14 UTC, EnitanOO commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Actions/Marketing/HostingTypeActions.cs
> +        internal void ClickRadioButton()
will check...

2021-07-30 15:16 UTC, leerogers-bjss requested changes

2021-07-30 15:16 UTC, leerogers-bjss commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Objects/Common/CommonSelectors.cs
> +
Rename this to ActionLink or move it to a more specific SelectorClass

2021-07-30 15:16 UTC, leerogers-bjss commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Objects/Marketing/CommonSelectors.cs
> +        internal static By RadioButton => By.CssSelector(".nhsuk-radios__item");
this already exists in Objects/Common/CommonSelectors as RadioButtonItems. so unneeded

2021-07-30 15:16 UTC, leerogers-bjss commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Actions/Common/CommonActions.cs
> +            Driver.FindElement(CommonSelectors.AddHostingType).Click();
this needs to be moved out of the Actions/Common/CommonActions Class, since this isn't a generic Common action.

would suggest Actions/Admin/CommonActions.cs

2021-07-30 15:34 UTC, EnitanOO commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Actions/Marketing/HostingTypeActions.cs
> +        internal void ClickRadioButton()
Removed

2021-07-30 15:51 UTC, EnitanOO commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Objects/Common/CommonSelectors.cs
> +
Renamed to ActionLink

2021-07-30 15:59 UTC, EnitanOO commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Objects/Marketing/CommonSelectors.cs
> +        internal static By RadioButton => By.CssSelector(".nhsuk-radios__item");
Removed

2021-07-30 16:00 UTC, EnitanOO commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Actions/Common/CommonActions.cs
> +            Driver.FindElement(CommonSelectors.AddHostingType).Click();
Moved

2021-07-30 16:53 UTC, EnitanOO commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Objects/Common/CommonSelectors.cs
> +
And moved to Admin/CommonObjects/

2021-07-30 16:56 UTC, EnitanOO commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Objects/Common/CommonSelectors.cs
> +
and moved to Objects.Admin.CommonObjects

2021-08-03 10:04 UTC, leerogers-bjss approved these changes

2021-08-03 10:16 UTC, merged