Feature/15987 add im1 integration view
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #322
Opened 2021-08-11 12:16 UTC by MichaelRobinson-BJSS

2021-08-11 15:19 UTC, PhysicsJon requested changes

2021-08-11 15:19 UTC, PhysicsJon commented on tests/NHSD.GPIT.BuyingCatalogue.Services.UnitTests/Solutions/InteroperabilityServiceTests.cs
> +                .Options;
Why are we using an In Memory Db within unit tests? Surely this should be mocked instead?

2021-08-11 15:19 UTC, PhysicsJon commented on tests/NHSD.GPIT.BuyingCatalogue.Services.UnitTests/Solutions/InteroperabilityServiceTests.cs
> +                .Options;
As above

2021-08-11 15:31 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.Services.UnitTests/Solutions/InteroperabilityServiceTests.cs
> +                .Options;
Using the in-memory DB is fine. Otherwise, we'd have to use `IDbRepository<T>`  – if we do that we are just adding an unnecessary abstraction as the EF Core context already implements the repository pattern. The only thing we would gain is the ability to mock the dependency. However, we can achieve the same thing using the in-memory DB.

Rather than create the in-memory DB test per test as here, we should create a new AutoFixture customization to create the in-memory context for us. There's an example of this in ORDAPI.

2021-08-11 16:37 UTC, MichaelRobinson-BJSS commented on tests/NHSD.GPIT.BuyingCatalogue.Services.UnitTests/Solutions/InteroperabilityServiceTests.cs
> +                .Options;
Migrated the ORDAPI attribute and updated tests accordingly. Done

2021-08-11 16:37 UTC, MichaelRobinson-BJSS commented on tests/NHSD.GPIT.BuyingCatalogue.Services.UnitTests/Solutions/InteroperabilityServiceTests.cs
> +                .Options;
As above

2021-08-12 07:53 UTC, MichaelRobinson-BJSS commented on tests/NHSD.GPIT.BuyingCatalogue.Services.UnitTests/Solutions/InteroperabilityServiceTests.cs
> +            var service = new InteroperabilityService(context);
Done

2021-08-12 07:53 UTC, MichaelRobinson-BJSS commented on tests/NHSD.GPIT.BuyingCatalogue.Services.UnitTests/Solutions/InteroperabilityServiceTests.cs
> +            var service = new InteroperabilityService(context);
Done

2021-08-12 07:54 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.Framework/Constants/Interoperability.cs
> +        public const string Provider = "Provider";
Done

2021-08-12 08:05 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/InteroperabilityModels/AddIm1IntegrationModel.cs
> +            BackLink = "./";
I couldn't find a scenario where it didn't work, but I've changed it to be absolute to be on the safe side.

2021-08-12 08:11 UTC, PhysicsJon approved these changes

2021-08-12 08:20 UTC, merged