Feature/15981 add desktop app type
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #342
Opened 2021-08-18 10:51 UTC by MichaelRobinson-BJSS

2021-08-19 15:59 UTC, leerogers-bjss requested changes

2021-08-19 15:59 UTC, leerogers-bjss commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Controllers/CatalogueSolutionsController.cs
> +                    model.SelectedApplicationType.ToString(),
I'm not sure i like this ToString
The reason we moved to nameof(_controllermethod_) is so that we wouldn't be using strings as part of a redirect to action (and to keep a single point of truth for the route values)

i see what you're trying to do, but we have examples of doing if-else and switches to select different redirect to actions pointing to different controllermethods.

so i would change it to that :)

2021-08-19 15:59 UTC, leerogers-bjss commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/InteroperabilityModels/AddGpConnectIntegrationModel.cs
> +        [Required(ErrorMessage = "Select if your system is a provider or consumer")]
has this been signed off by luke?

only thing is NHS prefer simple and to the point error messages (which always seem super snarky to me) and the "Select provider or consumer" seems more inline with what they would want :)

2021-08-19 15:59 UTC, leerogers-bjss commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/InteroperabilityModels/AddIm1IntegrationModel.cs
> +        [Required(ErrorMessage = "Select if your system is a provider or consumer")]
same as above

2021-08-19 15:59 UTC, leerogers-bjss commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Views/DesktopBased/Desktop.cshtml
> +            "INCOMPLETE" => NhsTagsTagHelper.TagColour.Grey,
We're not using Incomplete anymore

the options available are:
- Complete
- Not Started
- Cannot Start Yet
- Optional
- In Progress

so this should be Not Started
Also it should be only first letter capitalised

2021-08-20 07:45 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/InteroperabilityModels/AddGpConnectIntegrationModel.cs
> +        [Required(ErrorMessage = "Select if your system is a provider or consumer")]
This is what is in the acceptance criteria and was even raised as a bug. I don't recall seeing it in the AC when I first looked at this so I initially used my own judgement which I agree appears better, but the AC is the AC. It can easily be changed later though.

2021-08-20 07:45 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/InteroperabilityModels/AddIm1IntegrationModel.cs
> +        [Required(ErrorMessage = "Select if your system is a provider or consumer")]
This is what is in the acceptance criteria and was even raised as a bug. I don't recall seeing it in the AC when I first looked at this so I initially used my own judgement which I agree appears better, but the AC is the AC. It can easily be changed later though.

2021-08-20 07:47 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Views/DesktopBased/Desktop.cshtml
> +            "INCOMPLETE" => NhsTagsTagHelper.TagColour.Grey,
Done. As per previous discussions, the other states will be dealt with in an additional story.

2021-08-20 07:48 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Controllers/CatalogueSolutionsController.cs
> +                    model.SelectedApplicationType.ToString(),
Agreed. Was just a continuation of what Neha had done.

2021-08-20 08:34 UTC, leerogers-bjss approved these changes

2021-08-20 08:38 UTC, merged