15313 - Add Supplier Management Pages
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #372
Opened 2021-09-14 16:55 UTC by leerogers-bjss

Move all Supplier Management Pages into Suppliers Controller

Add new SuppliersService for managing handling of the details

Add Models and View for Handling Supplier Management

Update FieldSetContainerTagHelper and FieldSetFormLableTagHelper to correctly not set that it can handle a field counter.

Update UpdateOutputDiv to only apply a surrounding div to a form-group if there is a counter on the field
if there is no counter, then it will set the form-group as the top level by passing on all its attributes
and then removing itself. (this is so that inputs can work with fieldset-containers).

Move supplier related logic out of SolutionsService

Move Supplier related controllers out of HomeController

Add SupplierManagement.js to handle the showing and hiding of inactive suppliers on the manage all suppliers page.

Update existing tests to reflect the new arrangement Supplier logic moving from solutionsService to SuppliersService

Update GetListFromBuyingCatalogue to only show active suppliers

Add GetAllActiveSuppliers to SuppliersService

Update AddCatalogueSolutionController to use GetAllActiveSuppliers from GetAllSuppliers.

2021-09-15 17:27 UTC, bjss-chris requested changes
Sorry about the delay. A few comments but mostly fairly small things. Good work!

2021-09-15 17:27 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Views/Shared/Layouts/_AdminLayout.cshtml
> +    @RenderSection("Scripts", false)
We can use the async version here, `@await RenderSectionAsync("Scripts", false)`.

2021-09-15 17:27 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.WebApp.UnitTests/Areas/Admin/Controllers/AddCatalogueSolutionControllerTests.cs
> +            var controller = new AddCatalogueSolutionController(mockSolutions.Object, mockService.Object);
If you freeze the service mock, we should be able to have AutoFixture instantiate the controller, e.g.

```c#
public static async Task Get_Index_SuppliersInDatabase_ReturnsViewWithExpectedModel(
    List<Supplier> suppliers,
    [Frozen] Mock<ISuppliersService> mockService,
    AddCatalogueSolutionController controller)
```

2021-09-15 17:27 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.WebApp.UnitTests/Areas/Admin/Controllers/AddCatalogueSolutionControllerTests.cs
> +            var controller = GetController(mockService, mockSuppliersService, userId);
We can probably use AutoFixture to do what this method is doing as well but might require a little further investigation so I don't mind if you leave this as is for now.

2021-09-15 17:27 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.WebApp.UnitTests/Areas/Admin/Controllers/AddCatalogueSolutionControllerTests.cs
> +            var controller = new AddCatalogueSolutionController(mockService.Object, mockSuppliersService.Object);
We can freeze the mocks and use AutoFixture to create the controller here (similar to above, although both mocks need to be frozen in this case).

2021-09-15 17:27 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.WebApp.UnitTests/Areas/Admin/Controllers/AddCatalogueSolutionControllerTests.cs
> +            var controller = new AddCatalogueSolutionController(mockService.Object, mockSuppliersService.Object);
As above, we should be able to freeze the mocks here and have AutoFixture wire up the controller.

2021-09-15 17:27 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.WebApp.UnitTests/Areas/Admin/Controllers/HomeControllerTests.cs
>  using NHSD.GPIT.BuyingCatalogue.ServiceContracts.Solutions;
Think we can remove this as well.

2021-09-15 17:29 UTC, bjss-chris commented on database/NHSD.GPITBuyingCatalogue.Database/Catalogue/Tables/Suppliers.sql
> +     [Active] BIT NOT NULL DEFAULT 0,
I did wonder if `IsActive` might be better but can't make up my mind! What do you think?

2021-09-16 08:39 UTC, leerogers-bjss commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Controllers/SuppliersController.cs
> +            }
think i'm gona stick with my version, seems like extra boiler plate 😬

2021-09-16 08:49 UTC, leerogers-bjss commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/SupplierModels/DeleteContactModel.cs
> +        public string SupplierName { get; init; }
yeah its going to be, i'm talking to luke later today about applying the supplier name to all pages as a caption (and doing the same across the admin section) so will leave it for now.

if i find out i don't need it, i'll remove as part of the testing PR

2021-09-16 08:55 UTC, leerogers-bjss commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Views/Suppliers/EditSupplier.cshtml
> +        }
mikes work will make this redundant, so will change it over once mike has it in.

2021-09-16 09:05 UTC, leerogers-bjss commented on database/NHSD.GPITBuyingCatalogue.Database/Catalogue/Tables/Suppliers.sql
> +     [Active] BIT NOT NULL DEFAULT 0,
honestly, i have no strong preference either way, epics already have a bit that does this functionality also called 'Active'. so keeping it as active would atleast be consistent.

2021-09-16 10:12 UTC, bjss-chris requested changes

2021-09-16 10:12 UTC, bjss-chris commented on database/NHSD.GPITBuyingCatalogue.Database/NHSD.GPITBuyingCatalogue.Database.refactorlog
> +</Operations>
Auto-generated file but should have a trailing new line for git.

2021-09-16 10:12 UTC, bjss-chris commented on database/NHSD.GPITBuyingCatalogue.Database/NHSD.GPITBuyingCatalogue.Database.sqlproj
> +</Project>
As above, should end with trailing new line. (Good old VS again!)

2021-09-16 10:12 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.UI.Components/Views/Shared/TagHelpers/Helpers/TagHelperBuilders.cs
> +                    if (attribute.Name.Equals("class", System.StringComparison.InvariantCultureIgnoreCase))
Could add a `using System;` to avoid having to do `System.StringComparison` here.

I'd also go with `OrdinalIgnoreCase` here.

2021-09-16 10:12 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Controllers/SuppliersController.cs
> +            && string.Equals(sc.Department.Trim(), model.Department.Trim(), StringComparison.InvariantCultureIgnoreCase));
Should be using `CurrentCultureIgnoreCase` rather than `InvariantCulture` as we're testing user input here. Admittedly, probably unlikely to make a significant difference in English but still best practice.

2021-09-16 10:12 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Views/Shared/Layouts/_AdminLayout.cshtml
> +    @RenderSectionAsync("Scripts", false)
Need an `await` here.

2021-09-16 10:12 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.WebApp.UnitTests/Areas/Admin/Controllers/AddCatalogueSolutionControllerTests.cs
>          }
Recommend using AutoFixture idioms here, e.g.:

```c#
[Fact]
public static void Constructors_VerifyGuardClauses()
{
    var fixture = new Fixture().Customize(new AutoMoqCustomization());
    var assertion = new GuardClauseAssertion(fixture);
    var constructors = typeof(AddCatalogueSolutionController).GetConstructors();

   assertion.Verify(constructors);
}
```

2021-09-16 10:12 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.WebApp.UnitTests/Areas/Admin/Controllers/HomeControllerTests.cs
> +                .Be("mapper");
As above, recommend refactoring to use AutoFixture idioms here, e.g.:

```c#
[Fact]
public static void Constructors_VerifyGuardClauses()
{
    var fixture = new Fixture().Customize(new AutoMoqCustomization());
    var assertion = new GuardClauseAssertion(fixture);
    var constructors = typeof(HomeController).GetConstructors();

   assertion.Verify(constructors);
}
```

2021-09-16 10:58 UTC, bjss-chris approved these changes

2021-09-16 11:12 UTC, merged