Add the List Price index page
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #378
Opened 2021-09-17 14:47 UTC by bjss-colin

Add unit tests for ListPrice Index

Add boilerplate E2E tests

Add Element and Go Back e2e tests

Added:
Selector for the Continue link

The ManageListPrices automated test class to validate that
* All sections are displayed correctly
* Clicking the Go back button returns the user to the Manage Catalogue Solution page

2021-09-17 15:12 UTC, PhysicsJon requested changes
In addition to the comments added, I'm not a fan of the unit tests for class decorated. They don't really test anything functionally and we are going to be removing them from all test classes at some point in the near future

2021-09-17 15:12 UTC, PhysicsJon commented on src/NHSD.GPIT.BuyingCatalogue.EntityFramework/Catalogue/Models/CataloguePrice.Custom.cs
> +}
I'm not sure just how much value this brings. The catalogue should only be working on £ sterling for the foreseeable future and is unlikely to shift away from that

2021-09-17 15:12 UTC, PhysicsJon commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Objects/Common/CommonSelectors.cs
> +        internal static By ContinueLink => By.LinkText("Continue");
Is there a better selector than LinkText? This will break if the content changes in the future

2021-09-17 15:13 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.EntityFramework/Catalogue/Models/CataloguePrice.Custom.cs
> +}
I've removed this locally as it's failed build failures anyway. Just running all tests to confirm the removal hasn't damaged anything.

2021-09-17 15:24 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.EntityFramework/Catalogue/Models/CataloguePrice.Custom.cs
> +}
Done

2021-09-17 15:24 UTC, bjss-colin commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Objects/Common/CommonSelectors.cs
> +        internal static By ContinueLink => By.LinkText("Continue");
Changed to use `By.ClassName`

2021-09-17 17:56 UTC, leerogers-bjss requested changes

2021-09-17 17:56 UTC, leerogers-bjss commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Areas/Admin/ManageListPrices.cs
> +}
you're missing an E2E test for what happens if you click the continue button

2021-09-17 17:56 UTC, leerogers-bjss commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Areas/Admin/ManageListPrices.cs
> +                .BeTrue();
need a check here for if the table has displayed. easier way would be to stick a data-test-id on the top of the table and reference it here.

2021-09-17 17:56 UTC, leerogers-bjss commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Views/CatalogueSolutions/ManageCatalogueSolution.cshtml
> +                    <nhs-table-cell><a asp-controller="@typeof(ListPriceController).ControllerName()"
very silly one, but the anchor tag should be nested inside the table cell on a new line. just makes it easier to read

2021-09-18 16:55 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Views/CatalogueSolutions/ManageCatalogueSolution.cshtml
> +                    <nhs-table-cell><a asp-controller="@typeof(ListPriceController).ControllerName()"
Good point, I've updated the formatting.

2021-09-18 16:56 UTC, bjss-colin commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Areas/Admin/ManageListPrices.cs
> +                .BeTrue();
Updated the existing tests to include the existence and display of the table

2021-09-18 16:57 UTC, bjss-colin commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Areas/Admin/ManageListPrices.cs
> +}
I've added a test for the continue button but discovered that Selenium doesn't behave as expected when using `By.ClassName` with links. To work around this I've reintroduced the `By.LinkText` method and have moved the `By` objects, for the list price page, to their own `ManageListPriceObjects` class.

2021-09-20 08:53 UTC, PhysicsJon approved these changes

2021-09-20 09:13 UTC, merged