Add ability to add, edit and delete list prices
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #384
Opened 2021-09-22 12:42 UTC by bjss-colin

Add, Edit and Delete List Price functionality added
Database Schema updated to add Pricing Unit Definition and increase Description length

Due to the NHS Design Spec, the Add/Edit List Price page uses two drop down lists to capture the Time Unit that assign to two different properties on the model, these are for the `ProvisioningType.Declarative` and `ProvisioningType.OnDemand` time units.

Known issues, having a second pair of eyes cast over these would be good.
1. When the user fails validation on the Add List Price view, the conditional time unit select list, for the respective provisioning type, does not reappear.
2. When the user edits a list price, the conditional time unit select list, for the respective provisioning type, does not appear.
I'll see if I can solve this with the use of `aria-hidden` or any such tags.

2021-09-23 14:25 UTC, bjss-chris requested changes
Apologies about the slow review but there's quite a lot going on here! 😃

2021-09-23 14:25 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/ListPriceModels/EditListPriceModel.cs
> +        }
I'm not sure we need all of this (around the unit description and...

I think we can probably drop `Name` (see earlier comment).

I'd also skip setting `TierName` as I think this will likely change once tiered pricing is properly implemented.

As we're essentially allowing suppliers a free-for-all with the description I don't know if we need to add the `per`, although it's probably not a bad idea. However, I'm just thinking we have no idea what a supplier might enter even though I'd be surprised if there might be any units that aren't going to 'per [something]'...

2021-09-23 14:25 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/ListPriceModels/EditListPriceModel.cs
> +                : OnDemandTimeUnit.Value;
Could `DeclarativeTimeUnit` or `OnDemandTimeUnit` ever be `null`?

2021-09-23 14:25 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/ListPriceModels/EditListPriceModel.cs
> +        }
We can simplify this to `public bool TryParsePrice(out decimal price) => decimal.TryParse(Price, out price);`.

Also thinking it might be best to specify the number styles and culture explicitly, so

```c#
public bool TryParsePrice(out decimal price) => decimal.TryParse(Price, NumberStyles.Currency, CultureInfo.CurrentCulture, out price);
```

2021-09-23 14:25 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Views/ListPrice/EditListPrice.cshtml
> +                        SelectListItem[] provisioningTypes = new SelectList(Model.ProvisioningTypeListItems, "Value", "Text").ToArray();
We can use `var` here. Generally tend to prefer `ToList` over `ToArray` (as it's slightly more efficient, not that it will make a noticeable difference here).

2021-09-23 14:25 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Views/ListPrice/EditListPrice.cshtml
> +                        SelectList timeUnitsSelectList = new SelectList(Model.TimeUnitSelectListItems, "Value", "Text");
Can also use `var` here.

2021-09-23 14:25 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Areas/Admin/ListPrices/DeleteListPrice.cs
> +using Microsoft.EntityFrameworkCore;
Do we need this one?

2021-09-23 14:25 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Areas/Admin/ListPrices/DeleteListPrice.cs
> +using NHSD.GPIT.BuyingCatalogue.EntityFramework.Catalogue.Models;
Or this one?

2021-09-23 14:25 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Areas/Admin/ListPrices/EditListPrice.cs
> +using System.Linq;
Do we need this one?

2021-09-23 14:25 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Areas/Admin/ListPrices/EditListPrice.cs
> +            var price = 52.3M;
Can be `const`.

2021-09-23 14:25 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Objects/Admin/ListPricesObjects.cs
> +        internal static By UnitSummaryERror => By.Id("Unit-error");
Typo, should be `UnitSummaryError`.

2021-09-23 14:25 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.WebApp.UnitTests/Areas/Admin/Models/ListPriceModels/EditListPriceModelTests.cs
> +                Price = expectedPrice.ToString(),
Probably best to specify `CultureInfo.CurrentCulture` explicitly here (to match what I've suggested we do in `TryParsePrice`. If I remember correctly, current culture is the default but not a bad thing to specify it explicitly.

2021-09-23 14:25 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.WebApp.UnitTests/Areas/Admin/Models/ListPriceModels/EditListPriceModelTests.cs
> +        public static void TryParsePrice_WithInalidPrice_DoesNotParse(
Typo in method name, should be `TryParsePrice_WithInvalidPrice_DoesNotParse`.

2021-09-23 15:41 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/ListPriceModels/EditListPriceModel.cs
> +        }
Prepending "per" was added based on a discussion between Jon, Lee and myself. To keep things simple, I have removed it in the latest changes. If this becomes an issue in the future then we could look to reintroduce this logic.

2021-09-23 16:46 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/ListPriceModels/EditListPriceModel.cs
> +                : OnDemandTimeUnit.Value;
Both can be null but validation in the controller _should_ prevent this code from being hit. I'm wondering what the validation logic here should be. Defaulting wouldn't be acceptable as it influences billing. Maybe throwing an exception, or returning null, and validating again in the controller?

2021-09-23 16:47 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.UI.Components.WebApp/Models/RadioListModel.cs
> +        public string SelectedConditionalItem { get; set; }
Left alone for now as this is just the UI Component/Tag Helper code sample project.

2021-09-24 09:18 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Controllers/ListPriceController.cs
> +        }
Validator is now in place and has also influenced some other changes with the model to clean it up.

2021-09-24 09:19 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/ListPriceModels/EditListPriceModel.cs
> +                : OnDemandTimeUnit.Value;
Updated logic to be less exception-prone.

2021-09-24 11:47 UTC, bjss-chris requested changes

2021-09-24 11:47 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/ListPriceModels/EditListPriceModel.cs
> +            return null;
We can use a switch expression here.

```c#
return provisioningType switch
{
    ProvisioningType.Patient => TimeUnit.PerYear,
    ProvisioningType.Declarative when DeclarativeTimeUnit.HasValue => DeclarativeTimeUnit.Value,
    ProvisioningType.OnDemand when OnDemandTimeUnit.HasValue => OnDemandTimeUnit.Value,
    _ => null,
};
```

2021-09-24 11:47 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Validators/EditListPriceModelValidator.cs
> +        internal const string TimeUnitErrorMessage = "A time unit must be specified.";
Use in unit test?

2021-09-24 11:47 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Validators/EditListPriceModelValidator.cs
> +                  && cp.ProvisioningType == model.SelectedProvisioningType.Value
Similar to above, might be worth using `!` here.

```c#
&& cp.ProvisioningType == model.SelectedProvisioningType!.Value
```

2021-09-24 12:26 UTC, bjss-chris approved these changes

2021-09-24 12:26 UTC, bjss-chris commented
Good work 👍

2021-09-24 12:58 UTC, merged