Feature/15028 add edit associated service
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #402
Opened 2021-09-28 13:15 UTC by MichaelRobinson-BJSS

2021-09-28 13:45 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Controllers/AssociatedServicesController.cs
> +        [HttpGet("edit-associated-service/{associatedServiceId}")]
Not sure if we have an explicit URL convention. In some places it's more of a RESTful resource based implementation, like `{associatedServiceId}/edit-associated-service`.

2021-09-29 15:06 UTC, bjss-chris requested changes

2021-09-29 15:06 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.Test.Framework/SharedMocks/MockHttpSession.cs
> +            }
`else` is unnecessary here, we could just do

```c#
value = null;
return false;
```

Also, might this work as an alternative implementation?

```c#
public bool TryGetValue(string key, out byte[] value)
{
    value = sessionStorage.GetValueOrDefault(key);
    return value is not null;
}
```

2021-09-29 15:11 UTC, bjss-colin commented on tests/NHSD.GPIT.BuyingCatalogue.Test.Framework/SharedMocks/MockHttpSession.cs
> +            }
Could go one step further as `Dictionary<TKey, TValue>` also has a `TryGetValue` method

```csharp
public bool TryGetValue(string key, out byte[] value) => sessionStorage.TryGetValue(key, out value);
```

2021-09-30 09:03 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Controllers/AssociatedServicesController.cs
> +        [HttpGet("edit-associated-service/{associatedServiceId}")]
Done

2021-09-30 09:07 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.Framework/Extensions/SolutionExtensions.cs
> +            return JsonSerializer.Deserialize<ClientApplication>(solution.ClientApplication);
There are a lot of instances that this should be applied to. I was planning a separate PR to remove the remaining Newtonsoft references and I will fix this issue at the same time if that's ok.

2021-09-30 09:07 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.Framework/Extensions/SolutionExtensions.cs
> +            : JsonSerializer.Deserialize<string[]>(solution.Features);
As above

2021-09-30 09:08 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.Services/Orders/OrderService.cs
> +            var orderingParty = await dbContext.Organisations.SingleAsync(x => x.OdsCode == odsCode);
Done. I only said you had almost cured me!

2021-09-30 09:09 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.Framework/Extensions/SolutionExtensions.cs
> +            return JsonSerializer.Deserialize<List<Integration>>(solution.Integrations);
As above

2021-09-30 09:10 UTC, MichaelRobinson-BJSS commented on tests/NHSD.GPIT.BuyingCatalogue.Services.UnitTests/Orders/OrderItemServiceTests.cs
> +            updatedOrder.OrderItems.Should().Contain(x => x.CatalogueItemId == orderItem3.CatalogueItemId);
Done

2021-09-30 09:11 UTC, MichaelRobinson-BJSS commented on tests/NHSD.GPIT.BuyingCatalogue.Test.Framework/SharedMocks/MockHttpSession.cs
> +            }
Done

2021-09-30 09:13 UTC, MichaelRobinson-BJSS commented on tests/NHSD.GPIT.BuyingCatalogue.WebApp.UnitTests/Areas/Admin/Models/AddAnOrganisationModelTests.cs
> +            actual.SelectedOrganisation.Should().Be(default(int));
Done

2021-09-30 09:14 UTC, MichaelRobinson-BJSS commented on tests/NHSD.GPIT.BuyingCatalogue.Framework.UnitTests/Constants/SelectListsTests.cs
> +                    new SelectListItem { Text = "16GB or higher", Value = "16GB or higher" },
Done

2021-09-30 09:15 UTC, MichaelRobinson-BJSS commented on tests/NHSD.GPIT.BuyingCatalogue.Framework.UnitTests/Extensions/TypeExtensionsTests.cs
> +        internal static class TestControllerNoAttribute
Done

2021-09-30 09:17 UTC, MichaelRobinson-BJSS commented on tests/NHSD.GPIT.BuyingCatalogue.Services.UnitTests/Orders/OrderItemServiceTests.cs
> +using Microsoft.EntityFrameworkCore;
No, but for some strange reason Visual Studio isn't pointing that one out to me.

2021-09-30 09:20 UTC, MichaelRobinson-BJSS commented on tests/NHSD.GPIT.BuyingCatalogue.Services.UnitTests/Orders/OrderItemServiceTests.cs
> +            var updatedOrder = await context.Orders.AsAsyncEnumerable().FirstOrDefaultAsync();
It was in due to a type clash, but that clash appears to be due to the 'using Microsoft.EntityFramework' which probably explains why VS was not highlighting that using statement as redundant. Removing that using statement has resolved the clash so I have removed AsAsyncEnumerable now.

2021-09-30 09:21 UTC, MichaelRobinson-BJSS commented on tests/NHSD.GPIT.BuyingCatalogue.Services.UnitTests/Orders/OrderItemServiceTests.cs
> +            updatedOrder.OrderItems.Should().Contain(x => x.CatalogueItemId == orderItem1.CatalogueItemId);
Done

2021-09-30 09:22 UTC, MichaelRobinson-BJSS commented on tests/NHSD.GPIT.BuyingCatalogue.Services.UnitTests/Orders/OrderItemServiceTests.cs
> +            updatedOrder.OrderItems.Should().NotContain(x => x.CatalogueItemId == orderItem.CatalogueItemId);
Done

2021-09-30 09:39 UTC, bjss-chris approved these changes

2021-09-30 09:56 UTC, merged