Add in remediation status warnings
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #408
Opened 2021-09-29 14:02 UTC by PhysicsJon

Add component to layout - _Note: This is pending the official content for the notice_
Add tests to cover this in E2E framework
Fix bug on Features page

2021-09-29 15:32 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Models/SolutionDisplayBaseModel.cs
> +        public PublicationStatus PublicationStatus { get; set; }
This can go back to `get` only now can't it?

2021-09-29 15:32 UTC, bjss-chris commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Actions/Common/CommonActions.cs
> +        }
What's the plan here?

2021-09-29 15:37 UTC, PhysicsJon commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Models/SolutionDisplayBaseModel.cs
> +        public PublicationStatus PublicationStatus { get; set; }
Set to `init`

2021-09-29 15:37 UTC, PhysicsJon commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Actions/Common/CommonActions.cs
> +        }
This has been removed

2021-09-29 16:09 UTC, bjss-colin requested changes

2021-09-29 16:09 UTC, bjss-colin commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Areas/PublicBrowse/Solution/SolutionDescription.cs
> +        public void Dispose()
Is this an overhang from local testing?

2021-09-29 16:09 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Views/Shared/Layouts/_SolutionsLayout.cshtml
> +                                      next-subtext="@Model.PaginationFooter?.Next?.Name"
Formatting has gone a bit iffy

2021-09-29 16:09 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Views/Shared/Layouts/_SolutionsLayout.cshtml
> +                        new
This could probably be done in a single line

2021-09-29 16:09 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Views/Shared/Layouts/_SolutionsLayout.cshtml
> +                        new
Could be done on a single line

2021-09-30 09:45 UTC, bjss-chris commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Models/SolutionDisplayBaseModel.cs
> +        public PublicationStatus PublicationStatus { get; init; }
I still feel this should be `get` only as the `init` is only included for the unit test, if I remember correctly?

2021-09-30 10:05 UTC, bjss-chris approved these changes

2021-09-30 10:48 UTC, bjss-colin approved these changes

2021-09-30 10:48 UTC, merged