Add publication status automated tests
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #416
Opened 2021-09-30 16:52 UTC by bjss-colin

2021-09-30 17:05 UTC, PhysicsJon requested changes

2021-09-30 17:05 UTC, PhysicsJon commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Areas/Admin/ManageCatalogueSolution.cs
> +            await using (var context = GetEndToEndDbContext())
You can simplify the using statement here (see above test)

2021-09-30 17:05 UTC, PhysicsJon commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Areas/Admin/ManageCatalogueSolution.cs
> +                var publishedStatus = (await context.CatalogueItems.SingleAsync(c => c.Id == SolutionId)).PublishedStatus;
as above

2021-09-30 17:05 UTC, PhysicsJon commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Areas/Admin/ManageCatalogueSolution.cs
> +                    .Should()
Indentation has gone a bit weird

2021-10-01 08:28 UTC, bjss-colin commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Areas/Admin/ManageCatalogueSolution.cs
> +            await using (var context = GetEndToEndDbContext())
The reason for this is because it's used twice in the same test to confirm the publication status is being set when the user clicks save.

2021-10-01 08:39 UTC, PhysicsJon commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Areas/Admin/ManageCatalogueSolution.cs
> +            await using (var context = GetEndToEndDbContext())
if you just do `await using var context = GetEndToEndDbContext();` it stays open until all calls are completed then disposes of the context. You don't need to initialize it again

2021-10-01 08:52 UTC, bjss-colin commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Areas/Admin/ManageCatalogueSolution.cs
> +            await using (var context = GetEndToEndDbContext())
Introduced a new variable. Entity Framework was caching `CatalogueItem` on the first query which is why the context was being disposed as soon as it finished, and also to re-use the same variable name.

2021-10-01 08:53 UTC, PhysicsJon requested changes

2021-10-01 08:53 UTC, PhysicsJon commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Areas/Admin/ManageCatalogueSolution.cs
> +            await using var updatedContext = GetEndToEndDbContext();
you can remove this line and set the below calls to context as it still reads from the db regardless of any external updates via the application

2021-10-01 09:01 UTC, bjss-colin commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Areas/Admin/ManageCatalogueSolution.cs
> +            await using var updatedContext = GetEndToEndDbContext();
That's not the case here. When using `context` in the second instance it returns the Draft Publication Status from the beginning of the test rather than fetching the value that was updated in the application.

![image](https://user-images.githubusercontent.com/90630744/135594084-283abd3e-5929-4938-b196-707bf75ed6db.png)

The context needs to be disposed of and recreated for it to retrieve the actual value from the data store and not the cache.

2021-10-01 09:06 UTC, PhysicsJon commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Areas/Admin/ManageCatalogueSolution.cs
> +            await using var updatedContext = GetEndToEndDbContext();
Fair, I'm going to investigate further about this as it doesn't seem right.

2021-10-01 09:06 UTC, PhysicsJon approved these changes

2021-10-01 09:13 UTC, bjss-colin commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Areas/Admin/ManageCatalogueSolution.cs
> +            await using var updatedContext = GetEndToEndDbContext();
There's some [more info here](https://stackoverflow.com/a/68268995/5062791) with one way on how to disable that behaviour

2021-10-01 09:39 UTC, merged