Update Content
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #488
Opened 2021-11-04 15:44 UTC by leerogers-bjss

Sat down with luke and done a full content sweep

lots of updates to spelling and rewriting of some bad content.

will need a second pass

2021-11-04 15:57 UTC, bjss-colin requested changes

2021-11-04 15:57 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Views/ListPrice/EditListPrice.cshtml
> +                                    label-hint="Select the billing period for this list price." />
Does this need to he ported over to the Additional and Associated Services list price pages?

2021-11-04 17:07 UTC, bjss-colin requested changes

2021-11-04 17:07 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.EntityFramework/Catalogue/Models/PublicationStatus.cs
>      public enum PublicationStatus
Looks like these will change wording of the Publication Status list on Solution, Associated Service and Additional Service management pages

2021-11-09 09:33 UTC, leerogers-bjss commented on src/NHSD.GPIT.BuyingCatalogue.EntityFramework/Catalogue/Models/PublicationStatus.cs
>      public enum PublicationStatus
this is intentional

2021-11-09 09:38 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Views/ListPrice/EditListPrice.cshtml
> +                                    label-hint="Select the billing period for this list price." />
Views are duplicated at the moment for additional and associated services. We essentially have 3x3 cshtml files for list prices.

Haven't yet gotten around to making them generic.

2021-11-09 12:54 UTC, leerogers-bjss commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Views/ListPrice/EditListPrice.cshtml
> +                                    label-hint="Select the billing period for this list price." />
done that

2021-11-09 15:41 UTC, merged