Remove unneeded "Go back" and "Save and Continue" content
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #506
Opened 2021-11-10 17:26 UTC by leerogers-bjss

Remove all unneeded setting of "Go back" LinkText

Remove all unneeded setting of "Save and Continue" Submit Button text.

Remove testing for "Go back" and "./" from unit tests that don't need them

Update RoadMapModel.cs, RoadMap.cshtml and controllers to set the go back url using Url.Action

Update RoadMapModel.cs to use constructors to set values instead of random functions.

Update FeaturesModel.cs, Features.cshtml and controllers to set the go back url using Url.Action.

Update FeatuesModel.cs to use constructor instead of random functions to set values

Update SolutionCheckEpicsModel.cs, Capabilities.cshtml, AdditionalCapabilities.cshtml and controllers to set go back url using Url.Action

Update tests for FeaturesModel.cs and RoadMapModel.cs to take into account the use of constructors.

2021-11-10 17:43 UTC, bjss-colin requested changes

2021-11-10 17:43 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Models/SolutionCheckEpicsModel.cs
> +    public sealed class SolutionCheckEpicsModel : NavBaseModel, INoNavModel
Should `INoNavModel` be removed? Otherwise it reads as being a nav model, but not being one at the same time.

2021-11-10 17:44 UTC, leerogers-bjss commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Solutions/Models/SolutionCheckEpicsModel.cs
> +    public sealed class SolutionCheckEpicsModel : NavBaseModel, INoNavModel
yeah we need to keep it since INoNavModel has some weird fields that need to be set for the marketing page.

This wasn't named by myself.

2021-11-11 08:45 UTC, PhysicsJon approved these changes
Other than renaming the No Nav interface, it looks good

2021-11-11 09:08 UTC, bjss-colin approved these changes
As Jon said, we should probably rename `INoNavModel` interface at some point

2021-11-11 09:26 UTC, merged