16476: Edit/delete IM1 integration
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #514
Opened 2021-11-12 14:46 UTC by PhysicsJon

E2E tests to follow in another PR

2021-11-12 15:56 UTC, leerogers-bjss requested changes
looks good expect for these points.
i'm guessing you'll add E2E tests next?

2021-11-12 15:56 UTC, leerogers-bjss commented on src/NHSD.GPIT.BuyingCatalogue.Services/Solutions/InteroperabilityService.cs
> +            var solution = await dbContext.Solutions.SingleAsync(s => s.CatalogueItemId == solutionId);
should be SingleOrDefault incase a solutionId is input that doesn't exist

2021-11-12 15:56 UTC, leerogers-bjss commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Controllers/InteroperabilityController.cs
> +            var solution = await solutionsService.GetSolution(solutionId);
need to do ModelState.isValid check in this post method

2021-11-12 15:56 UTC, leerogers-bjss commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Views/Interoperability/AddEditIm1Integration.cshtml
> +                <nhs-submit-button text="Save and continue" />
dont need to add this text for submit buttons, it defaults to "Save and continue"

2021-11-12 15:56 UTC, leerogers-bjss commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Views/Interoperability/Interoperability.cshtml
> +                                    <a asp-action="EditIm1Integration" asp-controller="Interoperability"
controller on its own line please :)

2021-11-12 16:01 UTC, leerogers-bjss requested changes
another one i found

2021-11-12 16:01 UTC, leerogers-bjss commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/InteroperabilityModels/DeleteIntegrationModel.cs
> +            BackLink = $"/admin/catalogue-solutions/manage/{solution.Id}/interoperability";
backlink needs to be set with Url.Action in the controller. please don't use strings in the model.

2021-11-12 16:01 UTC, PhysicsJon commented on src/NHSD.GPIT.BuyingCatalogue.Services/Solutions/InteroperabilityService.cs
> +            var solution = await dbContext.Solutions.SingleAsync(s => s.CatalogueItemId == solutionId);
Also added a null check on the following line in case of null solution

2021-11-12 16:03 UTC, PhysicsJon commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/InteroperabilityModels/DeleteIntegrationModel.cs
> +            BackLink = $"/admin/catalogue-solutions/manage/{solution.Id}/interoperability";
This was done like this to keep consistency in the interoperablity models, I would be happy to raise these issues as tech debt to fix at a later point

2021-11-12 16:19 UTC, PhysicsJon commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/InteroperabilityModels/DeleteIntegrationModel.cs
> +            BackLink = $"/admin/catalogue-solutions/manage/{solution.Id}/interoperability";
updated

2021-11-12 16:26 UTC, leerogers-bjss submitted a review, later dismissed

2021-11-15 09:36 UTC, leerogers-bjss approved these changes

2021-11-15 09:36 UTC, merged