Feature/17398 type1 sla
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #516
Opened 2021-11-12 17:06 UTC by MichaelRobinson-BJSS

Add confirmation page when user changes type of sla
Default sla hours and levels when Type 1 selected

2021-11-12 17:17 UTC, leerogers-bjss requested changes
just one minor change and a note for future :)

2021-11-12 17:17 UTC, leerogers-bjss commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Views/ServiceLevelAgreements/EditServiceLevelAgreementTypeConfirmation.cshtml
> +                    <nhs-submit-button text="Save and continue" />
don't need to set this value since the button will default to it

2021-11-12 17:17 UTC, leerogers-bjss commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Areas/Admin/AddNewSolution/ServiceLevelAgreements/EditSlaTypeConfirmation.cs
> +            CommonActions.ElementIsDisplayed(CommonSelectors.SubmitButton).Should().BeTrue();
a note for future, there is a CommonActions.SaveButtonDisplayed that can cover this scenario

2021-11-12 17:25 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Views/ServiceLevelAgreements/EditServiceLevelAgreementTypeConfirmation.cshtml
> +                    <nhs-submit-button text="Save and continue" />
Done

2021-11-12 17:25 UTC, MichaelRobinson-BJSS commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Areas/Admin/AddNewSolution/ServiceLevelAgreements/EditSlaTypeConfirmation.cs
> +            CommonActions.ElementIsDisplayed(CommonSelectors.SubmitButton).Should().BeTrue();
Ok, noted

2021-11-15 09:38 UTC, bjss-colin approved these changes

2021-11-15 10:00 UTC, leerogers-bjss approved these changes

2021-11-15 10:14 UTC, merged