SPIKE: 19020: Import GP Practice List
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #618
Opened 2022-01-11 15:02 UTC by magnusjohnbjss

2022-01-12 09:46 UTC, leerogers-bjss requested changes
just a few questions and comments

2022-01-12 09:46 UTC, leerogers-bjss commented on database/NHSD.GPITBuyingCatalogue.Database/Organisations/Tables/GpPracticeSize.sql
> +	[ExtractDate] DATETIME2 NOT NULL
sounds silly, but can these be aligned?

2022-01-12 09:46 UTC, leerogers-bjss commented on src/NHSD.GPIT.BuyingCatalogue.ServiceContracts/Organisations/GpPractice.cs
> +    public sealed class GpPractice
is the captialisation to underscore naming convention required to extract from the csv?

2022-01-12 09:46 UTC, leerogers-bjss commented on src/NHSD.GPIT.BuyingCatalogue.EntityFramework/Organisations/Configuration/GpPracticeSizeEntityTypeConfiguration.cs
> +            builder.Property(g => g.CcgCode).IsRequired().HasMaxLength(10);
do we require the ccg code? I thought this was supposed to be just the service recipients ODS code and their practice size. any advantage tying it to the CCG when they might move?

2022-01-12 09:46 UTC, leerogers-bjss commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/ImportModels/ImportGpPracticeListModel.cs
> +        [Required(ErrorMessage = "CSV url required")]
the only validation attribute we use it string length because its required by the front end UI.

everything else should be handled by FluentValidation.

2022-01-12 09:53 UTC, magnusjohnbjss commented on src/NHSD.GPIT.BuyingCatalogue.EntityFramework/Organisations/Configuration/GpPracticeSizeEntityTypeConfiguration.cs
> +            builder.Property(g => g.CcgCode).IsRequired().HasMaxLength(10);
nope, thought it might be useful for validation purposes if there are queries about ccg codes when mergers / boundary changes occur but can remove

2022-01-12 09:53 UTC, magnusjohnbjss commented on src/NHSD.GPIT.BuyingCatalogue.ServiceContracts/Organisations/GpPractice.cs
> +    public sealed class GpPractice
yup, that's how the fields come from the source

2022-01-12 09:56 UTC, magnusjohnbjss commented on database/NHSD.GPITBuyingCatalogue.Database/Organisations/Tables/GpPracticeSize.sql
> +	[ExtractDate] DATETIME2 NOT NULL
thought they were, not sure why it's come through like that, will take a look

2022-01-12 12:17 UTC, leerogers-bjss commented on database/NHSD.GPITBuyingCatalogue.Database/Organisations/Tables/GpPracticeSize.sql
> +	[ExtractDate] DATETIME2 NOT NULL
yeah its just github, you just need to tab all the rows back and then tab them all up. its a bit silly

2022-01-13 09:29 UTC, magnusjohnbjss commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/ImportModels/ImportGpPracticeListModel.cs
> +        [Required(ErrorMessage = "CSV url required")]
is this right? we've got 50+ instances of Required attributes in the web models. i've created a fluent handler to properly handle the url validation, tho

2022-01-14 09:12 UTC, MichaelRobinson-BJSS commented on src/NHSD.GPIT.BuyingCatalogue.Services/Organisations/GpPracticeCache.cs
> +        private Dictionary<string, int> gpPracticeSizes;
I'd prefer we used IMemoryCache instead of a singleton. Look at FilterCache for an example

2022-02-22 09:37 UTC, closed without merging