Request an account form
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #629
Opened 2022-01-19 09:08 UTC by magnusjohnbjss

2022-01-19 09:19 UTC, bjss-colin reviewed
One minor comment/suggestion. All else looks good

2022-01-19 09:19 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Identity/Models/Registration/RegistrationDetailsViewModel.cs
> +        [EmailAddress(ErrorMessage = "Enter an email address in the correct format, like name@example.com")]
Unless there's a dependency on the `EmailAddressAttribute`, this too could live in FluentValidation

```csharp
RuleFor(x => x.EmailAddress)
    .NotEmpty()
    .WithMessage(EmailAddressErrorMessage)
    .EmailAddress()
    .WithMessage("Enter an email address in the correct format, like name@example.com");
```

2022-01-19 11:01 UTC, magnusjohnbjss commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Identity/Models/Registration/RegistrationDetailsViewModel.cs
> +        [EmailAddress(ErrorMessage = "Enter an email address in the correct format, like name@example.com")]
This needs a dedicated email validator, as it's validating the a@b.com format rather than the field being populated. As the fluent validation is part of another ticket I assumed this validator was in the pipeline so will switch over once that's merged.

2022-01-19 12:59 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Identity/Models/Registration/RegistrationDetailsViewModel.cs
> +        [EmailAddress(ErrorMessage = "Enter an email address in the correct format, like name@example.com")]
The sample above should validate for `a@b.com` format in the same fashion that ASP.NET Core's DataAnnotations do.

Any present or future code should include the correct validators behavior by default as the tech debt tasks are for migrating past implementations to our new approach.

2022-01-20 17:53 UTC, magnusjohn-bjss commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Identity/Models/Registration/RegistrationDetailsViewModel.cs
> +        [EmailAddress(ErrorMessage = "Enter an email address in the correct format, like name@example.com")]
Mea culpa, hadn't seen the existing `.EmailAddress()` validator, fixed now

2022-02-08 13:03 UTC, leerogers-bjss requested changes
just two minor changes

2022-02-08 13:03 UTC, leerogers-bjss commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Identity/Views/Account/Login.cshtml
> +                <a data-test-id="request-account-link" asp-controller="Registration" asp-action="Index">
needs name of and typeof for controller and action

2022-02-08 13:19 UTC, bjss-colin requested changes

2022-02-08 13:19 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.Services/Identity/RequestAccountService.cs
> +            await emailService.SendEmailAsync(request.EmailAddress, settings.UserTemplateId, null);
Wrap both in an `await Task.WhenAll(Task1, Task2)` to run in parallel

2022-02-08 13:19 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.Services/Identity/RequestAccountService.cs
> +            var userResearchConsent = request.HasGivenUserResearchConsent
There's an extension method, for bools, called `ToYesNo()`. That could work here.

2022-02-08 15:56 UTC, bjss-colin approved these changes

2022-02-08 16:17 UTC, leerogers-bjss requested changes
Unit tests for the RegistrationDetailsModelValidator?

2022-02-08 16:38 UTC, bjss-colin approved these changes

2022-02-08 16:50 UTC, merged