Add table to depict which solutions reference an assoc service
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #645
Opened 2022-01-24 12:07 UTC by bjss-colin

2022-01-24 12:15 UTC, leerogers-bjss requested changes

2022-01-24 12:15 UTC, leerogers-bjss commented on src/NHSD.GPIT.BuyingCatalogue.Services/AssociatedServices/AssociatedServicesService.cs
> +                .Include(ssa => ssa.CatalogueItem)
don't need to have an include to be able to select an item, the select handles this scenario

2022-01-24 12:15 UTC, leerogers-bjss commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/AssociatedServices/EditAssociatedServiceModel.cs
> +        public EditAssociatedServiceModel WithRelatedSolutions(IList<CatalogueItem> relatedSolutions)
not a fan of functions like this, and would rather have an overloaded constructor. @steves-bjss agree or disagree?

2022-01-24 12:15 UTC, leerogers-bjss commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Views/AssociatedServices/EditAssociatedService.cshtml
> +                            <nhs-table-cell><a asp-action="@nameof(CatalogueSolutionsController.ManageCatalogueSolution)"
new line the link please :)

2022-01-24 12:16 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/AssociatedServices/EditAssociatedServiceModel.cs
> +        public EditAssociatedServiceModel WithRelatedSolutions(IList<CatalogueItem> relatedSolutions)
This is required to re-populate the solutions when there is a model error

2022-01-24 12:22 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.Services/AssociatedServices/AssociatedServicesService.cs
> +                .Include(ssa => ssa.CatalogueItem)
Removed

2022-01-24 12:25 UTC, leerogers-bjss commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/AssociatedServices/EditAssociatedServiceModel.cs
> +        public EditAssociatedServiceModel WithRelatedSolutions(IList<CatalogueItem> relatedSolutions)
you should just be able to set the RelatedSolutions list directly?

2022-01-24 12:28 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/AssociatedServices/EditAssociatedServiceModel.cs
> +        public EditAssociatedServiceModel WithRelatedSolutions(IList<CatalogueItem> relatedSolutions)
I can, if that's the approach we're now wanting to follow. I implemented it in this manner as it's the approach we've been following up to now.

2022-01-24 12:37 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/AssociatedServices/EditAssociatedServiceModel.cs
> +        public EditAssociatedServiceModel WithRelatedSolutions(IList<CatalogueItem> relatedSolutions)
Done

2022-01-24 13:22 UTC, steves-bjss commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Models/AssociatedServices/EditAssociatedServiceModel.cs
> +        public EditAssociatedServiceModel WithRelatedSolutions(IList<CatalogueItem> relatedSolutions)
Personally I prefer the overloaded constructor too as everything gets set in one place.  However, it can get unwieldy if you end up with lots of dependencies or optionals after which the builder pattern is pretty good.  My main concern now would be consistency with rest of the solution.  Think I agree with Lee in this scenario as there aren't many places where we are using the builder pattern.

2022-01-24 13:31 UTC, leerogers-bjss requested changes

2022-01-24 13:31 UTC, leerogers-bjss commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Views/AssociatedServices/EditAssociatedService.cshtml
> +                                <a asp-action="@nameof(CatalogueSolutionsController.ManageCatalogueSolution)"
the link needs to go to the edit associated services page for the given solution

2022-01-24 14:04 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Views/AssociatedServices/EditAssociatedService.cshtml
> +                                <a asp-action="@nameof(CatalogueSolutionsController.ManageCatalogueSolution)"
That's a weird journey, in my opinion, since the user has very little feedback as to whether they've been navigated correctly or at all, other than the table itself being updated. Nonetheless, I've updated to redirect.

Before clicking edit
![image](https://user-images.githubusercontent.com/90630744/150796631-e47f908e-1fcc-4b0d-843f-4b7f8e2d366a.png)

After clicking edit
![image](https://user-images.githubusercontent.com/90630744/150796692-38f5c355-9586-427f-997d-8efd582c32d1.png)

2022-01-24 17:22 UTC, leerogers-bjss approved these changes

2022-01-25 09:46 UTC, leerogers-bjss approved these changes

2022-01-25 09:47 UTC, merged