Timescales for call-off agreement
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #650
Opened 2022-01-26 13:09 UTC by magnusjohn-bjss

2022-01-27 09:39 UTC, leerogers-bjss requested changes
looks good
however, since this story wasn't supposed to be in sprint, the task list item for this page was changed to an interim name.

So could you update the order task list item for this page to be "Timescales for Call-off Agreement" please?

2022-01-27 10:18 UTC, magnusjohn-bjss commented
> looks good however, since this story wasn't supposed to be in sprint, the task list item for this page was changed to an interim name.
> 
> So could you update the order task list item for this page to be "Timescales for Call-off Agreement" please?

updated

2022-01-31 13:50 UTC, leerogers-bjss requested changes

2022-01-31 13:50 UTC, leerogers-bjss commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Order/Validators/CommencementDateModelValidator.cs
>                  .Must(d => d > DateTime.UtcNow.AddDays(-60))
The Validator is missing date scenarios:

- Enter an approximate start date in a valid format
- Approximate start date must be in the future
- Approximate start date must be a real date
- Approximate start date must include a day
- Approximate start date must include a month
- Approximate start date must include a year
- Year must be four numbers 

you can find an example how to write this under the EditWorkOffPlansValidator, which also has the correct running order.

it should run:

- Enter an approximate start date
- Enter an approximate start date in a valid format
- Approximate start date must include a day
- Approximate start date must include a month
- Approximate start date must include a year
- Approximate start date must be a real date
- Approximate start date must be in the future
- Year must be four numbers 

Also the validator doesn't handle the scenario where you put text into the initial or maximum call off boxes and uses a default message.

So you also need

Initial period must be a number 
Maximum period must be a number

2022-02-01 09:35 UTC, leerogers-bjss requested changes
one minor change

2022-02-01 09:35 UTC, leerogers-bjss commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Order/Views/CommencementDate/CommencementDate.cshtml
> +            <nhs-submit-button text="Save and continue" />
don't need this text since Save and continue is the default value

2022-02-02 09:57 UTC, leerogers-bjss approved these changes

2022-02-02 11:15 UTC, bjss-colin approved these changes

2022-02-08 16:04 UTC, merged