Add supplier contact
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #655
Opened 2022-01-28 16:39 UTC by magnusjohn-bjss

2022-01-31 13:53 UTC, bjss-colin submitted a review, later dismissed

2022-01-31 16:20 UTC, leerogers-bjss requested changes, later dismissed
you can make these changes but i think we're missing the whole edit path.
will confirm with junior then give you a buzz

2022-01-31 16:20 UTC, leerogers-bjss commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Order/Views/Supplier/AddContact.cshtml
> +                    <nhs-submit-button text="Save and continue" />
don't need the text here, because the default text for this component is "Save and continue"

2022-01-31 16:20 UTC, leerogers-bjss commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Order/Views/Supplier/AddContact.cshtml
> +                <div data-test-id="save-button">
don't know why you need this data-test-id?

2022-01-31 16:20 UTC, leerogers-bjss commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Order/Views/Supplier/AddContact.cshtml
> +<div data-test-id="supplier-add-contact-page">
do you need this data-test-id?

2022-02-28 09:43 UTC, Okechukwu802 submitted a review, later dismissed

2022-02-28 12:26 UTC, Okechukwu802 approved these changes

2022-02-28 12:42 UTC, leerogers-bjss requested changes
just a minor one

2022-02-28 12:42 UTC, leerogers-bjss commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Order/Validators/Supplier/NewContactModelValidator.cs
> +        public NewContactModelValidator()
do we need a check here for if the temporary contact is the same as a supplier contact

2022-02-28 12:45 UTC, leerogers-bjss commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Order/Validators/Supplier/NewContactModelValidator.cs
> +        public NewContactModelValidator()
this will need new criteria and a story to update, so approving for now

2022-02-28 12:46 UTC, leerogers-bjss approved these changes

2022-02-28 12:47 UTC, merged