Fix form errors on add a user page
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #668
Opened 2022-02-08 10:09 UTC by leerogers-bjss

Update AddUserModelValidator to cover all form error scenarios

Update CreateBuyerService to no longer handle the form validation

Delete the old CreateBuyerService validation logic and tests

Delete the Results object since it's no longer being used

Add AddUserModelValidator Tests

Split AddUser E2E Tests into their own class

Update Test base to handle a bad logic scenario.
when a test logs you in, the next test will also see if you need to log in by checking for the existance of an input with the title "emailAddress". if the page the next test loads has an input called "emailAddress" it will then try to log in on that form and fail.
Change the Login functions to check if the user is already logged in by checking for the user-session cookie.

2022-02-10 10:58 UTC, bjss-colin requested changes
All looks good, just one comment/observation.

2022-02-10 10:58 UTC, bjss-colin commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Areas/Admin/Organisations/AddUsers.cs
> +    public sealed class AddUsers : AuthorityTestBase, IClassFixture<LocalWebApplicationFactory>
Missing a test to ensure all elements are displayed correctly on the page

2022-02-10 12:39 UTC, leerogers-bjss commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Areas/Admin/Organisations/AddUsers.cs
> +    public sealed class AddUsers : AuthorityTestBase, IClassFixture<LocalWebApplicationFactory>
done

2022-02-10 12:42 UTC, bjss-colin approved these changes

2022-02-11 15:00 UTC, MichaelRobinson-BJSS approved these changes

2022-02-14 09:56 UTC, merged