Manage buyer organisations and users search bar
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #670
Opened 2022-02-10 12:26 UTC by magnusjohn-bjss

2022-02-10 17:58 UTC, magnusjohn-bjss commented on tests/NHSD.GPIT.BuyingCatalogue.WebApp.UnitTests/Areas/Admin/Controllers/OrganisationsControllerTests.cs
>  namespace NHSD.GPIT.BuyingCatalogue.WebApp.UnitTests.Areas.Admin.Controllers
test case 'Get_SearchResults_ValidSearchTerm_NoMatches_ReturnsExpectedResult' added

2022-02-16 09:50 UTC, leerogers-bjss approved these changes, later dismissed

2022-02-16 09:50 UTC, leerogers-bjss commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Controllers/OrganisationsController.cs
> +            var results = await GetFilteredOrganisations(search);
one again, why not use OrganisationsService.GetOrganisationsFiltered?

2022-02-16 12:14 UTC, bjss-colin approved these changes, later dismissed
Dismissing my stale review, looks good from my perspective. Pending subsequent reviews from Lee & Oke

2022-02-16 12:37 UTC, magnusjohn-bjss commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Controllers/OrganisationsController.cs
> +            var results = await GetFilteredOrganisations(search);
moved filter logic to service layer

2022-02-22 09:36 UTC, leerogers-bjss requested changes
just a minor change then will approve

2022-02-22 09:36 UTC, leerogers-bjss commented on src/NHSD.GPIT.BuyingCatalogue.Services/Organisations/OrganisationsService.cs
> +            return await dbContext.Organisations
please limit to max of 15 with .Take(15)

2022-02-22 09:55 UTC, magnusjohn-bjss commented on src/NHSD.GPIT.BuyingCatalogue.Services/Organisations/OrganisationsService.cs
> +            return await dbContext.Organisations
added this at the controller level as it's a ui constraint

2022-02-22 10:06 UTC, Okechukwu802 submitted a review, later dismissed

2022-02-22 11:18 UTC, leerogers-bjss approved these changes

2022-02-22 12:09 UTC, Okechukwu802 approved these changes

2022-02-22 12:10 UTC, merged