Supplier defined epics search bar
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #674
Opened 2022-02-11 14:30 UTC by magnusjohn-bjss

2022-02-14 17:19 UTC, bjss-colin submitted a review, later dismissed

2022-02-16 09:49 UTC, leerogers-bjss requested changes, later dismissed

2022-02-16 09:49 UTC, leerogers-bjss commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Controllers/SupplierDefinedEpicsController.cs
> +            var allEpics = await supplierDefinedEpicsService.GetSupplierDefinedEpics();
why not supplierDefinedEpicsService.GetSupplierDefinedEpicsFiltered?

2022-02-22 09:36 UTC, leerogers-bjss requested changes
just a minor change then will approve

2022-02-22 09:36 UTC, leerogers-bjss commented on src/NHSD.GPIT.BuyingCatalogue.Services/Capabilities/SupplierDefinedEpicsService.cs
> +                .ToListAsync();
please add .Take(15) to limit to 15 only. thanks

2022-02-22 11:54 UTC, magnusjohn-bjss commented on src/NHSD.GPIT.BuyingCatalogue.Services/Capabilities/SupplierDefinedEpicsService.cs
> +                .ToListAsync();
added in controller

2022-02-22 14:18 UTC, leerogers-bjss approved these changes

2022-02-23 10:10 UTC, Okechukwu802 approved these changes

2022-02-23 10:42 UTC, merged