Add search bar to manage suppliers page
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #675
Opened 2022-02-14 13:51 UTC by bjss-colin

2022-02-14 14:36 UTC, leerogers-bjss requested changes

2022-02-14 14:36 UTC, leerogers-bjss commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Controllers/SuppliersController.cs
> +                    Url = currentPageUrl.AppendQueryParameterToUrl(nameof(search), r.Id.ToString()).ToString(),
on the supplier page, the URL should be a direct link to the suppliers edit page. the "CurrentPage" version is only for the marketing page.

2022-02-14 14:36 UTC, leerogers-bjss commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/wwwroot/ts/InactiveItemManagement.ts
> +    const checkbox = <HTMLInputElement>document.getElementById(inactiveItemsCheckbox);
the concept should be not to show the checkbox if you're searching. to facilitate this, magnus did a change that if there is a search term, it wouldn't fire this JS atall, so will need to talk to you/him about it

2022-02-14 15:43 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Controllers/SuppliersController.cs
> +                    Url = currentPageUrl.AppendQueryParameterToUrl(nameof(search), r.Id.ToString()).ToString(),
Updated to link to the "Edit Supplier" page

2022-02-14 15:44 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/wwwroot/ts/InactiveItemManagement.ts
> +    const checkbox = <HTMLInputElement>document.getElementById(inactiveItemsCheckbox);
I've plagiarized Magnus' change to replicate this behavior. Although I have slightly tweaked it as per the acceptance criteria so it disables the inactive filter, on the results page, irrespective as to whether there are any inactive suppliers.

2022-02-14 15:51 UTC, leerogers-bjss approved these changes
technical approval

2022-02-14 16:20 UTC, Okechukwu802 approved these changes

2022-02-14 16:20 UTC, leerogers-bjss approved these changes
technical approval

2022-02-16 09:48 UTC, leerogers-bjss approved these changes
technical approval

2022-02-16 14:08 UTC, merged