Catalogue solutions search bar
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #679
Opened 2022-02-15 15:22 UTC by magnusjohn-bjss

2022-02-16 09:43 UTC, leerogers-bjss requested changes, later dismissed

2022-02-16 09:43 UTC, leerogers-bjss commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Controllers/CatalogueSolutionsController.cs
> +            var allItems = await solutionsService.GetAllSolutions();
why not use somthing like solutionsService.GetAllSolutionsFiltered?

2022-02-16 17:09 UTC, magnusjohn-bjss commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Controllers/CatalogueSolutionsController.cs
> +            var allItems = await solutionsService.GetAllSolutions();
move filter logic to service layer

2022-02-21 14:38 UTC, steves-bjss approved these changes, later dismissed

2022-02-22 14:20 UTC, leerogers-bjss approved these changes

2022-02-23 12:38 UTC, Okechukwu802 approved these changes

2022-02-23 13:06 UTC, merged