Import practice lists
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #700
Opened 2022-02-23 15:27 UTC by magnusjohn-bjss

2022-02-25 09:58 UTC, steves-bjss requested changes

2022-02-25 09:58 UTC, steves-bjss commented on terraform/modules/bc_webapp_pri/variables.tf
> +variable "hangfire_pwd" {
This will need the password generation code adding too.  I will ping you about it separately.

2022-03-03 13:57 UTC, steves-bjss approved these changes

2022-03-03 16:56 UTC, Okechukwu802 approved these changes

2022-03-03 16:58 UTC, merged