Admin homepage & banner menu
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #725
Opened 2022-03-04 17:04 UTC by magnusjohn-bjss

2022-03-04 17:35 UTC, bjss-colin requested changes

2022-03-04 17:35 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Views/Home/Index.cshtml
> +                <p>Add new solutions and edit ones that are already published.</p>
Text here is incorrect, should read as
> Add users to buyer organisations and edit accounts that have already been created.

2022-03-04 17:35 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Views/Home/Index.cshtml
> +                <p>Add new supplier defined Epics and edit ones that are already published.</p>
As above.

Should read
> Add a new supplier organisation or edit the details for one that's already been created.

2022-03-07 09:39 UTC, bjss-colin approved these changes

2022-03-07 10:42 UTC, Okechukwu802 approved these changes

2022-03-07 13:23 UTC, merged