Admin user management
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #749
Opened 2022-03-24 14:29 UTC by magnusjohn-bjss

2022-03-28 13:51 UTC, Okechukwu802 approved these changes, later dismissed

2022-03-30 13:42 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.Services/Users/UsersService.cs
> +            user.NormalizedEmail = email?.ToUpperInvariant();
Arguably, we should be using `UserManager<TUser>` rather than accessing the `DbSet<AspNetUser>` directly. Doing so would correctly populate the relevant values when adding or updating a user in the user store.

Using `UserManager` and `RoleManager` is what I'd have in mind for the RBAC work since it becomes a seamless integration. So, for now, this is more of an observation than a request for any changes

2022-03-30 13:42 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.Services/Users/UsersService.cs
> +            user.NormalizedEmail = email?.ToUpperInvariant();
Arguably, we should be using `UserManager<TUser>` rather than accessing the `DbSet<AspNetUser>` directly. Doing so would correctly populate the relevant values when adding or updating a user in the user store.

Using `UserManager` and `RoleManager` is what I'd have in mind for the RBAC work since it becomes a seamless integration. So, for now, this is more of an observation than a request for any changes

2022-03-30 14:05 UTC, bjss-colin requested changes
Several duplicate review comments on the `UserController` just to highlight some requested changes in terms of validation.

2022-03-30 14:05 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.Services/NHSD.GPIT.BuyingCatalogue.Services.csproj
> +  <ItemGroup>
Possibly an artifact left over from Visual Studio

2022-03-30 14:05 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Controllers/UsersController.cs
> +            var user = await usersService.GetUser(userId);
Should validate that the user is not null since the ID comes from the URL and could be manipulated

2022-03-30 14:05 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Controllers/UsersController.cs
> +            var user = await usersService.GetUser(userId);
Should validate that the user is not null since the ID comes from the URL and could be manipulated

2022-03-30 14:05 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Controllers/UsersController.cs
> +            var user = await usersService.GetUser(userId);
Should validate that the user is not null since the ID comes from the URL and could be manipulated

2022-03-30 14:05 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Controllers/UsersController.cs
> +            var user = await usersService.GetUser(userId);
Should validate that the user is not null since the ID comes from the URL and could be manipulated

2022-03-30 14:05 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Controllers/UsersController.cs
> +            var user = await usersService.GetUser(userId);
Should validate that the user is not null since the ID comes from the URL and could be manipulated

2022-03-30 14:05 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Controllers/UsersController.cs
> +            var user = await usersService.GetUser(userId);
Should validate that the user is not null since the ID comes from the URL and could be manipulated

2022-03-30 14:05 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Controllers/UsersController.cs
> +            var user = await usersService.GetUser(userId);
Should validate that the user is not null since the ID comes from the URL and could be manipulated

2022-03-31 09:31 UTC, bjss-colin approved these changes

2022-03-31 09:39 UTC, Okechukwu802 approved these changes

2022-03-31 10:15 UTC, merged