Add Per solution funding
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #754
Opened 2022-03-28 15:29 UTC by leerogers-bjss

Add Per Solution funding controller, pages, validator and controller

Add OrderItemService for saving funding source information

Update RadioButtonTagHelper to accept a hint parameter as per the NHS Design

Update TableContentsTagHelper to add a Hint text section to the caption.

Fix capitalisation in TaskListTagHelper

Fix CommencementDateModel using system time for date conversion instead of treating everything as UTC

2022-03-28 16:12 UTC, bjss-colin requested changes
Just a few syntax related comments.

Indentation is slightly ajar in the cshtml files too, might want to take a quick look. Razer support is quite bad in VS 2022.

2022-03-28 16:12 UTC, ghost commented on src/NHSD.GPIT.BuyingCatalogue.EntityFramework/Extensions/OrderItemFundingTypeExtensions.cs
> +    public static class OrderItemFundingTypeExtensions
These can be made generic as we tend to use EnumsNET in quite a few places.

Replace the specific type `OrderItemFundingType` with `Enum` and add some constraints
Example
```csharp
public static string Name<TEnum>(this TEnum value)
            where TEnum : struct, Enum => value.AsString(EnumFormat.DisplayName);
```

2022-03-28 16:12 UTC, ghost commented on src/NHSD.GPIT.BuyingCatalogue.EntityFramework/Ordering/Models/OrderItem.Custom.cs
> +        public bool ItemIsLocalFundingOnly() => CatalogueItem?.Solution?.FrameworkSolutions?.All(fs => fs.Framework.LocalFundingOnly) ?? false;
As this is defined on the `OrderItem` object it's reasonable to rename to `IsLocalFundingOnly`. Then the readability becomes `orderItem.IsLocalFundingOnly()`

2022-03-28 16:12 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.Services/Orders/OrderItemService.cs
> +            switch (selectedFundingType)
Might be worth splitting this out to a method that returns a tuple `(double CentrallyAllocated, double LocallyAllocated)` for readability

2022-03-28 16:12 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Order/Validators/FundingSources/FundingSourceModelValidator.cs
> +                .When(fs => fs.SelectedFundingType == EntityFramework.Ordering.Models.OrderItemFundingType.MixedFunding)
Only a single `When` is required

> By default FluentValidation will apply the condition to all preceding validators in the same call to RuleFor
https://docs.fluentvalidation.net/en/latest/conditions.html#:~:text=By%20default%20FluentValidation%20will%20apply%20the%20condition%20to%20all%20preceding%20validators%20in%20the%20same%20call%20to%20RuleFor

2022-03-28 16:33 UTC, leerogers-bjss commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Order/Validators/FundingSources/FundingSourceModelValidator.cs
> +                .When(fs => fs.SelectedFundingType == EntityFramework.Ordering.Models.OrderItemFundingType.MixedFunding)
oh nice, done

2022-03-28 16:34 UTC, leerogers-bjss commented on src/NHSD.GPIT.BuyingCatalogue.EntityFramework/Ordering/Models/OrderItem.Custom.cs
> +        public bool ItemIsLocalFundingOnly() => CatalogueItem?.Solution?.FrameworkSolutions?.All(fs => fs.Framework.LocalFundingOnly) ?? false;
i'm currently rethinking this whole approach, since it doesn't work for additional or associated services due to their different structures.

2022-03-28 16:34 UTC, leerogers-bjss commented on src/NHSD.GPIT.BuyingCatalogue.EntityFramework/Extensions/OrderItemFundingTypeExtensions.cs
> +    public static class OrderItemFundingTypeExtensions
going to do this as a seperate tech debt PR

2022-03-28 16:45 UTC, leerogers-bjss commented on src/NHSD.GPIT.BuyingCatalogue.Services/Orders/OrderItemService.cs
> +            switch (selectedFundingType)
nice call, worked well, done

2022-03-30 11:33 UTC, leerogers-bjss commented on src/NHSD.GPIT.BuyingCatalogue.EntityFramework/Ordering/Models/OrderItem.Custom.cs
> +        public bool ItemIsLocalFundingOnly() => CatalogueItem?.Solution?.FrameworkSolutions?.All(fs => fs.Framework.LocalFundingOnly) ?? false;
fixed

2022-03-30 13:18 UTC, bjss-colin requested changes

2022-03-30 13:18 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Order/Views/FundingSource/FundingSources.cshtml
> +				<p>Central funding means you’re using your centrally held allocation to pay for the order. Any solutions or services you order will be paid for by either NHS England or NHS Digital. The supplier
There's a unicode character which is causing problems with syntax highlighting

> Central funding means you’re using your centrally held allocation to pay for the order

The symbol in the word `you're` is a [right single quotation mark](https://en.wikipedia.org/wiki/Right_single_quotation_mark) instead of being an apostrophe

2022-03-30 13:18 UTC, bjss-colin commented on tests/NHSD.GPIT.BuyingCatalogue.Services.UnitTests/TaskList/TaskListServiceTests.cs
> +        /* TODO - Reimplement Task list Unit Tests
Given this change has been done as part of this PR, I think these should be implemented within the scope of this PR also

2022-03-31 10:06 UTC, leerogers-bjss commented on tests/NHSD.GPIT.BuyingCatalogue.Services.UnitTests/TaskList/TaskListServiceTests.cs
> +        /* TODO - Reimplement Task list Unit Tests
this will be done along side the Unit tests i need to do for this work, i just put it in as a todo to remind myself

2022-03-31 10:08 UTC, leerogers-bjss commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Order/Views/FundingSource/FundingSources.cshtml
> +				<p>Central funding means you’re using your centrally held allocation to pay for the order. Any solutions or services you order will be paid for by either NHS England or NHS Digital. The supplier
done

2022-03-31 12:27 UTC, bjss-colin commented on tests/NHSD.GPIT.BuyingCatalogue.Services.UnitTests/TaskList/TaskListServiceTests.cs
> +        /* TODO - Reimplement Task list Unit Tests
Any reason the unit tests couldn't be included with the work? Ideally every PR should have the complimentary unit tests. Putting something like the End to End tests as a separate PR is reasonable since we'd have a level of coverage already with unit tests.

I appreciate this isn't going directly to the develop branch and we can add them later, which is why I'm inclined to approve this rather than put up much of a battle, but I don't think this is an approach we should be getting comfortable with.

2022-04-05 08:46 UTC, bjss-colin approved these changes

2022-04-05 09:03 UTC, merged