Creation of Regression Test Framework
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #775
Opened 2022-05-03 14:19 UTC by steves-bjss

Creation of Regression Test framework - azure-pipelines to be updated in further PR.

2022-05-04 11:17 UTC, Okechukwu802 approved these changes, later dismissed

2022-05-04 12:46 UTC, bjss-colin requested changes
All looks good, just one recommendation.

2022-05-04 12:46 UTC, bjss-colin commented on tests/NHSD.GPIT.BuyingCatalogue.RegressionTests/Utils/WebApplicationConnector.cs
> +            if (disposing && !disposed)
Condition and subsequent lines can be removed

2022-05-05 08:20 UTC, steves-bjss commented on tests/NHSD.GPIT.BuyingCatalogue.RegressionTests/Utils/WebApplicationConnector.cs
> +            if (disposing && !disposed)
Updated as suggested.

2022-05-05 08:21 UTC, bjss-colin approved these changes

2022-05-05 09:44 UTC, merged