Add Capping the Number of Tiers in Config
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #795
Opened 2022-05-18 10:26 UTC by leerogers-bjss

Added a new config setting for capping price tiers.

Have the Edit and Add Tiered Price pages only show the add tier button if the number of tiers is less than the maximum.

Update tests

2022-05-18 12:18 UTC, bjss-colin requested changes

2022-05-18 12:18 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Views/Shared/ListPrices/EditTieredListPrice.cshtml
> +				if(Model.Tiers.Count < Model.MaximumNumberOfTiers){
`MaximumNumberOfTiers` needs to be passed as a hidden input, or, ideally, repopulated in the controller on a failed POST, otherwise it reports an incorrect value if model validation fails

![image](https://user-images.githubusercontent.com/90630744/169036975-674f3fff-3d1c-49ea-a17c-ec76d42ee868.png)

2022-05-18 12:29 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Views/Shared/ListPrices/EditTieredListPrice.cshtml
> +				if(Model.Tiers.Count < Model.MaximumNumberOfTiers){
Offered to pick this up as Lee was busy on the supplier contacts / orders issue

2022-05-18 13:35 UTC, bjss-colin approved these changes

2022-05-23 12:41 UTC, Okechukwu802 approved these changes

2022-05-23 13:45 UTC, merged