add estimation period for quantity
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #830
Opened 2022-06-30 08:23 UTC by leerogers-bjss

Rename estimation period on order item price to billing period.

update order form quantity pages to display different content depending on the estimation period.

Add RangeDefinition logic to flat price tests.

Add SetOrderItemEstimation Tests

2022-06-30 08:37 UTC, bjss-colin requested changes

2022-06-30 08:37 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Views/Shared/ListPrices/AddEditFlatListPrice.cshtml
> +                label-text="Range definition"
Range definition isn't the correct term here for the label text as a flat price has no ranges. Might be worth running this by Luke to coin up a better term.

2022-06-30 09:21 UTC, magnusjohn-bjss approved these changes

2022-06-30 09:28 UTC, magnusjohn-bjss commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Views/Shared/ListPrices/AddEditFlatListPrice.cshtml
> +                label-text="Range definition"
Not sure I agree with this, range definition is the term we use for the plural of the unit description, it has descriptive lede text to make that clear and it should be consistent between flat & tiered prices.

2022-06-30 09:59 UTC, bjss-colin approved these changes
Approved for now but it's worth re-reviewing the `Range definition` term. I still don't think it's the right term here.

2022-07-01 08:16 UTC, bjss-colin approved these changes

2022-07-01 08:24 UTC, merged