Clean up post-work TODOs and Content Sweep
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #843
Opened 2022-07-08 11:00 UTC by leerogers-bjss

Content changes requested by luke from post-work content sweep.

2022-07-08 11:11 UTC, bjss-colin requested changes

2022-07-08 11:11 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Order/Views/Quantity/SelectServiceRecipientQuantity.cshtml
> +            <h2>@x</h2>
Needs a better variable name, also, should this be assigned to `label-text` on the `nhs-table` tag as we do with all other table headings?

2022-07-08 11:28 UTC, leerogers-bjss commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Order/Views/Quantity/SelectServiceRecipientQuantity.cshtml
> +            <h2>@x</h2>
doh, this was from when i was showing luke an example.

i'll get it fixed now

2022-07-08 12:16 UTC, bjss-colin requested changes

2022-07-08 12:16 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Order/Models/SolutionSelection/Quantity/SelectServiceRecipientQuantityModel.cs
> +            _ => RangeDefinition,
This should be "Quantity". I agreed this with Luke yesterday as it doesn't read well if the range definition has been entered as lowercase.

2022-07-11 08:14 UTC, bjss-colin approved these changes

2022-07-11 13:54 UTC, merged