Associated services only service & solution selection
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #888
Opened 2022-08-23 13:14 UTC by magnusjohn-bjss

2022-08-24 09:14 UTC, bjss-colin requested changes
Looks good, some minor suggestions added

2022-08-24 09:14 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.Services/Orders/SupplierService.cs
> +            return dbContext.Suppliers
It's worth pinning an `AsNoTracking` on this since it's used in a read-only scenario

2022-08-24 09:14 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.Services/Solutions/SolutionsService.cs
> +            return await dbContext.CatalogueItems
It's worth pinning an `AsNoTracking` on this since it's used in a read-only scenario

2022-08-24 09:14 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Order/Views/Shared/SelectSolution.cshtml
> +            @if (!Model.AssociatedServicesOnly
`if` condition can be shortened to `if (Model.CatalogueSolutions.Count > 1)`, unless everything after the OR needs to be wrapped in parenthesis?

2022-08-24 09:37 UTC, magnusjohn-bjss commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Order/Views/Shared/SelectSolution.cshtml
> +            @if (!Model.AssociatedServicesOnly
&& takes precedence over ||, so the parentheses are implicit (i.e. `!a || a && b` is equivalent to `!a || (a && b)`). want some added in anyway to prevent confusion? vs flags them as unnecessary is the only thing

2022-08-24 09:41 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Order/Views/Shared/SelectSolution.cshtml
> +            @if (!Model.AssociatedServicesOnly
That's fine, I couldn't quite remember the order and/or precedence between the two.

2022-08-24 09:42 UTC, bjss-colin submitted a review, later dismissed

2022-08-24 11:04 UTC, bjss-colin approved these changes, later dismissed

2022-08-24 14:39 UTC, bjss-colin submitted a review, later dismissed

2022-08-25 14:29 UTC, bjss-colin approved these changes, later dismissed

2022-08-30 15:24 UTC, imranbashir01 approved these changes

2022-08-30 15:29 UTC, seesharpsteve approved these changes

2022-08-30 15:35 UTC, steves-bjss approved these changes

2022-08-30 15:37 UTC, merged