Terraform changes for Disaster Recovery
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #907
Opened 2022-09-16 18:30 UTC by bjss-colin

Currently a draft raised for awareness.

* Updates the AzureRM provider version
* Retrieves the KeyVault secrets, from the primary environment, when the current environment is DR
* Moves KeyVault to a module that is conditionally deployed when the environment is not DR **
* Conditionally deploys a SQL instance and the databases when the environment is not DR

The KeyVault module transition is a destructive change and will require `terraform mv` to be run to move the existing KeyVault state binding to the new name of `module.azurerm_key_vault.keyvault`

2022-09-16 18:31 UTC, bjss-colin commented on terraform/resource_groups.tf
> -resource "azurerm_resource_group" "keyvault" {
Moved to the KeyVault module main.tf

2022-09-16 18:31 UTC, bjss-colin commented on terraform/resource_groups.tf
> -resource "azurerm_resource_group" "sql-server" {
Moved to the bc_sql_server module main.tf

2022-09-16 18:33 UTC, bjss-colin commented on terraform/modules/keyvault/keyvault_access_policy.tf
> +# Should we be managing a resource that we don't provision or deploy?
Commented this out with a reason. This changes properties on a KeyVault instance that isn't provisioned by this terraform configuration. We should either bring the core KeyVault instance under this tf config or maybe scrap this block.

2022-09-26 15:08 UTC, steves-bjss requested changes

2022-09-26 15:08 UTC, steves-bjss commented on azure-pipelines.yml
> +# - job: dockerBuildAndPush
Can you re-enable the rest of the build please.

2022-09-26 15:17 UTC, steves-bjss approved these changes

2022-09-26 16:24 UTC, merged