Add Framework Selection to funding sources.
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #913
Opened 2022-09-29 09:25 UTC by leerogers-bjss

Add framework selection logic and update funding sources to be saved by the continue button on funding sources page.

Update solution selection to no longer set forced funding types but to remove funding if the underlying data has changed (from forced to not forced).

Add tests for above scenarios.

2022-09-29 10:58 UTC, imranbashir01 approved these changes, later dismissed

2022-09-30 10:27 UTC, bjss-colin requested changes

2022-09-30 10:27 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Order/Models/FundingSources/ConfirmFrameworkChangeModel.cs
> +        public SelectList Options => new(
Use `SelectableRadioOption<T>` instead

2022-10-04 13:00 UTC, imranbashir01 approved these changes

2022-10-04 14:15 UTC, steves-bjss approved these changes

2022-10-04 14:17 UTC, bjss-colin approved these changes

2022-10-04 14:32 UTC, merged