Edit User Accounts
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #948
Opened 2022-11-11 09:59 UTC by dssherlock

2022-11-16 11:03 UTC, imranbashir01 approved these changes, later dismissed

2022-11-16 15:03 UTC, bjss-colin requested changes

2022-11-16 15:03 UTC, bjss-colin commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Areas/AccountManagement/EditUser.cs
> +    public sealed class EditUser : AccountManagerTestBase, IClassFixture<LocalWebApplicationFactory>
Let's implement `IDisposable` here to clean up any changes that the tests make. Tests should ideally clean up after themselves. As I'm currently in the process of improving the test times by using a shared database instance, it becomes more obvious that tests aren't resetting state back to what it was prior to changes, and it has a knock-on effect to other tests

For instance, `EditUser_EditUser_ExpectedResult` will result in User ID 3 (Bob, admin account) becoming an Account Manager and also Inactive.

The original object doesn't have to be cloned, instead the `Dispose` method can simply set the Role back to Admin and Inactive back to Active.

2022-11-16 15:21 UTC, dssherlock commented on tests/NHSD.GPIT.BuyingCatalogue.E2E.PublicBrowseTests/Areas/AccountManagement/EditUser.cs
> +    public sealed class EditUser : AccountManagerTestBase, IClassFixture<LocalWebApplicationFactory>
Yep sure! Tbh I thought the tests already had a dispose method. I'll take a look

2022-11-17 10:22 UTC, bjss-colin approved these changes

2022-11-17 12:04 UTC, merged