Incremental ODS updates
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #963
Opened 2022-11-28 18:22 UTC by magnusjohn-bjss

2022-11-29 11:32 UTC, bjss-colin requested changes
Functionality looks good. One minor point with regards to access controls

2022-11-29 11:32 UTC, bjss-colin commented on terraform/functionapp/main.tf
> +resource "azurerm_windows_function_app" "function_app" {
It's worth adding an `ip_restriction` block to grant access to the VPN while denying all other access requests since the function is marked as Anonymous auth. The VPN details can be found in the Plan or Apply stages, of any environment, in the WebApp deployment pipeline.

2022-11-29 15:03 UTC, bjss-colin approved these changes

2022-11-29 15:42 UTC, steves-bjss approved these changes

2022-11-30 11:36 UTC, imranbashir01 approved these changes

2022-11-30 12:44 UTC, merged