US-21447 change in Date format for Date Created in the Manage Orders
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #974
Opened 2022-12-06 15:11 UTC by DeepikaDK001

2022-12-06 15:17 UTC, magnusjohn-bjss approved these changes, later dismissed

2022-12-06 15:34 UTC, imranbashir01 approved these changes, later dismissed

2022-12-07 09:23 UTC, bjss-colin requested changes
If the admin pages are also being changed then it might be worth updating all date references in that case.

Doing a search for dd MM and ToLongDateString brings back a few results. The only place where the date format _**must**_ remain unchanged is `GpPracticeService`

2022-12-07 09:48 UTC, imranbashir01 submitted a review, later dismissed

2022-12-09 11:31 UTC, bjss-colin requested changes

2022-12-09 11:31 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Properties/launchSettings.json
> -{
Looks like there's just one last test that's failing, but we also need to keep this file as without it we can't run the app locally

2022-12-09 12:17 UTC, imranbashir01 approved these changes, later dismissed

2022-12-09 14:45 UTC, bjss-colin approved these changes

2022-12-09 14:48 UTC, imranbashir01 approved these changes

2022-12-09 14:50 UTC, merged