Max two account managers and display account type in User list
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #981
Opened 2022-12-13 09:49 UTC by dssherlock

2022-12-13 14:02 UTC, bjss-colin requested changes

2022-12-13 14:02 UTC, ghost commented on src/NHSD.GPIT.BuyingCatalogue.Framework/Extensions/AspNetUserExtensions.cs
> +            return roleName is not null ? OrganisationFunction.FromName(roleName)!.DisplayName : string.Empty;
Assuming you've hit the same problem, the agency user is what causes this to fail.

Considering Role Name should never be empty, I'd say it's an incorrect behavior to return an empty string. Since we don't use the agency user I've disabled this in the docker-compose file.

2022-12-13 14:02 UTC, ghost commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Admin/Validators/Users/UserDetailsModelValidator.cs
> +                || !usersService.IsAccountManagerLimit(int.Parse(selectedOrganisationId), userId).Result;
Rather than `int.Parse`, the model property `SelectedOrganisationId` could become an `int?` to leave ASP.NET Core handle the model binding.

2022-12-13 14:47 UTC, dssherlock commented on src/NHSD.GPIT.BuyingCatalogue.Framework/Extensions/AspNetUserExtensions.cs
> +            return roleName is not null ? OrganisationFunction.FromName(roleName)!.DisplayName : string.Empty;
Yep ok fair enough. It was also a safety check but providing a user always has a role assigned then thats fine.

2022-12-14 09:53 UTC, bjss-colin approved these changes

2022-12-16 20:40 UTC, merged