Edit user inset text change
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #992
Opened 2022-12-19 14:42 UTC by dssherlock

2022-12-19 16:54 UTC, bjss-colin requested changes

2022-12-19 16:54 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Views/Shared/OrganisationBase/UserDetails.cshtml
> +                <input type="hidden" asp-for="MaximumAccountManagerMessage" />
`MaximumAccountManagerMessage` is a getter only so we shouldn't need a hidden input here as it uses the `UserId` to return a message.

2022-12-19 16:54 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Models/OrganisationModels/UserDetailsModel.cs
> +                return UserId == 0 ? string.Format(AddMaximumAccountManagerMessage, maxAccountManagers) : string.Format(EditMaximumAccountManagerMessage, maxAccountManagers);
Since `maxAccountManagers` is a private read-only field, I'd expect this to be the default value for integers, `0`, if an admin or user removes causes a form validation error, causing the `AddMaximumAccountManagerMessage` to appear instead of `EditMaximumAccountManagerMessage`

2022-12-19 17:03 UTC, dssherlock commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Views/Shared/OrganisationBase/UserDetails.cshtml
> +                <input type="hidden" asp-for="MaximumAccountManagerMessage" />
Yep u r right this has changed so can be removed

2022-12-20 11:19 UTC, bjss-colin submitted a review, later dismissed

2022-12-22 16:34 UTC, steves-bjss approved these changes

2022-12-22 17:47 UTC, merged