US-2558: Added rules for the password creation.
nhs-digital-gp-it-futures/GPITBuyingCatalogue pull request #995
Opened 2023-01-03 11:03 UTC by DeepikaDK001

2023-01-03 11:25 UTC, bjss-colin requested changes

2023-01-03 11:25 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.Services/Users/UsersService.cs
> +        public async Task<bool> IsPasswordPresentInPastNPasswords(AspNetUser user, string email, string newPassword, int numOfPreviousPasswords)
`numOfPreviousPasswords` could be turned into a configuration value stored in the appsettings.json file and injected in the constructor, since it should be a single value throughout the app.

2023-01-03 11:25 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Identity/Models/ResetPasswordViewModel.cs
> +            public const int numOfPreviousPasswords = 5;
Can be mapped as a configuration value in appSettings.json as it isn't really a view model concern. There are some existing examples in code of mapping appSettings to objects - see `ServiceCollectionExtensions` in the WebApp.

2023-01-03 11:25 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.Services/Users/UsersService.cs
> +            var passwordHistQuery = (from hist in dbContext.AspNetUsers.TemporalAll()
This could be converted to the LINQ method style syntax, such as `.Where`, `.OrderByDescending`, `.Select` and `.Take`

2023-01-03 14:50 UTC, bjss-colin requested changes

2023-01-03 14:50 UTC, bjss-colin commented on tests/NHSD.GPIT.BuyingCatalogue.Services.UnitTests/Users/UsersServiceTests.cs
> +            Assert.Throws<ArgumentNullException>(() => _ = new UsersService(null, new AccountManagementSettings(), null, null, null));
Have a look at the `VerifyGuardClause` tests that exist in the unit test suite. It would be good to switch to that format to ensure all constructor parameters are tested

2023-01-03 14:50 UTC, bjss-colin commented on tests/NHSD.GPIT.BuyingCatalogue.Framework.UnitTests/Identity/PasswordValidatorTests.cs
> -        [InlineData("Pass123123")]
Let's add these as a test scenario to test the negative path where the specified password does not meet the password policy requirements

2023-01-03 14:50 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.WebApp/Areas/Identity/Controllers/AccountController.cs
> +            if (usedPassword)
This code path needs to be unit tested

2023-01-03 14:50 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.Services/Users/UsersService.cs
> +        public bool IsPasswordPresentInPastNPasswords(AspNetUser user, string email, string newPassword)
This method needs to be unit tested to cover the happy and unhappy path

2023-01-03 14:50 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.Services/Users/UsersService.cs
> +        public bool IsPasswordPresentInPastNPasswords(AspNetUser user, string email, string newPassword)
Might be worth renaming this method now that the number of previous passwords is a config value. `IsPasswordValid` or something along those lines.

2023-01-03 14:50 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.Services/Users/UsersService.cs
> +                .Select(x => x.PasswordHash)
Having thought of this more, we will need a Distinct on the `PasswordHash`.

The Temporal tables will be updated any time a change is made to a user, including the first and/or last name. If somebody updates the name of an account 5 times it'll retrieve their **current** password five times. This will then allow the user to use their **previous** password.

As a result of this, what we should do is retrieve the last 5 _unique_ passwords and compare against those.

2023-01-04 13:24 UTC, bjss-colin requested changes

2023-01-04 13:24 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.Services/Users/UsersService.cs
> +        public bool IsPasswordValid(AspNetUser user, string email, string newPassword)
Glancing more at this - we shouldn't need `string email` since the `AspNetUser` is already being passed in. I propose `email` is removed and the `Where` lambda is updated to search by the `user.Id`.

Additionally, to make this method async, you could add `.ToListAsync()` after the `.Take`, and `await` the operation by placing the `await` keyword just after the `=` on line 180. The method return type would need to change to `Task<bool>` in both the interface and class. That way, the database call will be a non-blocking operation.

2023-01-04 13:24 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.Services/Users/UsersService.cs
> +        public UsersService(UserManager<AspNetUser> userManager, AccountManagementSettings accountManagementSettings, BuyingCatalogueDbContext dbContext, IPasswordHasher<AspNetUser> passwordHash, Pas
Spelling mistake - `passwordResetSettings`

2023-01-04 15:20 UTC, bjss-colin submitted a review, later dismissed
Looks good, nice work 👍 

It just needs test approval and a demo to a BA prior to being merged

2023-01-05 10:46 UTC, imranbashir01 submitted a review, later dismissed

2023-01-06 09:14 UTC, imranbashir01 approved these changes, later dismissed

2023-01-06 09:27 UTC, bjss-colin requested changes

2023-01-06 09:27 UTC, bjss-colin commented on src/NHSD.GPIT.BuyingCatalogue.Services/Users/UsersService.cs
> +                .Distinct()
This may also need to be updated to
```csharp
.DistinctBy(x => x.PasswordHash)
```
as the `Distinct` isn't guaranteed to return unique passwords since it now includes `LastUpdated`.

2023-01-06 10:45 UTC, bjss-colin approved these changes

2023-01-06 11:10 UTC, imranbashir01 approved these changes

2023-01-06 11:19 UTC, merged